package mro.app.applyItem.vo;

// Generated 2013/1/2 �U�� 05:22:00 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mro.base.entity.AItem;

/**
 * AItemspec generated by hbm2java
 */
@Entity
public class ListAItemspecVO implements java.io.Serializable {
	private static final long serialVersionUID = 6578907611809950225L;
	private BigDecimal AItemspecid;
	private AItem AItem;
	private BigDecimal allasspecusevalue=new BigDecimal(0);
	private BigDecimal alllocspecusevalue=new BigDecimal(0);
	private String alnvalue;
	private String assetattrid;
	private String changeby;
	private Date changedate;
	private String classstructureid;
	private BigDecimal displaysequence;
	private String is01;
	private String is02;
	private String is03;
	private Date is04;
	private BigDecimal is05;
	private String itemnum;
	private String itemsetid;
	private BigDecimal itemspecid;
	private String measureunitid;
	private BigDecimal numvalue;
	private String orgid;
	private BigDecimal rotating=new BigDecimal(0);
	private String section;
	private String eauditusername;
	private Date eaudittimestamp;
	private String eaudittype;
	private String esigtransid;
	private String duplicateitemspec;
	private String status;

	private String description;
	private String datatype;
	private BigDecimal decimalplaces;
	private BigDecimal itemrequirevalue;
	private String oldValue;
	private String oldMeasureunitid;	
	public ListAItemspecVO() {
	}


	@Id
	@Column(name = "A_ITEMSPECID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAItemspecid() {
		return this.AItemspecid;
	}

	public void setAItemspecid(BigDecimal AItemspecid) {
		this.AItemspecid = AItemspecid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EAUDITTRANSID", nullable = false)
	public AItem getAItem() {
		return this.AItem;
	}

	public void setAItem(AItem AItem) {
		this.AItem = AItem;
	}

	@Column(name = "ALLASSPECUSEVALUE", precision = 22, scale = 0)
	public BigDecimal getAllasspecusevalue() {
		return this.allasspecusevalue;
	}

	public void setAllasspecusevalue(BigDecimal allasspecusevalue) {
		this.allasspecusevalue = allasspecusevalue;
	}

	@Column(name = "ALLLOCSPECUSEVALUE", precision = 22, scale = 0)
	public BigDecimal getAlllocspecusevalue() {
		return this.alllocspecusevalue;
	}

	public void setAlllocspecusevalue(BigDecimal alllocspecusevalue) {
		this.alllocspecusevalue = alllocspecusevalue;
	}

	@Column(name = "ALNVALUE", length = 200)
	public String getAlnvalue() {
		return this.alnvalue;
	}

	public void setAlnvalue(String alnvalue) {
		this.alnvalue = alnvalue;
	}

	@Column(name = "ASSETATTRID", length = 8)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Column(name = "CHANGEBY", length = 30)
	public String getChangeby() {
		return this.changeby;
	}

	public void setChangeby(String changeby) {
		this.changeby = changeby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGEDATE", length = 7)
	public Date getChangedate() {
		return this.changedate;
	}

	public void setChangedate(Date changedate) {
		this.changedate = changedate;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "DISPLAYSEQUENCE", precision = 22, scale = 0)
	public BigDecimal getDisplaysequence() {
		return this.displaysequence;
	}

	public void setDisplaysequence(BigDecimal displaysequence) {
		this.displaysequence = displaysequence;
	}

	@Column(name = "IS01", length = 10)
	public String getIs01() {
		return this.is01;
	}

	public void setIs01(String is01) {
		this.is01 = is01;
	}

	@Column(name = "IS02", length = 10)
	public String getIs02() {
		return this.is02;
	}

	public void setIs02(String is02) {
		this.is02 = is02;
	}

	@Column(name = "IS03", length = 10)
	public String getIs03() {
		return this.is03;
	}

	public void setIs03(String is03) {
		this.is03 = is03;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IS04", length = 7)
	public Date getIs04() {
		return this.is04;
	}

	public void setIs04(Date is04) {
		this.is04 = is04;
	}

	@Column(name = "IS05", precision = 15)
	public BigDecimal getIs05() {
		return this.is05;
	}

	public void setIs05(BigDecimal is05) {
		this.is05 = is05;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "ITEMSETID", length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "ITEMSPECID", precision = 22, scale = 0)
	public BigDecimal getItemspecid() {
		return this.itemspecid;
	}

	public void setItemspecid(BigDecimal itemspecid) {
		this.itemspecid = itemspecid;
	}

	@Column(name = "MEASUREUNITID", length = 50)
	public String getMeasureunitid() {
		return this.measureunitid;
	}

	public void setMeasureunitid(String measureunitid) {
		this.measureunitid = measureunitid;
	}

	@Column(name = "NUMVALUE", precision = 10)
	public BigDecimal getNumvalue() {
		return this.numvalue;
	}

	public void setNumvalue(BigDecimal numvalue) {
		this.numvalue = numvalue;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ROTATING", precision = 22, scale = 0)
	public BigDecimal getRotating() {
		return this.rotating;
	}

	public void setRotating(BigDecimal rotating) {
		this.rotating = rotating;
	}

	@Column(name = "SECTION", length = 10)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "EAUDITUSERNAME", nullable = false, length = 18)
	public String getEauditusername() {
		return this.eauditusername;
	}

	public void setEauditusername(String eauditusername) {
		this.eauditusername = eauditusername;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EAUDITTIMESTAMP", nullable = false, length = 7)
	public Date getEaudittimestamp() {
		return this.eaudittimestamp;
	}

	public void setEaudittimestamp(Date eaudittimestamp) {
		this.eaudittimestamp = eaudittimestamp;
	}

	@Column(name = "EAUDITTYPE", nullable = false, length = 1)
	public String getEaudittype() {
		return this.eaudittype;
	}

	public void setEaudittype(String eaudittype) {
		this.eaudittype = eaudittype;
	}

	@Column(name = "ESIGTRANSID", length = 40)
	public String getEsigtransid() {
		return this.esigtransid;
	}

	public void setEsigtransid(String esigtransid) {
		this.esigtransid = esigtransid;
	}

	@Column(name = "DUPLICATEITEMSPEC", length = 50)
	public String getDuplicateitemspec() {
		return this.duplicateitemspec;
	}

	public void setDuplicateitemspec(String duplicateitemspec) {
		this.duplicateitemspec = duplicateitemspec;
	}

	@Column(name = "STATUS", length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DATATYPE")
	public String getDatatype() {
		return datatype;
	}


	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "ITEMREQUIREVALUE")
	public BigDecimal getItemrequirevalue() {
		return itemrequirevalue;
	}


	public void setItemrequirevalue(BigDecimal itemrequirevalue) {
		this.itemrequirevalue = itemrequirevalue;
	}
	
	@Column(name = "OLD_VALUE")
	public String getOldValue() {
		return oldValue;
	}


	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	@Column(name = "OLD_MEASUREUNITID")
	public String getOldMeasureunitid() {
		return oldMeasureunitid;
	}


	public void setOldMeasureunitid(String oldMeasureunitid) {
		this.oldMeasureunitid = oldMeasureunitid;
	}

	@Column(name="DECIMALPLACES")
	public BigDecimal getDecimalplaces() {
		return decimalplaces;
	}

	public void setDecimalplaces(BigDecimal decimalplaces) {
		this.decimalplaces = decimalplaces;
	}
}
