package mro.base.entity.view;

// Generated 2015/3/23 �U�� 04:18:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EpMroItemCategoryVId generated by hbm2java
 */
@Entity
@Table(name = "EP_MRO_ITEM_CATEGORY_V")
public class EpMroItemCategoryV implements java.io.Serializable {

	private String itemCode;
	private String description;
	private String primaryUomCode;
	private String ospItemFlag;
	private BigDecimal epCategoryId;
	private String concatSegment;
	private BigDecimal companyId;
	private BigDecimal categoryId;

	public EpMroItemCategoryV() {
	}

	public EpMroItemCategoryV(BigDecimal epCategoryId, BigDecimal companyId,
			BigDecimal categoryId) {
		this.epCategoryId = epCategoryId;
		this.companyId = companyId;
		this.categoryId = categoryId;
	}

	public EpMroItemCategoryV(String itemCode, String description,
			String primaryUomCode, String ospItemFlag, BigDecimal epCategoryId,
			String concatSegment, BigDecimal companyId, BigDecimal categoryId) {
		this.itemCode = itemCode;
		this.description = description;
		this.primaryUomCode = primaryUomCode;
		this.ospItemFlag = ospItemFlag;
		this.epCategoryId = epCategoryId;
		this.concatSegment = concatSegment;
		this.companyId = companyId;
		this.categoryId = categoryId;
	}
	@Id
	@Column(name = "ITEM_CODE", length = 180)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "DESCRIPTION", length = 720)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PRIMARY_UOM_CODE", length = 9)
	public String getPrimaryUomCode() {
		return this.primaryUomCode;
	}

	public void setPrimaryUomCode(String primaryUomCode) {
		this.primaryUomCode = primaryUomCode;
	}

	@Column(name = "OSP_ITEM_FLAG", length = 3)
	public String getOspItemFlag() {
		return this.ospItemFlag;
	}

	public void setOspItemFlag(String ospItemFlag) {
		this.ospItemFlag = ospItemFlag;
	}

	@Column(name = "EP_CATEGORY_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEpCategoryId() {
		return this.epCategoryId;
	}

	public void setEpCategoryId(BigDecimal epCategoryId) {
		this.epCategoryId = epCategoryId;
	}

	@Column(name = "CONCAT_SEGMENT", length = 1800)
	public String getConcatSegment() {
		return this.concatSegment;
	}

	public void setConcatSegment(String concatSegment) {
		this.concatSegment = concatSegment;
	}

	@Column(name = "COMPANY_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(BigDecimal companyId) {
		this.companyId = companyId;
	}

	@Column(name = "CATEGORY_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

}
