package mro.base.entity.view;

// Generated 2015/1/15 �W�� 10:20:11 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HrDeputyActiveVId generated by hbm2java
 */
@Entity
@Table(name = "HR_DEPUTY_ACTIVE_V")
public class HrDeputyActiveV implements java.io.Serializable {

	private BigDecimal id;
	private String empNo;
	private String deputyNo;
	private Date startdatetime;
	private Date enddatetime;
	private String system;
	private String seqNo;
	private Date cancelDate;
	private Date creationDate;
	private String companyName;

	public HrDeputyActiveV() {
	}

	public HrDeputyActiveV(String empNo, String deputyNo, Date startdatetime,
			Date enddatetime) {
		this.empNo = empNo;
		this.deputyNo = deputyNo;
		this.startdatetime = startdatetime;
		this.enddatetime = enddatetime;
	}

	public HrDeputyActiveV(BigDecimal id, String empNo, String deputyNo,
			Date startdatetime, Date enddatetime, String system, String seqNo,
			Date cancelDate, Date creationDate, String companyName) {
		this.id = id;
		this.empNo = empNo;
		this.deputyNo = deputyNo;
		this.startdatetime = startdatetime;
		this.enddatetime = enddatetime;
		this.system = system;
		this.seqNo = seqNo;
		this.cancelDate = cancelDate;
		this.creationDate = creationDate;
		this.companyName = companyName;
	}
	@Id
	@Column(name = "ID", precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "EMP_NO", nullable = false, length = 10)
	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	@Column(name = "DEPUTY_NO", nullable = false, length = 10)
	public String getDeputyNo() {
		return this.deputyNo;
	}

	public void setDeputyNo(String deputyNo) {
		this.deputyNo = deputyNo;
	}

	@Column(name = "STARTDATETIME", nullable = false, length = 7)
	public Date getStartdatetime() {
		return this.startdatetime;
	}

	public void setStartdatetime(Date startdatetime) {
		this.startdatetime = startdatetime;
	}

	@Column(name = "ENDDATETIME", nullable = false, length = 7)
	public Date getEnddatetime() {
		return this.enddatetime;
	}

	public void setEnddatetime(Date enddatetime) {
		this.enddatetime = enddatetime;
	}

	@Column(name = "SYSTEM", length = 10)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "SEQ_NO", length = 25)
	public String getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(String seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "CANCEL_DATE", length = 7)
	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	@Column(name = "CREATION_DATE", length = 7)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "COMPANY_NAME", length = 60)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

}
