package mro.base.entity.view;

// Generated 2015/6/10 �U�� 02:14:57 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MroApplyList generated by hbm2java
 */
@Entity
@Table(name = "MRO_APPLY_LIST")
public class MroApplyList implements java.io.Serializable {
	private String applyNum;
	private BigDecimal taskId;
	private String status;

	public MroApplyList(){
		
	}
	public MroApplyList(String applyNum, BigDecimal taskId, String status) {
		this.applyNum = applyNum;
		this.taskId = taskId;
		this.status = status;
	}
	@Id
	@Column(name = "APPLY_NUM", length = 80)
	public String getApplyNum() {
		return this.applyNum;
	}

	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	@Column(name = "TASK_ID", precision = 22, scale = 0)
	public BigDecimal getTaskId() {
		return this.taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


}
