package mro.base.entity.view;

// Generated 2015/1/12 �U�� 03:42:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MroApplySignListId generated by hbm2java
 */
@Entity
@Table(name = "MRO_APPLY_SIGN_LIST")
public class MroApplySignList implements java.io.Serializable {

	private BigDecimal taskId;
	private BigDecimal taskListId;
	private String status;
	private String actorId;
	private String createBy;
	private Date createDate;
	private String applyNum;
	private String sourceSystem;
	private String sourceCategory;
	private BigDecimal processId;
	private String deputyEmpNo;
	private String actorName;
	private Date fromDate;

	public MroApplySignList() {
	}

	public MroApplySignList(BigDecimal taskId) {
		this.taskId = taskId;
	}

	public MroApplySignList(BigDecimal taskId, BigDecimal taskListId,
			String status, String actorId, String createBy, Date createDate,
			String applyNum, String sourceSystem, String sourceCategory,
			BigDecimal processId, String deputyEmpNo,String actorName,
			Date fromDate) {
		this.taskId = taskId;
		this.taskListId = taskListId;
		this.status = status;
		this.actorId = actorId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.applyNum = applyNum;
		this.sourceSystem = sourceSystem;
		this.sourceCategory = sourceCategory;
		this.processId = processId;
		this.deputyEmpNo = deputyEmpNo;
		this.actorName = actorName;
		this.fromDate = fromDate;
	}
	@Id
	@Column(name = "TASK_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskId() {
		return this.taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}

	@Column(name = "TASK_LIST_ID", precision = 22, scale = 0)
	public BigDecimal getTaskListId() {
		return this.taskListId;
	}

	public void setTaskListId(BigDecimal taskListId) {
		this.taskListId = taskListId;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ACTOR_ID", length = 30)
	public String getActorId() {
		return this.actorId;
	}

	public void setActorId(String actorId) {
		this.actorId = actorId;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "APPLY_NUM", length = 50)
	public String getApplyNum() {
		return this.applyNum;
	}

	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	@Column(name = "SOURCE_SYSTEM", length = 50)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	@Column(name = "SOURCE_CATEGORY", length = 50)
	public String getSourceCategory() {
		return this.sourceCategory;
	}

	public void setSourceCategory(String sourceCategory) {
		this.sourceCategory = sourceCategory;
	}

	@Column(name = "PROCESS_ID", precision = 22, scale = 0)
	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	@Column(name = "DEPUTY_EMP_NO", length = 10)
	public String getDeputyEmpNo() {
		return this.deputyEmpNo;
	}

	public void setDeputyEmpNo(String deputyEmpNo) {
		this.deputyEmpNo = deputyEmpNo;
	}
	@Column(name = "ACTOR_NAME")
	public String getActorName() {
		return actorName;
	}

	public void setActorName(String actorName) {
		this.actorName = actorName;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 7)
	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}


}
