package mro.base.entity.view;

// Generated 2015/1/12 �U�� 03:42:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MroApplySignListId generated by hbm2java
 */
@Entity
@Table(name = "MRO_SIGN_TASK_LIST_V")
public class MroSignTaskListV  implements java.io.Serializable {

	private BigDecimal taskListId;
	private String actorId;
	private Date signDate;
	private String signerComment;
	private String action;
	private BigDecimal signSeqId;
	private String actorDept;
	private String signDescription;
	private Date fromDate;
	private BigDecimal taskId;
	private String name;
	private String actor;
	private String actorDeptName;
	private String lastSignPhase;
	private String deputy;
	private String actionName;

	public MroSignTaskListV() {
	}

	@Id
	@Column(name = "TASK_LIST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskListId() {
		return this.taskListId;
	}

	public void setTaskListId(BigDecimal taskListId) {
		this.taskListId = taskListId;
	}
	@Column(name = "ACTOR_ID", length = 50)
	public String getActorId() {
		return this.actorId;
	}

	public void setActorId(String actorId) {
		this.actorId = actorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIGN_DATE", length = 7)
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	@Column(name = "SIGNER_COMMENT", length = 1024)
	public String getSignerComment() {
		return this.signerComment;
	}

	public void setSignerComment(String signerComment) {
		this.signerComment = signerComment;
	}

	@Column(name = "ACTION", length = 50)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "SIGN_SEQ_ID", precision = 22, scale = 0)
	public BigDecimal getSignSeqId() {
		return this.signSeqId;
	}

	public void setSignSeqId(BigDecimal signSeqId) {
		this.signSeqId = signSeqId;
	}

	@Column(name = "ACTOR_DEPT", length = 50)
	public String getActorDept() {
		return this.actorDept;
	}

	public void setActorDept(String actorDept) {
		this.actorDept = actorDept;
	}

	@Column(name = "SIGN_DESCRIPTION", length = 20)
	public String getSignDescription() {
		return this.signDescription;
	}

	public void setSignDescription(String signDescription) {
		this.signDescription = signDescription;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 7)
	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	@Column(name = "TASK_ID")
	public BigDecimal getTaskId() {
		return taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}


	@Column(name = "ACTOR")
	public String getActor() {
		return actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}
	@Column(name = "ACTOR_DEPT_NAME")
	public String getActorDeptName() {
		return actorDeptName;
	}

	public void setActorDeptName(String actorDeptName) {
		this.actorDeptName = actorDeptName;
	}
	@Column(name = "LAST_SIGN_PHASE")
	public String getLastSignPhase() {
		return lastSignPhase;
	}

	public void setLastSignPhase(String lastSignPhase) {
		this.lastSignPhase = lastSignPhase;
	}
	@Column(name = "DEPUTY")
	public String getDeputy() {
		return deputy;
	}

	public void setDeputy(String deputy) {
		this.deputy = deputy;
	}
	@Column(name = "NAME")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "ACITON_NAME")
	public String getActionName() {
		return actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}
	

}
