package mro.app.item.vo;

// Generated 2012/10/17 �U�� 02:15:15 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Item generated by hbm2java
 */
@Entity
public class ListItemBeanInvvendorVO implements java.io.Serializable {
	private static final long serialVersionUID = -2130541345756905725L;
	private BigDecimal rownum;
	private String vendor;
	private String modelnum;
	private String name;
	private String mcpurcommand;
	
	
	public ListItemBeanInvvendorVO() {
	}

	@Id
	@Column(name = "ROWNUM")
	public BigDecimal getRownum() {
		return rownum;
	}


	public void setRownum(BigDecimal rownum) {
		this.rownum = rownum;
	}

	@Column(name = "VENDOR")
	public String getVendor() {
		return vendor;
	}


	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "MODELNUM")
	public String getModelnum() {
		return modelnum;
	}


	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "NAME")
	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "MCPURCOMMAND")
	public String getMcpurcommand() {
		return mcpurcommand;
	}


	public void setMcpurcommand(String mcpurcommand) {
		this.mcpurcommand = mcpurcommand;
	}
	



}
