package mro.app.item.vo;

// Generated 2012/10/17 �U�� 02:15:15 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@Entity
public class ListItemBeanItemspecVO  implements java.io.Serializable {
	private static final long serialVersionUID = -1160881344752824549L;
	private BigDecimal itemspecid;
	private String itemnum;
	private String assetattrid;
	private BigDecimal rotating;
	private String classstructureid;
	private BigDecimal allasspecusevalue;
	private BigDecimal alllocspecusevalue;
	private BigDecimal displaysequence;
	private BigDecimal numvalue;
	private String measureunitid;
	private String alnvalue;
	private Date changedate;
	private String changeby;
	private String is01;
	private String is02;
	private String is03;
	private Date is04;
	private BigDecimal is05;
	private String orgid;
	private String itemsetid;
	private String section;
	private String duplicateitemspec;
	private String status;
	private String datatype;
	private BigDecimal itemrequirevalue;
	private String assetattributeDescription;
	
	public ListItemBeanItemspecVO() {
	}

	@Id
	@Column(name = "ITEMSPECID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemspecid() {
		return this.itemspecid;
	}

	public void setItemspecid(BigDecimal itemspecid) {
		this.itemspecid = itemspecid;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "ASSETATTRID", nullable = false, length = 8)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Column(name = "ROTATING", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRotating() {
		return this.rotating;
	}

	public void setRotating(BigDecimal rotating) {
		this.rotating = rotating;
	}

	@Column(name = "CLASSSTRUCTUREID", nullable = false, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "ALLASSPECUSEVALUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAllasspecusevalue() {
		return this.allasspecusevalue;
	}

	public void setAllasspecusevalue(BigDecimal allasspecusevalue) {
		this.allasspecusevalue = allasspecusevalue;
	}

	@Column(name = "ALLLOCSPECUSEVALUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAlllocspecusevalue() {
		return this.alllocspecusevalue;
	}

	public void setAlllocspecusevalue(BigDecimal alllocspecusevalue) {
		this.alllocspecusevalue = alllocspecusevalue;
	}

	@Column(name = "DISPLAYSEQUENCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDisplaysequence() {
		return this.displaysequence;
	}

	public void setDisplaysequence(BigDecimal displaysequence) {
		this.displaysequence = displaysequence;
	}

	@Column(name = "NUMVALUE", precision = 10)
	public BigDecimal getNumvalue() {
		return this.numvalue;
	}

	public void setNumvalue(BigDecimal numvalue) {
		this.numvalue = numvalue;
	}

	@Column(name = "MEASUREUNITID", length = 50)
	public String getMeasureunitid() {
		return this.measureunitid;
	}

	public void setMeasureunitid(String measureunitid) {
		this.measureunitid = measureunitid;
	}

	@Column(name = "ALNVALUE", length = 200)
	public String getAlnvalue() {
		return this.alnvalue;
	}

	public void setAlnvalue(String alnvalue) {
		this.alnvalue = alnvalue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGEDATE", nullable = false, length = 7)
	public Date getChangedate() {
		return this.changedate;
	}

	public void setChangedate(Date changedate) {
		this.changedate = changedate;
	}

	@Column(name = "CHANGEBY", nullable = false, length = 30)
	public String getChangeby() {
		return this.changeby;
	}

	public void setChangeby(String changeby) {
		this.changeby = changeby;
	}

	@Column(name = "IS01", length = 10)
	public String getIs01() {
		return this.is01;
	}

	public void setIs01(String is01) {
		this.is01 = is01;
	}

	@Column(name = "IS02", length = 10)
	public String getIs02() {
		return this.is02;
	}

	public void setIs02(String is02) {
		this.is02 = is02;
	}

	@Column(name = "IS03", length = 10)
	public String getIs03() {
		return this.is03;
	}

	public void setIs03(String is03) {
		this.is03 = is03;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IS04", length = 7)
	public Date getIs04() {
		return this.is04;
	}

	public void setIs04(Date is04) {
		this.is04 = is04;
	}

	@Column(name = "IS05", precision = 15)
	public BigDecimal getIs05() {
		return this.is05;
	}

	public void setIs05(BigDecimal is05) {
		this.is05 = is05;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "SECTION", length = 10)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "DUPLICATEITEMSPEC", length = 50)
	public String getDuplicateitemspec() {
		return this.duplicateitemspec;
	}

	public void setDuplicateitemspec(String duplicateitemspec) {
		this.duplicateitemspec = duplicateitemspec;
	}

	@Column(name = "STATUS", length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@Column(name = "ITEMREQUIREVALUE")
	public BigDecimal getItemrequirevalue() {
		return this.itemrequirevalue;
	}

	public void setItemrequirevalue(BigDecimal itemrequirevalue) {
		this.itemrequirevalue = itemrequirevalue;
	}
	
	@Column(name = "ASSETATTRIBUTE_DESCRIPTION")
	public String getAssetattributeDescription() {
		return assetattributeDescription;
	}

	public void setAssetattributeDescription(String assetattributeDescription) {
		this.assetattributeDescription = assetattributeDescription;
	}
	@Column(name = "DATATYPE")
	public String getDatatype() {
		return datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}
}
