package mro.app.item.vo;

// Generated 2012/10/30 �W�� 10:55:39 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Matusetrans generated by hbm2java
 */
@Entity
@Table(name = "MATUSETRANS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SITEID", "MATUSETRANSID" }))
public class ListItemBeanMatusetransVO implements java.io.Serializable {
	private static final long serialVersionUID = -7322727470157945270L;
	private BigDecimal matusetransid;
	private String itemnum;
	private String storeloc;
	private Timestamp transdate;
	private Timestamp actualdate;
	private BigDecimal quantity;
	private BigDecimal curbal;
	private BigDecimal physcnt;
	private BigDecimal unitcost;
	private BigDecimal actualcost;
	private String ponum;
	private BigDecimal conversion;
	private String assetnum;
	private String enterby;
	private String it1;
	private String it2;
	private String it3;
	private BigDecimal it4;
	private String it5;
	private String memo;
	private BigDecimal outside;
	private String issueto;
	private String packingslipnum;
	private BigDecimal polinenum;
	private BigDecimal rollup;
	private String itin1;
	private String itin2;
	private String itin3;
	private String binnum;
	private String lotnum;
	private String issuetype;
	private String gldebitacct;
	private String glcreditacct;
	private BigDecimal linecost;
	private String financialperiod;
	private String currencycode;
	private BigDecimal currencyunitcost;
	private String rotassetnum;
	private BigDecimal currencylinecost;
	private String location;
	private String description;
	private BigDecimal exchangerate;
	private BigDecimal sparepartadded;
	private BigDecimal qtyrequested;
	private BigDecimal exchangerate2;
	private BigDecimal linecost2;
	private String mrnum;
	private BigDecimal mrlinenum;
	private BigDecimal matrectransid;
	private String it6;
	private String it7;
	private String it8;
	private String it9;
	private String it10;
	private String itin4;
	private String itin5;
	private String itin6;
	private String itin7;
	private String sourcesysid;
	private String ownersysid;
	private String externalrefid;
	private String sendersysid;
	private String fincntrlid;
	private BigDecimal issueid;
	private BigDecimal qtyreturned;
	private String orgid;
	private String siteid;
	private String refwo;
	private BigDecimal enteredastask;
	private String linetype;
	private String itemsetid;
	private String conditioncode;
	private BigDecimal condrate;
	private String commoditygroup;
	private String commodity;
	private String tositeid;
	private String langcode;
	private BigDecimal hasld;
	private String rowstamp;
	
	private String workorderAssetnum;

	public ListItemBeanMatusetransVO() {
	}

	@Id
	@Column(name = "MATUSETRANSID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMatusetransid() {
		return this.matusetransid;
	}

	public void setMatusetransid(BigDecimal matusetransid) {
		this.matusetransid = matusetransid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "STORELOC", length = 16)
	public String getStoreloc() {
		return this.storeloc;
	}

	public void setStoreloc(String storeloc) {
		this.storeloc = storeloc;
	}


	@Column(name = "TRANSDATE", nullable = false, length = 7)
	public Timestamp getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Timestamp transdate) {
		this.transdate = transdate;
	}


	@Column(name = "ACTUALDATE", nullable = false, length = 7)
	public Timestamp getActualdate() {
		return this.actualdate;
	}

	public void setActualdate(Timestamp actualdate) {
		this.actualdate = actualdate;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 15)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "CURBAL", nullable = false, precision = 15)
	public BigDecimal getCurbal() {
		return this.curbal;
	}

	public void setCurbal(BigDecimal curbal) {
		this.curbal = curbal;
	}

	@Column(name = "PHYSCNT", nullable = false, precision = 15)
	public BigDecimal getPhyscnt() {
		return this.physcnt;
	}

	public void setPhyscnt(BigDecimal physcnt) {
		this.physcnt = physcnt;
	}

	@Column(name = "UNITCOST", nullable = false, precision = 10)
	public BigDecimal getUnitcost() {
		return this.unitcost;
	}

	public void setUnitcost(BigDecimal unitcost) {
		this.unitcost = unitcost;
	}

	@Column(name = "ACTUALCOST", nullable = false, precision = 10)
	public BigDecimal getActualcost() {
		return this.actualcost;
	}

	public void setActualcost(BigDecimal actualcost) {
		this.actualcost = actualcost;
	}

	@Column(name = "PONUM", length = 80)
	public String getPonum() {
		return this.ponum;
	}

	public void setPonum(String ponum) {
		this.ponum = ponum;
	}

	@Column(name = "CONVERSION", precision = 15)
	public BigDecimal getConversion() {
		return this.conversion;
	}

	public void setConversion(BigDecimal conversion) {
		this.conversion = conversion;
	}

	@Column(name = "ASSETNUM", length = 20)
	public String getAssetnum() {
		return this.assetnum;
	}

	public void setAssetnum(String assetnum) {
		this.assetnum = assetnum;
	}

	@Column(name = "ENTERBY", nullable = false, length = 30)
	public String getEnterby() {
		return this.enterby;
	}

	public void setEnterby(String enterby) {
		this.enterby = enterby;
	}

	@Column(name = "IT1", length = 10)
	public String getIt1() {
		return this.it1;
	}

	public void setIt1(String it1) {
		this.it1 = it1;
	}

	@Column(name = "IT2", length = 10)
	public String getIt2() {
		return this.it2;
	}

	public void setIt2(String it2) {
		this.it2 = it2;
	}

	@Column(name = "IT3", length = 10)
	public String getIt3() {
		return this.it3;
	}

	public void setIt3(String it3) {
		this.it3 = it3;
	}

	@Column(name = "IT4", precision = 15)
	public BigDecimal getIt4() {
		return this.it4;
	}

	public void setIt4(BigDecimal it4) {
		this.it4 = it4;
	}

	@Column(name = "IT5", length = 10)
	public String getIt5() {
		return this.it5;
	}

	public void setIt5(String it5) {
		this.it5 = it5;
	}

	@Column(name = "MEMO", length = 254)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "OUTSIDE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOutside() {
		return this.outside;
	}

	public void setOutside(BigDecimal outside) {
		this.outside = outside;
	}

	@Column(name = "ISSUETO", length = 30)
	public String getIssueto() {
		return this.issueto;
	}

	public void setIssueto(String issueto) {
		this.issueto = issueto;
	}

	@Column(name = "PACKINGSLIPNUM", length = 20)
	public String getPackingslipnum() {
		return this.packingslipnum;
	}

	public void setPackingslipnum(String packingslipnum) {
		this.packingslipnum = packingslipnum;
	}

	@Column(name = "POLINENUM", precision = 22, scale = 0)
	public BigDecimal getPolinenum() {
		return this.polinenum;
	}

	public void setPolinenum(BigDecimal polinenum) {
		this.polinenum = polinenum;
	}

	@Column(name = "ROLLUP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRollup() {
		return this.rollup;
	}

	public void setRollup(BigDecimal rollup) {
		this.rollup = rollup;
	}

	@Column(name = "ITIN1", length = 10)
	public String getItin1() {
		return this.itin1;
	}

	public void setItin1(String itin1) {
		this.itin1 = itin1;
	}

	@Column(name = "ITIN2", length = 10)
	public String getItin2() {
		return this.itin2;
	}

	public void setItin2(String itin2) {
		this.itin2 = itin2;
	}

	@Column(name = "ITIN3", length = 10)
	public String getItin3() {
		return this.itin3;
	}

	public void setItin3(String itin3) {
		this.itin3 = itin3;
	}

	@Column(name = "BINNUM", length = 30)
	public String getBinnum() {
		return this.binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}

	@Column(name = "LOTNUM", length = 8)
	public String getLotnum() {
		return this.lotnum;
	}

	public void setLotnum(String lotnum) {
		this.lotnum = lotnum;
	}

	@Column(name = "ISSUETYPE", nullable = false, length = 20)
	public String getIssuetype() {
		return this.issuetype;
	}

	public void setIssuetype(String issuetype) {
		this.issuetype = issuetype;
	}

	@Column(name = "GLDEBITACCT", length = 10)
	public String getGldebitacct() {
		return this.gldebitacct;
	}

	public void setGldebitacct(String gldebitacct) {
		this.gldebitacct = gldebitacct;
	}

	@Column(name = "GLCREDITACCT", length = 10)
	public String getGlcreditacct() {
		return this.glcreditacct;
	}

	public void setGlcreditacct(String glcreditacct) {
		this.glcreditacct = glcreditacct;
	}

	@Column(name = "LINECOST", nullable = false, precision = 10)
	public BigDecimal getLinecost() {
		return this.linecost;
	}

	public void setLinecost(BigDecimal linecost) {
		this.linecost = linecost;
	}

	@Column(name = "FINANCIALPERIOD", length = 6)
	public String getFinancialperiod() {
		return this.financialperiod;
	}

	public void setFinancialperiod(String financialperiod) {
		this.financialperiod = financialperiod;
	}

	@Column(name = "CURRENCYCODE", nullable = false, length = 8)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "CURRENCYUNITCOST", precision = 10)
	public BigDecimal getCurrencyunitcost() {
		return this.currencyunitcost;
	}

	public void setCurrencyunitcost(BigDecimal currencyunitcost) {
		this.currencyunitcost = currencyunitcost;
	}

	@Column(name = "ROTASSETNUM", length = 20)
	public String getRotassetnum() {
		return this.rotassetnum;
	}

	public void setRotassetnum(String rotassetnum) {
		this.rotassetnum = rotassetnum;
	}

	@Column(name = "CURRENCYLINECOST", precision = 10)
	public BigDecimal getCurrencylinecost() {
		return this.currencylinecost;
	}

	public void setCurrencylinecost(BigDecimal currencylinecost) {
		this.currencylinecost = currencylinecost;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "EXCHANGERATE", precision = 14, scale = 7)
	public BigDecimal getExchangerate() {
		return this.exchangerate;
	}

	public void setExchangerate(BigDecimal exchangerate) {
		this.exchangerate = exchangerate;
	}

	@Column(name = "SPAREPARTADDED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSparepartadded() {
		return this.sparepartadded;
	}

	public void setSparepartadded(BigDecimal sparepartadded) {
		this.sparepartadded = sparepartadded;
	}

	@Column(name = "QTYREQUESTED", precision = 15)
	public BigDecimal getQtyrequested() {
		return this.qtyrequested;
	}

	public void setQtyrequested(BigDecimal qtyrequested) {
		this.qtyrequested = qtyrequested;
	}

	@Column(name = "EXCHANGERATE2", precision = 14, scale = 7)
	public BigDecimal getExchangerate2() {
		return this.exchangerate2;
	}

	public void setExchangerate2(BigDecimal exchangerate2) {
		this.exchangerate2 = exchangerate2;
	}

	@Column(name = "LINECOST2", precision = 10)
	public BigDecimal getLinecost2() {
		return this.linecost2;
	}

	public void setLinecost2(BigDecimal linecost2) {
		this.linecost2 = linecost2;
	}

	@Column(name = "MRNUM", length = 8)
	public String getMrnum() {
		return this.mrnum;
	}

	public void setMrnum(String mrnum) {
		this.mrnum = mrnum;
	}

	@Column(name = "MRLINENUM", precision = 22, scale = 0)
	public BigDecimal getMrlinenum() {
		return this.mrlinenum;
	}

	public void setMrlinenum(BigDecimal mrlinenum) {
		this.mrlinenum = mrlinenum;
	}

	@Column(name = "MATRECTRANSID", precision = 22, scale = 0)
	public BigDecimal getMatrectransid() {
		return this.matrectransid;
	}

	public void setMatrectransid(BigDecimal matrectransid) {
		this.matrectransid = matrectransid;
	}

	@Column(name = "IT6", length = 10)
	public String getIt6() {
		return this.it6;
	}

	public void setIt6(String it6) {
		this.it6 = it6;
	}

	@Column(name = "IT7", length = 10)
	public String getIt7() {
		return this.it7;
	}

	public void setIt7(String it7) {
		this.it7 = it7;
	}

	@Column(name = "IT8", length = 10)
	public String getIt8() {
		return this.it8;
	}

	public void setIt8(String it8) {
		this.it8 = it8;
	}

	@Column(name = "IT9", length = 10)
	public String getIt9() {
		return this.it9;
	}

	public void setIt9(String it9) {
		this.it9 = it9;
	}

	@Column(name = "IT10", length = 10)
	public String getIt10() {
		return this.it10;
	}

	public void setIt10(String it10) {
		this.it10 = it10;
	}

	@Column(name = "ITIN4", length = 10)
	public String getItin4() {
		return this.itin4;
	}

	public void setItin4(String itin4) {
		this.itin4 = itin4;
	}

	@Column(name = "ITIN5", length = 10)
	public String getItin5() {
		return this.itin5;
	}

	public void setItin5(String itin5) {
		this.itin5 = itin5;
	}

	@Column(name = "ITIN6", length = 10)
	public String getItin6() {
		return this.itin6;
	}

	public void setItin6(String itin6) {
		this.itin6 = itin6;
	}

	@Column(name = "ITIN7", length = 10)
	public String getItin7() {
		return this.itin7;
	}

	public void setItin7(String itin7) {
		this.itin7 = itin7;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "FINCNTRLID", length = 8)
	public String getFincntrlid() {
		return this.fincntrlid;
	}

	public void setFincntrlid(String fincntrlid) {
		this.fincntrlid = fincntrlid;
	}

	@Column(name = "ISSUEID", precision = 22, scale = 0)
	public BigDecimal getIssueid() {
		return this.issueid;
	}

	public void setIssueid(BigDecimal issueid) {
		this.issueid = issueid;
	}

	@Column(name = "QTYRETURNED", precision = 15)
	public BigDecimal getQtyreturned() {
		return this.qtyreturned;
	}

	public void setQtyreturned(BigDecimal qtyreturned) {
		this.qtyreturned = qtyreturned;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "REFWO", length = 10)
	public String getRefwo() {
		return this.refwo;
	}

	public void setRefwo(String refwo) {
		this.refwo = refwo;
	}

	@Column(name = "ENTEREDASTASK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEnteredastask() {
		return this.enteredastask;
	}

	public void setEnteredastask(BigDecimal enteredastask) {
		this.enteredastask = enteredastask;
	}

	@Column(name = "LINETYPE", nullable = false, length = 15)
	public String getLinetype() {
		return this.linetype;
	}

	public void setLinetype(String linetype) {
		this.linetype = linetype;
	}

	@Column(name = "ITEMSETID", length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "CONDRATE", precision = 22, scale = 0)
	public BigDecimal getCondrate() {
		return this.condrate;
	}

	public void setCondrate(BigDecimal condrate) {
		this.condrate = condrate;
	}

	@Column(name = "COMMODITYGROUP", length = 8)
	public String getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "COMMODITY", length = 8)
	public String getCommodity() {
		return this.commodity;
	}

	public void setCommodity(String commodity) {
		this.commodity = commodity;
	}

	@Column(name = "TOSITEID", nullable = false, length = 8)
	public String getTositeid() {
		return this.tositeid;
	}

	public void setTositeid(String tositeid) {
		this.tositeid = tositeid;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHasld() {
		return this.hasld;
	}

	public void setHasld(BigDecimal hasld) {
		this.hasld = hasld;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Column(name = "WORKORDER_ASSETNUM")
	public String getWorkorderAssetnum() {
		return workorderAssetnum;
	}

	public void setWorkorderAssetnum(String workorderAssetnum) {
		this.workorderAssetnum = workorderAssetnum;
	}
}
