package mro.app.item.vo;

// Generated 2012/10/30 �W�� 09:47:49 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Sparepart generated by hbm2java
 */
@Entity
public class ListItemBeanDoclinksVO implements java.io.Serializable {
	private static final long serialVersionUID = -2020120369197562246L;

	@Id
	private long doclinksid;

	private BigDecimal docinfoid;

	private String doctype;

	private String document;
	
	private String urlname;
	
	private String description;

	private String docversion;

	private BigDecimal ownerid;

	private String ownertable;



    public ListItemBeanDoclinksVO() {
    }


   
	public long getDoclinksid() {
		return doclinksid;
	}


	public void setDoclinksid(long doclinksid) {
		this.doclinksid = doclinksid;
	}



	public BigDecimal getDocinfoid() {
		return docinfoid;
	}



	public void setDocinfoid(BigDecimal docinfoid) {
		this.docinfoid = docinfoid;
	}



	public String getDoctype() {
		return doctype;
	}



	public void setDoctype(String doctype) {
		this.doctype = doctype;
	}



	public String getDocument() {
		return document;
	}



	public void setDocument(String document) {
		this.document = document;
	}



	public String getUrlname() {
		return urlname;
	}



	public void setUrlname(String urlname) {
		this.urlname = urlname;
	}



	public String getDescription() {
		return description;
	}



	public void setDescription(String description) {
		this.description = description;
	}



	public String getDocversion() {
		return docversion;
	}



	public void setDocversion(String docversion) {
		this.docversion = docversion;
	}



	public BigDecimal getOwnerid() {
		return ownerid;
	}



	public void setOwnerid(BigDecimal ownerid) {
		this.ownerid = ownerid;
	}



	public String getOwnertable() {
		return ownertable;
	}



	public void setOwnertable(String ownertable) {
		this.ownertable = ownertable;
	}

	

}
