package mro.app.item.vo;

// Generated 2012/10/30 �W�� 09:47:49 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Sparepart generated by hbm2java
 */
@Entity
public class ListItemBeanSparepartVO implements java.io.Serializable {
	private static final long serialVersionUID = -6895394951143574806L;
	private BigDecimal sparepartid;
	private String assetnum;
	private String itemnum;
	private BigDecimal quantity;
	private String description;
	private String siteid;
	private String orgid;
	private String itemsetid;
	private String langcode;
	private BigDecimal hasld;
	private String rowstamp;
	
	private String assetDescription;
	
	public ListItemBeanSparepartVO() {
	}

	@Id
	@Column(name = "SPAREPARTID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSparepartid() {
		return this.sparepartid;
	}

	public void setSparepartid(BigDecimal sparepartid) {
		this.sparepartid = sparepartid;
	}

	@Column(name = "ASSETNUM", nullable = false, length = 20)
	public String getAssetnum() {
		return this.assetnum;
	}

	public void setAssetnum(String assetnum) {
		this.assetnum = assetnum;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 15)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHasld() {
		return this.hasld;
	}

	public void setHasld(BigDecimal hasld) {
		this.hasld = hasld;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}
	@Column(name = "ASSET_DESCRIPTION")
	public String getAssetDescription() {
		return assetDescription;
	}

	public void setAssetDescription(String assetDescription) {
		this.assetDescription = assetDescription;
	}

}
