package mro.base.entity;

// Generated 2014/4/29 �U�� 01:56:17 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AItemSimple generated by hbm2java
 */
@Entity
@Table(name = "A_ITEM_SIMPLE")
public class AItemSimple implements java.io.Serializable {

	private BigDecimal AItemSimpleId;
	private String oriitemnum;
	private String applyNum;
	private String changeby;
	private String moqMpqFlag;
	private String assetattrid;
	private Date createDate;
	private Date uploadDate;
	private String updateBy;
	private String errorLog;

	public AItemSimple() {
	}

	public AItemSimple(BigDecimal AItemSimpleId) {
		this.AItemSimpleId = AItemSimpleId;
	}

	public AItemSimple(BigDecimal AItemSimpleId, String oriitemnum,
			String applyNum, String changeby, String moqMpqFlag,
			String assetattrid, Date createDate, Date uploadDate,
			String updateBy,String errorLog) {
		this.AItemSimpleId = AItemSimpleId;
		this.oriitemnum = oriitemnum;
		this.applyNum = applyNum;
		this.changeby = changeby;
		this.moqMpqFlag = moqMpqFlag;
		this.assetattrid = assetattrid;
		this.createDate = createDate;
		this.uploadDate = uploadDate;
		this.updateBy = updateBy;
		this.errorLog = errorLog;
	}

	@Id
	@SequenceGenerator(name="A_ITEM_SIMPLE_ID_GENERATOR", sequenceName="A_ITEM_SIMPLE_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="A_ITEM_SIMPLE_ID_GENERATOR")
	@Column(name = "A_ITEM_SIMPLE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAItemSimpleId() {
		return this.AItemSimpleId;
	}

	public void setAItemSimpleId(BigDecimal AItemSimpleId) {
		this.AItemSimpleId = AItemSimpleId;
	}

	@Column(name = "ORIITEMNUM", length = 30)
	public String getOriitemnum() {
		return this.oriitemnum;
	}

	public void setOriitemnum(String oriitemnum) {
		this.oriitemnum = oriitemnum;
	}

	@Column(name = "APPLY_NUM", length = 30)
	public String getApplyNum() {
		return this.applyNum;
	}

	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	@Column(name = "CHANGEBY", length = 30)
	public String getChangeby() {
		return this.changeby;
	}

	public void setChangeby(String changeby) {
		this.changeby = changeby;
	}

	@Column(name = "MOQ_MPQ_FLAG", length = 1)
	public String getMoqMpqFlag() {
		return this.moqMpqFlag;
	}

	public void setMoqMpqFlag(String moqMpqFlag) {
		this.moqMpqFlag = moqMpqFlag;
	}

	@Column(name = "ASSETATTRID", length = 200)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_DATE", length = 7)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "UPDATE_BY", length = 30)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	@Column(name = "ERROR_LOG")
	public String getErrorLog() {
		return errorLog;
	}

	public void setErrorLog(String errorLog) {
		this.errorLog = errorLog;
	}

}
