package mro.base.entity;

// Generated 2012/12/18 �U�� 03:14:23 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Alndomain generated by hbm2java
 */
@Entity
@Table(name = "ALNDOMAIN", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DOMAINID", "VALUE", "SITEID", "ORGID" }))
public class Alndomain implements java.io.Serializable {

	private BigDecimal alndomainid;
	private String domainid;
	private String value;
	private String description;
	private String siteid;
	private String orgid;
	private Date inactiveDate;

	public Alndomain() {
	}
	
	@Override
	public boolean equals(Object obj) {
	    if(obj instanceof Alndomain && 
	    	((Alndomain)obj).getAlndomainid().compareTo(this.alndomainid)==0) {
	        return true;
	    }else {
	        return false;
	    }
	}
	
	public Alndomain(BigDecimal alndomainid, String domainid, String value) {
		this.alndomainid = alndomainid;
		this.domainid = domainid;
		this.value = value;
	}

	public Alndomain(BigDecimal alndomainid, String domainid, String value,
			String description, String siteid, String orgid,Date inactiveDate) {
		this.alndomainid = alndomainid;
		this.domainid = domainid;
		this.value = value;
		this.description = description;
		this.siteid = siteid;
		this.orgid = orgid;
		this.inactiveDate=inactiveDate;
	}

	@Id
	@SequenceGenerator(name="ALNDOMAIN_ALNDOMAINID_GENERATOR", sequenceName="ALNDOMAINSEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ALNDOMAIN_ALNDOMAINID_GENERATOR")
	@Column(name = "ALNDOMAINID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAlndomainid() {
		return this.alndomainid;
	}

	public void setAlndomainid(BigDecimal alndomainid) {
		this.alndomainid = alndomainid;
	}

	@Column(name = "DOMAINID", nullable = false, length = 18)
	public String getDomainid() {
		return this.domainid;
	}

	public void setDomainid(String domainid) {
		this.domainid = domainid;
	}

	@Column(name = "VALUE", nullable = false, length = 25)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE")
	public Date getInactiveDate() {
		return inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

}
