package mro.base.entity;

// Generated 2014/5/30 �U�� 05:11:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlndomainCommon generated by hbm2java
 */
@Entity
@Table(name = "ALNDOMAIN_COMMON")
public class AlndomainCommon implements java.io.Serializable {

	private BigDecimal alndomainidCommonId;
	private String itemtype;
	private String assetattrid;
	private String value;
	private String description;
	private String siteid;
	private String orgid;
	private String updateBy;
	private Date uploadDate;

	public AlndomainCommon() {
	}

	public AlndomainCommon(BigDecimal alndomainidCommonId, String itemtype,
			String assetattrid, String value) {
		this.alndomainidCommonId = alndomainidCommonId;
		this.itemtype = itemtype;
		this.assetattrid = assetattrid;
		this.value = value;
	}

	public AlndomainCommon(BigDecimal alndomainidCommonId, String itemtype,
			String assetattrid, String value, String description,
			String siteid, String orgid, String updateBy, Date uploadDate) {
		this.alndomainidCommonId = alndomainidCommonId;
		this.itemtype = itemtype;
		this.assetattrid = assetattrid;
		this.value = value;
		this.description = description;
		this.siteid = siteid;
		this.orgid = orgid;
		this.updateBy = updateBy;
		this.uploadDate = uploadDate;
	}

	@Id
	@SequenceGenerator(name="ALNDOMAINID_COMMON_ID_GENERATOR", sequenceName="ALNDOMAIN_COMMON_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ALNDOMAINID_COMMON_ID_GENERATOR")
	@Column(name = "ALNDOMAINID_COMMON_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAlndomainidCommonId() {
		return this.alndomainidCommonId;
	}

	public void setAlndomainidCommonId(BigDecimal alndomainidCommonId) {
		this.alndomainidCommonId = alndomainidCommonId;
	}

	@Column(name = "ITEMTYPE", nullable = false, length = 18)
	public String getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(String itemtype) {
		this.itemtype = itemtype;
	}

	@Column(name = "ASSETATTRID", nullable = false, length = 8)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Column(name = "VALUE", nullable = false, length = 25)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "UPDATE_BY", length = 30)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_DATE", length = 7)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

}
