package mro.base.entity;

// Generated 2012/10/25 �U�� 02:04:05 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Altitem generated by hbm2java
 */
@Entity
@Table(name = "ALTITEM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "ALTITEMNUM", "ITEMSETID", "SITEID" }))
public class Altitem implements java.io.Serializable {

	private BigDecimal altitemid;
	private String itemnum;
	private String altitemnum;
	private String itemsetid;
	private String rowstamp;
	private String notation;
	private String siteid;
	private Date enterdate;
	private String requestedby2;

	public Altitem() {
	}

	public Altitem(BigDecimal altitemid, String itemnum, String altitemnum,
			String itemsetid, String rowstamp) {
		this.altitemid = altitemid;
		this.itemnum = itemnum;
		this.altitemnum = altitemnum;
		this.itemsetid = itemsetid;
		this.rowstamp = rowstamp;
	}

	public Altitem(BigDecimal altitemid, String itemnum, String altitemnum,
			String itemsetid, String rowstamp, String notation, String siteid,
			Date enterdate, String requestedby2) {
		this.altitemid = altitemid;
		this.itemnum = itemnum;
		this.altitemnum = altitemnum;
		this.itemsetid = itemsetid;
		this.rowstamp = rowstamp;
		this.notation = notation;
		this.siteid = siteid;
		this.enterdate = enterdate;
		this.requestedby2 = requestedby2;
	}

	@Id
	@Column(name = "ALTITEMID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAltitemid() {
		return this.altitemid;
	}

	public void setAltitemid(BigDecimal altitemid) {
		this.altitemid = altitemid;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "ALTITEMNUM", nullable = false, length = 30)
	public String getAltitemnum() {
		return this.altitemnum;
	}

	public void setAltitemnum(String altitemnum) {
		this.altitemnum = altitemnum;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Column(name = "NOTATION", length = 100)
	public String getNotation() {
		return this.notation;
	}

	public void setNotation(String notation) {
		this.notation = notation;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTERDATE", length = 7)
	public Date getEnterdate() {
		return this.enterdate;
	}

	public void setEnterdate(Date enterdate) {
		this.enterdate = enterdate;
	}

	@Column(name = "REQUESTEDBY2", length = 30)
	public String getRequestedby2() {
		return this.requestedby2;
	}

	public void setRequestedby2(String requestedby2) {
		this.requestedby2 = requestedby2;
	}

}
