package mro.base.entity;

// Generated 2012/12/18 �U�� 03:11:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Assetattribute generated by hbm2java
 */
@Entity
@Table(name = "ASSETATTRIBUTE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ASSETATTRID", "ORGID", "SITEID" }))
public class Assetattribute implements java.io.Serializable {

	private BigDecimal assetattributeid;
	private String assetattrid;
	private String description;
	private String datatype;
	private String measureunitid;
	private String domainid;
	private String attrdescprefix;
	private String orgid;
	private String siteid;
	private BigDecimal decimalplaces;

	@Override
	public boolean equals(Object obj) {
	    if(obj instanceof Assetattribute && 
	    	((Assetattribute)obj).getAssetattributeid().compareTo(this.assetattributeid)==0) {
	        return true;
	    }else {
	        return false;
	    }
	}
	
	public Assetattribute() {
	}

	public Assetattribute(BigDecimal assetattributeid, String assetattrid,
			String datatype) {
		this.assetattributeid = assetattributeid;
		this.assetattrid = assetattrid;
		this.datatype = datatype;
	}

	public Assetattribute(BigDecimal assetattributeid, String assetattrid,
			String description, String datatype, String measureunitid,
			String domainid, String attrdescprefix, String orgid, String siteid,
			BigDecimal decimalplaces) {
		this.assetattributeid = assetattributeid;
		this.assetattrid = assetattrid;
		this.description = description;
		this.datatype = datatype;
		this.measureunitid = measureunitid;
		this.domainid = domainid;
		this.attrdescprefix = attrdescprefix;
		this.orgid = orgid;
		this.siteid = siteid;
		this.decimalplaces = decimalplaces;
	}

	@Id
	@SequenceGenerator(name="ASSETATTRIBUTEID_GENERATOR", sequenceName="ASSETATTRIBUTESEQ" ,allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ASSETATTRIBUTEID_GENERATOR")
	@Column(name = "ASSETATTRIBUTEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAssetattributeid() {
		return this.assetattributeid;
	}

	public void setAssetattributeid(BigDecimal assetattributeid) {
		this.assetattributeid = assetattributeid;
	}

	@Column(name = "ASSETATTRID", nullable = false, length = 8)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DATATYPE", nullable = false, length = 8)
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "MEASUREUNITID", length = 50)
	public String getMeasureunitid() {
		return this.measureunitid;
	}

	public void setMeasureunitid(String measureunitid) {
		this.measureunitid = measureunitid;
	}

	@Column(name = "DOMAINID", length = 18)
	public String getDomainid() {
		return this.domainid;
	}

	public void setDomainid(String domainid) {
		this.domainid = domainid;
	}

	@Column(name = "ATTRDESCPREFIX", length = 120)
	public String getAttrdescprefix() {
		return this.attrdescprefix;
	}

	public void setAttrdescprefix(String attrdescprefix) {
		this.attrdescprefix = attrdescprefix;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}
	@Column(name = "DECIMALPLACES")
	public BigDecimal getDecimalplaces() {
		return decimalplaces;
	}

	public void setDecimalplaces(BigDecimal decimalplaces) {
		this.decimalplaces = decimalplaces;
	}

}
