package mro.base.entity;

// Generated 2016/10/3 �U�� 05:10:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BulletinboardSite generated by hbm2java
 */
@Entity
@Table(name = "BULLETINBOARD_SITE")
public class BulletinboardSite implements java.io.Serializable {

	private String id;
	private Bulletinboard bulletinboard;
	private LocationSiteMap locationSiteMap;

	public BulletinboardSite() {
	}

	public BulletinboardSite(String id, Bulletinboard bulletinboard,
			LocationSiteMap locationSiteMap) {
		this.id = id;
		this.bulletinboard = bulletinboard;
		this.locationSiteMap = locationSiteMap;
	}

	@Id	
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BULLETINBOARDID")
	public Bulletinboard getBulletinboard() {
		return bulletinboard;
	}

	public void setBulletinboard(Bulletinboard bulletinboard) {
		this.bulletinboard = bulletinboard;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}

}
