package mro.base.entity;

// Generated 2014/4/29 �U�� 03:13:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bulletinboard generated by hbm2java
 */
@Entity
@Table(name = "BULLETINBOARD")
public class Bulletinboard implements java.io.Serializable {

	private BigDecimal bulletinboardid;
	private String subject;
	private String message;
	private String postby;
	private Date postdate;
	private Date expiredate;
	private String type;

	public Bulletinboard() {
	}

	public Bulletinboard(BigDecimal bulletinboardid, String subject, String postby,
			Date postdate, Date expiredate) {
		this.bulletinboardid = bulletinboardid;
		this.subject = subject;
		this.postby = postby;
		this.postdate = postdate;
		this.expiredate = expiredate;
	}

	public Bulletinboard(BigDecimal bulletinboardid, String subject,
			String message, String postby, Date postdate, Date expiredate,
			String type) {
		this.bulletinboardid = bulletinboardid;
		this.subject = subject;
		this.message = message;
		this.postby = postby;
		this.postdate = postdate;
		this.expiredate = expiredate;
		this.type = type;
	}

	@Id 
	@SequenceGenerator(name="BULLETINBOARDID_GENERATOR", sequenceName="BULLETINBOARDSEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="BULLETINBOARDID_GENERATOR")
	@Column(name = "BULLETINBOARDID", unique = true, nullable = false, length = 10)
	public BigDecimal getBulletinboardid() {
		return this.bulletinboardid;
	}

	public void setBulletinboardid(BigDecimal bulletinboardid) {
		this.bulletinboardid = bulletinboardid;
	}

	@Column(name = "SUBJECT", nullable = false, length = 300)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "MESSAGE", length = 4000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "POSTBY", nullable = false, length = 18)
	public String getPostby() {
		return this.postby;
	}

	public void setPostby(String postby) {
		this.postby = postby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "POSTDATE", nullable = false, length = 7)
	public Date getPostdate() {
		return this.postdate;
	}

	public void setPostdate(Date postdate) {
		this.postdate = postdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIREDATE", nullable = false, length = 7)
	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}
	
	@Column(name = "TYPE")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
