package mro.base.entity;

// Generated 2013/10/7 �U�� 04:40:49 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClassstructureItemchangeSign generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_ITEMCHANGE_SIGN", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CLASSSTRUCTUREID", "PLANT_CODE" }))
public class ClassstructureItemchangeSign implements java.io.Serializable {

	private BigDecimal itemChangeSignId;
	private String classstructureid;
	private String plantCode;
	private String ehsEmpno;
	private String gpEmpno;
	private String bondedEmpno;
	private String buyerEmpno;
	private String mcEmpno;
	private String itemGroupEmpno;
	private Date lastUpdate;
	private String lastUpdateBy;
	private String finalAppoveNotifyEmpno;
	private String disciplinaryBoard;

	public ClassstructureItemchangeSign() {
	}

	public ClassstructureItemchangeSign(BigDecimal itemChangeSignId) {
		this.itemChangeSignId = itemChangeSignId;
	}

	public ClassstructureItemchangeSign(BigDecimal itemChangeSignId,
			String classstructureid, String plantCode, String ehsEmpno,
			String gpEmpno, String bondedEmpno, String buyerEmpno,
			String mcEmpno, String itemGroupEmpno, Date lastUpdate,
			String lastUpdateBy, String finalAppoveNotifyEmpno,String disciplinaryBoard) {
		this.itemChangeSignId = itemChangeSignId;
		this.classstructureid = classstructureid;
		this.plantCode = plantCode;
		this.ehsEmpno = ehsEmpno;
		this.gpEmpno = gpEmpno;
		this.bondedEmpno = bondedEmpno;
		this.buyerEmpno = buyerEmpno;
		this.mcEmpno = mcEmpno;
		this.itemGroupEmpno = itemGroupEmpno;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.finalAppoveNotifyEmpno = finalAppoveNotifyEmpno;
		this.disciplinaryBoard =disciplinaryBoard;
	}

	@Id
	@SequenceGenerator(name="ITEM_CHANGE_SIGN_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_ITEM_SIGN_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ITEM_CHANGE_SIGN_ID_GENERATOR")
	@Column(name = "ITEM_CHANGE_SIGN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemChangeSignId() {
		return this.itemChangeSignId;
	}

	public void setItemChangeSignId(BigDecimal itemChangeSignId) {
		this.itemChangeSignId = itemChangeSignId;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "PLANT_CODE", length = 26)
	public String getPlantCode() {
		return this.plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	@Column(name = "EHS_EMPNO", length = 30)
	public String getEhsEmpno() {
		return this.ehsEmpno;
	}

	public void setEhsEmpno(String ehsEmpno) {
		this.ehsEmpno = ehsEmpno;
	}

	@Column(name = "GP_EMPNO", length = 30)
	public String getGpEmpno() {
		return this.gpEmpno;
	}

	public void setGpEmpno(String gpEmpno) {
		this.gpEmpno = gpEmpno;
	}

	@Column(name = "BONDED_EMPNO", length = 30)
	public String getBondedEmpno() {
		return this.bondedEmpno;
	}

	public void setBondedEmpno(String bondedEmpno) {
		this.bondedEmpno = bondedEmpno;
	}

	@Column(name = "BUYER_EMPNO", length = 30)
	public String getBuyerEmpno() {
		return this.buyerEmpno;
	}

	public void setBuyerEmpno(String buyerEmpno) {
		this.buyerEmpno = buyerEmpno;
	}

	@Column(name = "MC_EMPNO", length = 30)
	public String getMcEmpno() {
		return this.mcEmpno;
	}

	public void setMcEmpno(String mcEmpno) {
		this.mcEmpno = mcEmpno;
	}

	@Column(name = "ITEM_GROUP_EMPNO", length = 30)
	public String getItemGroupEmpno() {
		return this.itemGroupEmpno;
	}

	public void setItemGroupEmpno(String itemGroupEmpno) {
		this.itemGroupEmpno = itemGroupEmpno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Column(name = "FINAL_APPOVE_NOTIFY_EMPNO", length = 500)
	public String getFinalAppoveNotifyEmpno() {
		return this.finalAppoveNotifyEmpno;
	}

	public void setFinalAppoveNotifyEmpno(String finalAppoveNotifyEmpno) {
		this.finalAppoveNotifyEmpno = finalAppoveNotifyEmpno;
	}

	@Column(name = "DISCIPLINARY_BOARD")
	public String getDisciplinaryBoard() {
		return disciplinaryBoard;
	}

	public void setDisciplinaryBoard(String disciplinaryBoard) {
		this.disciplinaryBoard = disciplinaryBoard;
	}
}
