package mro.base.entity;

// Generated 2013/3/21 �U�� 01:55:15 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassstructureSign generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_SIGN")
public class ClassstructureSign implements java.io.Serializable {

	private BigDecimal classstructureSignId;
	private String plantCode;
	private String classstructureid;
	private String controlMcEmpno;
	private String pmreqMcEmpno;
	private Date lastUpdate;
	private String lastUpdateBy;

	public ClassstructureSign() {
	}

	public ClassstructureSign(BigDecimal classstructureSignId) {
		this.classstructureSignId = classstructureSignId;
	}

	public ClassstructureSign(BigDecimal classstructureSignId,
			String plantCode, String classstructureid,
			String controlMcEmpno, String pmreqMcEmpno,
			Date lastUpdate, String lastUpdateBy) {
		this.classstructureSignId = classstructureSignId;
		this.plantCode = plantCode;
		this.classstructureid = classstructureid;
		this.controlMcEmpno = controlMcEmpno;
		this.pmreqMcEmpno = pmreqMcEmpno;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@SequenceGenerator(name="CLASSSTRUCTURE_SIGN_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_SIGN_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CLASSSTRUCTURE_SIGN_ID_GENERATOR")
	@Column(name = "CLASSSTRUCTURE_SIGN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getClassstructureSignId() {
		return this.classstructureSignId;
	}

	public void setClassstructureSignId(BigDecimal classstructureSignId) {
		this.classstructureSignId = classstructureSignId;
	}

	@Column(name = "PLANT_CODE", length = 20)
	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}


	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "CONTROL_MC_EMPNO", length = 30)
	public String getControlMcEmpno() {
		return this.controlMcEmpno;
	}

	public void setControlMcEmpno(String controlMcEmpno) {
		this.controlMcEmpno = controlMcEmpno;
	}

	@Column(name = "PMREQ_MC_EMPNO", length = 30)
	public String getPmreqMcEmpno() {
		return this.pmreqMcEmpno;
	}

	public void setPmreqMcEmpno(String pmreqMcEmpno) {
		this.pmreqMcEmpno = pmreqMcEmpno;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}
}
