package mro.base.entity;

// Generated 2014/8/18 �W�� 10:02:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassstructureLineApply generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_LINE_APPLY")
public class ClassstructureLineApply implements java.io.Serializable {

	private BigDecimal applyLineId;
	private ClassstructureHeaderApply classstructureHeaderApply;
	private String classstructureid;
	private String domainid;
	private Date inactiveDate;
	private BigDecimal lineNum;
	private String lineRemark;
	private String createBy;
	private Date createDate;
	private String value;
	private String description;
	private String assetattrid;
	private String changeTypeFlag;
	private Alndomain alndomain;

	public ClassstructureLineApply() {
	}

	public ClassstructureLineApply(BigDecimal applyLineId) {
		this.applyLineId = applyLineId;
	}
	public ClassstructureLineApply(BigDecimal applyLineId,
			ClassstructureHeaderApply classstructureHeaderApply,
			String classstructureid, String domainid,Date inactiveDate, BigDecimal lineNum,
			String lineRemark, String createBy, Date createDate, String value,
			String description,String assetattrid,String changeTypeFlag,Alndomain alndomain) {
		this.applyLineId = applyLineId;
		this.classstructureHeaderApply = classstructureHeaderApply;
		this.classstructureid = classstructureid;
		this.domainid = domainid;
		this.inactiveDate = inactiveDate;
		this.lineNum = lineNum;
		this.lineRemark = lineRemark;
		this.createBy = createBy;
		this.createDate = createDate;
		this.value = value;
		this.description = description;
		this.assetattrid = assetattrid;
		this.changeTypeFlag = changeTypeFlag;
		this.alndomain = alndomain;
	}

	@Id
	@SequenceGenerator(name="APPLY_LINE_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_LINE_APPLY_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="APPLY_LINE_ID_GENERATOR")
	@Column(name = "APPLY_LINE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getApplyLineId() {
		return this.applyLineId;
	}

	public void setApplyLineId(BigDecimal applyLineId) {
		this.applyLineId = applyLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLY_HEADER_ID")
	public ClassstructureHeaderApply getClassstructureHeaderApply() {
		return this.classstructureHeaderApply;
	}

	public void setClassstructureHeaderApply(
			ClassstructureHeaderApply classstructureHeaderApply) {
		this.classstructureHeaderApply = classstructureHeaderApply;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}



	@Column(name = "DOMAINID", length = 18)
	public String getDomainid() {
		return this.domainid;
	}

	public void setDomainid(String domainid) {
		this.domainid = domainid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	@Column(name = "LINE_NUM", precision = 22, scale = 0)
	public BigDecimal getLineNum() {
		return this.lineNum;
	}

	public void setLineNum(BigDecimal lineNum) {
		this.lineNum = lineNum;
	}

	@Column(name = "LINE_REMARK", length = 500)
	public String getLineRemark() {
		return this.lineRemark;
	}

	public void setLineRemark(String lineRemark) {
		this.lineRemark = lineRemark;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "VALUE", length = 25)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name = "ASSETATTRID")
	public String getAssetattrid() {
		return assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}
	@Column(name = "CHANGE_TYPE_FLAG")
	public String getChangeTypeFlag() {
		return changeTypeFlag;
	}

	public void setChangeTypeFlag(String changeTypeFlag) {
		this.changeTypeFlag = changeTypeFlag;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALNDOMAINID")
	public Alndomain getAlndomain() {
		return alndomain;
	}

	public void setAlndomain(Alndomain alndomain) {
		this.alndomain = alndomain;
	}
	

}
