package mro.base.entity;

// Generated 2012/12/24 �U�� 12:02:27 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Classspec generated by hbm2java
 */
@Entity
@Table(name = "CLASSSPEC", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CLASSSTRUCTUREID", "ASSETATTRID", "SECTION", "ORGID", "SITEID" }))
public class Classspec implements java.io.Serializable {

	private BigDecimal classspecid;
	private String classstructureid;
	private String assetattrid;
	private String measureunitid;
	private String domainid;
	private BigDecimal defaultnumvalue;
	private String defaultalnvalue;
	private String attrdescprefix;
	private BigDecimal useinitemspec;
	private BigDecimal itemsequence;
	private BigDecimal itemrequirevalue;
	private BigDecimal useinitemdesc;
	private BigDecimal useinassetspec;
	private BigDecimal assetsequence;
	private BigDecimal assetrequirevalue;
	private BigDecimal useinassetdesc;
	private BigDecimal useinlocspec;
	private BigDecimal locsequence;
	private BigDecimal locrequirevalue;
	private BigDecimal useinlocdesc;
	private String cs01;
	private String cs02;
	private String cs03;
	private Date cs04;
	private BigDecimal cs05;
	private String orgid;
	private String section;
	private String siteid;
	private Date inactiveDate;

	public Classspec() {
	}

	public Classspec(BigDecimal classspecid, String classstructureid,
			String assetattrid, BigDecimal itemsequence,
			BigDecimal itemrequirevalue) {
		this.classspecid = classspecid;
		this.classstructureid = classstructureid;
		this.assetattrid = assetattrid;
		this.itemsequence = itemsequence;
		this.itemrequirevalue = itemrequirevalue;
	}

	public Classspec(BigDecimal classspecid, String classstructureid,
			String assetattrid, String measureunitid, String domainid,
			BigDecimal defaultnumvalue, String defaultalnvalue,
			String attrdescprefix, BigDecimal useinitemspec,
			BigDecimal itemsequence, BigDecimal itemrequirevalue,
			BigDecimal useinitemdesc, BigDecimal useinassetspec,
			BigDecimal assetsequence, BigDecimal assetrequirevalue,
			BigDecimal useinassetdesc, BigDecimal useinlocspec,
			BigDecimal locsequence, BigDecimal locrequirevalue,
			BigDecimal useinlocdesc, String cs01, String cs02, String cs03,
			Date cs04, BigDecimal cs05, String orgid, String section,
			String siteid, Date inactiveDate) {
		this.classspecid = classspecid;
		this.classstructureid = classstructureid;
		this.assetattrid = assetattrid;
		this.measureunitid = measureunitid;
		this.domainid = domainid;
		this.defaultnumvalue = defaultnumvalue;
		this.defaultalnvalue = defaultalnvalue;
		this.attrdescprefix = attrdescprefix;
		this.useinitemspec = useinitemspec;
		this.itemsequence = itemsequence;
		this.itemrequirevalue = itemrequirevalue;
		this.useinitemdesc = useinitemdesc;
		this.useinassetspec = useinassetspec;
		this.assetsequence = assetsequence;
		this.assetrequirevalue = assetrequirevalue;
		this.useinassetdesc = useinassetdesc;
		this.useinlocspec = useinlocspec;
		this.locsequence = locsequence;
		this.locrequirevalue = locrequirevalue;
		this.useinlocdesc = useinlocdesc;
		this.cs01 = cs01;
		this.cs02 = cs02;
		this.cs03 = cs03;
		this.cs04 = cs04;
		this.cs05 = cs05;
		this.orgid = orgid;
		this.section = section;
		this.siteid = siteid;
		this.inactiveDate = inactiveDate;
	}

	@Id
	@SequenceGenerator(name="CLASSSPECID_GENERATOR", sequenceName="CLASSSPECSEQ" ,allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CLASSSPECID_GENERATOR")
	@Column(name = "CLASSSPECID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getClassspecid() {
		return this.classspecid;
	}

	public void setClassspecid(BigDecimal classspecid) {
		this.classspecid = classspecid;
	}

	@Column(name = "CLASSSTRUCTUREID", nullable = false, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "ASSETATTRID", nullable = false, length = 8)
	public String getAssetattrid() {
		return this.assetattrid;
	}

	public void setAssetattrid(String assetattrid) {
		this.assetattrid = assetattrid;
	}

	@Column(name = "MEASUREUNITID", length = 50)
	public String getMeasureunitid() {
		return this.measureunitid;
	}

	public void setMeasureunitid(String measureunitid) {
		this.measureunitid = measureunitid;
	}

	@Column(name = "DOMAINID", length = 18)
	public String getDomainid() {
		return this.domainid;
	}

	public void setDomainid(String domainid) {
		this.domainid = domainid;
	}

	@Column(name = "DEFAULTNUMVALUE", precision = 10)
	public BigDecimal getDefaultnumvalue() {
		return this.defaultnumvalue;
	}

	public void setDefaultnumvalue(BigDecimal defaultnumvalue) {
		this.defaultnumvalue = defaultnumvalue;
	}

	@Column(name = "DEFAULTALNVALUE", length = 25)
	public String getDefaultalnvalue() {
		return this.defaultalnvalue;
	}

	public void setDefaultalnvalue(String defaultalnvalue) {
		this.defaultalnvalue = defaultalnvalue;
	}

	@Column(name = "ATTRDESCPREFIX", length = 120)
	public String getAttrdescprefix() {
		return this.attrdescprefix;
	}

	public void setAttrdescprefix(String attrdescprefix) {
		this.attrdescprefix = attrdescprefix;
	}

	@Column(name = "USEINITEMSPEC", precision = 22, scale = 0)
	public BigDecimal getUseinitemspec() {
		return this.useinitemspec;
	}

	public void setUseinitemspec(BigDecimal useinitemspec) {
		this.useinitemspec = useinitemspec;
	}

	@Column(name = "ITEMSEQUENCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemsequence() {
		return this.itemsequence;
	}

	public void setItemsequence(BigDecimal itemsequence) {
		this.itemsequence = itemsequence;
	}

	@Column(name = "ITEMREQUIREVALUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemrequirevalue() {
		return this.itemrequirevalue;
	}

	public void setItemrequirevalue(BigDecimal itemrequirevalue) {
		this.itemrequirevalue = itemrequirevalue;
	}

	@Column(name = "USEINITEMDESC", precision = 22, scale = 0)
	public BigDecimal getUseinitemdesc() {
		return this.useinitemdesc;
	}

	public void setUseinitemdesc(BigDecimal useinitemdesc) {
		this.useinitemdesc = useinitemdesc;
	}

	@Column(name = "USEINASSETSPEC", precision = 22, scale = 0)
	public BigDecimal getUseinassetspec() {
		return this.useinassetspec;
	}

	public void setUseinassetspec(BigDecimal useinassetspec) {
		this.useinassetspec = useinassetspec;
	}

	@Column(name = "ASSETSEQUENCE", precision = 22, scale = 0)
	public BigDecimal getAssetsequence() {
		return this.assetsequence;
	}

	public void setAssetsequence(BigDecimal assetsequence) {
		this.assetsequence = assetsequence;
	}

	@Column(name = "ASSETREQUIREVALUE", precision = 22, scale = 0)
	public BigDecimal getAssetrequirevalue() {
		return this.assetrequirevalue;
	}

	public void setAssetrequirevalue(BigDecimal assetrequirevalue) {
		this.assetrequirevalue = assetrequirevalue;
	}

	@Column(name = "USEINASSETDESC", precision = 22, scale = 0)
	public BigDecimal getUseinassetdesc() {
		return this.useinassetdesc;
	}

	public void setUseinassetdesc(BigDecimal useinassetdesc) {
		this.useinassetdesc = useinassetdesc;
	}

	@Column(name = "USEINLOCSPEC", precision = 22, scale = 0)
	public BigDecimal getUseinlocspec() {
		return this.useinlocspec;
	}

	public void setUseinlocspec(BigDecimal useinlocspec) {
		this.useinlocspec = useinlocspec;
	}

	@Column(name = "LOCSEQUENCE", precision = 22, scale = 0)
	public BigDecimal getLocsequence() {
		return this.locsequence;
	}

	public void setLocsequence(BigDecimal locsequence) {
		this.locsequence = locsequence;
	}

	@Column(name = "LOCREQUIREVALUE", precision = 22, scale = 0)
	public BigDecimal getLocrequirevalue() {
		return this.locrequirevalue;
	}

	public void setLocrequirevalue(BigDecimal locrequirevalue) {
		this.locrequirevalue = locrequirevalue;
	}

	@Column(name = "USEINLOCDESC", precision = 22, scale = 0)
	public BigDecimal getUseinlocdesc() {
		return this.useinlocdesc;
	}

	public void setUseinlocdesc(BigDecimal useinlocdesc) {
		this.useinlocdesc = useinlocdesc;
	}

	@Column(name = "CS01", length = 10)
	public String getCs01() {
		return this.cs01;
	}

	public void setCs01(String cs01) {
		this.cs01 = cs01;
	}

	@Column(name = "CS02", length = 10)
	public String getCs02() {
		return this.cs02;
	}

	public void setCs02(String cs02) {
		this.cs02 = cs02;
	}

	@Column(name = "CS03", length = 10)
	public String getCs03() {
		return this.cs03;
	}

	public void setCs03(String cs03) {
		this.cs03 = cs03;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CS04", length = 7)
	public Date getCs04() {
		return this.cs04;
	}

	public void setCs04(Date cs04) {
		this.cs04 = cs04;
	}

	@Column(name = "CS05", precision = 15)
	public BigDecimal getCs05() {
		return this.cs05;
	}

	public void setCs05(BigDecimal cs05) {
		this.cs05 = cs05;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SECTION", length = 10)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

}
