package mro.base.entity;

// Generated 2014/8/18 �U�� 02:38:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassstructureApplySign generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_APPLY_SIGN")
public class ClassstructureApplySign implements java.io.Serializable {

	private String classstructureid;
	private String MGSigner;
	private Date lastUpdate;
	private String lastUpdateBy;

	public ClassstructureApplySign() {
	}

	public ClassstructureApplySign(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	public ClassstructureApplySign(String classstructureid, String MGSigner,
			Date lastUpdate, String lastUpdateBy) {
		this.classstructureid = classstructureid;
		this.MGSigner = MGSigner;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@Column(name = "CLASSSTRUCTUREID", unique = true, nullable = false, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "M_G_SIGNER", length = 30)
	public String getMGSigner() {
		return this.MGSigner;
	}

	public void setMGSigner(String MGSigner) {
		this.MGSigner = MGSigner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
