package mro.base.entity;

// Generated 2014/1/3 �U�� 04:16:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClassstructureItemSiteSign generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_ITEM_SITE_SIGN", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CLASSSTRUCTUREID", "LOCATION_SITE" }))
public class ClassstructureItemSiteSign implements java.io.Serializable {

	private BigDecimal itemSiteSignId;
	private String classstructureid;
	private String locationSite;
	private String ehsEmpno;
	private String mcEmpno;
	private String itemGroupEmpno;
	private Date lastUpdate;
	private String lastUpdateBy;
	private String finalAppoveNotifyEmpno;
	private String buyerEmpno;
	private String mc2Empno;
	private String disciplinaryBoard;
	private String addBuyerEmpno;

	public ClassstructureItemSiteSign() {
	}

	public ClassstructureItemSiteSign(BigDecimal itemSiteSignId) {
		this.itemSiteSignId = itemSiteSignId;
	}

	public ClassstructureItemSiteSign(BigDecimal itemSiteSignId,
			String classstructureid, String locationSite, String ehsEmpno,
			String mcEmpno, String itemGroupEmpno, Date lastUpdate,
			String lastUpdateBy, String finalAppoveNotifyEmpno,String buyerEmpno,
			String mc2Empno,String disciplinaryBoard,String addBuyerEmpno) {
		this.itemSiteSignId = itemSiteSignId;
		this.classstructureid = classstructureid;
		this.locationSite = locationSite;
		this.ehsEmpno = ehsEmpno;
		this.mcEmpno = mcEmpno;
		this.itemGroupEmpno = itemGroupEmpno;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.finalAppoveNotifyEmpno = finalAppoveNotifyEmpno;
		this.buyerEmpno = buyerEmpno;
		this.mc2Empno = mc2Empno;
		this.disciplinaryBoard =disciplinaryBoard;
		this.addBuyerEmpno = addBuyerEmpno;
	}

	@Id
	@SequenceGenerator(name="ITEM_SITE_SIGN_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_ITEM_SITE_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ITEM_SITE_SIGN_ID_GENERATOR")
	@Column(name = "ITEM_SITE_SIGN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemSiteSignId() {
		return this.itemSiteSignId;
	}

	public void setItemSiteSignId(BigDecimal itemSiteSignId) {
		this.itemSiteSignId = itemSiteSignId;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "LOCATION_SITE", length = 26)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "EHS_EMPNO", length = 30)
	public String getEhsEmpno() {
		return this.ehsEmpno;
	}

	public void setEhsEmpno(String ehsEmpno) {
		this.ehsEmpno = ehsEmpno;
	}

	@Column(name = "MC_EMPNO", length = 30)
	public String getMcEmpno() {
		return this.mcEmpno;
	}

	public void setMcEmpno(String mcEmpno) {
		this.mcEmpno = mcEmpno;
	}

	@Column(name = "ITEM_GROUP_EMPNO", length = 30)
	public String getItemGroupEmpno() {
		return this.itemGroupEmpno;
	}

	public void setItemGroupEmpno(String itemGroupEmpno) {
		this.itemGroupEmpno = itemGroupEmpno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Column(name = "FINAL_APPOVE_NOTIFY_EMPNO", length = 500)
	public String getFinalAppoveNotifyEmpno() {
		return this.finalAppoveNotifyEmpno;
	}

	public void setFinalAppoveNotifyEmpno(String finalAppoveNotifyEmpno) {
		this.finalAppoveNotifyEmpno = finalAppoveNotifyEmpno;
	}
	@Column(name = "BUYER_EMPNO")
	public String getBuyerEmpno() {
		return buyerEmpno;
	}

	public void setBuyerEmpno(String buyerEmpno) {
		this.buyerEmpno = buyerEmpno;
	}
	@Column(name = "MC2_EMPNO", length = 30)
	public String getMc2Empno() {
		return mc2Empno;
	}

	public void setMc2Empno(String mc2Empno) {
		this.mc2Empno = mc2Empno;
	}

	@Column(name = "DISCIPLINARY_BOARD")
	public String getDisciplinaryBoard() {
		return disciplinaryBoard;
	}

	public void setDisciplinaryBoard(String disciplinaryBoard) {
		this.disciplinaryBoard = disciplinaryBoard;
	}
	@Column(name = "ADD_BUYER_EMPNO")
	public String getAddBuyerEmpno() {
		return addBuyerEmpno;
	}

	public void setAddBuyerEmpno(String addBuyerEmpno) {
		this.addBuyerEmpno = addBuyerEmpno;
	}
	
}
