package mro.base.entity;

// Generated 2014/3/11 �U�� 02:27:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassstructurePrtype generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_PRTYPE")
public class ClassstructurePrtype implements java.io.Serializable {

	private BigDecimal classstructurePrtypeId;
	private String classstructureid;
	private String prtype;
	private Date lastUpdate;
	private String lastUpdateBy;

	public ClassstructurePrtype() {
	}

	public ClassstructurePrtype(BigDecimal classstructurePrtypeId,
			String classstructureid, String prtype) {
		this.classstructurePrtypeId = classstructurePrtypeId;
		this.classstructureid = classstructureid;
		this.prtype = prtype;
	}

	public ClassstructurePrtype(BigDecimal classstructurePrtypeId,
			String classstructureid, String prtype, Date lastUpdate,
			String lastUpdateBy) {
		this.classstructurePrtypeId = classstructurePrtypeId;
		this.classstructureid = classstructureid;
		this.prtype = prtype;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@SequenceGenerator(name="CLASSSTRUCTURE_PRTYPE_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_PRTYPE_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CLASSSTRUCTURE_PRTYPE_ID_GENERATOR")
	@Column(name = "CLASSSTRUCTURE_PRTYPE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getClassstructurePrtypeId() {
		return this.classstructurePrtypeId;
	}

	public void setClassstructurePrtypeId(BigDecimal classstructurePrtypeId) {
		this.classstructurePrtypeId = classstructurePrtypeId;
	}

	@Column(name = "CLASSSTRUCTUREID", nullable = false, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "PRTYPE", nullable = false, length = 30)
	public String getPrtype() {
		return this.prtype;
	}

	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 20)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
