package mro.base.entity;

// Generated 2012/12/17 �W�� 10:56:26 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Classstructure generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE")
public class Classstructure implements java.io.Serializable {

	private Long classstructureuid;
	private String classstructureid;
	private String description;
	private String orgid;
	private String parent;
	private String classificationid;
	private String type;
	private String siteid;
	private Long haschildren;
	private Date enterdate;
	private Date inactiveDate;
	private String storeCategory;
	
	public Classstructure() {
	}

	public Classstructure(Long classstructureuid,
			String classstructureid, String classificationid,
			Long haschildren) {
		this.classstructureuid = classstructureuid;
		this.classstructureid = classstructureid;
		this.classificationid = classificationid;
		this.haschildren = haschildren;
	}

	public Classstructure(Long classstructureuid,
			String classstructureid, String description, String orgid,
			String parent, String classificationid, String type, String siteid,
			Long haschildren, Date enterdate, Date inactiveDate,String storeCategory) {
		this.classstructureuid = classstructureuid;
		this.classstructureid = classstructureid;
		this.description = description;
		this.orgid = orgid;
		this.parent = parent;
		this.classificationid = classificationid;
		this.type = type;
		this.siteid = siteid;
		this.haschildren = haschildren;
		this.enterdate = enterdate;
		this.inactiveDate = inactiveDate;
		this.storeCategory = storeCategory;
	}

	@Id
	@SequenceGenerator(name="CLASSSTRUCTURE_CLASSSTRUCTUREUID_GENERATOR", sequenceName="CLASSSTRUCTURESEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="CLASSSTRUCTURE_CLASSSTRUCTUREUID_GENERATOR")
	@Column(name = "CLASSSTRUCTUREUID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getClassstructureuid() {
		return this.classstructureuid;
	}

	public void setClassstructureuid(Long classstructureuid) {
		this.classstructureuid = classstructureuid;
	}

	@Column(name = "CLASSSTRUCTUREID", nullable = false, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "PARENT", length = 26)
	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	@Column(name = "CLASSIFICATIONID", nullable = false, length = 26)
	public String getClassificationid() {
		return this.classificationid;
	}

	public void setClassificationid(String classificationid) {
		this.classificationid = classificationid;
	}

	@Column(name = "TYPE", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "HASCHILDREN", nullable = false, precision = 22, scale = 0)
	public Long getHaschildren() {
		return this.haschildren;
	}

	public void setHaschildren(Long haschildren) {
		this.haschildren = haschildren;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTERDATE", length = 7)
	public Date getEnterdate() {
		return this.enterdate;
	}

	public void setEnterdate(Date enterdate) {
		this.enterdate = enterdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}
	
	@Column(name = "STORE_CATEGORY", length = 20)
	public String getStoreCategory() {
		return storeCategory;
	}

	public void setStoreCategory(String storeCategory) {
		this.storeCategory = storeCategory;
	}
}
