package mro.base.entity;

// Generated 2014/8/18 �U�� 02:37:02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassstructureHeaderApply generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_HEADER_APPLY")
public class ClassstructureHeaderApply implements java.io.Serializable {

	private BigDecimal applyHeaderId;
	private String deptcode;
	private String organizationCode;
	private String classstructureid;
	private String status;
	private String createBy;
	private Date createDate;
	private Date lastUpdateDate;
	private BigDecimal taskId;
	private String applyHeaderNum;
	private String headerRemark;
	private String action;
	private String changeTypeFlag;

	public ClassstructureHeaderApply() {
	}

	public ClassstructureHeaderApply(BigDecimal applyHeaderId) {
		this.applyHeaderId = applyHeaderId;
	}

	public ClassstructureHeaderApply(BigDecimal applyHeaderId, String deptcode,
			String organizationCode, String classstructureid, String status,
			String createBy, Date createDate, Date lastUpdateDate,
			BigDecimal taskId, String applyHeaderNum, String headerRemark,String action,
			String changeTypeFlag) {
		this.applyHeaderId = applyHeaderId;
		this.deptcode = deptcode;
		this.organizationCode = organizationCode;
		this.classstructureid = classstructureid;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lastUpdateDate = lastUpdateDate;
		this.taskId = taskId;
		this.applyHeaderNum = applyHeaderNum;
		this.headerRemark = headerRemark;
		this.action = action;
		this.changeTypeFlag = changeTypeFlag;
	}

	@Id
	@SequenceGenerator(name="APPLY_HEADER_ID_GENERATOR", sequenceName="CLASSSTRUCTURE_HEADER_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="APPLY_HEADER_ID_GENERATOR")
	@Column(name = "APPLY_HEADER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getApplyHeaderId() {
		return this.applyHeaderId;
	}

	public void setApplyHeaderId(BigDecimal applyHeaderId) {
		this.applyHeaderId = applyHeaderId;
	}

	@Column(name = "DEPTCODE", length = 30)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "ORGANIZATION_CODE", length = 30)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "TASK_ID", precision = 22, scale = 0)
	public BigDecimal getTaskId() {
		return this.taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}

	@Column(name = "APPLY_HEADER_NUM", length = 30)
	public String getApplyHeaderNum() {
		return this.applyHeaderNum;
	}

	public void setApplyHeaderNum(String applyHeaderNum) {
		this.applyHeaderNum = applyHeaderNum;
	}

	@Column(name = "HEADER_REMARK", length = 300)
	public String getHeaderRemark() {
		return this.headerRemark;
	}

	public void setHeaderRemark(String headerRemark) {
		this.headerRemark = headerRemark;
	}

	@Column(name = "ACTION")
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "CHANGE_TYPE_FLAG")
	public String getChangeTypeFlag() {
		return changeTypeFlag;
	}

	public void setChangeTypeFlag(String changeTypeFlag) {
		this.changeTypeFlag = changeTypeFlag;
	}
}
