package mro.base.entity;

// Generated 2016/4/7 �W�� 11:04:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * ClassstructureGp generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_GP", uniqueConstraints = @UniqueConstraint(columnNames = "CLASSSTRUCTUREID"))
public class ClassstructureGp implements java.io.Serializable {

	private String id;
	private String classstructureid;
	private String deliveryType;
	private String remainType;
	private Date lastUpdate;
	private String lastUpdateBy;

	public ClassstructureGp() {
	}

	public ClassstructureGp(String id) {
		this.id = id;
	}

	public ClassstructureGp(String id, String classstructureid,
			String deliveryType, String remainType, Date lastUpdate,
			String lastUpdateBy) {
		this.id = id;
		this.classstructureid = classstructureid;
		this.deliveryType = deliveryType;
		this.remainType = remainType;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id	
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CLASSSTRUCTUREID", unique = true, length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "DELIVERY_TYPE", length = 50)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "REMAIN_TYPE", length = 50)
	public String getRemainType() {
		return this.remainType;
	}

	public void setRemainType(String remainType) {
		this.remainType = remainType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
