package mro.base.entity;

// Generated 2015/5/29 �U�� 03:15:21 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClassstructureSubinventory generated by hbm2java
 */
@Entity
@Table(name = "CLASSSTRUCTURE_SUBINVENTORY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CLASSSTRUCTUREID", "PLANT_CODE" }))
public class ClassstructureSubinventory implements java.io.Serializable {

	private BigDecimal id;
	private String classstructureid;
	private String plantCode;
	private String subinventory;
	private Date lastUpdate;
	private String lastUpdateBy;

	public ClassstructureSubinventory() {
	}

	public ClassstructureSubinventory(BigDecimal id) {
		this.id = id;
	}

	public ClassstructureSubinventory(BigDecimal id, String classstructureid,
			String plantCode, String subinventory, Date lastUpdate,
			String lastUpdateBy) {
		this.id = id;
		this.classstructureid = classstructureid;
		this.plantCode = plantCode;
		this.subinventory = subinventory;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@SequenceGenerator(name="ID_GENERATOR", sequenceName="SUBINVENTORY_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ID_GENERATOR")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "PLANT_CODE", length = 26)
	public String getPlantCode() {
		return this.plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	@Column(name = "SUBINVENTORY", length = 20)
	public String getSubinventory() {
		return this.subinventory;
	}

	public void setSubinventory(String subinventory) {
		this.subinventory = subinventory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
