package mro.base.entity;

// Generated 2012/12/28 �W�� 11:24:06 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Companies generated by hbm2java
 */
@Entity
@Table(name = "COMPANIES")
public class Company implements java.io.Serializable {

	private BigDecimal companiesId;
	private String company;
	private String name;
	private String changeBy;
	private Date changeDate;
	private String currencyCode;
	private BigDecimal disabled;
	private String orgId;
	private String vatRegistration;

	public Company() {
	}

	public Company(BigDecimal companiesId, String company,
			String currencyCode, BigDecimal disabled, String orgId) {
		this.companiesId = companiesId;
		this.company = company;
		this.currencyCode = currencyCode;
		this.disabled = disabled;
		this.orgId = orgId;
	}

	public Company(BigDecimal companiesId, String company, String name,
			String changeBy, Date changeDate, String currencyCode,
			BigDecimal disabled, String orgId, String vatRegistration) {
		this.companiesId = companiesId;
		this.company = company;
		this.name = name;
		this.changeBy = changeBy;
		this.changeDate = changeDate;
		this.currencyCode = currencyCode;
		this.disabled = disabled;
		this.orgId = orgId;
		this.vatRegistration = vatRegistration;
	}

	@Id
	@SequenceGenerator(name="COMPANIES_COMPANIESID_GENERATOR", sequenceName="COMPANIESSEQ")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="COMPANIES_COMPANIESID_GENERATOR")
	@Column(name = "COMPANIES_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCompaniesId() {
		return this.companiesId;
	}

	public void setCompaniesId(BigDecimal companiesId) {
		this.companiesId = companiesId;
	}

	@Column(name = "COMPANY", nullable = false, length = 30)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "NAME", length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CHANGE_BY", length = 30)
	public String getChangeBy() {
		return this.changeBy;
	}

	public void setChangeBy(String changeBy) {
		this.changeBy = changeBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGE_DATE", length = 7)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Column(name = "CURRENCY_CODE", nullable = false, length = 8)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "DISABLED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDisabled() {
		return this.disabled;
	}

	public void setDisabled(BigDecimal disabled) {
		this.disabled = disabled;
	}

	@Column(name = "ORG_ID", nullable = false, length = 8)
	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	@Column(name = "VAT_REGISTRATION", length = 20)
	public String getVatRegistration() {
		return this.vatRegistration;
	}

	public void setVatRegistration(String vatRegistration) {
		this.vatRegistration = vatRegistration;
	}

}
