package mro.base.entity;

// Generated 2012/10/30 �U�� 01:23:09 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EamSnapshotBssT generated by hbm2java
 */
@Entity
@Table(name = "EAM_SNAPSHOT_BSS_T")
public class EamSnapshotBssT implements java.io.Serializable {

	private String rowstamp;
	private String bssloc;
	private String dept;
	private String eqpid;
	private String itemnum;
	private String owner;
	private BigDecimal qty;
	private String remark;
	private String shop;
	private String siteid;
	private String sublocation;
	private Timestamp transdate;
	private Timestamp trkdate;
	private String trkno;
	private BigDecimal avgmcost;
	private BigDecimal avgmqty;
	private BigDecimal cost;
	private BigDecimal hcost;
	private BigDecimal hqty;
	private BigDecimal m1cost;
	private BigDecimal m1qty;
	private BigDecimal m2cost;
	private BigDecimal m2qty;
	private BigDecimal m3cost;
	private BigDecimal m3qty;
	private BigDecimal m4cost;
	private BigDecimal m4qty;
	private BigDecimal m5cost;
	private BigDecimal m5qty;
	private BigDecimal mcost;
	private BigDecimal mqty;

	public EamSnapshotBssT() {
	}

	public EamSnapshotBssT(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Id
	@Column(name = "ROWSTAMP", unique = true, nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Column(name = "BSSLOC", length = 16)
	public String getBssloc() {
		return this.bssloc;
	}

	public void setBssloc(String bssloc) {
		this.bssloc = bssloc;
	}

	@Column(name = "DEPT", length = 20)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "EQPID", length = 30)
	public String getEqpid() {
		return this.eqpid;
	}

	public void setEqpid(String eqpid) {
		this.eqpid = eqpid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "OWNER", length = 16)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "QTY", precision = 15)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "REMARK", length = 240)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "SHOP", length = 20)
	public String getShop() {
		return this.shop;
	}

	public void setShop(String shop) {
		this.shop = shop;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "SUBLOCATION", length = 50)
	public String getSublocation() {
		return this.sublocation;
	}

	public void setSublocation(String sublocation) {
		this.sublocation = sublocation;
	}

	@Column(name = "TRANSDATE", length = 7)
	public Timestamp getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Timestamp transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRKDATE", length = 7)
	public Timestamp getTrkdate() {
		return this.trkdate;
	}

	public void setTrkdate(Timestamp trkdate) {
		this.trkdate = trkdate;
	}

	@Column(name = "TRKNO", length = 30)
	public String getTrkno() {
		return this.trkno;
	}

	public void setTrkno(String trkno) {
		this.trkno = trkno;
	}

	@Column(name = "AVGMCOST", precision = 15)
	public BigDecimal getAvgmcost() {
		return this.avgmcost;
	}

	public void setAvgmcost(BigDecimal avgmcost) {
		this.avgmcost = avgmcost;
	}

	@Column(name = "AVGMQTY", precision = 15)
	public BigDecimal getAvgmqty() {
		return this.avgmqty;
	}

	public void setAvgmqty(BigDecimal avgmqty) {
		this.avgmqty = avgmqty;
	}

	@Column(name = "COST", precision = 15)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "HCOST", precision = 15)
	public BigDecimal getHcost() {
		return this.hcost;
	}

	public void setHcost(BigDecimal hcost) {
		this.hcost = hcost;
	}

	@Column(name = "HQTY", precision = 15)
	public BigDecimal getHqty() {
		return this.hqty;
	}

	public void setHqty(BigDecimal hqty) {
		this.hqty = hqty;
	}

	@Column(name = "M1COST", precision = 15)
	public BigDecimal getM1cost() {
		return this.m1cost;
	}

	public void setM1cost(BigDecimal m1cost) {
		this.m1cost = m1cost;
	}

	@Column(name = "M1QTY", precision = 15)
	public BigDecimal getM1qty() {
		return this.m1qty;
	}

	public void setM1qty(BigDecimal m1qty) {
		this.m1qty = m1qty;
	}

	@Column(name = "M2COST", precision = 15)
	public BigDecimal getM2cost() {
		return this.m2cost;
	}

	public void setM2cost(BigDecimal m2cost) {
		this.m2cost = m2cost;
	}

	@Column(name = "M2QTY", precision = 15)
	public BigDecimal getM2qty() {
		return this.m2qty;
	}

	public void setM2qty(BigDecimal m2qty) {
		this.m2qty = m2qty;
	}

	@Column(name = "M3COST", precision = 15)
	public BigDecimal getM3cost() {
		return this.m3cost;
	}

	public void setM3cost(BigDecimal m3cost) {
		this.m3cost = m3cost;
	}

	@Column(name = "M3QTY", precision = 15)
	public BigDecimal getM3qty() {
		return this.m3qty;
	}

	public void setM3qty(BigDecimal m3qty) {
		this.m3qty = m3qty;
	}

	@Column(name = "M4COST", precision = 15)
	public BigDecimal getM4cost() {
		return this.m4cost;
	}

	public void setM4cost(BigDecimal m4cost) {
		this.m4cost = m4cost;
	}

	@Column(name = "M4QTY", precision = 15)
	public BigDecimal getM4qty() {
		return this.m4qty;
	}

	public void setM4qty(BigDecimal m4qty) {
		this.m4qty = m4qty;
	}

	@Column(name = "M5COST", precision = 15)
	public BigDecimal getM5cost() {
		return this.m5cost;
	}

	public void setM5cost(BigDecimal m5cost) {
		this.m5cost = m5cost;
	}

	@Column(name = "M5QTY", precision = 15)
	public BigDecimal getM5qty() {
		return this.m5qty;
	}

	public void setM5qty(BigDecimal m5qty) {
		this.m5qty = m5qty;
	}

	@Column(name = "MCOST", precision = 15)
	public BigDecimal getMcost() {
		return this.mcost;
	}

	public void setMcost(BigDecimal mcost) {
		this.mcost = mcost;
	}

	@Column(name = "MQTY", precision = 15)
	public BigDecimal getMqty() {
		return this.mqty;
	}

	public void setMqty(BigDecimal mqty) {
		this.mqty = mqty;
	}

}
