package mro.base.entity;

// Generated 2013/2/4 �W�� 09:40:12 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ErpSubinventory generated by hbm2java
 */
@Entity
@Table(name = "ERP_SUBINVENTORY")
public class ErpSubinventory implements java.io.Serializable {

	private BigDecimal subinventoryId;
	private String organizationId;
	private String secondaryInventoryName;
	private String description;
	private BigDecimal locatorType;
	private String attribute2;
	private String ownerDept;
	private String cutDeptChr;
	private String attribute14;
	private String inventoryFlag;

	public ErpSubinventory() {
	}

	public ErpSubinventory(BigDecimal subinventoryId,
			String organizationId, String secondaryInventoryName,
			BigDecimal locatorType) {
		this.subinventoryId = subinventoryId;
		this.organizationId = organizationId;
		this.secondaryInventoryName = secondaryInventoryName;
		this.locatorType = locatorType;
	}

	public ErpSubinventory(BigDecimal subinventoryId,
			String organizationId, String secondaryInventoryName,
			String description, BigDecimal locatorType, String attribute2,
			String ownerDept, String cutDeptChr, String attribute14,
			String inventoryFlag) {
		this.subinventoryId = subinventoryId;
		this.organizationId = organizationId;
		this.secondaryInventoryName = secondaryInventoryName;
		this.description = description;
		this.locatorType = locatorType;
		this.attribute2 = attribute2;
		this.ownerDept = ownerDept;
		this.cutDeptChr = cutDeptChr;
		this.attribute14 = attribute14;
		this.inventoryFlag = inventoryFlag;
	}

	@Id
	@Column(name = "SUBINVENTORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSubinventoryId() {
		return this.subinventoryId;
	}

	public void setSubinventoryId(BigDecimal subinventoryId) {
		this.subinventoryId = subinventoryId;
	}

	@Column(name = "ORGANIZATION_ID")
	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "SECONDARY_INVENTORY_NAME", nullable = false, length = 20)
	public String getSecondaryInventoryName() {
		return this.secondaryInventoryName;
	}

	public void setSecondaryInventoryName(String secondaryInventoryName) {
		this.secondaryInventoryName = secondaryInventoryName;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LOCATOR_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLocatorType() {
		return this.locatorType;
	}

	public void setLocatorType(BigDecimal locatorType) {
		this.locatorType = locatorType;
	}

	@Column(name = "ATTRIBUTE2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "OWNER_DEPT", length = 20)
	public String getOwnerDept() {
		return this.ownerDept;
	}

	public void setOwnerDept(String ownerDept) {
		this.ownerDept = ownerDept;
	}

	@Column(name = "CUT_DEPT_CHR", length = 20)
	public String getCutDeptChr() {
		return this.cutDeptChr;
	}

	public void setCutDeptChr(String cutDeptChr) {
		this.cutDeptChr = cutDeptChr;
	}

	@Column(name = "ATTRIBUTE14", length = 20)
	public String getAttribute14() {
		return this.attribute14;
	}

	public void setAttribute14(String attribute14) {
		this.attribute14 = attribute14;
	}
	@Column(name = "INVENTORY_FLAG")
	public String getInventoryFlag() {
		return inventoryFlag;
	}

	public void setInventoryFlag(String inventoryFlag) {
		this.inventoryFlag = inventoryFlag;
	}

}
