package mro.base.entity;

// Generated 2016/7/7 �U�� 04:38:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GpTypeMapping generated by hbm2java
 */
@Entity
@Table(name = "GP_TYPE_MAPPING", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DELIVERY_TYPE", "REMAIN_TYPE" }))
public class GpTypeMapping implements java.io.Serializable {

	private String id;
	private String deliveryType;
	private String remainType;
	private String evLv;
	private String sapCode;
	private Date lastUpdate;
	private String lastUpdateBy;

	public GpTypeMapping() {
	}

	public GpTypeMapping(String id) {
		this.id = id;
	}

	public GpTypeMapping(String id, String deliveryType, String remainType,
			String evLv, String sapCode, Date lastUpdate, String lastUpdateBy) {
		this.id = id;
		this.deliveryType = deliveryType;
		this.remainType = remainType;
		this.evLv = evLv;
		this.sapCode = sapCode;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "DELIVERY_TYPE", length = 50)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "REMAIN_TYPE", length = 50)
	public String getRemainType() {
		return this.remainType;
	}

	public void setRemainType(String remainType) {
		this.remainType = remainType;
	}

	@Column(name = "EV_LV", length = 50)
	public String getEvLv() {
		return this.evLv;
	}

	public void setEvLv(String evLv) {
		this.evLv = evLv;
	}

	@Column(name = "SAP_CODE", length = 50)
	public String getSapCode() {
		return this.sapCode;
	}

	public void setSapCode(String sapCode) {
		this.sapCode = sapCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
