package mro.base.entity;

// Generated 2013/3/7 �U�� 05:27:13 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrEmp generated by hbm2java
 */
@Entity
@Table(name = "HR_EMP")
public class HrEmp implements java.io.Serializable {

	private String empNo;
	private String name;
	private String sex;
	private String locationId;
	private String deptNo;
	private String managerId;
	private String perType;
	private String shiftGroup;
	private String EMail;
	private String leaderNo;
	private String extNo;
	private String leaderEmail;
	private String ismanager;
	private String cardNo;
	private String cardKey;
	private String perState;
	private String domainAccount;
	private String cardGroup;
	private String onLineGroup;
	private String nameE;
	private BigDecimal titleGroup;
	private String titleChange;
	private String fstEdu;
	private BigDecimal yearOld;
	private Date hireDate;
	private Date leaveDate;
	private Date returnDate;
	private String realDeptNo;
	private String realDeptName;
	private String empNoOld;
	private String egCode;
	private String esgCode;
	private Date updateDate;

	public HrEmp() {
	}

	public HrEmp(String empNo) {
		this.empNo = empNo;
	}

	public HrEmp(String empNo, String name, String sex, String locationId,
			String deptNo, String managerId, String perType, String shiftGroup,
			String EMail, String leaderNo, String extNo, String leaderEmail,
			String ismanager, String cardNo, String cardKey, String perState,
			String domainAccount, String cardGroup, String onLineGroup,
			String nameE, BigDecimal titleGroup, String titleChange,
			String fstEdu, BigDecimal yearOld, Date hireDate, Date leaveDate,
			Date returnDate, String realDeptNo, String realDeptName,
			String empNoOld, String egCode, String esgCode,Date updateDate) {
		this.empNo = empNo;
		this.name = name;
		this.sex = sex;
		this.locationId = locationId;
		this.deptNo = deptNo;
		this.managerId = managerId;
		this.perType = perType;
		this.shiftGroup = shiftGroup;
		this.EMail = EMail;
		this.leaderNo = leaderNo;
		this.extNo = extNo;
		this.leaderEmail = leaderEmail;
		this.ismanager = ismanager;
		this.cardNo = cardNo;
		this.cardKey = cardKey;
		this.perState = perState;
		this.domainAccount = domainAccount;
		this.cardGroup = cardGroup;
		this.onLineGroup = onLineGroup;
		this.nameE = nameE;
		this.titleGroup = titleGroup;
		this.titleChange = titleChange;
		this.fstEdu = fstEdu;
		this.yearOld = yearOld;
		this.hireDate = hireDate;
		this.leaveDate = leaveDate;
		this.returnDate = returnDate;
		this.realDeptNo = realDeptNo;
		this.realDeptName = realDeptName;
		this.empNoOld = empNoOld;
		this.egCode = egCode;
		this.esgCode = esgCode;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "EMP_NO", unique = true, nullable = false, length = 10)
	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	@Column(name = "NAME", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SEX", length = 3)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "LOCATION_ID", length = 2)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "DEPT_NO", length = 12)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "MANAGER_ID", length = 10)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "PER_TYPE", length = 1)
	public String getPerType() {
		return this.perType;
	}

	public void setPerType(String perType) {
		this.perType = perType;
	}

	@Column(name = "SHIFT_GROUP", length = 24)
	public String getShiftGroup() {
		return this.shiftGroup;
	}

	public void setShiftGroup(String shiftGroup) {
		this.shiftGroup = shiftGroup;
	}

	@Column(name = "E_MAIL", length = 90)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "LEADER_NO", length = 10)
	public String getLeaderNo() {
		return this.leaderNo;
	}

	public void setLeaderNo(String leaderNo) {
		this.leaderNo = leaderNo;
	}

	@Column(name = "EXT_NO", length = 200)
	public String getExtNo() {
		return this.extNo;
	}

	public void setExtNo(String extNo) {
		this.extNo = extNo;
	}

	@Column(name = "LEADER_EMAIL", length = 50)
	public String getLeaderEmail() {
		return this.leaderEmail;
	}

	public void setLeaderEmail(String leaderEmail) {
		this.leaderEmail = leaderEmail;
	}

	@Column(name = "ISMANAGER", length = 1)
	public String getIsmanager() {
		return this.ismanager;
	}

	public void setIsmanager(String ismanager) {
		this.ismanager = ismanager;
	}

	@Column(name = "CARD_NO", length = 5)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "CARD_KEY", length = 30)
	public String getCardKey() {
		return this.cardKey;
	}

	public void setCardKey(String cardKey) {
		this.cardKey = cardKey;
	}

	@Column(name = "PER_STATE", length = 1)
	public String getPerState() {
		return this.perState;
	}

	public void setPerState(String perState) {
		this.perState = perState;
	}

	@Column(name = "DOMAIN_ACCOUNT", length = 50)
	public String getDomainAccount() {
		return this.domainAccount;
	}

	public void setDomainAccount(String domainAccount) {
		this.domainAccount = domainAccount;
	}

	@Column(name = "CARD_GROUP", length = 9)
	public String getCardGroup() {
		return this.cardGroup;
	}

	public void setCardGroup(String cardGroup) {
		this.cardGroup = cardGroup;
	}

	@Column(name = "ON_LINE_GROUP", length = 1)
	public String getOnLineGroup() {
		return this.onLineGroup;
	}

	public void setOnLineGroup(String onLineGroup) {
		this.onLineGroup = onLineGroup;
	}

	@Column(name = "NAME_E", length = 200)
	public String getNameE() {
		return this.nameE;
	}

	public void setNameE(String nameE) {
		this.nameE = nameE;
	}

	@Column(name = "TITLE_GROUP", precision = 22, scale = 0)
	public BigDecimal getTitleGroup() {
		return this.titleGroup;
	}

	public void setTitleGroup(BigDecimal titleGroup) {
		this.titleGroup = titleGroup;
	}

	@Column(name = "TITLE_CHANGE", length = 30)
	public String getTitleChange() {
		return this.titleChange;
	}

	public void setTitleChange(String titleChange) {
		this.titleChange = titleChange;
	}

	@Column(name = "FST_EDU", length = 6)
	public String getFstEdu() {
		return this.fstEdu;
	}

	public void setFstEdu(String fstEdu) {
		this.fstEdu = fstEdu;
	}

	@Column(name = "YEAR_OLD", precision = 22, scale = 0)
	public BigDecimal getYearOld() {
		return this.yearOld;
	}

	public void setYearOld(BigDecimal yearOld) {
		this.yearOld = yearOld;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HIRE_DATE", length = 7)
	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LEAVE_DATE", length = 7)
	public Date getLeaveDate() {
		return this.leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETURN_DATE", length = 7)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Column(name = "REAL_DEPT_NO", length = 10)
	public String getRealDeptNo() {
		return this.realDeptNo;
	}

	public void setRealDeptNo(String realDeptNo) {
		this.realDeptNo = realDeptNo;
	}

	@Column(name = "REAL_DEPT_NAME", length = 90)
	public String getRealDeptName() {
		return this.realDeptName;
	}

	public void setRealDeptName(String realDeptName) {
		this.realDeptName = realDeptName;
	}

	@Column(name = "EMP_NO_OLD", length = 14)
	public String getEmpNoOld() {
		return this.empNoOld;
	}

	public void setEmpNoOld(String empNoOld) {
		this.empNoOld = empNoOld;
	}

	@Column(name = "EG_CODE", length = 10)
	public String getEgCode() {
		return this.egCode;
	}

	public void setEgCode(String egCode) {
		this.egCode = egCode;
	}

	@Column(name = "ESG_CODE", length = 20)
	public String getEsgCode() {
		return this.esgCode;
	}

	public void setEsgCode(String esgCode) {
		this.esgCode = esgCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
