package mro.base.entity;

// Generated 2013/3/7 �U�� 05:27:13 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrOrg generated by hbm2java
 */
@Entity
@Table(name = "HR_ORG")
public class HrOrg implements java.io.Serializable {

	private String deptNo;
	private String fullName;
	private String topDept;
	private String managerId;
	private BigDecimal deptLevel;
	private String notesGroup;
	private String shortName;
	private String classNo;
	private String shortNameE;
	private String realTopDept;
	private String oldDeptNo;
	private Date updateDate;
	private String kostl;

	public HrOrg() {
	}

	public HrOrg(String deptNo) {
		this.deptNo = deptNo;
	}

	public HrOrg(String deptNo, String fullName, String topDept,
			String managerId, BigDecimal deptLevel, String notesGroup,
			String shortName, String classNo, String shortNameE,
			String realTopDept, String oldDeptNo,Date updateDate) {
		this.deptNo = deptNo;
		this.fullName = fullName;
		this.topDept = topDept;
		this.managerId = managerId;
		this.deptLevel = deptLevel;
		this.notesGroup = notesGroup;
		this.shortName = shortName;
		this.classNo = classNo;
		this.shortNameE = shortNameE;
		this.realTopDept = realTopDept;
		this.oldDeptNo = oldDeptNo;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "DEPT_NO", unique = true, nullable = false, length = 12)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "FULL_NAME", length = 1000)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "TOP_DEPT", length = 12)
	public String getTopDept() {
		return this.topDept;
	}

	public void setTopDept(String topDept) {
		this.topDept = topDept;
	}

	@Column(name = "MANAGER_ID", length = 10)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "DEPT_LEVEL", precision = 22, scale = 0)
	public BigDecimal getDeptLevel() {
		return this.deptLevel;
	}

	public void setDeptLevel(BigDecimal deptLevel) {
		this.deptLevel = deptLevel;
	}

	@Column(name = "NOTES_GROUP", length = 100)
	public String getNotesGroup() {
		return this.notesGroup;
	}

	public void setNotesGroup(String notesGroup) {
		this.notesGroup = notesGroup;
	}

	@Column(name = "SHORT_NAME", length = 120)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "CLASS_NO", length = 18)
	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	@Column(name = "SHORT_NAME_E", length = 180)
	public String getShortNameE() {
		return this.shortNameE;
	}

	public void setShortNameE(String shortNameE) {
		this.shortNameE = shortNameE;
	}

	@Column(name = "REAL_TOP_DEPT", length = 10)
	public String getRealTopDept() {
		return this.realTopDept;
	}

	public void setRealTopDept(String realTopDept) {
		this.realTopDept = realTopDept;
	}

	@Column(name = "OLD_DEPT_NO", length = 79)
	public String getOldDeptNo() {
		return this.oldDeptNo;
	}

	public void setOldDeptNo(String oldDeptNo) {
		this.oldDeptNo = oldDeptNo;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
    
	@Column(name = "KOSTL", length = 20)
	public String getKostl() {
		return kostl;
	}

	public void setKostl(String kostl) {
		this.kostl = kostl;
	}
	
	

}
