package mro.base.entity;

// Generated 2014/7/28 �W�� 10:41:46 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvbalancesHighlightLog generated by hbm2java
 */
@Entity
@Table(name = "INVBALANCES_HIGHLIGHT_LOG")
public class InvbalancesHighlightLog implements java.io.Serializable {

	private BigDecimal highlightResponseLogId;
	private String itemnum;
	private String deptcode;
	private String type;
	private String reasonType;
	private String remark;
	private String createBy;
	private Date createDate;
	private String siteId;	
	private BigDecimal deleted;
	private String deletedBy;
	private Date deletedUpdate;
	private BigDecimal invbalancesid;
	private Pr pr;

	public InvbalancesHighlightLog() {
	}

	public InvbalancesHighlightLog(BigDecimal highlightResponseLogId) {
		this.highlightResponseLogId = highlightResponseLogId;
	}

	public InvbalancesHighlightLog(BigDecimal highlightResponseLogId,
			String itemnum, String deptcode, String type, String reasonType,
			String remark, String createBy, Date createDate,String siteId,
			BigDecimal deleted,String deletedBy,Date deletedUpdate,
			BigDecimal invbalancesid,Pr pr) {
		this.highlightResponseLogId = highlightResponseLogId;
		this.itemnum = itemnum;
		this.deptcode = deptcode;
		this.type = type;
		this.reasonType = reasonType;
		this.remark = remark;
		this.createBy = createBy;
		this.createDate = createDate;
		this.siteId = siteId;
		this.deleted = deleted;
		this.deletedBy = deletedBy;
		this.deletedUpdate = deletedUpdate;
		this.invbalancesid = invbalancesid;
		this.pr = pr;
	}

	@Id
	@SequenceGenerator(name="HIGHLIGHT_RESPONSE_LOG_ID_GENERATOR", sequenceName="INVBALANCES_HIGHLIGHT_LOG_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="HIGHLIGHT_RESPONSE_LOG_ID_GENERATOR")
	@Column(name = "HIGHLIGHT_RESPONSE_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHighlightResponseLogId() {
		return this.highlightResponseLogId;
	}

	public void setHighlightResponseLogId(BigDecimal highlightResponseLogId) {
		this.highlightResponseLogId = highlightResponseLogId;
	}

	@Column(name = "ITEMNUM", length = 30,nullable = false)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "DEPTCODE", length = 12,nullable = false)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "TYPE", length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "REASON_TYPE", length = 30)
	public String getReasonType() {
		return this.reasonType;
	}

	public void setReasonType(String reasonType) {
		this.reasonType = reasonType;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(name = "SITE_ID" )
	public String getSiteId() {
		return siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}
	@Column(name = "DELETED" )
	public BigDecimal getDeleted() {
		return deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}
	@Column(name = "DELETED_BY" )
	public String getDeletedBy() {
		return deletedBy;
	}

	public void setDeletedBy(String deletedBy) {
		this.deletedBy = deletedBy;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELETED_UPDATE", length = 7)
	public Date getDeletedUpdate() {
		return deletedUpdate;
	}

	public void setDeletedUpdate(Date deletedUpdate) {
		this.deletedUpdate = deletedUpdate;
	}
	@Column(name = "INVBALANCESID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInvbalancesid() {
		return this.invbalancesid;
	}

	public void setInvbalancesid(BigDecimal invbalancesid) {
		this.invbalancesid = invbalancesid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRID")
	public Pr getPr() {
		return this.pr;
	}

	public void setPr(Pr pr) {
		this.pr = pr;
	}

}
