package mro.base.entity;

// Generated 2013/2/26 �U�� 03:42:44 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Invbalances generated by hbm2java
 */
@Entity
@Table(name = "INVBALANCES", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "LOCATION", "BINNUM", "LOTNUM", "CONDITIONCODE", "SITEID",
		"ITEMSETID" }))
public class Invbalances implements java.io.Serializable {

	private BigDecimal invbalancesid;
	private String itemnum;
	private String location;
	private String binnum;
	private String lotnum;
	private long curbal;
	private long physcnt;
	private Date physcntdate;
	private long reconciled;
	private String sourcesysid;
	private String ownersysid;
	private String externalrefid;
	private String sendersysid;
	private String orgid;
	private String siteid;
	private String itemsetid;
	private String conditioncode;
	private String deptcode;
	private String dept;
	private String lastrequestedby;
	private Date lastrequestdate;
	private BigDecimal onhandqty;
	private BigDecimal sstock;
	private BigDecimal minlevel;
	private String applyno;
	private BigDecimal usedqtymtd;
	private BigDecimal stdcost;
	private BigDecimal iqc;
	private BigDecimal issuemtdate;
	private BigDecimal poqty;
	private BigDecimal prqty;
	private BigDecimal nextqty;
	private String remark;
	private BigDecimal mquotalast; 
	private long hasld;
	private String costtype;
	private BigDecimal usefreq; 
	private String lastrequestedby2;
	private BigDecimal deptvendoritemqty;
	private BigDecimal deptvendorssqty;
	private BigDecimal prlineid;
	private Date debugInsertDate;
	private BigDecimal beforeUpdateQty;
	private Date debugUpdateDate;
	private BigDecimal oriavguseqty;
	private String lastHighlightResponseBy;
	private Date lastHighlightResponseDate;
	private Date highlightInitialDate;

	public Invbalances() {
	}

	public Invbalances(BigDecimal invbalancesid, String itemnum,
			String location, long curbal, long physcnt,
			long reconciled, String orgid, String siteid,
			String itemsetid, long hasld) {
		this.invbalancesid = invbalancesid;
		this.itemnum = itemnum;
		this.location = location;
		this.curbal = curbal;
		this.physcnt = physcnt;
		this.reconciled = reconciled;
		this.orgid = orgid;
		this.siteid = siteid;
		this.itemsetid = itemsetid;
		this.hasld = hasld;
	}

	public Invbalances(BigDecimal invbalancesid, String itemnum,
			String location, String binnum, String lotnum, long curbal,
			long physcnt, Date physcntdate, long reconciled,
			String sourcesysid, String ownersysid, String externalrefid,
			String sendersysid, String orgid, String siteid, String itemsetid,
			String conditioncode, String deptcode,
			String dept, String lastrequestedby, Date lastrequestdate,
			BigDecimal onhandqty, BigDecimal sstock, BigDecimal minlevel,
			String applyno, BigDecimal usedqtymtd, BigDecimal stdcost,
			BigDecimal iqc, BigDecimal issuemtdate, BigDecimal poqty,
			BigDecimal prqty, BigDecimal nextqty, String remark,
			BigDecimal mquotalast, long hasld, String costtype,
			BigDecimal usefreq, String lastrequestedby2,
			BigDecimal deptvendoritemqty, BigDecimal deptvendorssqty,
			BigDecimal prlineid, Date debugInsertDate,
			BigDecimal beforeUpdateQty, Date debugUpdateDate,
			BigDecimal oriavguseqty,
			String lastHighlightResponseBy,Date lastHighlightResponseDate,
			Date highlightInitialDate) {
		this.invbalancesid = invbalancesid;
		this.itemnum = itemnum;
		this.location = location;
		this.binnum = binnum;
		this.lotnum = lotnum;
		this.curbal = curbal;
		this.physcnt = physcnt;
		this.physcntdate = physcntdate;
		this.reconciled = reconciled;
		this.sourcesysid = sourcesysid;
		this.ownersysid = ownersysid;
		this.externalrefid = externalrefid;
		this.sendersysid = sendersysid;
		this.orgid = orgid;
		this.siteid = siteid;
		this.itemsetid = itemsetid;
		this.conditioncode = conditioncode;
		this.deptcode = deptcode;
		this.dept = dept;
		this.lastrequestedby = lastrequestedby;
		this.lastrequestdate = lastrequestdate;
		this.onhandqty = onhandqty;
		this.sstock = sstock;
		this.minlevel = minlevel;
		this.applyno = applyno;
		this.usedqtymtd = usedqtymtd;
		this.stdcost = stdcost;
		this.iqc = iqc;
		this.issuemtdate = issuemtdate;
		this.poqty = poqty;
		this.prqty = prqty;
		this.nextqty = nextqty;
		this.remark = remark;
		this.mquotalast = mquotalast;
		this.hasld = hasld;
		this.costtype = costtype;
		this.usefreq = usefreq;
		this.lastrequestedby2 = lastrequestedby2;
		this.deptvendoritemqty = deptvendoritemqty;
		this.deptvendorssqty = deptvendorssqty;
		this.prlineid = prlineid;
		this.debugInsertDate = debugInsertDate;
		this.beforeUpdateQty = beforeUpdateQty;
		this.debugUpdateDate = debugUpdateDate;
		this.oriavguseqty = oriavguseqty;
		this.lastHighlightResponseBy = lastHighlightResponseBy;
		this.lastHighlightResponseDate = lastHighlightResponseDate;
		this.highlightInitialDate  = highlightInitialDate;
	}

	@Id
	@SequenceGenerator(name="INVBALANCESID_GENERATOR", sequenceName="INVBALANCESSEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="INVBALANCESID_GENERATOR")
	@Column(name = "INVBALANCESID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInvbalancesid() {
		return this.invbalancesid;
	}

	public void setInvbalancesid(BigDecimal invbalancesid) {
		this.invbalancesid = invbalancesid;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "LOCATION", nullable = false, length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "BINNUM", length = 30)
	public String getBinnum() {
		return this.binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}

	@Column(name = "LOTNUM", length = 8)
	public String getLotnum() {
		return this.lotnum;
	}

	public void setLotnum(String lotnum) {
		this.lotnum = lotnum;
	}

	@Column(name = "CURBAL", nullable = false, precision = 15)
	public long getCurbal() {
		return this.curbal;
	}

	public void setCurbal(long curbal) {
		this.curbal = curbal;
	}

	@Column(name = "PHYSCNT", nullable = false, precision = 15)
	public long getPhyscnt() {
		return this.physcnt;
	}

	public void setPhyscnt(long physcnt) {
		this.physcnt = physcnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PHYSCNTDATE", length = 7)
	public Date getPhyscntdate() {
		return this.physcntdate;
	}

	public void setPhyscntdate(Date physcntdate) {
		this.physcntdate = physcntdate;
	}

	@Column(name = "RECONCILED", nullable = false, precision = 22, scale = 0)
	public long getReconciled() {
		return this.reconciled;
	}

	public void setReconciled(long reconciled) {
		this.reconciled = reconciled;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "DEPTCODE", length = 48)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "DEPT", length = 48)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "LASTREQUESTEDBY", length = 30)
	public String getLastrequestedby() {
		return this.lastrequestedby;
	}

	public void setLastrequestedby(String lastrequestedby) {
		this.lastrequestedby = lastrequestedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTREQUESTDATE", length = 7)
	public Date getLastrequestdate() {
		return this.lastrequestdate;
	}

	public void setLastrequestdate(Date lastrequestdate) {
		this.lastrequestdate = lastrequestdate;
	}

	@Column(name = "ONHANDQTY", precision = 15)
	public BigDecimal getOnhandqty() {
		return this.onhandqty;
	}

	public void setOnhandqty(BigDecimal onhandqty) {
		this.onhandqty = onhandqty;
	}

	@Column(name = "SSTOCK", precision = 15)
	public BigDecimal getSstock() {
		return this.sstock;
	}

	public void setSstock(BigDecimal sstock) {
		this.sstock = sstock;
	}

	@Column(name = "MINLEVEL", precision = 15)
	public BigDecimal getMinlevel() {
		return this.minlevel;
	}

	public void setMinlevel(BigDecimal minlevel) {
		this.minlevel = minlevel;
	}

	@Column(name = "APPLYNO", length = 30)
	public String getApplyno() {
		return this.applyno;
	}

	public void setApplyno(String applyno) {
		this.applyno = applyno;
	}

	@Column(name = "USEDQTYMTD", precision = 15)
	public BigDecimal getUsedqtymtd() {
		return this.usedqtymtd;
	}

	public void setUsedqtymtd(BigDecimal usedqtymtd) {
		this.usedqtymtd = usedqtymtd;
	}

	@Column(name = "STDCOST", precision = 10)
	public BigDecimal getStdcost() {
		return this.stdcost;
	}

	public void setStdcost(BigDecimal stdcost) {
		this.stdcost = stdcost;
	}

	@Column(name = "IQC", precision = 15)
	public BigDecimal getIqc() {
		return this.iqc;
	}

	public void setIqc(BigDecimal iqc) {
		this.iqc = iqc;
	}

	@Column(name = "ISSUEMTDATE", precision = 15)
	public BigDecimal getIssuemtdate() {
		return this.issuemtdate;
	}

	public void setIssuemtdate(BigDecimal issuemtdate) {
		this.issuemtdate = issuemtdate;
	}

	@Column(name = "POQTY", precision = 15)
	public BigDecimal getPoqty() {
		return this.poqty;
	}

	public void setPoqty(BigDecimal poqty) {
		this.poqty = poqty;
	}

	@Column(name = "PRQTY", precision = 15)
	public BigDecimal getPrqty() {
		return this.prqty;
	}

	public void setPrqty(BigDecimal prqty) {
		this.prqty = prqty;
	}

	@Column(name = "NEXTQTY", precision = 16)
	public BigDecimal getNextqty() {
		return this.nextqty;
	}

	public void setNextqty(BigDecimal nextqty) {
		this.nextqty = nextqty;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "MQUOTALAST", precision = 15)
	public BigDecimal getMquotalast() {
		return this.mquotalast;
	}

	public void setMquotalast(BigDecimal mquotalast) {
		this.mquotalast = mquotalast;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public long getHasld() {
		return this.hasld;
	}

	public void setHasld(long hasld) {
		this.hasld = hasld;
	}

	@Column(name = "COSTTYPE", length = 80)
	public String getCosttype() {
		return this.costtype;
	}

	public void setCosttype(String costtype) {
		this.costtype = costtype;
	}

	@Column(name = "USEFREQ", precision = 22, scale = 0)
	public BigDecimal getUsefreq() {
		return this.usefreq;
	}

	public void setUsefreq(BigDecimal usefreq) {
		this.usefreq = usefreq;
	}

	@Column(name = "LASTREQUESTEDBY2", length = 30)
	public String getLastrequestedby2() {
		return this.lastrequestedby2;
	}

	public void setLastrequestedby2(String lastrequestedby2) {
		this.lastrequestedby2 = lastrequestedby2;
	}

	@Column(name = "DEPTVENDORITEMQTY", precision = 16)
	public BigDecimal getDeptvendoritemqty() {
		return this.deptvendoritemqty;
	}

	public void setDeptvendoritemqty(BigDecimal deptvendoritemqty) {
		this.deptvendoritemqty = deptvendoritemqty;
	}

	@Column(name = "DEPTVENDORSSQTY", precision = 16)
	public BigDecimal getDeptvendorssqty() {
		return this.deptvendorssqty;
	}

	public void setDeptvendorssqty(BigDecimal deptvendorssqty) {
		this.deptvendorssqty = deptvendorssqty;
	}

	@Column(name = "PRLINEID", precision = 22, scale = 0)
	public BigDecimal getPrlineid() {
		return this.prlineid;
	}

	public void setPrlineid(BigDecimal prlineid) {
		this.prlineid = prlineid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEBUG_INSERT_DATE", length = 7)
	public Date getDebugInsertDate() {
		return this.debugInsertDate;
	}

	public void setDebugInsertDate(Date debugInsertDate) {
		this.debugInsertDate = debugInsertDate;
	}

	@Column(name = "BEFORE_UPDATE_QTY", precision = 15)
	public BigDecimal getBeforeUpdateQty() {
		return this.beforeUpdateQty;
	}

	public void setBeforeUpdateQty(BigDecimal beforeUpdateQty) {
		this.beforeUpdateQty = beforeUpdateQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEBUG_UPDATE_DATE", length = 7)
	public Date getDebugUpdateDate() {
		return this.debugUpdateDate;
	}

	public void setDebugUpdateDate(Date debugUpdateDate) {
		this.debugUpdateDate = debugUpdateDate;
	}

	@Column(name = "ORIAVGUSEQTY", precision = 15)
	public BigDecimal getOriavguseqty() {
		return this.oriavguseqty;
	}

	public void setOriavguseqty(BigDecimal oriavguseqty) {
		this.oriavguseqty = oriavguseqty;
	}
	@Column(name = "LAST_HIGHLIGHT_REPONSE_BY")
	public String getLastHighlightResponseBy() {
		return lastHighlightResponseBy;
	}

	public void setLastHighlightResponseBy(String lastHighlightResponseBy) {
		this.lastHighlightResponseBy = lastHighlightResponseBy;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_HIGHLIGHT_REPONSE_DATE", length = 7)
	public Date getLastHighlightResponseDate() {
		return lastHighlightResponseDate;
	}

	public void setLastHighlightResponseDate(Date lastHighlightResponseDate) {
		this.lastHighlightResponseDate = lastHighlightResponseDate;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HIGHLIGHT_INITIAL_DATE", length = 7)
	public Date getHighlightInitialDate() {
		return highlightInitialDate;
	}

	public void setHighlightInitialDate(Date highlightInitialDate) {
		this.highlightInitialDate = highlightInitialDate;
	}

}
