package mro.base.entity;

// Generated 2012/10/25 �U�� 06:18:03 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Invcost generated by hbm2java
 */
@Entity
@Table(name = "INVCOST", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "LOCATION", "CONDITIONCODE", "SITEID", "ITEMSETID" }))
public class Invcost implements java.io.Serializable {

	private BigDecimal invcostid;
	private String itemnum;
	private String location;
	private String conditioncode;
	private BigDecimal condrate;
	private String itemsetid;
	private String siteid;
	private BigDecimal stdcost;
	private BigDecimal avgcost;
	private BigDecimal lastcost;
	private String glaccount;
	private String controlacc;
	private String shrinkageacc;
	private String invcostadjacc;
	private String orgid;
	private String rowstamp;
	private Date lastupdate;

	public Invcost() {
	}

	public Invcost(BigDecimal invcostid, String itemnum, String location,
			BigDecimal condrate, String itemsetid, String siteid,
			BigDecimal stdcost, BigDecimal avgcost, BigDecimal lastcost,
			String orgid, String rowstamp) {
		this.invcostid = invcostid;
		this.itemnum = itemnum;
		this.location = location;
		this.condrate = condrate;
		this.itemsetid = itemsetid;
		this.siteid = siteid;
		this.stdcost = stdcost;
		this.avgcost = avgcost;
		this.lastcost = lastcost;
		this.orgid = orgid;
		this.rowstamp = rowstamp;
	}

	public Invcost(BigDecimal invcostid, String itemnum, String location,
			String conditioncode, BigDecimal condrate, String itemsetid,
			String siteid, BigDecimal stdcost, BigDecimal avgcost,
			BigDecimal lastcost, String glaccount, String controlacc,
			String shrinkageacc, String invcostadjacc, String orgid,
			String rowstamp,Date lastupdate) {
		this.invcostid = invcostid;
		this.itemnum = itemnum;
		this.location = location;
		this.conditioncode = conditioncode;
		this.condrate = condrate;
		this.itemsetid = itemsetid;
		this.siteid = siteid;
		this.stdcost = stdcost;
		this.avgcost = avgcost;
		this.lastcost = lastcost;
		this.glaccount = glaccount;
		this.controlacc = controlacc;
		this.shrinkageacc = shrinkageacc;
		this.invcostadjacc = invcostadjacc;
		this.orgid = orgid;
		this.rowstamp = rowstamp;
		this.lastupdate = lastupdate;
	}

	@Id
	@Column(name = "INVCOSTID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInvcostid() {
		return this.invcostid;
	}

	public void setInvcostid(BigDecimal invcostid) {
		this.invcostid = invcostid;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "LOCATION", nullable = false, length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "CONDRATE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCondrate() {
		return this.condrate;
	}

	public void setCondrate(BigDecimal condrate) {
		this.condrate = condrate;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "STDCOST", nullable = false, precision = 10)
	public BigDecimal getStdcost() {
		return this.stdcost;
	}

	public void setStdcost(BigDecimal stdcost) {
		this.stdcost = stdcost;
	}

	@Column(name = "AVGCOST", nullable = false, precision = 10)
	public BigDecimal getAvgcost() {
		return this.avgcost;
	}

	public void setAvgcost(BigDecimal avgcost) {
		this.avgcost = avgcost;
	}

	@Column(name = "LASTCOST", nullable = false, precision = 10)
	public BigDecimal getLastcost() {
		return this.lastcost;
	}

	public void setLastcost(BigDecimal lastcost) {
		this.lastcost = lastcost;
	}

	@Column(name = "GLACCOUNT", length = 10)
	public String getGlaccount() {
		return this.glaccount;
	}

	public void setGlaccount(String glaccount) {
		this.glaccount = glaccount;
	}

	@Column(name = "CONTROLACC", length = 10)
	public String getControlacc() {
		return this.controlacc;
	}

	public void setControlacc(String controlacc) {
		this.controlacc = controlacc;
	}

	@Column(name = "SHRINKAGEACC", length = 10)
	public String getShrinkageacc() {
		return this.shrinkageacc;
	}

	public void setShrinkageacc(String shrinkageacc) {
		this.shrinkageacc = shrinkageacc;
	}

	@Column(name = "INVCOSTADJACC", length = 10)
	public String getInvcostadjacc() {
		return this.invcostadjacc;
	}

	public void setInvcostadjacc(String invcostadjacc) {
		this.invcostadjacc = invcostadjacc;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE")
	public Date getLastupdate() {
		return lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}
	
}
