package mro.base.entity;

// Generated 2013/2/26 �W�� 11:34:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "INVENTORY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "LOCATION", "SITEID", "ITEMSETID", "BINNUM" }))
public class Inventory implements java.io.Serializable {

	private BigDecimal inventoryid;
	private String itemsetid;
	private String manufacturer;
	private String modelnum;
	private String orderunit;
	private String shrinkageacc;
	private BigDecimal sstock;
	private String vendor;
	private String abctype;
	private String binnum;
	private String catalogcode;
	private String controlacc;
	private String glaccount;
	private String invcostadjacc;
	private String issueunit;
	private Date lastissuedate;
	private String orgid;
	private String siteid;
	private String sourcesysid;
	private String ownersysid;
	private String externalrefid;
	private String category;
	private long ccf;
	private BigDecimal deliverytime;
	private long issue1yrago;
	private long issue2yrago;
	private long issue3yrago;
	private long issueytd;
	private String itemnum;
	private String location;
	private long maxlevel;
	private BigDecimal minlevel;
	private long orderqty;
	private String sendersysid;
	private String storeloc;
	private String storelocsiteid;
	private long internal;
	private BigDecimal onhandqty;
	private BigDecimal iqc;
	private BigDecimal prqty;
	private BigDecimal poqty;
	private BigDecimal issuemtdate;
	private BigDecimal nextqty;
	private BigDecimal cmominlevel;
	private BigDecimal cmodeptminlevel;
	private String cmommcontrol;
	private BigDecimal cmovendordepoint;
	private BigDecimal mquotalast;
	private BigDecimal stock;
	private String mccommand;
	private long vendoritemflag;
	private BigDecimal idledays;
	private BigDecimal storevendoritemqty;
	private BigDecimal storevendorssqty;
	private BigDecimal qty1;
	private BigDecimal qty2;
	private BigDecimal qty3;
	private BigDecimal qty4;
	private BigDecimal qty5;
	private BigDecimal oriavguseqty;
	private BigDecimal avstock;
	private BigDecimal sestock;
	private BigDecimal sdstock;
	private BigDecimal mcdemand;
	private BigDecimal mcbssonhand;
	private BigDecimal mtstock;
	private BigDecimal stockIdledays;
	private Date syncLastupdate;
	private BigDecimal stockdays;
	
	public Inventory() {
	}

	public Inventory(BigDecimal inventoryid, String itemsetid,
			String issueunit, String orgid, String siteid, String category,
			long ccf, BigDecimal deliverytime, long issue1yrago,
			long issue2yrago, long issue3yrago,
			long issueytd, String itemnum, String location,
			long maxlevel, BigDecimal minlevel, long orderqty,
			long internal, long vendoritemflag, BigDecimal stockdays) {
		this.inventoryid = inventoryid;
		this.itemsetid = itemsetid;
		this.issueunit = issueunit;
		this.orgid = orgid;
		this.siteid = siteid;
		this.category = category;
		this.ccf = ccf;
		this.deliverytime = deliverytime;
		this.issue1yrago = issue1yrago;
		this.issue2yrago = issue2yrago;
		this.issue3yrago = issue3yrago;
		this.issueytd = issueytd;
		this.itemnum = itemnum;
		this.location = location;
		this.maxlevel = maxlevel;
		this.minlevel = minlevel;
		this.orderqty = orderqty;
		this.internal = internal;
		this.vendoritemflag = vendoritemflag;
		this.stockdays = stockdays;
	}

	public Inventory(BigDecimal inventoryid, String itemsetid,
			String manufacturer, String modelnum, String orderunit,
			String shrinkageacc, BigDecimal sstock, String vendor,
			String abctype, String binnum, String catalogcode,
			String controlacc, String glaccount, String invcostadjacc,
			String issueunit, Date lastissuedate, String orgid, String siteid,
			String sourcesysid, String ownersysid, String externalrefid,
			String category, long ccf, BigDecimal deliverytime,
			long issue1yrago, long issue2yrago,
			long issue3yrago, long issueytd, String itemnum,
			String location, long maxlevel, BigDecimal minlevel,
			long orderqty, String sendersysid, String storeloc,
			String storelocsiteid, long internal, BigDecimal onhandqty,
			BigDecimal iqc, BigDecimal prqty, BigDecimal poqty,
			BigDecimal issuemtdate, BigDecimal nextqty, BigDecimal cmominlevel,
			BigDecimal cmodeptminlevel, String cmommcontrol,
			BigDecimal cmovendordepoint, BigDecimal mquotalast,
			BigDecimal stock, String mccommand, long vendoritemflag,
			BigDecimal idledays, BigDecimal storevendoritemqty,
			BigDecimal storevendorssqty, BigDecimal qty1, BigDecimal qty2,
			BigDecimal qty3, BigDecimal qty4, BigDecimal qty5,
			BigDecimal oriavguseqty, BigDecimal avstock, BigDecimal sestock,
			BigDecimal mcdemand, BigDecimal mcbssonhand,BigDecimal mtstock,
			BigDecimal stockIdledays,Date syncLastupdate,BigDecimal sdstock,
			BigDecimal stockdays) {
		this.inventoryid = inventoryid;
		this.itemsetid = itemsetid;
		this.manufacturer = manufacturer;
		this.modelnum = modelnum;
		this.orderunit = orderunit;
		this.shrinkageacc = shrinkageacc;
		this.sstock = sstock;
		this.vendor = vendor;
		this.abctype = abctype;
		this.binnum = binnum;
		this.catalogcode = catalogcode;
		this.controlacc = controlacc;
		this.glaccount = glaccount;
		this.invcostadjacc = invcostadjacc;
		this.issueunit = issueunit;
		this.lastissuedate = lastissuedate;
		this.orgid = orgid;
		this.siteid = siteid;
		this.sourcesysid = sourcesysid;
		this.ownersysid = ownersysid;
		this.externalrefid = externalrefid;
		this.category = category;
		this.ccf = ccf;
		this.deliverytime = deliverytime;
		this.issue1yrago = issue1yrago;
		this.issue2yrago = issue2yrago;
		this.issue3yrago = issue3yrago;
		this.issueytd = issueytd;
		this.itemnum = itemnum;
		this.location = location;
		this.maxlevel = maxlevel;
		this.minlevel = minlevel;
		this.orderqty = orderqty;
		this.sendersysid = sendersysid;
		this.storeloc = storeloc;
		this.storelocsiteid = storelocsiteid;
		this.internal = internal;
		this.onhandqty = onhandqty;
		this.iqc = iqc;
		this.prqty = prqty;
		this.poqty = poqty;
		this.issuemtdate = issuemtdate;
		this.nextqty = nextqty;
		this.cmominlevel = cmominlevel;
		this.cmodeptminlevel = cmodeptminlevel;
		this.cmommcontrol = cmommcontrol;
		this.cmovendordepoint = cmovendordepoint;
		this.mquotalast = mquotalast;
		this.stock = stock;
		this.mccommand = mccommand;
		this.vendoritemflag = vendoritemflag;
		this.idledays = idledays;
		this.storevendoritemqty = storevendoritemqty;
		this.storevendorssqty = storevendorssqty;
		this.qty1 = qty1;
		this.qty2 = qty2;
		this.qty3 = qty3;
		this.qty4 = qty4;
		this.qty5 = qty5;
		this.oriavguseqty = oriavguseqty;
		this.avstock = avstock;
		this.sestock = sestock;
		this.mcdemand = mcdemand;
		this.mcbssonhand = mcbssonhand;
		this.mtstock = mtstock;
		this.stockIdledays = stockIdledays;
		this.syncLastupdate = syncLastupdate;
		this.sdstock = sdstock;
		this.stockdays = stockdays;
	}

	@Id
	@SequenceGenerator(name="INVENTORYID_GENERATOR", sequenceName="INVENTORYSEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="INVENTORYID_GENERATOR")
	@Column(name = "INVENTORYID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInventoryid() {
		return this.inventoryid;
	}

	public void setInventoryid(BigDecimal inventoryid) {
		this.inventoryid = inventoryid;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "MANUFACTURER", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "MODELNUM", length = 50)
	public String getModelnum() {
		return this.modelnum;
	}

	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "ORDERUNIT", length = 50)
	public String getOrderunit() {
		return this.orderunit;
	}

	public void setOrderunit(String orderunit) {
		this.orderunit = orderunit;
	}

	@Column(name = "SHRINKAGEACC", length = 10)
	public String getShrinkageacc() {
		return this.shrinkageacc;
	}

	public void setShrinkageacc(String shrinkageacc) {
		this.shrinkageacc = shrinkageacc;
	}

	@Column(name = "SSTOCK", precision = 15)
	public BigDecimal getSstock() {
		return this.sstock;
	}

	public void setSstock(BigDecimal sstock) {
		this.sstock = sstock;
	}

	@Column(name = "VENDOR", length = 30)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "ABCTYPE", length = 1)
	public String getAbctype() {
		return this.abctype;
	}

	public void setAbctype(String abctype) {
		this.abctype = abctype;
	}

	@Column(name = "BINNUM", length = 30)
	public String getBinnum() {
		return this.binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}

	@Column(name = "CATALOGCODE", length = 50)
	public String getCatalogcode() {
		return this.catalogcode;
	}

	public void setCatalogcode(String catalogcode) {
		this.catalogcode = catalogcode;
	}

	@Column(name = "CONTROLACC", length = 10)
	public String getControlacc() {
		return this.controlacc;
	}

	public void setControlacc(String controlacc) {
		this.controlacc = controlacc;
	}

	@Column(name = "GLACCOUNT", length = 10)
	public String getGlaccount() {
		return this.glaccount;
	}

	public void setGlaccount(String glaccount) {
		this.glaccount = glaccount;
	}

	@Column(name = "INVCOSTADJACC", length = 10)
	public String getInvcostadjacc() {
		return this.invcostadjacc;
	}

	public void setInvcostadjacc(String invcostadjacc) {
		this.invcostadjacc = invcostadjacc;
	}

	@Column(name = "ISSUEUNIT",  length = 50)
	public String getIssueunit() {
		return this.issueunit;
	}

	public void setIssueunit(String issueunit) {
		this.issueunit = issueunit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTISSUEDATE", length = 7)
	public Date getLastissuedate() {
		return this.lastissuedate;
	}

	public void setLastissuedate(Date lastissuedate) {
		this.lastissuedate = lastissuedate;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "CATEGORY", nullable = false, length = 16)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "CCF", nullable = false, precision = 22, scale = 0)
	public long getCcf() {
		return this.ccf;
	}

	public void setCcf(long ccf) {
		this.ccf = ccf;
	}

	@Column(name = "DELIVERYTIME", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDeliverytime() {
		return this.deliverytime;
	}

	public void setDeliverytime(BigDecimal deliverytime) {
		this.deliverytime = deliverytime;
	}

	@Column(name = "ISSUE1YRAGO", nullable = false, precision = 15)
	public long getIssue1yrago() {
		return this.issue1yrago;
	}

	public void setIssue1yrago(long issue1yrago) {
		this.issue1yrago = issue1yrago;
	}

	@Column(name = "ISSUE2YRAGO", nullable = false, precision = 15)
	public long getIssue2yrago() {
		return this.issue2yrago;
	}

	public void setIssue2yrago(long issue2yrago) {
		this.issue2yrago = issue2yrago;
	}

	@Column(name = "ISSUE3YRAGO", nullable = false, precision = 15)
	public long getIssue3yrago() {
		return this.issue3yrago;
	}

	public void setIssue3yrago(long issue3yrago) {
		this.issue3yrago = issue3yrago;
	}

	@Column(name = "ISSUEYTD", nullable = false, precision = 15)
	public long getIssueytd() {
		return this.issueytd;
	}

	public void setIssueytd(long issueytd) {
		this.issueytd = issueytd;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "LOCATION", nullable = false, length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "MAXLEVEL", nullable = false, precision = 15)
	public long getMaxlevel() {
		return this.maxlevel;
	}

	public void setMaxlevel(long maxlevel) {
		this.maxlevel = maxlevel;
	}

	@Column(name = "MINLEVEL", nullable = false, precision = 15)
	public BigDecimal getMinlevel() {
		return this.minlevel;
	}

	public void setMinlevel(BigDecimal minlevel) {
		this.minlevel = minlevel;
	}

	@Column(name = "ORDERQTY", nullable = false, precision = 15)
	public long getOrderqty() {
		return this.orderqty;
	}

	public void setOrderqty(long orderqty) {
		this.orderqty = orderqty;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "STORELOC", length = 16)
	public String getStoreloc() {
		return this.storeloc;
	}

	public void setStoreloc(String storeloc) {
		this.storeloc = storeloc;
	}

	@Column(name = "STORELOCSITEID", length = 8)
	public String getStorelocsiteid() {
		return this.storelocsiteid;
	}

	public void setStorelocsiteid(String storelocsiteid) {
		this.storelocsiteid = storelocsiteid;
	}

	@Column(name = "INTERNAL", nullable = false, precision = 22, scale = 0)
	public long getInternal() {
		return this.internal;
	}

	public void setInternal(long internal) {
		this.internal = internal;
	}

	@Column(name = "ONHANDQTY", precision = 15)
	public BigDecimal getOnhandqty() {
		return this.onhandqty;
	}

	public void setOnhandqty(BigDecimal onhandqty) {
		this.onhandqty = onhandqty;
	}

	@Column(name = "IQC", precision = 15)
	public BigDecimal getIqc() {
		return this.iqc;
	}

	public void setIqc(BigDecimal iqc) {
		this.iqc = iqc;
	}

	@Column(name = "PRQTY", precision = 15)
	public BigDecimal getPrqty() {
		return this.prqty;
	}

	public void setPrqty(BigDecimal prqty) {
		this.prqty = prqty;
	}

	@Column(name = "POQTY", precision = 15)
	public BigDecimal getPoqty() {
		return this.poqty;
	}

	public void setPoqty(BigDecimal poqty) {
		this.poqty = poqty;
	}

	@Column(name = "ISSUEMTDATE", precision = 15)
	public BigDecimal getIssuemtdate() {
		return this.issuemtdate;
	}

	public void setIssuemtdate(BigDecimal issuemtdate) {
		this.issuemtdate = issuemtdate;
	}

	@Column(name = "NEXTQTY", precision = 16)
	public BigDecimal getNextqty() {
		return this.nextqty;
	}

	public void setNextqty(BigDecimal nextqty) {
		this.nextqty = nextqty;
	}

	@Column(name = "CMOMINLEVEL", precision = 15)
	public BigDecimal getCmominlevel() {
		return this.cmominlevel;
	}

	public void setCmominlevel(BigDecimal cmominlevel) {
		this.cmominlevel = cmominlevel;
	}

	@Column(name = "CMODEPTMINLEVEL", precision = 15)
	public BigDecimal getCmodeptminlevel() {
		return this.cmodeptminlevel;
	}

	public void setCmodeptminlevel(BigDecimal cmodeptminlevel) {
		this.cmodeptminlevel = cmodeptminlevel;
	}

	@Column(name = "CMOMMCONTROL")
	public String getCmommcontrol() {
		return this.cmommcontrol;
	}

	public void setCmommcontrol(String cmommcontrol) {
		this.cmommcontrol = cmommcontrol;
	}

	@Column(name = "CMOVENDORDEPOINT", precision = 15)
	public BigDecimal getCmovendordepoint() {
		return this.cmovendordepoint;
	}

	public void setCmovendordepoint(BigDecimal cmovendordepoint) {
		this.cmovendordepoint = cmovendordepoint;
	}

	@Column(name = "MQUOTALAST", precision = 15)
	public BigDecimal getMquotalast() {
		return this.mquotalast;
	}

	public void setMquotalast(BigDecimal mquotalast) {
		this.mquotalast = mquotalast;
	}

	@Column(name = "STOCK", precision = 15)
	public BigDecimal getStock() {
		return this.stock;
	}

	public void setStock(BigDecimal stock) {
		this.stock = stock;
	}

	@Column(name = "MCCOMMAND", length = 250)
	public String getMccommand() {
		return this.mccommand;
	}

	public void setMccommand(String mccommand) {
		this.mccommand = mccommand;
	}

	@Column(name = "VENDORITEMFLAG", nullable = false, precision = 22, scale = 0)
	public long getVendoritemflag() {
		return this.vendoritemflag;
	}

	public void setVendoritemflag(long vendoritemflag) {
		this.vendoritemflag = vendoritemflag;
	}

	@Column(name = "IDLEDAYS", precision = 16)
	public BigDecimal getIdledays() {
		return this.idledays;
	}

	public void setIdledays(BigDecimal idledays) {
		this.idledays = idledays;
	}

	@Column(name = "STOREVENDORITEMQTY", precision = 16)
	public BigDecimal getStorevendoritemqty() {
		return this.storevendoritemqty;
	}

	public void setStorevendoritemqty(BigDecimal storevendoritemqty) {
		this.storevendoritemqty = storevendoritemqty;
	}

	@Column(name = "STOREVENDORSSQTY", precision = 16)
	public BigDecimal getStorevendorssqty() {
		return this.storevendorssqty;
	}

	public void setStorevendorssqty(BigDecimal storevendorssqty) {
		this.storevendorssqty = storevendorssqty;
	}

	@Column(name = "QTY1", precision = 15)
	public BigDecimal getQty1() {
		return this.qty1;
	}

	public void setQty1(BigDecimal qty1) {
		this.qty1 = qty1;
	}

	@Column(name = "QTY2", precision = 15)
	public BigDecimal getQty2() {
		return this.qty2;
	}

	public void setQty2(BigDecimal qty2) {
		this.qty2 = qty2;
	}

	@Column(name = "QTY3", precision = 15)
	public BigDecimal getQty3() {
		return this.qty3;
	}

	public void setQty3(BigDecimal qty3) {
		this.qty3 = qty3;
	}

	@Column(name = "QTY4", precision = 15)
	public BigDecimal getQty4() {
		return this.qty4;
	}

	public void setQty4(BigDecimal qty4) {
		this.qty4 = qty4;
	}

	@Column(name = "QTY5", precision = 15)
	public BigDecimal getQty5() {
		return this.qty5;
	}

	public void setQty5(BigDecimal qty5) {
		this.qty5 = qty5;
	}

	@Column(name = "ORIAVGUSEQTY", precision = 15)
	public BigDecimal getOriavguseqty() {
		return this.oriavguseqty;
	}

	public void setOriavguseqty(BigDecimal oriavguseqty) {
		this.oriavguseqty = oriavguseqty;
	}

	@Column(name = "AVSTOCK", precision = 15)
	public BigDecimal getAvstock() {
		return this.avstock;
	}

	public void setAvstock(BigDecimal avstock) {
		this.avstock = avstock;
	}

	@Column(name = "SESTOCK", precision = 15)
	public BigDecimal getSestock() {
		return this.sestock;
	}

	public void setSestock(BigDecimal sestock) {
		this.sestock = sestock;
	}

	@Column(name = "MCDEMAND", precision = 15)
	public BigDecimal getMcdemand() {
		return this.mcdemand;
	}

	public void setMcdemand(BigDecimal mcdemand) {
		this.mcdemand = mcdemand;
	}

	@Column(name = "MCBSSONHAND", precision = 15)
	public BigDecimal getMcbssonhand() {
		return this.mcbssonhand;
	}

	public void setMcbssonhand(BigDecimal mcbssonhand) {
		this.mcbssonhand = mcbssonhand;
	}

	@Column(name = "MTSTOCK", precision = 15)
	public BigDecimal getMtstock() {
		return mtstock;
	}

	public void setMtstock(BigDecimal mtstock) {
		this.mtstock = mtstock;
	}
	@Column(name = "STOCK_IDLEDAYS")
	public BigDecimal getStockIdledays() {
		return stockIdledays;
	}

	public void setStockIdledays(BigDecimal stockIdledays) {
		this.stockIdledays = stockIdledays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SYNC_LASTUPDATE")
	public Date getSyncLastupdate() {
		return syncLastupdate;
	}

	public void setSyncLastupdate(Date syncLastupdate) {
		this.syncLastupdate = syncLastupdate;
	}
	@Column(name = "SDSTOCK", precision = 15)
	public BigDecimal getSdstock() {
		return sdstock;
	}

	public void setSdstock(BigDecimal sdstock) {
		this.sdstock = sdstock;
	}
	@Column(name = "STOCK_DAYS", precision = 15)
	public BigDecimal getStockdays() {
		return stockdays;
	}

	public void setStockdays(BigDecimal stockdays) {
		this.stockdays = stockdays;
	}

}
