package mro.base.entity;

// Generated 2013/1/15 �W�� 10:27:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Invvendor generated by hbm2java
 */
@Entity
@Table(name = "INVVENDOR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "VENDOR", "MANUFACTURER", "MODELNUM", "CONDITIONCODE",
		"ITEMSETID", "ORGID", "SITEID" }))
public class Invvendor implements java.io.Serializable {

	private BigDecimal invvendorid;
	private Item item;
	private String itemnum;
	private String vendor;
	private String manufacturer;
	private String modelnum;
	private String catalogcode;
	private String tax1code;
	private String tax2code;
	private String tax3code;
	private BigDecimal bidprice;
	private Date biddate;
	private BigDecimal promdeliverytime;
	private String tax4code;
	private String tax5code;
	private BigDecimal lastcost;
	private Date lastdate;
	private String catalogwebpage;
	private String sourcesysid;
	private String ownersysid;
	private String externalrefid;
	private String sendersysid;
	private String orderunit;
	private BigDecimal isdefault;
	private String ecompartnum1;
	private String ecompartnum2;
	private String description;
	private String orgid;
	private String siteid;
	private String itemsetid;
	private String conditioncode;
	private String erpLastPo;
	private Date createpodate;
	private BigDecimal disabled;

	public Invvendor() {
	}

	public Invvendor(BigDecimal invvendorid, String itemnum, String orgid,
			String itemsetid) {
		this.invvendorid = invvendorid;
		this.itemnum = itemnum;
		this.orgid = orgid;
		this.itemsetid = itemsetid;
	}

	public Invvendor(BigDecimal invvendorid, Item item, String itemnum,
			String vendor, String manufacturer, String modelnum,
			String catalogcode, String tax1code, String tax2code,
			String tax3code, BigDecimal bidprice, Date biddate,
			BigDecimal promdeliverytime, String tax4code, String tax5code,
			BigDecimal lastcost, Date lastdate, String catalogwebpage,
			String sourcesysid, String ownersysid, String externalrefid,
			String sendersysid, String orderunit, BigDecimal isdefault,
			String ecompartnum1, String ecompartnum2, String description,
			String orgid, String siteid, String itemsetid,
			String conditioncode, String erpLastPo, Date createpodate,
			BigDecimal disabled) {
		this.invvendorid = invvendorid;
		this.item = item;
		this.itemnum = itemnum;
		this.vendor = vendor;
		this.manufacturer = manufacturer;
		this.modelnum = modelnum;
		this.catalogcode = catalogcode;
		this.tax1code = tax1code;
		this.tax2code = tax2code;
		this.tax3code = tax3code;
		this.bidprice = bidprice;
		this.biddate = biddate;
		this.promdeliverytime = promdeliverytime;
		this.tax4code = tax4code;
		this.tax5code = tax5code;
		this.lastcost = lastcost;
		this.lastdate = lastdate;
		this.catalogwebpage = catalogwebpage;
		this.sourcesysid = sourcesysid;
		this.ownersysid = ownersysid;
		this.externalrefid = externalrefid;
		this.sendersysid = sendersysid;
		this.orderunit = orderunit;
		this.isdefault = isdefault;
		this.ecompartnum1 = ecompartnum1;
		this.ecompartnum2 = ecompartnum2;
		this.description = description;
		this.orgid = orgid;
		this.siteid = siteid;
		this.itemsetid = itemsetid;
		this.conditioncode = conditioncode;
		this.erpLastPo = erpLastPo;
		this.createpodate = createpodate;
		this.disabled = disabled;
	}

	@Id
	@SequenceGenerator(name="INVVENDOR_INVVENDORID_GENERATOR", sequenceName="INVVENDORSEQ")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="INVVENDOR_INVVENDORID_GENERATOR")
	@Column(name = "INVVENDORID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getInvvendorid() {
		return this.invvendorid;
	}

	public void setInvvendorid(BigDecimal invvendorid) {
		this.invvendorid = invvendorid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "VENDOR", length = 30)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "MANUFACTURER", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "MODELNUM", length = 50)
	public String getModelnum() {
		return this.modelnum;
	}

	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "CATALOGCODE", length = 50)
	public String getCatalogcode() {
		return this.catalogcode;
	}

	public void setCatalogcode(String catalogcode) {
		this.catalogcode = catalogcode;
	}

	@Column(name = "TAX1CODE", length = 8)
	public String getTax1code() {
		return this.tax1code;
	}

	public void setTax1code(String tax1code) {
		this.tax1code = tax1code;
	}

	@Column(name = "TAX2CODE", length = 8)
	public String getTax2code() {
		return this.tax2code;
	}

	public void setTax2code(String tax2code) {
		this.tax2code = tax2code;
	}

	@Column(name = "TAX3CODE", length = 8)
	public String getTax3code() {
		return this.tax3code;
	}

	public void setTax3code(String tax3code) {
		this.tax3code = tax3code;
	}

	@Column(name = "BIDPRICE", precision = 10)
	public BigDecimal getBidprice() {
		return this.bidprice;
	}

	public void setBidprice(BigDecimal bidprice) {
		this.bidprice = bidprice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIDDATE", length = 7)
	public Date getBiddate() {
		return this.biddate;
	}

	public void setBiddate(Date biddate) {
		this.biddate = biddate;
	}

	@Column(name = "PROMDELIVERYTIME", precision = 22, scale = 0)
	public BigDecimal getPromdeliverytime() {
		return this.promdeliverytime;
	}

	public void setPromdeliverytime(BigDecimal promdeliverytime) {
		this.promdeliverytime = promdeliverytime;
	}

	@Column(name = "TAX4CODE", length = 8)
	public String getTax4code() {
		return this.tax4code;
	}

	public void setTax4code(String tax4code) {
		this.tax4code = tax4code;
	}

	@Column(name = "TAX5CODE", length = 8)
	public String getTax5code() {
		return this.tax5code;
	}

	public void setTax5code(String tax5code) {
		this.tax5code = tax5code;
	}

	@Column(name = "LASTCOST", precision = 10)
	public BigDecimal getLastcost() {
		return this.lastcost;
	}

	public void setLastcost(BigDecimal lastcost) {
		this.lastcost = lastcost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTDATE", length = 7)
	public Date getLastdate() {
		return this.lastdate;
	}

	public void setLastdate(Date lastdate) {
		this.lastdate = lastdate;
	}

	@Column(name = "CATALOGWEBPAGE", length = 250)
	public String getCatalogwebpage() {
		return this.catalogwebpage;
	}

	public void setCatalogwebpage(String catalogwebpage) {
		this.catalogwebpage = catalogwebpage;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "ORDERUNIT", length = 50)
	public String getOrderunit() {
		return this.orderunit;
	}

	public void setOrderunit(String orderunit) {
		this.orderunit = orderunit;
	}

	@Column(name = "ISDEFAULT", precision = 22, scale = 0)
	public BigDecimal getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(BigDecimal isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "ECOMPARTNUM1", length = 30)
	public String getEcompartnum1() {
		return this.ecompartnum1;
	}

	public void setEcompartnum1(String ecompartnum1) {
		this.ecompartnum1 = ecompartnum1;
	}

	@Column(name = "ECOMPARTNUM2", length = 30)
	public String getEcompartnum2() {
		return this.ecompartnum2;
	}

	public void setEcompartnum2(String ecompartnum2) {
		this.ecompartnum2 = ecompartnum2;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ITEMSETID", nullable = false, length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "ERP_LAST_PO", length = 20)
	public String getErpLastPo() {
		return this.erpLastPo;
	}

	public void setErpLastPo(String erpLastPo) {
		this.erpLastPo = erpLastPo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEPODATE", length = 7)
	public Date getCreatepodate() {
		return this.createpodate;
	}

	public void setCreatepodate(Date createpodate) {
		this.createpodate = createpodate;
	}

	@Column(name = "DISABLED", precision = 22, scale = 0)
	public BigDecimal getDisabled() {
		return this.disabled;
	}

	public void setDisabled(BigDecimal disabled) {
		this.disabled = disabled;
	}

}
