package mro.base.entity;

// Generated 2014/1/8 �U�� 03:42:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemTransferLineApply generated by hbm2java
 */
@Entity
@Table(name = "ITEM_TRANSFER_LINE_APPLY")
public class ItemTransferLineApply implements java.io.Serializable {

	private BigDecimal applyLineId;
	private ItemTransferHeaderApply itemTransferHeaderApply;
	private BigDecimal itemid;
	private String itemnum;
	private String status;
	private String createBy;
	private Date createDate;
	private BigDecimal lineNum;
	private String lineRemark;
	private String description;
	private String extraRemark;
	
	public ItemTransferLineApply() {
	}

	public ItemTransferLineApply(BigDecimal applyLineId) {
		this.applyLineId = applyLineId;
	}

	public ItemTransferLineApply(BigDecimal applyLineId,
			ItemTransferHeaderApply itemTransferHeaderApply, BigDecimal itemid,
			String itemnum, String status,
			String createBy,
			Date createDate,BigDecimal lineNum,String lineRemark,String description,
			String extraRemark) {
		this.applyLineId = applyLineId;
		this.itemTransferHeaderApply = itemTransferHeaderApply;
		this.itemid = itemid;
		this.itemnum = itemnum;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lineNum = lineNum;
		this.lineRemark = lineRemark;
		this.description = description;
		this.extraRemark = extraRemark;
	}

	@Id
	@SequenceGenerator(name="APPLY_LINE_ID_GENERATOR", sequenceName="ITEM_TRANSFER_LINE_APPLY_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="APPLY_LINE_ID_GENERATOR")
	@Column(name = "APPLY_LINE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getApplyLineId() {
		return this.applyLineId;
	}

	public void setApplyLineId(BigDecimal applyLineId) {
		this.applyLineId = applyLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLY_HEADER_ID")
	public ItemTransferHeaderApply getItemTransferHeaderApply() {
		return this.itemTransferHeaderApply;
	}

	public void setItemTransferHeaderApply(
			ItemTransferHeaderApply itemTransferHeaderApply) {
		this.itemTransferHeaderApply = itemTransferHeaderApply;
	}

	@Column(name = "ITEMID", precision = 22, scale = 0)
	public BigDecimal getItemid() {
		return this.itemid;
	}

	public void setItemid(BigDecimal itemid) {
		this.itemid = itemid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@Column(name = "LINE_NUM")
	public BigDecimal getLineNum() {
		return lineNum;
	}

	public void setLineNum(BigDecimal lineNum) {
		this.lineNum = lineNum;
	}
	
	@Column(name = "LINE_REMARK")
	public String getLineRemark() {
		return lineRemark;
	}

	public void setLineRemark(String lineRemark) {
		this.lineRemark = lineRemark;
	}
	
	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name = "EXTRA_REMARK")
	public String getExtraRemark() {
		return extraRemark;
	}

	public void setExtraRemark(String extraRemark) {
		this.extraRemark = extraRemark;
	}

}
