package mro.base.entity;

// Generated 2015/2/12 �U�� 03:17:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ItemMapping generated by hbm2java
 */
@Entity
@Table(name = "ITEM_MAPPING")
public class ItemMapping implements java.io.Serializable {

	private String uuid;
	private BigDecimal eaudittransid;
	private BigDecimal itemId;
	private String newMatnr;
	private String oldMatnr;
	private String oldMatkl;
	private String newMatkl;
	private String oldMeins;
	private String newMeins;
	private BigDecimal transRate;
	private BigDecimal oldMeinsQty;
	private BigDecimal newMeinsQty;
	private String erpFlg;
	private String mespn;
	private String plant;
	private String packageUnit;
	private BigDecimal transferQuantity;
	private String oldDescription;
	private String newDescription;
	private String supplierFlag;

	public ItemMapping() {
	}

	public ItemMapping(String uuid) {
		this.uuid = uuid;
	}

	public ItemMapping(String uuid, BigDecimal eaudittransid,
			BigDecimal itemId, String newMatnr, String oldMatnr,
			String oldMatkl, String newMatkl, String oldMeins, String newMeins,
			BigDecimal transRate, BigDecimal oldMeinsQty,
			BigDecimal newMeinsQty, String erpFlg, String mespn, String plant,
			String packageUnit, BigDecimal transferQuantity,
			String oldDescription, String newDescription,String supplierFlag) {
		this.uuid = uuid;
		this.eaudittransid = eaudittransid;
		this.itemId = itemId;
		this.newMatnr = newMatnr;
		this.oldMatnr = oldMatnr;
		this.oldMatkl = oldMatkl;
		this.newMatkl = newMatkl;
		this.oldMeins = oldMeins;
		this.newMeins = newMeins;
		this.transRate = transRate;
		this.oldMeinsQty = oldMeinsQty;
		this.newMeinsQty = newMeinsQty;
		this.erpFlg = erpFlg;
		this.mespn = mespn;
		this.plant = plant;
		this.packageUnit = packageUnit;
		this.transferQuantity = transferQuantity;
		this.oldDescription = oldDescription;
		this.newDescription = newDescription;
		this.supplierFlag = supplierFlag;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "UUID", unique = true, nullable = false, length = 32)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "EAUDITTRANSID", precision = 22, scale = 0)
	public BigDecimal getEaudittransid() {
		return this.eaudittransid;
	}

	public void setEaudittransid(BigDecimal eaudittransid) {
		this.eaudittransid = eaudittransid;
	}

	@Column(name = "ITEM_ID", precision = 22, scale = 0)
	public BigDecimal getItemId() {
		return this.itemId;
	}

	public void setItemId(BigDecimal itemId) {
		this.itemId = itemId;
	}

	@Column(name = "NEW_MATNR", length = 20)
	public String getNewMatnr() {
		return this.newMatnr;
	}

	public void setNewMatnr(String newMatnr) {
		this.newMatnr = newMatnr;
	}

	@Column(name = "OLD_MATNR", length = 50)
	public String getOldMatnr() {
		return this.oldMatnr;
	}

	public void setOldMatnr(String oldMatnr) {
		this.oldMatnr = oldMatnr;
	}

	@Column(name = "OLD_MATKL", length = 200)
	public String getOldMatkl() {
		return this.oldMatkl;
	}

	public void setOldMatkl(String oldMatkl) {
		this.oldMatkl = oldMatkl;
	}

	@Column(name = "NEW_MATKL", length = 5)
	public String getNewMatkl() {
		return this.newMatkl;
	}

	public void setNewMatkl(String newMatkl) {
		this.newMatkl = newMatkl;
	}

	@Column(name = "OLD_MEINS", length = 10)
	public String getOldMeins() {
		return this.oldMeins;
	}

	public void setOldMeins(String oldMeins) {
		this.oldMeins = oldMeins;
	}

	@Column(name = "NEW_MEINS", length = 5)
	public String getNewMeins() {
		return this.newMeins;
	}

	public void setNewMeins(String newMeins) {
		this.newMeins = newMeins;
	}

	@Column(name = "TRANS_RATE", precision = 22, scale = 0)
	public BigDecimal getTransRate() {
		return this.transRate;
	}

	public void setTransRate(BigDecimal transRate) {
		this.transRate = transRate;
	}

	@Column(name = "OLD_MEINS_QTY", precision = 22, scale = 0)
	public BigDecimal getOldMeinsQty() {
		return this.oldMeinsQty;
	}

	public void setOldMeinsQty(BigDecimal oldMeinsQty) {
		this.oldMeinsQty = oldMeinsQty;
	}

	@Column(name = "NEW_MEINS_QTY", precision = 22, scale = 0)
	public BigDecimal getNewMeinsQty() {
		return this.newMeinsQty;
	}

	public void setNewMeinsQty(BigDecimal newMeinsQty) {
		this.newMeinsQty = newMeinsQty;
	}

	@Column(name = "ERP_FLG", length = 1)
	public String getErpFlg() {
		return this.erpFlg;
	}

	public void setErpFlg(String erpFlg) {
		this.erpFlg = erpFlg;
	}

	@Column(name = "MESPN", length = 10)
	public String getMespn() {
		return this.mespn;
	}

	public void setMespn(String mespn) {
		this.mespn = mespn;
	}

	@Column(name = "PLANT", length = 200)
	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	@Column(name = "PACKAGE_UNIT", length = 10)
	public String getPackageUnit() {
		return this.packageUnit;
	}

	public void setPackageUnit(String packageUnit) {
		this.packageUnit = packageUnit;
	}

	@Column(name = "TRANSFER_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getTransferQuantity() {
		return this.transferQuantity;
	}

	public void setTransferQuantity(BigDecimal transferQuantity) {
		this.transferQuantity = transferQuantity;
	}

	@Column(name = "OLD_DESCRIPTION", length = 250)
	public String getOldDescription() {
		return this.oldDescription;
	}

	public void setOldDescription(String oldDescription) {
		this.oldDescription = oldDescription;
	}

	@Column(name = "NEW_DESCRIPTION", length = 250)
	public String getNewDescription() {
		return this.newDescription;
	}

	public void setNewDescription(String newDescription) {
		this.newDescription = newDescription;
	}
	
	@Column(name = "SUPPLIER_FLAG")
	public String getSupplierFlag() {
		return supplierFlag;
	}

	public void setSupplierFlag(String supplierFlag) {
		this.supplierFlag = supplierFlag;
	}

}
