package mro.base.entity;

// Generated 2013/5/22 �W�� 09:51:07 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ItemSecondItemnum generated by hbm2java
 */
@Entity
@Table(name = "ITEM_SECOND_ITEMNUM")
public class ItemSecondItemnum implements java.io.Serializable {

	private BigDecimal itemSecondItemnumId;
	private Item item;
	private String secondItemnum;
	private BigDecimal eaudittransid;

	public ItemSecondItemnum() {
	}

	public ItemSecondItemnum(BigDecimal itemSecondItemnumId) {
		this.itemSecondItemnumId = itemSecondItemnumId;
	}

	public ItemSecondItemnum(BigDecimal itemSecondItemnumId, Item item,
			String secondItemnum,BigDecimal eaudittransid) {
		this.itemSecondItemnumId = itemSecondItemnumId;
		this.item = item;
		this.secondItemnum = secondItemnum;
		this.eaudittransid = eaudittransid;
	}

	@Id
	@SequenceGenerator(name="SECOND_ITEMNUM_GENERATOR", sequenceName="ITEM_SECOND_ITEMNUM_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SECOND_ITEMNUM_GENERATOR")
	@Column(name = "ITEM_SECOND_ITEMNUM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemSecondItemnumId() {
		return this.itemSecondItemnumId;
	}

	public void setItemSecondItemnumId(BigDecimal itemSecondItemnumId) {
		this.itemSecondItemnumId = itemSecondItemnumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "SECOND_ITEMNUM", length = 30)
	public String getSecondItemnum() {
		return this.secondItemnum;
	}

	public void setSecondItemnum(String secondItemnum) {
		this.secondItemnum = secondItemnum;
	}
	@Column(name = "EAUDITTRANSID", precision = 22, scale = 0)
	public BigDecimal getEaudittransid() {
		return this.eaudittransid;
	}

	public void setEaudittransid(BigDecimal eaudittransid) {
		this.eaudittransid = eaudittransid;
	}

}
