package mro.base.entity;

// Generated 2016/9/5 �U�� 03:36:41 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ItemControlConfig generated by hbm2java
 */
@Entity
@Table(name = "ITEM_CONTROL_CONFIG")
public class ItemControlConfig implements java.io.Serializable {

	private String id;
	private String itemnum;
	private String locationSite;
	private String reorderDisableFlag;
	private String highlightDisableFlag;
	private Date lastUpdate;
	private String lastUpdateBy;
	private Item item;

	public ItemControlConfig() {
	}

	public ItemControlConfig(String id) {
		this.id = id;
	}

	public ItemControlConfig(String id, String itemnum, String locationSite,
			String reorderDisableFlag, String highlightDisableFlag,
			Date lastUpdate, String lastUpdateBy, Item item) {
		this.id = id;
		this.itemnum = itemnum;
		this.locationSite = locationSite;
		this.reorderDisableFlag = reorderDisableFlag;
		this.highlightDisableFlag = highlightDisableFlag;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.item = item;
	}	
	@Id	
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "LOCATION_SITE", length = 26)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "REORDER_DISABLE_FLAG", length = 1)
	public String getReorderDisableFlag() {
		return this.reorderDisableFlag;
	}

	public void setReorderDisableFlag(String reorderDisableFlag) {
		this.reorderDisableFlag = reorderDisableFlag;
	}

	@Column(name = "HIGHLIGHT_DISABLE_FLAG", length = 1)
	public String getHighlightDisableFlag() {
		return this.highlightDisableFlag;
	}

	public void setHighlightDisableFlag(String highlightDisableFlag) {
		this.highlightDisableFlag = highlightDisableFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

}
