package mro.base.entity;

// Generated 2013/2/25 �W�� 10:03:29 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemAttribute generated by hbm2java
 */
@Entity
@Table(name = "ITEM_ATTRIBUTE")
public class ItemAttribute implements java.io.Serializable {

	private BigDecimal itemAttributeId;
	private Item item;
	private BigDecimal eaudittransid;
	private BigDecimal deliverytime;
	private BigDecimal unitcost;
	private String currencyCode;
	private String gpProductCategory;
	private String gpDeliveryType;
	private String gpRemainType;
	private String gpControlFlag;
	private Date gpReportDate;
	private String mcContinuityUse;
	private BigDecimal mcOriMinLevel;
	private BigDecimal mcUseFrequencyLevel;
	private BigDecimal mcTotalMinLevel;
	private BigDecimal mcEveryUseLevel;
	private BigDecimal mcSuggestingSafeLevel;
	private BigDecimal mcOrderQuantity;
	private BigDecimal mcMinPackageQuantity;
	private String mcRemark;
	private BigDecimal mcStockDay;
	private String secondItemFlag;
	private String minBasicUnit;
	private String packageUnit;
	private BigDecimal transferQuantity;
	
	private String strategyMgmtFlag;
	private String facilitySupplierName;
	private String facilitySupplierAddress;
	private String facilitySupplierPhone;
	private String facilitySupplierContact;
	private String facilitySupplierItemnum;
	private BigDecimal oriUnitcost;
	private String oriCurrency;
	private BigDecimal oriRate;
	private String mcUseFrequencyType;
	private String secondSourceItemnum;
	private String inspectionType;
	private String facilityNum;
	private String gpEvLv;
	private String gpRiskLv;
	private String secondItemType;
	
	public ItemAttribute() {
	}

	public ItemAttribute(BigDecimal itemAttributeId) {
		this.itemAttributeId = itemAttributeId;
	}

	public ItemAttribute(BigDecimal itemAttributeId, Item item,
			BigDecimal eaudittransid, BigDecimal deliverytime,
			BigDecimal unitcost,String currencyCode, String gpProductCategory,
			String gpDeliveryType, String gpRemainType, String gpControlFlag,
			Date gpReportDate, String mcContinuityUse,
			BigDecimal mcOriMinLevel, BigDecimal mcUseFrequencyLevel,
			BigDecimal mcTotalMinLevel, BigDecimal mcEveryUseLevel,
			BigDecimal mcSuggestingSafeLevel, BigDecimal mcOrderQuantity,
			BigDecimal mcMinPackageQuantity, String mcRemark,
			BigDecimal mcStockDay,String secondItemFlag,
			String minBasicUnit, String packageUnit, BigDecimal transferQuantity,
			String strategyMgmtFlag,
			String facilitySupplierName,
			String facilitySupplierAddress,
			String facilitySupplierPhone,
			String facilitySupplierContact,
			String facilitySupplierItemnum,
			BigDecimal oriUnitcost,String oriCurrency,BigDecimal oriRate,
			String mcUseFrequencyType,String secondSourceItemnum,
			String inspectionType,String facilityNum,String gpEvLv,String gpRiskLv,
			String secondItemType) {
		this.itemAttributeId = itemAttributeId;
		this.item = item;
		this.eaudittransid = eaudittransid;
		this.deliverytime = deliverytime;
		this.unitcost = unitcost;
		this.currencyCode=currencyCode;
		this.gpProductCategory = gpProductCategory;
		this.gpDeliveryType = gpDeliveryType;
		this.gpRemainType = gpRemainType;
		this.gpControlFlag = gpControlFlag;
		this.gpReportDate = gpReportDate;
		this.mcContinuityUse = mcContinuityUse;
		this.mcOriMinLevel = mcOriMinLevel;
		this.mcUseFrequencyLevel = mcUseFrequencyLevel;
		this.mcTotalMinLevel = mcTotalMinLevel;
		this.mcEveryUseLevel = mcEveryUseLevel;
		this.mcSuggestingSafeLevel = mcSuggestingSafeLevel;
		this.mcOrderQuantity = mcOrderQuantity;
		this.mcMinPackageQuantity = mcMinPackageQuantity;
		this.mcRemark = mcRemark;
		this.mcStockDay = mcStockDay;
		this.secondItemFlag = secondItemFlag;
		this.minBasicUnit = minBasicUnit;
		this.packageUnit = packageUnit;
		this.transferQuantity = transferQuantity;
		this.strategyMgmtFlag = strategyMgmtFlag;
		this.facilitySupplierName = facilitySupplierName;
		this.facilitySupplierAddress = facilitySupplierAddress;
		this.facilitySupplierPhone = facilitySupplierPhone;
		this.facilitySupplierContact = facilitySupplierContact;
		this.facilitySupplierItemnum = facilitySupplierItemnum;
		this.oriUnitcost = oriUnitcost;
		this.oriCurrency = oriCurrency;
		this.oriRate = oriRate;
		this.mcUseFrequencyType = mcUseFrequencyType;
		this.secondSourceItemnum = secondSourceItemnum;
		this.inspectionType = inspectionType;
		this.facilityNum = facilityNum;
		this.gpEvLv = gpEvLv;
		this.gpRiskLv = gpRiskLv;
		this.secondItemType = secondItemType;
	}

	@Id
	@SequenceGenerator(name="ATTRIBUTE_GENERATOR", sequenceName="ITEM_ATTRIBUTE_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ATTRIBUTE_GENERATOR")
	@Column(name = "ITEM_ATTRIBUTE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemAttributeId() {
		return this.itemAttributeId;
	}

	public void setItemAttributeId(BigDecimal itemAttributeId) {
		this.itemAttributeId = itemAttributeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "EAUDITTRANSID", precision = 22, scale = 0)
	public BigDecimal getEaudittransid() {
		return this.eaudittransid;
	}

	public void setEaudittransid(BigDecimal eaudittransid) {
		this.eaudittransid = eaudittransid;
	}

	@Column(name = "DELIVERYTIME", precision = 22, scale = 0)
	public BigDecimal getDeliverytime() {
		return this.deliverytime;
	}

	public void setDeliverytime(BigDecimal deliverytime) {
		this.deliverytime = deliverytime;
	}

	@Column(name = "UNITCOST", precision = 22, scale = 0)
	public BigDecimal getUnitcost() {
		return this.unitcost;
	}

	public void setUnitcost(BigDecimal unitcost) {
		this.unitcost = unitcost;
	}
	@Column(name = "CURRENCY_CODE", length = 20)
	public String getCurrencyCode() {
		return currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}
	@Column(name = "GP_PRODUCT_CATEGORY")
	public String getGpProductCategory() {
		return this.gpProductCategory;
	}

	public void setGpProductCategory(String gpProductCategory) {
		this.gpProductCategory = gpProductCategory;
	}

	@Column(name = "GP_DELIVERY_TYPE", length = 1)
	public String getGpDeliveryType() {
		return this.gpDeliveryType;
	}

	public void setGpDeliveryType(String gpDeliveryType) {
		this.gpDeliveryType = gpDeliveryType;
	}

	@Column(name = "GP_REMAIN_TYPE", length = 1)
	public String getGpRemainType() {
		return this.gpRemainType;
	}

	public void setGpRemainType(String gpRemainType) {
		this.gpRemainType = gpRemainType;
	}

	@Column(name = "GP_CONTROL_FLAG", length = 1)
	public String getGpControlFlag() {
		return this.gpControlFlag;
	}

	public void setGpControlFlag(String gpControlFlag) {
		this.gpControlFlag = gpControlFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GP_REPORT_DATE", length = 7)
	public Date getGpReportDate() {
		return this.gpReportDate;
	}

	public void setGpReportDate(Date gpReportDate) {
		this.gpReportDate = gpReportDate;
	}
	@Column(name = "MC_CONTINUITY_USE", length = 1)
	public String getMcContinuityUse() {
		return this.mcContinuityUse;
	}

	public void setMcContinuityUse(String mcContinuityUse) {
		this.mcContinuityUse = mcContinuityUse;
	}

	@Column(name = "MC_ORI_MIN_LEVEL", precision = 22, scale = 0)
	public BigDecimal getMcOriMinLevel() {
		return this.mcOriMinLevel;
	}

	public void setMcOriMinLevel(BigDecimal mcOriMinLevel) {
		this.mcOriMinLevel = mcOriMinLevel;
	}

	@Column(name = "MC_USE_FREQUENCY_LEVEL", precision = 22, scale = 0)
	public BigDecimal getMcUseFrequencyLevel() {
		return this.mcUseFrequencyLevel;
	}

	public void setMcUseFrequencyLevel(BigDecimal mcUseFrequencyLevel) {
		this.mcUseFrequencyLevel = mcUseFrequencyLevel;
	}

	@Column(name = "MC_TOTAL_MIN_LEVEL", precision = 22, scale = 0)
	public BigDecimal getMcTotalMinLevel() {
		return this.mcTotalMinLevel;
	}

	public void setMcTotalMinLevel(BigDecimal mcTotalMinLevel) {
		this.mcTotalMinLevel = mcTotalMinLevel;
	}

	@Column(name = "MC_EVERY_USE_LEVEL", precision = 22, scale = 0)
	public BigDecimal getMcEveryUseLevel() {
		return this.mcEveryUseLevel;
	}

	public void setMcEveryUseLevel(BigDecimal mcEveryUseLevel) {
		this.mcEveryUseLevel = mcEveryUseLevel;
	}

	@Column(name = "MC_SUGGESTING_SAFE_LEVEL", precision = 22, scale = 0)
	public BigDecimal getMcSuggestingSafeLevel() {
		return this.mcSuggestingSafeLevel;
	}

	public void setMcSuggestingSafeLevel(BigDecimal mcSuggestingSafeLevel) {
		this.mcSuggestingSafeLevel = mcSuggestingSafeLevel;
	}

	@Column(name = "MC_ORDER_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getMcOrderQuantity() {
		return this.mcOrderQuantity;
	}

	public void setMcOrderQuantity(BigDecimal mcOrderQuantity) {
		this.mcOrderQuantity = mcOrderQuantity;
	}

	@Column(name = "MC_MIN_PACKAGE_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getMcMinPackageQuantity() {
		return this.mcMinPackageQuantity;
	}

	public void setMcMinPackageQuantity(BigDecimal mcMinPackageQuantity) {
		this.mcMinPackageQuantity = mcMinPackageQuantity;
	}

	@Column(name = "MC_REMARK", length = 500)
	public String getMcRemark() {
		return this.mcRemark;
	}

	public void setMcRemark(String mcRemark) {
		this.mcRemark = mcRemark;
	}

	@Column(name = "MC_STOCK_DAY", precision = 22, scale = 0)
	public BigDecimal getMcStockDay() {
		return this.mcStockDay;
	}

	public void setMcStockDay(BigDecimal mcStockDay) {
		this.mcStockDay = mcStockDay;
	}
	@Column(name = "SECOND_ITEM_FLAG")
	public String getSecondItemFlag() {
		return secondItemFlag;
	}

	public void setSecondItemFlag(String secondItemFlag) {
		this.secondItemFlag = secondItemFlag;
	}
	@Column(name = "MIN_BASIC_UNIT", length = 30)
	public String getMinBasicUnit() {
		return this.minBasicUnit;
	}

	public void setMinBasicUnit(String minBasicUnit) {
		this.minBasicUnit = minBasicUnit;
	}

	@Column(name = "PACKAGE_UNIT", length = 30)
	public String getPackageUnit() {
		return this.packageUnit;
	}

	public void setPackageUnit(String packageUnit) {
		this.packageUnit = packageUnit;
	}

	@Column(name = "TRANSFER_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getTransferQuantity() {
		return this.transferQuantity;
	}

	public void setTransferQuantity(BigDecimal transferQuantity) {
		this.transferQuantity = transferQuantity;
	}
	
	@Column(name = "STRATEGY_MGMT_FLAG")
	public String getStrategyMgmtFlag() {
		return strategyMgmtFlag;
	}

	public void setStrategyMgmtFlag(String strategyMgmtFlag) {
		this.strategyMgmtFlag = strategyMgmtFlag;
	}
	
	@Column(name = "FACILITY_SUPPPLIER_NAME")
	public String getFacilitySupplierName() {
		return facilitySupplierName;
	}

	public void setFacilitySupplierName(String facilitySupplierName) {
		this.facilitySupplierName = facilitySupplierName;
	}
	
	@Column(name = "FACILITY_SUPPLIER_ADDRESS")
	public String getFacilitySupplierAddress() {
		return facilitySupplierAddress;
	}

	public void setFacilitySupplierAddress(String facilitySupplierAddress) {
		this.facilitySupplierAddress = facilitySupplierAddress;
	}
	
	@Column(name = "FACILITY_SUPPLIER_PHONE")
	public String getFacilitySupplierPhone() {
		return facilitySupplierPhone;
	}

	public void setFacilitySupplierPhone(String facilitySupplierPhone) {
		this.facilitySupplierPhone = facilitySupplierPhone;
	}
	
	@Column(name = "FACILITY_SUPPLIER_CONTACT")
	public String getFacilitySupplierContact() {
		return facilitySupplierContact;
	}

	public void setFacilitySupplierContact(String facilitySupplierContact) {
		this.facilitySupplierContact = facilitySupplierContact;
	}
	
	@Column(name = "FACILITY_SUPPLIER_ITEMNUM")
	public String getFacilitySupplierItemnum() {
		return facilitySupplierItemnum;
	}

	public void setFacilitySupplierItemnum(String facilitySupplierItemnum) {
		this.facilitySupplierItemnum = facilitySupplierItemnum;
	}
	@Column(name = "ORI_UNITCOST")
	public BigDecimal getOriUnitcost() {
		return oriUnitcost;
	}

	public void setOriUnitcost(BigDecimal oriUnitcost) {
		this.oriUnitcost = oriUnitcost;
	}
	@Column(name = "ORI_CURRENCY")
	public String getOriCurrency() {
		return oriCurrency;
	}

	public void setOriCurrency(String oriCurrency) {
		this.oriCurrency = oriCurrency;
	}
	@Column(name = "ORI_RATE")
	public BigDecimal getOriRate() {
		return oriRate;
	}

	public void setOriRate(BigDecimal oriRate) {
		this.oriRate = oriRate;
	}
	@Column(name = "MC_USE_FREQUENCY_TYPE")
	public String getMcUseFrequencyType() {
		return mcUseFrequencyType;
	}

	public void setMcUseFrequencyType(String mcUseFrequencyType) {
		this.mcUseFrequencyType = mcUseFrequencyType;
	}
	@Column(name = "SECOND_SOURCE_ITEMNUM")
	public String getSecondSourceItemnum() {
		return secondSourceItemnum;
	}

	public void setSecondSourceItemnum(String secondSourceItemnum) {
		this.secondSourceItemnum = secondSourceItemnum;
	}
	@Column(name = "INSPECTION_TYPE")
	public String getInspectionType() {
		return inspectionType;
	}

	public void setInspectionType(String inspectionType) {
		this.inspectionType = inspectionType;
	}
	@Column(name = "FACILITY_NUM")
	public String getFacilityNum() {
		return facilityNum;
	}

	public void setFacilityNum(String facilityNum) {
		this.facilityNum = facilityNum;
	}

	@Column(name = "GP_EV_LV", length = 50)
	public String getGpEvLv() {
		return gpEvLv;
	}

	public void setGpEvLv(String gpEvLv) {
		this.gpEvLv = gpEvLv;
	}
	
	@Column(name = "GP_RISK_LV", length = 50)
	public String getGpRiskLv() {
		return gpRiskLv;
	}

	public void setGpRiskLv(String gpRiskLv) {
		this.gpRiskLv = gpRiskLv;
	}
	
	@Column(name = "SECOND_ITEM_TYPE", length = 15)
	public String getSecondItemType() {
		return secondItemType;
	}

	public void setSecondItemType(String secondItemType) {
		this.secondItemType = secondItemType;
	}
	
}
