package mro.base.entity;

// Generated 2016/3/2 �U�� 02:35:17 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemSiteTransferLog generated by hbm2java
 */
@Entity
@Table(name = "ITEM_SITE_TRANSFER_LOG")
public class ItemSiteTransferLog implements java.io.Serializable {

	private BigDecimal itemSiteTransferId;
	private BigDecimal itemid;
	private String itemnum;
	private String plantCode;
	private String status;
	private BigDecimal applyCategory;
	private String applyKeyId;
	private String createBy;
	private Date createDate;
	private Date transferDate;
	private String actionType;
	private String storageLocation;
	private String materialGroup;

	public ItemSiteTransferLog() {
	}

	public ItemSiteTransferLog(BigDecimal itemSiteTransferId) {
		this.itemSiteTransferId = itemSiteTransferId;
	}

	public ItemSiteTransferLog(BigDecimal itemSiteTransferId,
			BigDecimal itemid, String itemnum, String plantCode, String status,
			BigDecimal applyCategory, String applyKeyId, String createBy,
			Date createDate, Date transferDate, String actionType,
			String storageLocation, String materialGroup) {
		this.itemSiteTransferId = itemSiteTransferId;
		this.itemid = itemid;
		this.itemnum = itemnum;
		this.plantCode = plantCode;
		this.status = status;
		this.applyCategory = applyCategory;
		this.applyKeyId = applyKeyId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.transferDate = transferDate;
		this.actionType = actionType;
		this.storageLocation = storageLocation;
		this.materialGroup = materialGroup;
	}

	@Id
	@SequenceGenerator(name="ITEM_SITE_TRANSFER_ID_GENERATOR", sequenceName="ITEM_SITE_TRANSFER_LOG_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ITEM_SITE_TRANSFER_ID_GENERATOR")
	@Column(name = "ITEM_SITE_TRANSFER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemSiteTransferId() {
		return this.itemSiteTransferId;
	}

	public void setItemSiteTransferId(BigDecimal itemSiteTransferId) {
		this.itemSiteTransferId = itemSiteTransferId;
	}

	@Column(name = "ITEMID", precision = 22, scale = 0)
	public BigDecimal getItemid() {
		return this.itemid;
	}

	public void setItemid(BigDecimal itemid) {
		this.itemid = itemid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "PLANT_CODE", length = 4)
	public String getPlantCode() {
		return this.plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	@Column(name = "STATUS", length = 6)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "APPLY_CATEGORY", precision = 22, scale = 0)
	public BigDecimal getApplyCategory() {
		return this.applyCategory;
	}

	public void setApplyCategory(BigDecimal applyCategory) {
		this.applyCategory = applyCategory;
	}

	@Column(name = "APPLY_KEY_ID", length = 30)
	public String getApplyKeyId() {
		return this.applyKeyId;
	}

	public void setApplyKeyId(String applyKeyId) {
		this.applyKeyId = applyKeyId;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSFER_DATE", length = 7)
	public Date getTransferDate() {
		return this.transferDate;
	}

	public void setTransferDate(Date transferDate) {
		this.transferDate = transferDate;
	}

	@Column(name = "ACTION_TYPE", length = 1)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "STORAGE_LOCATION", length = 4)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "MATERIAL_GROUP", length = 9)
	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

}
