package mro.base.entity;

// Generated 2014/1/8 �U�� 03:42:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemTransferHeaderApply generated by hbm2java
 */
@Entity
@Table(name = "ITEM_TRANSFER_HEADER_APPLY")
public class ItemTransferHeaderApply implements java.io.Serializable {

	private BigDecimal applyHeaderId;
	private String action;
	private String deptcode;
	private String locationSite;
	private String status;
	private String createBy;
	private Date createDate;
	private Date lastUpdateDate;
	private BigDecimal taskId;
	private String applyHeaderNum;
	private String classstructureid;
	private String headerRemark;
	private String in20;
	private Set<ItemTransferLineApply> itemTransferLineApplies = new HashSet<ItemTransferLineApply>(
			0);

	public ItemTransferHeaderApply() {
	}

	public ItemTransferHeaderApply(BigDecimal applyHeaderId) {
		this.applyHeaderId = applyHeaderId;
	}

	public ItemTransferHeaderApply(BigDecimal applyHeaderId, String action,
			String deptcode,  String locationSite,
			String status, String createBy, Date createDate,
			Date lastUpdateDate, BigDecimal taskId, String applyHeaderNum,
			Set<ItemTransferLineApply> itemTransferLineApplies,String classstructureid,
			String headerRemark,String in20) {
		this.applyHeaderId = applyHeaderId;
		this.action = action;
		this.deptcode = deptcode;
		this.locationSite = locationSite;
		this.status = status;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lastUpdateDate = lastUpdateDate;
		this.taskId = taskId;
		this.applyHeaderNum = applyHeaderNum;
		this.itemTransferLineApplies = itemTransferLineApplies;
		this.classstructureid = classstructureid;
		this.headerRemark = headerRemark;
		this.in20 = in20;
	}

	@Id
	@SequenceGenerator(name="APPLY_HEADER_ID_GENERATOR", sequenceName="ITEM_TRANSFER_HEADER_APPLY_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="APPLY_HEADER_ID_GENERATOR")
	@Column(name = "APPLY_HEADER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getApplyHeaderId() {
		return this.applyHeaderId;
	}

	public void setApplyHeaderId(BigDecimal applyHeaderId) {
		this.applyHeaderId = applyHeaderId;
	}

	@Column(name = "ACTION", length = 10)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "DEPTCODE", length = 30)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "LOCATION_SITE", length = 30)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "TASK_ID", precision = 22, scale = 0)
	public BigDecimal getTaskId() {
		return this.taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}

	@Column(name = "APPLY_HEADER_NUM", length = 30)
	public String getApplyHeaderNum() {
		return this.applyHeaderNum;
	}

	public void setApplyHeaderNum(String applyHeaderNum) {
		this.applyHeaderNum = applyHeaderNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemTransferHeaderApply")
	public Set<ItemTransferLineApply> getItemTransferLineApplies() {
		return this.itemTransferLineApplies;
	}

	public void setItemTransferLineApplies(
			Set<ItemTransferLineApply> itemTransferLineApplies) {
		this.itemTransferLineApplies = itemTransferLineApplies;
	}
	
	@Column(name = "CLASSSTRUCTUREID")
	public String getClassstructureid() {
		return classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}
	@Column(name = "HEADER_REMARK")
	public String getHeaderRemark() {
		return headerRemark;
	}

	public void setHeaderRemark(String headerRemark) {
		this.headerRemark = headerRemark;
	}

	@Column(name = "IN20", length = 1)
	public String getIn20() {
		return this.in20;
	}

	public void setIn20(String in20) {
		this.in20 = in20;
	}
}
