package mro.base.entity;

// Generated 2014/1/6 �W�� 11:35:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ItemSite generated by hbm2java
 */
@Entity
@Table(name = "ITEM_SITE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMID", "ITEMNUM", "LOCATION_SITE" }))
public class ItemSite implements java.io.Serializable {

	private BigDecimal itemSiteId;
	private BigDecimal itemid;
	private String itemnum;
	private String locationSite;
	private String enableFlag;
	private String lastUpdatedBy;
	private Date lastUpdateDate;

	public ItemSite() {
	}

	public ItemSite(BigDecimal itemSiteId) {
		this.itemSiteId = itemSiteId;
	}

	public ItemSite(BigDecimal itemSiteId, BigDecimal itemid, String itemnum,
			String locationSite, String enableFlag, String lastUpdatedBy,
			Date lastUpdateDate) {
		this.itemSiteId = itemSiteId;
		this.itemid = itemid;
		this.itemnum = itemnum;
		this.locationSite = locationSite;
		this.enableFlag = enableFlag;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@SequenceGenerator(name="ITEM_SITE_ID_GENERATOR", sequenceName="ITEM_SITE_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ITEM_SITE_ID_GENERATOR")
	@Column(name = "ITEM_SITE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getItemSiteId() {
		return this.itemSiteId;
	}

	public void setItemSiteId(BigDecimal itemSiteId) {
		this.itemSiteId = itemSiteId;
	}

	@Column(name = "ITEMID", precision = 22, scale = 0)
	public BigDecimal getItemid() {
		return this.itemid;
	}

	public void setItemid(BigDecimal itemid) {
		this.itemid = itemid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "LOCATION_SITE", length = 50)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "ENABLE_FLAG", length = 1)
	public String getEnableFlag() {
		return this.enableFlag;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	@Column(name = "LAST_UPDATED_BY", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
