package mro.base.entity;

// Generated 2015/9/30 �U�� 03:11:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LampControlLineLog generated by hbm2java
 */
@Entity
@Table(name = "LAMP_CONTROL_LINE_LOG")
public class LampControlLineLog implements java.io.Serializable {

	private BigDecimal logId;
	private LampControlLine lampControlLine;
	private String lastUpdateBy;
	private Date lastUpdate;
	private BigDecimal needQty;
	private Date needDate;
	private BigDecimal mcQty;
	private BigDecimal matuseQty;
	private String remark;

	public LampControlLineLog() {
	}

	public LampControlLineLog(BigDecimal logId, String lastUpdateBy) {
		this.logId = logId;
		this.lastUpdateBy = lastUpdateBy;
	}

	public LampControlLineLog(BigDecimal logId,
			LampControlLine lampControlLine, String lastUpdateBy,
			Date lastUpdate, BigDecimal needQty, Date needDate,
			BigDecimal mcQty, BigDecimal matuseQty, String remark) {
		this.logId = logId;
		this.lampControlLine = lampControlLine;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdate = lastUpdate;
		this.needQty = needQty;
		this.needDate = needDate;
		this.mcQty = mcQty;
		this.matuseQty = matuseQty;
		this.remark = remark;
	}

	@Id
	@SequenceGenerator(name="LOG_ID_GENERATOR", sequenceName="LAMP_CONTROL_LINE_SEQ_LOG", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LOG_ID_GENERATOR")
	@Column(name = "LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLogId() {
		return this.logId;
	}

	public void setLogId(BigDecimal logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LINE_ID")
	public LampControlLine getLampControlLine() {
		return this.lampControlLine;
	}

	public void setLampControlLine(LampControlLine lampControlLine) {
		this.lampControlLine = lampControlLine;
	}

	@Column(name = "LAST_UPDATE_BY", nullable = false, length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "NEED_QTY", precision = 22, scale = 0)
	public BigDecimal getNeedQty() {
		return this.needQty;
	}

	public void setNeedQty(BigDecimal needQty) {
		this.needQty = needQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEED_DATE", length = 7)
	public Date getNeedDate() {
		return this.needDate;
	}

	public void setNeedDate(Date needDate) {
		this.needDate = needDate;
	}

	@Column(name = "MC_QTY", precision = 22, scale = 0)
	public BigDecimal getMcQty() {
		return this.mcQty;
	}

	public void setMcQty(BigDecimal mcQty) {
		this.mcQty = mcQty;
	}

	@Column(name = "MATUSE_QTY", precision = 22, scale = 0)
	public BigDecimal getMatuseQty() {
		return this.matuseQty;
	}

	public void setMatuseQty(BigDecimal matuseQty) {
		this.matuseQty = matuseQty;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
