package mro.base.entity;

// Generated 2015/9/30 �U�� 03:11:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LampControlHeader generated by hbm2java
 */
@Entity
@Table(name = "LAMP_CONTROL_HEADER")
public class LampControlHeader implements java.io.Serializable {

	private BigDecimal headerId;
	private String createBy;
	private Date createDate;
	private String lastUpdateBy;
	private Date lastUpdate;
	private String itemnum;
	private String organizationCode;
	private String deptCode;
	private String deleted;
	private String remark;
	private Item item;
	private Set<LampControlLine> lampControlLines = new HashSet<LampControlLine>(
			0);
	
	@Override
	public boolean equals(Object obj) {
	    if(obj instanceof LampControlHeader && 
	    	((LampControlHeader)obj).getHeaderId().compareTo(this.headerId)==0) {
	        return true;
	    }else {
	        return false;
	    }
	}
	
	public LampControlHeader() {
	}

	public LampControlHeader(BigDecimal headerId, String createBy,
			String lastUpdateBy, String itemnum, String organizationCode,
			String deptCode) {
		this.headerId = headerId;
		this.createBy = createBy;
		this.lastUpdateBy = lastUpdateBy;
		this.itemnum = itemnum;
		this.organizationCode = organizationCode;
		this.deptCode = deptCode;
	}
	public LampControlHeader(BigDecimal headerId, String createBy,
			Date createDate, String lastUpdateBy, Date lastUpdate,
			String itemnum, String organizationCode, String deptCode,
			String deleted, String remark, Item item,
			Set<LampControlLine> lampControlLines) {
		this.headerId = headerId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdate = lastUpdate;
		this.itemnum = itemnum;
		this.organizationCode = organizationCode;
		this.deptCode = deptCode;
		this.deleted = deleted;
		this.remark = remark;
		this.item = item;
		this.lampControlLines = lampControlLines;
	}

	@Id
	@SequenceGenerator(name="HEADER_ID_GENERATOR", sequenceName="LAMP_CONTROL_HEADER_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="HEADER_ID_GENERATOR")
	@Column(name = "HEADER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHeaderId() {
		return this.headerId;
	}

	public void setHeaderId(BigDecimal headerId) {
		this.headerId = headerId;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_BY", nullable = false, length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "ORGANIZATION_CODE", nullable = false, length = 20)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "DEPT_CODE", nullable = false, length = 12)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "DELETED", length = 1)
	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEMID")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lampControlHeader")
	public Set<LampControlLine> getLampControlLines() {
		return this.lampControlLines;
	}

	public void setLampControlLines(Set<LampControlLine> lampControlLines) {
		this.lampControlLines = lampControlLines;
	}

}
