package mro.base.entity;

// Generated 2015/9/30 �U�� 03:11:22 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LampControlLine generated by hbm2java
 */
@Entity
@Table(name = "LAMP_CONTROL_LINE")
public class LampControlLine implements java.io.Serializable {

	private BigDecimal lineId;
	private LampControlHeader lampControlHeader;
	private String createBy;
	private Date createDate;
	private String lastUpdateBy;
	private Date lastUpdate;
	private BigDecimal needQty;
	private Date needDate;
	private BigDecimal mcQty;
	private BigDecimal matuseQty;
	private String remark;
	private Date controlDateStart;
	private Date controlDateEnd;
	private Set<LampControlLineLog> lampControlLineLogs = new HashSet<LampControlLineLog>(
			0);

	public LampControlLine() {
	}

	public LampControlLine(BigDecimal lineId, String createBy,
			String lastUpdateBy) {
		this.lineId = lineId;
		this.createBy = createBy;
		this.lastUpdateBy = lastUpdateBy;
	}

	public LampControlLine(BigDecimal lineId,
			LampControlHeader lampControlHeader, String createBy,
			Date createDate, String lastUpdateBy, Date lastUpdate,
			BigDecimal needQty, Date needDate, BigDecimal mcQty,
			BigDecimal matuseQty, String remark, Date controlDateStart,
			Date controlDateEnd, Set<LampControlLineLog> lampControlLineLogs) {
		this.lineId = lineId;
		this.lampControlHeader = lampControlHeader;
		this.createBy = createBy;
		this.createDate = createDate;
		this.lastUpdateBy = lastUpdateBy;
		this.lastUpdate = lastUpdate;
		this.needQty = needQty;
		this.needDate = needDate;
		this.mcQty = mcQty;
		this.matuseQty = matuseQty;
		this.remark = remark;
		this.controlDateStart = controlDateStart;
		this.controlDateEnd = controlDateEnd;
		this.lampControlLineLogs = lampControlLineLogs;
	}

	@Id
	@SequenceGenerator(name="LINE_ID_GENERATOR", sequenceName="LAMP_CONTROL_LINE_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LINE_ID_GENERATOR")
	@Column(name = "LINE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLineId() {
		return this.lineId;
	}

	public void setLineId(BigDecimal lineId) {
		this.lineId = lineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HEADER_ID")
	public LampControlHeader getLampControlHeader() {
		return this.lampControlHeader;
	}

	public void setLampControlHeader(LampControlHeader lampControlHeader) {
		this.lampControlHeader = lampControlHeader;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_BY", nullable = false, length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "NEED_QTY", precision = 22, scale = 0)
	public BigDecimal getNeedQty() {
		return this.needQty;
	}

	public void setNeedQty(BigDecimal needQty) {
		this.needQty = needQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEED_DATE", length = 7)
	public Date getNeedDate() {
		return this.needDate;
	}

	public void setNeedDate(Date needDate) {
		this.needDate = needDate;
	}

	@Column(name = "MC_QTY", precision = 22, scale = 0)
	public BigDecimal getMcQty() {
		return this.mcQty;
	}

	public void setMcQty(BigDecimal mcQty) {
		this.mcQty = mcQty;
	}

	@Column(name = "MATUSE_QTY", precision = 22, scale = 0)
	public BigDecimal getMatuseQty() {
		return this.matuseQty;
	}

	public void setMatuseQty(BigDecimal matuseQty) {
		this.matuseQty = matuseQty;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONTROL_DATE_START", length = 7)
	public Date getControlDateStart() {
		return this.controlDateStart;
	}

	public void setControlDateStart(Date controlDateStart) {
		this.controlDateStart = controlDateStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONTROL_DATE_END", length = 7)
	public Date getControlDateEnd() {
		return this.controlDateEnd;
	}

	public void setControlDateEnd(Date controlDateEnd) {
		this.controlDateEnd = controlDateEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lampControlLine")
	public Set<LampControlLineLog> getLampControlLineLogs() {
		return this.lampControlLineLogs;
	}

	public void setLampControlLineLogs(
			Set<LampControlLineLog> lampControlLineLogs) {
		this.lampControlLineLogs = lampControlLineLogs;
	}

}
