package mro.base.entity;

// Generated 2013/12/27 �U�� 02:06:08 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * LocationMap generated by hbm2java
 */
@Entity
@Table(name = "LOCATION_MAP", uniqueConstraints = {
		@UniqueConstraint(columnNames = "ORGANIZATION_CODE"),
		@UniqueConstraint(columnNames = "ORGANIZATION_NAME"),
		@UniqueConstraint(columnNames = "SITE_ID") })
public class LocationMap implements java.io.Serializable {

	private BigDecimal locationMapId;
	private String locationId;
	private String sapPsaDesc;
	private String siteId;
	private String organizationCode;
	private String org;
	private String currencycode;
	private String organizationName;
	private Date createDate;
	private String createBy;
	private String nonvaluePlant;
	private LocationSiteMap locationSiteMap;
	private String oldOrganizationCode;
	private String oldsiteId;

	public LocationMap() {
	}

	public LocationMap(BigDecimal locationMapId) {
		this.locationMapId = locationMapId;
	}

	public LocationMap(BigDecimal locationMapId, String locationId,
			String sapPsaDesc, String siteId, String organizationCode,
			String org, String currencycode, String organizationName,
			 Date createDate, String createBy,
			String nonvaluePlant,LocationSiteMap locationSiteMap,
			String oldOrganizationCode,String oldsiteId) {
		this.locationMapId = locationMapId;
		this.locationId = locationId;
		this.sapPsaDesc = sapPsaDesc;
		this.siteId = siteId;
		this.organizationCode = organizationCode;
		this.org = org;
		this.currencycode = currencycode;
		this.organizationName = organizationName;
		this.createDate = createDate;
		this.createBy = createBy;
		this.nonvaluePlant = nonvaluePlant;
		this.locationSiteMap = locationSiteMap;
		this.oldOrganizationCode = oldOrganizationCode;
		this.oldsiteId = oldsiteId;
	}

	@Id
	@SequenceGenerator(name="LOCATION_MAP_ID_GENERATOR", sequenceName="LOCATION_MAP_SEQ", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LOCATION_MAP_ID_GENERATOR")
	@Column(name = "LOCATION_MAP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLocationMapId() {
		return this.locationMapId;
	}

	public void setLocationMapId(BigDecimal locationMapId) {
		this.locationMapId = locationMapId;
	}

	@Column(name = "LOCATION_ID", length = 6)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "SAP_PSA_DESC", length = 30)
	public String getSapPsaDesc() {
		return this.sapPsaDesc;
	}

	public void setSapPsaDesc(String sapPsaDesc) {
		this.sapPsaDesc = sapPsaDesc;
	}

	@Column(name = "SITE_ID", unique = true, precision = 22, scale = 0)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@Column(name = "ORGANIZATION_CODE", unique = true, length = 20)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "ORG", length = 10)
	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	@Column(name = "CURRENCYCODE", length = 8)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "ORGANIZATION_NAME", unique = true, length = 50)
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_BY", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	
	@Column(name = "NONVALUE_PLANT", length = 6)
	public String getNonvaluePlant() {
		return nonvaluePlant;
	}

	public void setNonvaluePlant(String nonvaluePlant) {
		this.nonvaluePlant = nonvaluePlant;
	}	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}
	@Column(name = "OLD_ORGANIZATION_CODE")
	public String getOldOrganizationCode() {
		return oldOrganizationCode;
	}

	public void setOldOrganizationCode(String oldOrganizationCode) {
		this.oldOrganizationCode = oldOrganizationCode;
	}
	@Column(name = "OLD_SITE_ID")
	public String getOldsiteId() {
		return oldsiteId;
	}

	public void setOldsiteId(String oldsiteId) {
		this.oldsiteId = oldsiteId;
	}
	
}
