package mro.base.entity;

// Generated 2014/1/17 �W�� 10:38:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationSiteMap generated by hbm2java
 */
@Entity
@Table(name = "LOCATION_SITE_MAP")
public class LocationSiteMap implements java.io.Serializable {

	private String locationSite;
	private Date lastUpdateDate;
	private String lastUpdatedBy;
	private String epMallCompanyId;
	
	@Override
	public boolean equals(Object obj) {
	    if(obj!=null && obj instanceof LocationSiteMap && 
	    	((LocationSiteMap)obj).locationSite.equals(this.locationSite)) {
	        return true;
	    }else {
	        return false;
	    }
	}
	
	public LocationSiteMap() {
	}	public LocationSiteMap(String locationSite) {
		this.locationSite = locationSite;
	}

	public LocationSiteMap(String locationSite,
			Date lastUpdateDate, String lastUpdatedBy, String epMallCompanyId) {
		this.locationSite = locationSite;
		this.lastUpdateDate = lastUpdateDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.epMallCompanyId = epMallCompanyId;
	}

	@Id
	@Column(name = "LOCATION_SITE", length = 50)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "LAST_UPDATED_BY", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "EP_MALL_COMPANY_ID", length = 50)
	public String getEpMallCompanyId() {
		return this.epMallCompanyId;
	}

	public void setEpMallCompanyId(String epMallCompanyId) {
		this.epMallCompanyId = epMallCompanyId;
	}

}
