package mro.base.entity;

// Generated 2013/2/26 �U�� 02:32:37 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Longdescription generated by hbm2java
 */
@Entity
@Table(name = "LONGDESCRIPTION", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LDKEY", "LDOWNERTABLE", "LANGCODE", "LDOWNERCOL" }))
public class Longdescription implements java.io.Serializable {

	private BigDecimal longdescriptionid;
	private BigDecimal ldkey;
	private String ldownertable;
	private String ldownercol;
	private String langcode;
	private String ldtext;
	private Date createDate;

	public Longdescription() {
	}

	public Longdescription(BigDecimal longdescriptionid, BigDecimal ldkey,
			String ldownertable, String ldownercol, String langcode) {
		this.longdescriptionid = longdescriptionid;
		this.ldkey = ldkey;
		this.ldownertable = ldownertable;
		this.ldownercol = ldownercol;
		this.langcode = langcode;
	}

	public Longdescription(BigDecimal longdescriptionid, BigDecimal ldkey,
			String ldownertable, String ldownercol, String langcode,
			String ldtext, Date createDate) {
		this.longdescriptionid = longdescriptionid;
		this.ldkey = ldkey;
		this.ldownertable = ldownertable;
		this.ldownercol = ldownercol;
		this.langcode = langcode;
		this.ldtext = ldtext;
		this.createDate = createDate;
	}

	@Id
	@SequenceGenerator(name="LONGDESCRIPTIONID_GENERATOR", sequenceName="LONGDESCRIPTIONSEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="LONGDESCRIPTIONID_GENERATOR")
	@Column(name = "LONGDESCRIPTIONID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getLongdescriptionid() {
		return this.longdescriptionid;
	}

	public void setLongdescriptionid(BigDecimal longdescriptionid) {
		this.longdescriptionid = longdescriptionid;
	}

	@Column(name = "LDKEY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLdkey() {
		return this.ldkey;
	}

	public void setLdkey(BigDecimal ldkey) {
		this.ldkey = ldkey;
	}

	@Column(name = "LDOWNERTABLE", nullable = false, length = 18)
	public String getLdownertable() {
		return this.ldownertable;
	}

	public void setLdownertable(String ldownertable) {
		this.ldownertable = ldownertable;
	}

	@Column(name = "LDOWNERCOL", nullable = false, length = 18)
	public String getLdownercol() {
		return this.ldownercol;
	}

	public void setLdownercol(String ldownercol) {
		this.ldownercol = ldownercol;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "LDTEXT", length = 4000)
	public String getLdtext() {
		return this.ldtext;
	}

	public void setLdtext(String ldtext) {
		this.ldtext = ldtext;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
