package mro.base.entity;

// Generated 2017/1/16 �W�� 09:58:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MailConfig generated by hbm2java
 */
@Entity
@Table(name = "MAIL_CONFIG")
public class MailConfig implements java.io.Serializable {

	private String appId;
	private String appDesc;
	private String selectStatement;
	private String notifyEmail;
	private String alertSubject;
	private String alertHeader;
	private String ccEmail;
	private String perLineFlag;
	private BigDecimal createdBy;
	private Date creationDate;
	private BigDecimal lastupdateBy;
	private Date lastupdateDate;
	private String groupValue;

	public MailConfig() {
	}

	public MailConfig(String appId, String appDesc, String selectStatement,
			String notifyEmail) {
		this.appId = appId;
		this.appDesc = appDesc;
		this.selectStatement = selectStatement;
		this.notifyEmail = notifyEmail;
	}

	public MailConfig(String appId, String appDesc, String selectStatement,
			String notifyEmail, String alertSubject, String alertHeader,
			String ccEmail, String perLineFlag, BigDecimal createdBy,
			Date creationDate, BigDecimal lastupdateBy, Date lastupdateDate,
			String groupValue) {
		this.appId = appId;
		this.appDesc = appDesc;
		this.selectStatement = selectStatement;
		this.notifyEmail = notifyEmail;
		this.alertSubject = alertSubject;
		this.alertHeader = alertHeader;
		this.ccEmail = ccEmail;
		this.perLineFlag = perLineFlag;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastupdateBy = lastupdateBy;
		this.lastupdateDate = lastupdateDate;
		this.groupValue = groupValue;
	}

	@Id
	@Column(name = "APP_ID", unique = true, nullable = false, length = 200)
	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@Column(name = "APP_DESC", nullable = false, length = 200)
	public String getAppDesc() {
		return this.appDesc;
	}

	public void setAppDesc(String appDesc) {
		this.appDesc = appDesc;
	}

	@Column(name = "SELECT_STATEMENT", nullable = false, length = 4000)
	public String getSelectStatement() {
		return this.selectStatement;
	}

	public void setSelectStatement(String selectStatement) {
		this.selectStatement = selectStatement;
	}

	@Column(name = "NOTIFY_EMAIL", nullable = false, length = 4000)
	public String getNotifyEmail() {
		return this.notifyEmail;
	}

	public void setNotifyEmail(String notifyEmail) {
		this.notifyEmail = notifyEmail;
	}

	@Column(name = "ALERT_SUBJECT", length = 200)
	public String getAlertSubject() {
		return this.alertSubject;
	}

	public void setAlertSubject(String alertSubject) {
		this.alertSubject = alertSubject;
	}

	@Column(name = "ALERT_HEADER", length = 4000)
	public String getAlertHeader() {
		return this.alertHeader;
	}

	public void setAlertHeader(String alertHeader) {
		this.alertHeader = alertHeader;
	}

	@Column(name = "CC_EMAIL", length = 4000)
	public String getCcEmail() {
		return this.ccEmail;
	}

	public void setCcEmail(String ccEmail) {
		this.ccEmail = ccEmail;
	}

	@Column(name = "PER_LINE_FLAG", length = 1)
	public String getPerLineFlag() {
		return this.perLineFlag;
	}

	public void setPerLineFlag(String perLineFlag) {
		this.perLineFlag = perLineFlag;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public BigDecimal getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(BigDecimal createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 7)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LASTUPDATE_BY", precision = 22, scale = 0)
	public BigDecimal getLastupdateBy() {
		return this.lastupdateBy;
	}

	public void setLastupdateBy(BigDecimal lastupdateBy) {
		this.lastupdateBy = lastupdateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LASTUPDATE_DATE", length = 7)
	public Date getLastupdateDate() {
		return this.lastupdateDate;
	}

	public void setLastupdateDate(Date lastupdateDate) {
		this.lastupdateDate = lastupdateDate;
	}

	@Column(name = "GROUP_VALUE", length = 50)
	public String getGroupValue() {
		return this.groupValue;
	}

	public void setGroupValue(String groupValue) {
		this.groupValue = groupValue;
	}

}
