package mro.base.entity;

// Generated 2014/9/25 �U�� 01:56:02 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * MailQueue generated by hbm2java
 */
@Entity
@Table(name = "MAIL_QUEUE")
public class MailQueue implements java.io.Serializable {

	private String mqId;
	private String mqToList;
	private String mqCcList;
	private String mqBccList;
	private String mqSubject;
	private String mqMessage;
	private String mqFrom;
	private Date mqCreateDate;
	private Date mqSendDate;
	private String mqStatus;
	private BigDecimal mqRetry;

	public MailQueue() {
	}

	public MailQueue(String mqId) {
		this.mqId = mqId;
	}

	public MailQueue(String mqId, String mqToList, String mqCcList,
			String mqBccList, String mqSubject, String mqMessage,
			String mqFrom,  Date mqCreateDate,
			Date mqSendDate, String mqStatus, BigDecimal mqRetry) {
		this.mqId = mqId;
		this.mqToList = mqToList;
		this.mqCcList = mqCcList;
		this.mqBccList = mqBccList;
		this.mqSubject = mqSubject;
		this.mqMessage = mqMessage;
		this.mqFrom = mqFrom;
		this.mqCreateDate = mqCreateDate;
		this.mqSendDate = mqSendDate;
		this.mqStatus = mqStatus;
		this.mqRetry = mqRetry;
	}

	@Id
//	@SequenceGenerator(name="MQ_ID_GENERATOR", sequenceName="MAIL_QUEUE_SEQ", allocationSize=1)
//	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MQ_ID_GENERATOR")
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "MQ_ID", unique = true, nullable = false)
	public String getMqId() {
		return this.mqId;
	}

	public void setMqId(String mqId) {
		this.mqId = mqId;
	}

	@Column(name = "MQ_TO_LIST", length = 1000)
	public String getMqToList() {
		return this.mqToList;
	}

	public void setMqToList(String mqToList) {
		this.mqToList = mqToList;
	}

	@Column(name = "MQ_CC_LIST", length = 1000)
	public String getMqCcList() {
		return this.mqCcList;
	}

	public void setMqCcList(String mqCcList) {
		this.mqCcList = mqCcList;
	}

	@Column(name = "MQ_BCC_LIST", length = 1000)
	public String getMqBccList() {
		return this.mqBccList;
	}

	public void setMqBccList(String mqBccList) {
		this.mqBccList = mqBccList;
	}

	@Column(name = "MQ_SUBJECT", length = 200)
	public String getMqSubject() {
		return this.mqSubject;
	}

	public void setMqSubject(String mqSubject) {
		this.mqSubject = mqSubject;
	}

	@Column(name = "MQ_MESSAGE", length = 4000)
	public String getMqMessage() {
		return this.mqMessage;
	}

	public void setMqMessage(String mqMessage) {
		this.mqMessage = mqMessage;
	}

	@Column(name = "MQ_FROM", length = 50)
	public String getMqFrom() {
		return this.mqFrom;
	}

	public void setMqFrom(String mqFrom) {
		this.mqFrom = mqFrom;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MQ_CREATE_DATE", length = 7)
	public Date getMqCreateDate() {
		return this.mqCreateDate;
	}

	public void setMqCreateDate(Date mqCreateDate) {
		this.mqCreateDate = mqCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MQ_SEND_DATE", length = 7)
	public Date getMqSendDate() {
		return this.mqSendDate;
	}

	public void setMqSendDate(Date mqSendDate) {
		this.mqSendDate = mqSendDate;
	}

	@Column(name = "MQ_STATUS", length = 20)
	public String getMqStatus() {
		return this.mqStatus;
	}

	public void setMqStatus(String mqStatus) {
		this.mqStatus = mqStatus;
	}

	@Column(name = "MQ_RETRY", precision = 22, scale = 0)
	public BigDecimal getMqRetry() {
		return this.mqRetry;
	}

	public void setMqRetry(BigDecimal mqRetry) {
		this.mqRetry = mqRetry;
	}

}
