package mro.base.entity;

// Generated 2012/10/30 �W�� 10:55:39 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Matrectrans generated by hbm2java
 */
@Entity
@Table(name = "MATRECTRANS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SITEID", "MATRECTRANSID" }))
public class Matrectrans implements java.io.Serializable {

	private BigDecimal matrectransid;
	private String itemnum;
	private String tostoreloc;
	private Date transdate;
	private Date actualdate;
	private BigDecimal quantity;
	private String receivedunit;
	private String issuetype;
	private BigDecimal unitcost;
	private BigDecimal actualcost;
	private String ponum;
	private String invoicenum;
	private String rejectcode;
	private BigDecimal rejectqty;
	private BigDecimal conversion;
	private String assetnum;
	private String enterby;
	private String it1;
	private String it2;
	private String it3;
	private BigDecimal it4;
	private String it5;
	private BigDecimal outside;
	private String issueto;
	private String packingslipnum;
	private BigDecimal polinenum;
	private BigDecimal issue;
	private String requestedby;
	private BigDecimal totalcurbal;
	private BigDecimal oldavgcost;
	private String itin1;
	private String itin2;
	private String itin3;
	private String tobin;
	private String gldebitacct;
	private String glcreditacct;
	private BigDecimal linecost;
	private String financialperiod;
	private String currencycode;
	private BigDecimal exchangerate;
	private BigDecimal currencyunitcost;
	private String manufacturer;
	private String modelnum;
	private BigDecimal currencylinecost;
	private String location;
	private String description;
	private String remark;
	private String fromstoreloc;
	private String frombin;
	private BigDecimal qtyheld;
	private String fromlot;
	private String tolot;
	private BigDecimal loadedcost;
	private String tax1code;
	private BigDecimal tax1;
	private String tax2code;
	private BigDecimal tax2;
	private String tax3code;
	private BigDecimal tax3;
	private String tax4code;
	private BigDecimal tax4;
	private String tax5code;
	private BigDecimal tax5;
	private BigDecimal prorated;
	private BigDecimal proratecost;
	private String status;
	private Date statusdate;
	private String statuschangeby;
	private String sourcesysid;
	private BigDecimal qtyrequested;
	private BigDecimal curbal;
	private BigDecimal exchangerate2;
	private BigDecimal linecost2;
	private String mrnum;
	private BigDecimal mrlinenum;
	private String ownersysid;
	private String externalrefid;
	private String it6;
	private String it7;
	private String it8;
	private String it9;
	private String it10;
	private String itin4;
	private String itin5;
	private String itin6;
	private String itin7;
	private String sendersysid;
	private String fincntrlid;
	private String orgid;
	private String siteid;
	private BigDecimal costinfo;
	private BigDecimal belongsto;
	private String refwo;
	private BigDecimal enteredastask;
	private String fromsiteid;
	private BigDecimal receiptref;
	private String linetype;
	private String itemsetid;
	private String conditioncode;
	private String fromconditioncode;
	private BigDecimal condrate;
	private String commoditygroup;
	private String commodity;
	private BigDecimal matusetransid;
	private String courier;
	private String langcode;
	private BigDecimal inspectedqty;
	private String positeid;
	private BigDecimal hasld;
	private String rotassetnum;
	private String rowstamp;
	private String transType;
	private String binnum;

	public Matrectrans() {
	}

	public Matrectrans(BigDecimal matrectransid, Date transdate,
			Date actualdate, BigDecimal unitcost, BigDecimal actualcost,
			BigDecimal rejectqty, String enterby, BigDecimal outside,
			BigDecimal issue, BigDecimal linecost, String currencycode,
			BigDecimal loadedcost, BigDecimal prorated, BigDecimal curbal,
			String orgid, String siteid, BigDecimal costinfo,
			BigDecimal enteredastask, String fromsiteid, String linetype,
			String langcode, BigDecimal hasld, String rowstamp) {
		this.matrectransid = matrectransid;
		this.transdate = transdate;
		this.actualdate = actualdate;
		this.unitcost = unitcost;
		this.actualcost = actualcost;
		this.rejectqty = rejectqty;
		this.enterby = enterby;
		this.outside = outside;
		this.issue = issue;
		this.linecost = linecost;
		this.currencycode = currencycode;
		this.loadedcost = loadedcost;
		this.prorated = prorated;
		this.curbal = curbal;
		this.orgid = orgid;
		this.siteid = siteid;
		this.costinfo = costinfo;
		this.enteredastask = enteredastask;
		this.fromsiteid = fromsiteid;
		this.linetype = linetype;
		this.langcode = langcode;
		this.hasld = hasld;
		this.rowstamp = rowstamp;
	}

	public Matrectrans(BigDecimal matrectransid, String itemnum,
			String tostoreloc, Date transdate, Date actualdate,
			BigDecimal quantity, String receivedunit, String issuetype,
			BigDecimal unitcost, BigDecimal actualcost, String ponum,
			String invoicenum, String rejectcode, BigDecimal rejectqty,
			BigDecimal conversion, String assetnum, String enterby, String it1,
			String it2, String it3, BigDecimal it4, String it5,
			BigDecimal outside, String issueto, String packingslipnum,
			BigDecimal polinenum, BigDecimal issue, String requestedby,
			BigDecimal totalcurbal, BigDecimal oldavgcost, String itin1,
			String itin2, String itin3, String tobin, String gldebitacct,
			String glcreditacct, BigDecimal linecost, String financialperiod,
			String currencycode, BigDecimal exchangerate,
			BigDecimal currencyunitcost, String manufacturer, String modelnum,
			BigDecimal currencylinecost, String location, String description,
			String remark, String fromstoreloc, String frombin,
			BigDecimal qtyheld, String fromlot, String tolot,
			BigDecimal loadedcost, String tax1code, BigDecimal tax1,
			String tax2code, BigDecimal tax2, String tax3code, BigDecimal tax3,
			String tax4code, BigDecimal tax4, String tax5code, BigDecimal tax5,
			BigDecimal prorated, BigDecimal proratecost, String status,
			Date statusdate, String statuschangeby, String sourcesysid,
			BigDecimal qtyrequested, BigDecimal curbal,
			BigDecimal exchangerate2, BigDecimal linecost2, String mrnum,
			BigDecimal mrlinenum, String ownersysid, String externalrefid,
			String it6, String it7, String it8, String it9, String it10,
			String itin4, String itin5, String itin6, String itin7,
			String sendersysid, String fincntrlid, String orgid, String siteid,
			BigDecimal costinfo, BigDecimal belongsto, String refwo,
			BigDecimal enteredastask, String fromsiteid, BigDecimal receiptref,
			String linetype, String itemsetid, String conditioncode,
			String fromconditioncode, BigDecimal condrate,
			String commoditygroup, String commodity, BigDecimal matusetransid,
			String courier, String langcode, BigDecimal inspectedqty,
			String positeid, BigDecimal hasld, String rotassetnum,
			String rowstamp,String transType,String binnum) {
		this.matrectransid = matrectransid;
		this.itemnum = itemnum;
		this.tostoreloc = tostoreloc;
		this.transdate = transdate;
		this.actualdate = actualdate;
		this.quantity = quantity;
		this.receivedunit = receivedunit;
		this.issuetype = issuetype;
		this.unitcost = unitcost;
		this.actualcost = actualcost;
		this.ponum = ponum;
		this.invoicenum = invoicenum;
		this.rejectcode = rejectcode;
		this.rejectqty = rejectqty;
		this.conversion = conversion;
		this.assetnum = assetnum;
		this.enterby = enterby;
		this.it1 = it1;
		this.it2 = it2;
		this.it3 = it3;
		this.it4 = it4;
		this.it5 = it5;
		this.outside = outside;
		this.issueto = issueto;
		this.packingslipnum = packingslipnum;
		this.polinenum = polinenum;
		this.issue = issue;
		this.requestedby = requestedby;
		this.totalcurbal = totalcurbal;
		this.oldavgcost = oldavgcost;
		this.itin1 = itin1;
		this.itin2 = itin2;
		this.itin3 = itin3;
		this.tobin = tobin;
		this.gldebitacct = gldebitacct;
		this.glcreditacct = glcreditacct;
		this.linecost = linecost;
		this.financialperiod = financialperiod;
		this.currencycode = currencycode;
		this.exchangerate = exchangerate;
		this.currencyunitcost = currencyunitcost;
		this.manufacturer = manufacturer;
		this.modelnum = modelnum;
		this.currencylinecost = currencylinecost;
		this.location = location;
		this.description = description;
		this.remark = remark;
		this.fromstoreloc = fromstoreloc;
		this.frombin = frombin;
		this.qtyheld = qtyheld;
		this.fromlot = fromlot;
		this.tolot = tolot;
		this.loadedcost = loadedcost;
		this.tax1code = tax1code;
		this.tax1 = tax1;
		this.tax2code = tax2code;
		this.tax2 = tax2;
		this.tax3code = tax3code;
		this.tax3 = tax3;
		this.tax4code = tax4code;
		this.tax4 = tax4;
		this.tax5code = tax5code;
		this.tax5 = tax5;
		this.prorated = prorated;
		this.proratecost = proratecost;
		this.status = status;
		this.statusdate = statusdate;
		this.statuschangeby = statuschangeby;
		this.sourcesysid = sourcesysid;
		this.qtyrequested = qtyrequested;
		this.curbal = curbal;
		this.exchangerate2 = exchangerate2;
		this.linecost2 = linecost2;
		this.mrnum = mrnum;
		this.mrlinenum = mrlinenum;
		this.ownersysid = ownersysid;
		this.externalrefid = externalrefid;
		this.it6 = it6;
		this.it7 = it7;
		this.it8 = it8;
		this.it9 = it9;
		this.it10 = it10;
		this.itin4 = itin4;
		this.itin5 = itin5;
		this.itin6 = itin6;
		this.itin7 = itin7;
		this.sendersysid = sendersysid;
		this.fincntrlid = fincntrlid;
		this.orgid = orgid;
		this.siteid = siteid;
		this.costinfo = costinfo;
		this.belongsto = belongsto;
		this.refwo = refwo;
		this.enteredastask = enteredastask;
		this.fromsiteid = fromsiteid;
		this.receiptref = receiptref;
		this.linetype = linetype;
		this.itemsetid = itemsetid;
		this.conditioncode = conditioncode;
		this.fromconditioncode = fromconditioncode;
		this.condrate = condrate;
		this.commoditygroup = commoditygroup;
		this.commodity = commodity;
		this.matusetransid = matusetransid;
		this.courier = courier;
		this.langcode = langcode;
		this.inspectedqty = inspectedqty;
		this.positeid = positeid;
		this.hasld = hasld;
		this.rotassetnum = rotassetnum;
		this.rowstamp = rowstamp;
		this.transType = transType;
		this.binnum = binnum;
	}

	@Id
	@Column(name = "MATRECTRANSID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMatrectransid() {
		return this.matrectransid;
	}

	public void setMatrectransid(BigDecimal matrectransid) {
		this.matrectransid = matrectransid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "TOSTORELOC", length = 16)
	public String getTostoreloc() {
		return this.tostoreloc;
	}

	public void setTostoreloc(String tostoreloc) {
		this.tostoreloc = tostoreloc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSDATE", nullable = false, length = 7)
	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTUALDATE", nullable = false, length = 7)
	public Date getActualdate() {
		return this.actualdate;
	}

	public void setActualdate(Date actualdate) {
		this.actualdate = actualdate;
	}

	@Column(name = "QUANTITY", precision = 15)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "RECEIVEDUNIT", length = 50)
	public String getReceivedunit() {
		return this.receivedunit;
	}

	public void setReceivedunit(String receivedunit) {
		this.receivedunit = receivedunit;
	}

	@Column(name = "ISSUETYPE", length = 25)
	public String getIssuetype() {
		return this.issuetype;
	}

	public void setIssuetype(String issuetype) {
		this.issuetype = issuetype;
	}

	@Column(name = "UNITCOST", nullable = false, precision = 10)
	public BigDecimal getUnitcost() {
		return this.unitcost;
	}

	public void setUnitcost(BigDecimal unitcost) {
		this.unitcost = unitcost;
	}

	@Column(name = "ACTUALCOST", nullable = false, precision = 10)
	public BigDecimal getActualcost() {
		return this.actualcost;
	}

	public void setActualcost(BigDecimal actualcost) {
		this.actualcost = actualcost;
	}

	@Column(name = "PONUM", length = 80)
	public String getPonum() {
		return this.ponum;
	}

	public void setPonum(String ponum) {
		this.ponum = ponum;
	}

	@Column(name = "INVOICENUM", length = 8)
	public String getInvoicenum() {
		return this.invoicenum;
	}

	public void setInvoicenum(String invoicenum) {
		this.invoicenum = invoicenum;
	}

	@Column(name = "REJECTCODE", length = 6)
	public String getRejectcode() {
		return this.rejectcode;
	}

	public void setRejectcode(String rejectcode) {
		this.rejectcode = rejectcode;
	}

	@Column(name = "REJECTQTY", nullable = false, precision = 15)
	public BigDecimal getRejectqty() {
		return this.rejectqty;
	}

	public void setRejectqty(BigDecimal rejectqty) {
		this.rejectqty = rejectqty;
	}

	@Column(name = "CONVERSION", precision = 15)
	public BigDecimal getConversion() {
		return this.conversion;
	}

	public void setConversion(BigDecimal conversion) {
		this.conversion = conversion;
	}

	@Column(name = "ASSETNUM", length = 20)
	public String getAssetnum() {
		return this.assetnum;
	}

	public void setAssetnum(String assetnum) {
		this.assetnum = assetnum;
	}

	@Column(name = "ENTERBY", nullable = false, length = 30)
	public String getEnterby() {
		return this.enterby;
	}

	public void setEnterby(String enterby) {
		this.enterby = enterby;
	}

	@Column(name = "IT1", length = 10)
	public String getIt1() {
		return this.it1;
	}

	public void setIt1(String it1) {
		this.it1 = it1;
	}

	@Column(name = "IT2", length = 10)
	public String getIt2() {
		return this.it2;
	}

	public void setIt2(String it2) {
		this.it2 = it2;
	}

	@Column(name = "IT3", length = 10)
	public String getIt3() {
		return this.it3;
	}

	public void setIt3(String it3) {
		this.it3 = it3;
	}

	@Column(name = "IT4", precision = 15)
	public BigDecimal getIt4() {
		return this.it4;
	}

	public void setIt4(BigDecimal it4) {
		this.it4 = it4;
	}

	@Column(name = "IT5", length = 10)
	public String getIt5() {
		return this.it5;
	}

	public void setIt5(String it5) {
		this.it5 = it5;
	}

	@Column(name = "OUTSIDE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOutside() {
		return this.outside;
	}

	public void setOutside(BigDecimal outside) {
		this.outside = outside;
	}

	@Column(name = "ISSUETO", length = 30)
	public String getIssueto() {
		return this.issueto;
	}

	public void setIssueto(String issueto) {
		this.issueto = issueto;
	}

	@Column(name = "PACKINGSLIPNUM", length = 20)
	public String getPackingslipnum() {
		return this.packingslipnum;
	}

	public void setPackingslipnum(String packingslipnum) {
		this.packingslipnum = packingslipnum;
	}

	@Column(name = "POLINENUM", precision = 22, scale = 0)
	public BigDecimal getPolinenum() {
		return this.polinenum;
	}

	public void setPolinenum(BigDecimal polinenum) {
		this.polinenum = polinenum;
	}

	@Column(name = "ISSUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIssue() {
		return this.issue;
	}

	public void setIssue(BigDecimal issue) {
		this.issue = issue;
	}

	@Column(name = "REQUESTEDBY", length = 20)
	public String getRequestedby() {
		return this.requestedby;
	}

	public void setRequestedby(String requestedby) {
		this.requestedby = requestedby;
	}

	@Column(name = "TOTALCURBAL", precision = 15)
	public BigDecimal getTotalcurbal() {
		return this.totalcurbal;
	}

	public void setTotalcurbal(BigDecimal totalcurbal) {
		this.totalcurbal = totalcurbal;
	}

	@Column(name = "OLDAVGCOST", precision = 10)
	public BigDecimal getOldavgcost() {
		return this.oldavgcost;
	}

	public void setOldavgcost(BigDecimal oldavgcost) {
		this.oldavgcost = oldavgcost;
	}

	@Column(name = "ITIN1", length = 10)
	public String getItin1() {
		return this.itin1;
	}

	public void setItin1(String itin1) {
		this.itin1 = itin1;
	}

	@Column(name = "ITIN2", length = 10)
	public String getItin2() {
		return this.itin2;
	}

	public void setItin2(String itin2) {
		this.itin2 = itin2;
	}

	@Column(name = "ITIN3", length = 10)
	public String getItin3() {
		return this.itin3;
	}

	public void setItin3(String itin3) {
		this.itin3 = itin3;
	}

	@Column(name = "TOBIN", length = 30)
	public String getTobin() {
		return this.tobin;
	}

	public void setTobin(String tobin) {
		this.tobin = tobin;
	}

	@Column(name = "GLDEBITACCT", length = 10)
	public String getGldebitacct() {
		return this.gldebitacct;
	}

	public void setGldebitacct(String gldebitacct) {
		this.gldebitacct = gldebitacct;
	}

	@Column(name = "GLCREDITACCT", length = 10)
	public String getGlcreditacct() {
		return this.glcreditacct;
	}

	public void setGlcreditacct(String glcreditacct) {
		this.glcreditacct = glcreditacct;
	}

	@Column(name = "LINECOST", nullable = false)
	public BigDecimal getLinecost() {
		return this.linecost;
	}

	public void setLinecost(BigDecimal linecost) {
		this.linecost = linecost;
	}

	@Column(name = "FINANCIALPERIOD", length = 6)
	public String getFinancialperiod() {
		return this.financialperiod;
	}

	public void setFinancialperiod(String financialperiod) {
		this.financialperiod = financialperiod;
	}

	@Column(name = "CURRENCYCODE", nullable = false, length = 8)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "EXCHANGERATE", precision = 14, scale = 7)
	public BigDecimal getExchangerate() {
		return this.exchangerate;
	}

	public void setExchangerate(BigDecimal exchangerate) {
		this.exchangerate = exchangerate;
	}

	@Column(name = "CURRENCYUNITCOST", precision = 10)
	public BigDecimal getCurrencyunitcost() {
		return this.currencyunitcost;
	}

	public void setCurrencyunitcost(BigDecimal currencyunitcost) {
		this.currencyunitcost = currencyunitcost;
	}

	@Column(name = "MANUFACTURER", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "MODELNUM", length = 50)
	public String getModelnum() {
		return this.modelnum;
	}

	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "CURRENCYLINECOST", precision = 10)
	public BigDecimal getCurrencylinecost() {
		return this.currencylinecost;
	}

	public void setCurrencylinecost(BigDecimal currencylinecost) {
		this.currencylinecost = currencylinecost;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FROMSTORELOC", length = 16)
	public String getFromstoreloc() {
		return this.fromstoreloc;
	}

	public void setFromstoreloc(String fromstoreloc) {
		this.fromstoreloc = fromstoreloc;
	}

	@Column(name = "FROMBIN", length = 30)
	public String getFrombin() {
		return this.frombin;
	}

	public void setFrombin(String frombin) {
		this.frombin = frombin;
	}

	@Column(name = "QTYHELD", precision = 15)
	public BigDecimal getQtyheld() {
		return this.qtyheld;
	}

	public void setQtyheld(BigDecimal qtyheld) {
		this.qtyheld = qtyheld;
	}

	@Column(name = "FROMLOT", length = 8)
	public String getFromlot() {
		return this.fromlot;
	}

	public void setFromlot(String fromlot) {
		this.fromlot = fromlot;
	}

	@Column(name = "TOLOT", length = 8)
	public String getTolot() {
		return this.tolot;
	}

	public void setTolot(String tolot) {
		this.tolot = tolot;
	}

	@Column(name = "LOADEDCOST", nullable = false)
	public BigDecimal getLoadedcost() {
		return this.loadedcost;
	}

	public void setLoadedcost(BigDecimal loadedcost) {
		this.loadedcost = loadedcost;
	}

	@Column(name = "TAX1CODE", length = 8)
	public String getTax1code() {
		return this.tax1code;
	}

	public void setTax1code(String tax1code) {
		this.tax1code = tax1code;
	}

	@Column(name = "TAX1", precision = 10)
	public BigDecimal getTax1() {
		return this.tax1;
	}

	public void setTax1(BigDecimal tax1) {
		this.tax1 = tax1;
	}

	@Column(name = "TAX2CODE", length = 8)
	public String getTax2code() {
		return this.tax2code;
	}

	public void setTax2code(String tax2code) {
		this.tax2code = tax2code;
	}

	@Column(name = "TAX2", precision = 10)
	public BigDecimal getTax2() {
		return this.tax2;
	}

	public void setTax2(BigDecimal tax2) {
		this.tax2 = tax2;
	}

	@Column(name = "TAX3CODE", length = 8)
	public String getTax3code() {
		return this.tax3code;
	}

	public void setTax3code(String tax3code) {
		this.tax3code = tax3code;
	}

	@Column(name = "TAX3", precision = 10)
	public BigDecimal getTax3() {
		return this.tax3;
	}

	public void setTax3(BigDecimal tax3) {
		this.tax3 = tax3;
	}

	@Column(name = "TAX4CODE", length = 8)
	public String getTax4code() {
		return this.tax4code;
	}

	public void setTax4code(String tax4code) {
		this.tax4code = tax4code;
	}

	@Column(name = "TAX4", precision = 10)
	public BigDecimal getTax4() {
		return this.tax4;
	}

	public void setTax4(BigDecimal tax4) {
		this.tax4 = tax4;
	}

	@Column(name = "TAX5CODE", length = 8)
	public String getTax5code() {
		return this.tax5code;
	}

	public void setTax5code(String tax5code) {
		this.tax5code = tax5code;
	}

	@Column(name = "TAX5", precision = 10)
	public BigDecimal getTax5() {
		return this.tax5;
	}

	public void setTax5(BigDecimal tax5) {
		this.tax5 = tax5;
	}

	@Column(name = "PRORATED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProrated() {
		return this.prorated;
	}

	public void setProrated(BigDecimal prorated) {
		this.prorated = prorated;
	}

	@Column(name = "PRORATECOST", precision = 10)
	public BigDecimal getProratecost() {
		return this.proratecost;
	}

	public void setProratecost(BigDecimal proratecost) {
		this.proratecost = proratecost;
	}

	@Column(name = "STATUS", length = 12)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STATUSDATE", length = 7)
	public Date getStatusdate() {
		return this.statusdate;
	}

	public void setStatusdate(Date statusdate) {
		this.statusdate = statusdate;
	}

	@Column(name = "STATUSCHANGEBY", length = 30)
	public String getStatuschangeby() {
		return this.statuschangeby;
	}

	public void setStatuschangeby(String statuschangeby) {
		this.statuschangeby = statuschangeby;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "QTYREQUESTED", precision = 15)
	public BigDecimal getQtyrequested() {
		return this.qtyrequested;
	}

	public void setQtyrequested(BigDecimal qtyrequested) {
		this.qtyrequested = qtyrequested;
	}

	@Column(name = "CURBAL", nullable = false, precision = 15)
	public BigDecimal getCurbal() {
		return this.curbal;
	}

	public void setCurbal(BigDecimal curbal) {
		this.curbal = curbal;
	}

	@Column(name = "EXCHANGERATE2", precision = 14, scale = 7)
	public BigDecimal getExchangerate2() {
		return this.exchangerate2;
	}

	public void setExchangerate2(BigDecimal exchangerate2) {
		this.exchangerate2 = exchangerate2;
	}

	@Column(name = "LINECOST2", precision = 10)
	public BigDecimal getLinecost2() {
		return this.linecost2;
	}

	public void setLinecost2(BigDecimal linecost2) {
		this.linecost2 = linecost2;
	}

	@Column(name = "MRNUM", length = 8)
	public String getMrnum() {
		return this.mrnum;
	}

	public void setMrnum(String mrnum) {
		this.mrnum = mrnum;
	}

	@Column(name = "MRLINENUM", precision = 22, scale = 0)
	public BigDecimal getMrlinenum() {
		return this.mrlinenum;
	}

	public void setMrlinenum(BigDecimal mrlinenum) {
		this.mrlinenum = mrlinenum;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "IT6", length = 10)
	public String getIt6() {
		return this.it6;
	}

	public void setIt6(String it6) {
		this.it6 = it6;
	}

	@Column(name = "IT7", length = 10)
	public String getIt7() {
		return this.it7;
	}

	public void setIt7(String it7) {
		this.it7 = it7;
	}

	@Column(name = "IT8", length = 10)
	public String getIt8() {
		return this.it8;
	}

	public void setIt8(String it8) {
		this.it8 = it8;
	}

	@Column(name = "IT9", length = 10)
	public String getIt9() {
		return this.it9;
	}

	public void setIt9(String it9) {
		this.it9 = it9;
	}

	@Column(name = "IT10", length = 10)
	public String getIt10() {
		return this.it10;
	}

	public void setIt10(String it10) {
		this.it10 = it10;
	}

	@Column(name = "ITIN4", length = 10)
	public String getItin4() {
		return this.itin4;
	}

	public void setItin4(String itin4) {
		this.itin4 = itin4;
	}

	@Column(name = "ITIN5", length = 10)
	public String getItin5() {
		return this.itin5;
	}

	public void setItin5(String itin5) {
		this.itin5 = itin5;
	}

	@Column(name = "ITIN6", length = 10)
	public String getItin6() {
		return this.itin6;
	}

	public void setItin6(String itin6) {
		this.itin6 = itin6;
	}

	@Column(name = "ITIN7", length = 10)
	public String getItin7() {
		return this.itin7;
	}

	public void setItin7(String itin7) {
		this.itin7 = itin7;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "FINCNTRLID", length = 8)
	public String getFincntrlid() {
		return this.fincntrlid;
	}

	public void setFincntrlid(String fincntrlid) {
		this.fincntrlid = fincntrlid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "COSTINFO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCostinfo() {
		return this.costinfo;
	}

	public void setCostinfo(BigDecimal costinfo) {
		this.costinfo = costinfo;
	}

	@Column(name = "BELONGSTO", precision = 22, scale = 0)
	public BigDecimal getBelongsto() {
		return this.belongsto;
	}

	public void setBelongsto(BigDecimal belongsto) {
		this.belongsto = belongsto;
	}

	@Column(name = "REFWO", length = 10)
	public String getRefwo() {
		return this.refwo;
	}

	public void setRefwo(String refwo) {
		this.refwo = refwo;
	}

	@Column(name = "ENTEREDASTASK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEnteredastask() {
		return this.enteredastask;
	}

	public void setEnteredastask(BigDecimal enteredastask) {
		this.enteredastask = enteredastask;
	}

	@Column(name = "FROMSITEID", nullable = false, length = 8)
	public String getFromsiteid() {
		return this.fromsiteid;
	}

	public void setFromsiteid(String fromsiteid) {
		this.fromsiteid = fromsiteid;
	}

	@Column(name = "RECEIPTREF", precision = 22, scale = 0)
	public BigDecimal getReceiptref() {
		return this.receiptref;
	}

	public void setReceiptref(BigDecimal receiptref) {
		this.receiptref = receiptref;
	}

	@Column(name = "LINETYPE", nullable = false, length = 15)
	public String getLinetype() {
		return this.linetype;
	}

	public void setLinetype(String linetype) {
		this.linetype = linetype;
	}

	@Column(name = "ITEMSETID", length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "FROMCONDITIONCODE", length = 30)
	public String getFromconditioncode() {
		return this.fromconditioncode;
	}

	public void setFromconditioncode(String fromconditioncode) {
		this.fromconditioncode = fromconditioncode;
	}

	@Column(name = "CONDRATE", precision = 22, scale = 0)
	public BigDecimal getCondrate() {
		return this.condrate;
	}

	public void setCondrate(BigDecimal condrate) {
		this.condrate = condrate;
	}

	@Column(name = "COMMODITYGROUP", length = 8)
	public String getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "COMMODITY", length = 8)
	public String getCommodity() {
		return this.commodity;
	}

	public void setCommodity(String commodity) {
		this.commodity = commodity;
	}

	@Column(name = "MATUSETRANSID", precision = 22, scale = 0)
	public BigDecimal getMatusetransid() {
		return this.matusetransid;
	}

	public void setMatusetransid(BigDecimal matusetransid) {
		this.matusetransid = matusetransid;
	}

	@Column(name = "COURIER", length = 30)
	public String getCourier() {
		return this.courier;
	}

	public void setCourier(String courier) {
		this.courier = courier;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "INSPECTEDQTY", precision = 15)
	public BigDecimal getInspectedqty() {
		return this.inspectedqty;
	}

	public void setInspectedqty(BigDecimal inspectedqty) {
		this.inspectedqty = inspectedqty;
	}

	@Column(name = "POSITEID", length = 8)
	public String getPositeid() {
		return this.positeid;
	}

	public void setPositeid(String positeid) {
		this.positeid = positeid;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHasld() {
		return this.hasld;
	}

	public void setHasld(BigDecimal hasld) {
		this.hasld = hasld;
	}

	@Column(name = "ROTASSETNUM", length = 20)
	public String getRotassetnum() {
		return this.rotassetnum;
	}

	public void setRotassetnum(String rotassetnum) {
		this.rotassetnum = rotassetnum;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Column(name = "TRANS_TYPE")
	public String getTransType() {
		return transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}
	@Column(name = "BINNUM")
	public String getBinnum() {
		return binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}
	
}
