package mro.base.entity;

// Generated 2012/12/18 �U�� 05:05:28 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Measureunit generated by hbm2java
 */
@Entity
@Table(name = "MEASUREUNIT", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MEASUREUNITID", "SITEID", "ORGID" }))
public class Measureunit implements java.io.Serializable {

	private BigDecimal measureunituid;
	private String measureunitid;
	private String abbreviation;
	private String description;
	private String orgid;
	private String siteid;
	private String module;

	public Measureunit() {
	}

	public Measureunit(BigDecimal measureunituid, String measureunitid) {
		this.measureunituid = measureunituid;
		this.measureunitid = measureunitid;
	}

	public Measureunit(BigDecimal measureunituid, String measureunitid,
			String abbreviation, String description, String orgid,
			String siteid, String module) {
		this.measureunituid = measureunituid;
		this.measureunitid = measureunitid;
		this.abbreviation = abbreviation;
		this.description = description;
		this.orgid = orgid;
		this.siteid = siteid;
		this.module = module;
	}

	@Id
	@SequenceGenerator(name="MEASUREUNIT_MEASUREUNITID_GENERATOR", sequenceName="MEASUREUNITSEQ" , allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MEASUREUNIT_MEASUREUNITID_GENERATOR")
	@Column(name = "MEASUREUNITUID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMeasureunituid() {
		return this.measureunituid;
	}

	public void setMeasureunituid(BigDecimal measureunituid) {
		this.measureunituid = measureunituid;
	}

	@Column(name = "MEASUREUNITID", nullable = false, length = 50)
	public String getMeasureunitid() {
		return this.measureunitid;
	}

	public void setMeasureunitid(String measureunitid) {
		this.measureunitid = measureunitid;
	}

	@Column(name = "ABBREVIATION", length = 50)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "MODULE", length = 15)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

}
