package mro.base.entity;

// Generated 2013/10/21 �W�� 09:56:54 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeasureunitDomain generated by hbm2java
 */
@Entity
@Table(name = "MEASUREUNIT_DOMAIN")
public class MeasureunitDomain implements java.io.Serializable {

	private BigDecimal measureunitDomainId;
	private String domainid;
	private String value;
	private String description;
	private String siteid;
	private String orgid;
	private Date inactiveDate;

	public MeasureunitDomain() {
	}

	public MeasureunitDomain(BigDecimal measureunitDomainId, String domainid) {
		this.measureunitDomainId = measureunitDomainId;
		this.domainid = domainid;
	}

	public MeasureunitDomain(BigDecimal measureunitDomainId, String domainid,
			String value, String description, String siteid, String orgid,Date inactiveDate) {
		this.measureunitDomainId = measureunitDomainId;
		this.domainid = domainid;
		this.value = value;
		this.description = description;
		this.siteid = siteid;
		this.orgid = orgid;
		this.inactiveDate=inactiveDate;
	}

	@Id
	@SequenceGenerator(name="MEASUREUNIT_DOMAIN_ID_GENERATOR", sequenceName="MEASUREUNIT_DOMAIN_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MEASUREUNIT_DOMAIN_ID_GENERATOR")
	@Column(name = "MEASUREUNIT_DOMAIN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMeasureunitDomainId() {
		return this.measureunitDomainId;
	}

	public void setMeasureunitDomainId(BigDecimal measureunitDomainId) {
		this.measureunitDomainId = measureunitDomainId;
	}

	@Column(name = "DOMAINID", nullable = false, length = 18)
	public String getDomainid() {
		return this.domainid;
	}

	public void setDomainid(String domainid) {
		this.domainid = domainid;
	}

	@Column(name = "VALUE", length = 25)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE")
	public Date getInactiveDate() {
		return inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}
}
