package mro.base.entity;

// Generated 2015/10/7 �W�� 10:17:55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * MroExclusiveReturn generated by hbm2java
 */
@Entity
@Table(name = "MRO_EXCLUSIVE_RETURN", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ORGANIZATION_CODE", "DEPT_NO", "ITEMNUM", "CLASSSTRUCTUREID" }))
public class MroExclusiveReturn implements java.io.Serializable {

	private String uuid;
	private String organizationCode;
	private String deptNo;
	private String itemnum;
	private String createBy;
	private Date createDate;
	private String remark;
	private String classstructureid;
	private LocationSiteMap locationSiteMap;

	public MroExclusiveReturn() {
	}

	public MroExclusiveReturn(String uuid) {
		this.uuid = uuid;
	}

	public MroExclusiveReturn(String uuid, String organizationCode,
			String deptNo, String itemnum, String createBy, Date createDate,
			String remark, String classstructureid,LocationSiteMap locationSiteMap) {
		this.uuid = uuid;
		this.organizationCode = organizationCode;
		this.deptNo = deptNo;
		this.itemnum = itemnum;
		this.createBy = createBy;
		this.createDate = createDate;
		this.remark = remark;
		this.classstructureid = classstructureid;
		this.locationSiteMap = locationSiteMap;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "UUID", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "ORGANIZATION_CODE", length = 10)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "DEPT_NO", length = 30)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 1)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}

}
