package mro.base.entity;

// Generated 2016/1/20 �W�� 09:58:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MroInvbalancesHighlightVId generated by hbm2java
 */
@Entity
@Table(name = "MRO_INVBALANCES_HIGHLIGHT_V")
public class MroInvbalancesHighlightV implements java.io.Serializable {

	private BigDecimal invbalancesid;
	private String fab;
	private String siteid;
	private String shop;
	private String binnum;
	private String itemnum;
	private String commoditygroup;
	private String description;
	private String lastrequestedby2;
	private Date lastHighlightResponseDate;
	private Date highlightInitialDate;
	private String location;
	private String displayName;
	private String reasonType;
	private Date createDate;
	private BigDecimal stock;
	private BigDecimal idledays;
	private BigDecimal sumofconter;
	private BigDecimal oriavguseqty;
	private BigDecimal sstock;
	private BigDecimal minlevel;
	private BigDecimal mcMinPackageQuantity;
	private BigDecimal avghdqtyThree;
	private BigDecimal avghdqtyThreeLimit;
	private BigDecimal threeMonthAvgRecommand;
	private Character sumofconterFlag;
	private Character threeMonthAvgFlag;
	private Character highlightFlag;

	public MroInvbalancesHighlightV() {
	}

	public MroInvbalancesHighlightV(BigDecimal invbalancesid, String fab,
			String siteid, String shop, String binnum, String itemnum,
			String commoditygroup,String description, String lastrequestedby2,
			Date highlightInitialDate, String location, String displayName,
			String reasonType, Date createDate, BigDecimal stock,
			BigDecimal idledays, BigDecimal sumofconter,
			BigDecimal oriavguseqty, BigDecimal sstock, BigDecimal minlevel,
			BigDecimal mcMinPackageQuantity, BigDecimal avghdqtyThree,
			BigDecimal avghdqtyThreeLimit, BigDecimal threeMonthAvgRecommand,
			Character sumofconterFlag, Character threeMonthAvgFlag,
			Character highlightFlag,Date lastHighlightResponseDate) {
		this.invbalancesid = invbalancesid;
		this.fab = fab;
		this.siteid = siteid;
		this.shop = shop;
		this.binnum = binnum;
		this.itemnum = itemnum;
		this.commoditygroup = commoditygroup;
		this.description = description;
		this.lastrequestedby2 = lastrequestedby2;
		this.highlightInitialDate = highlightInitialDate;
		this.location = location;
		this.displayName = displayName;
		this.reasonType = reasonType;
		this.createDate = createDate;
		this.stock = stock;
		this.idledays = idledays;
		this.sumofconter = sumofconter;
		this.oriavguseqty = oriavguseqty;
		this.sstock = sstock;
		this.minlevel = minlevel;
		this.mcMinPackageQuantity = mcMinPackageQuantity;
		this.avghdqtyThree = avghdqtyThree;
		this.avghdqtyThreeLimit = avghdqtyThreeLimit;
		this.threeMonthAvgRecommand = threeMonthAvgRecommand;
		this.sumofconterFlag = sumofconterFlag;
		this.threeMonthAvgFlag = threeMonthAvgFlag;
		this.highlightFlag = highlightFlag;
		this.lastHighlightResponseDate = lastHighlightResponseDate;
	}
	@Id
	@Column(name = "INVBALANCESID", precision = 22, scale = 0)
	public BigDecimal getInvbalancesid() {
		return this.invbalancesid;
	}

	public void setInvbalancesid(BigDecimal invbalancesid) {
		this.invbalancesid = invbalancesid;
	}

	@Column(name = "FAB", length = 20)
	public String getFab() {
		return this.fab;
	}

	public void setFab(String fab) {
		this.fab = fab;
	}

	@Column(name = "SITEID", length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "SHOP", length = 30)
	public String getShop() {
		return this.shop;
	}

	public void setShop(String shop) {
		this.shop = shop;
	}

	@Column(name = "BINNUM", length = 30)
	public String getBinnum() {
		return this.binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}
	
	@Column(name = "COMMODITYGROUP", length = 8)
	public String getCommoditygroup() {
		return commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LASTREQUESTEDBY2", length = 30)
	public String getLastrequestedby2() {
		return this.lastrequestedby2;
	}

	public void setLastrequestedby2(String lastrequestedby2) {
		this.lastrequestedby2 = lastrequestedby2;
	}

	@Column(name = "LAST_HIGHLIGHT_REPONSE_DATE", length = 7)
	public Date getLastHighlightResponseDate() {
		return lastHighlightResponseDate;
	}

	public void setLastHighlightResponseDate(Date lastHighlightResponseDate) {
		this.lastHighlightResponseDate = lastHighlightResponseDate;
	}

	@Column(name = "HIGHLIGHT_INITIAL_DATE", length = 7)
	public Date getHighlightInitialDate() {
		return this.highlightInitialDate;
	}

	public void setHighlightInitialDate(Date highlightInitialDate) {
		this.highlightInitialDate = highlightInitialDate;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "DISPLAY_NAME", length = 60)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "REASON_TYPE", length = 30)
	public String getReasonType() {
		return this.reasonType;
	}

	public void setReasonType(String reasonType) {
		this.reasonType = reasonType;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "STOCK", precision = 15)
	public BigDecimal getStock() {
		return this.stock;
	}

	public void setStock(BigDecimal stock) {
		this.stock = stock;
	}

	@Column(name = "IDLEDAYS", precision = 16)
	public BigDecimal getIdledays() {
		return this.idledays;
	}

	public void setIdledays(BigDecimal idledays) {
		this.idledays = idledays;
	}

	@Column(name = "SUMOFCONTER", precision = 22, scale = 0)
	public BigDecimal getSumofconter() {
		return this.sumofconter;
	}

	public void setSumofconter(BigDecimal sumofconter) {
		this.sumofconter = sumofconter;
	}

	@Column(name = "ORIAVGUSEQTY", precision = 15)
	public BigDecimal getOriavguseqty() {
		return this.oriavguseqty;
	}

	public void setOriavguseqty(BigDecimal oriavguseqty) {
		this.oriavguseqty = oriavguseqty;
	}

	@Column(name = "SSTOCK", precision = 15)
	public BigDecimal getSstock() {
		return this.sstock;
	}

	public void setSstock(BigDecimal sstock) {
		this.sstock = sstock;
	}

	@Column(name = "MINLEVEL", precision = 15)
	public BigDecimal getMinlevel() {
		return this.minlevel;
	}

	public void setMinlevel(BigDecimal minlevel) {
		this.minlevel = minlevel;
	}

	@Column(name = "MC_MIN_PACKAGE_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getMcMinPackageQuantity() {
		return this.mcMinPackageQuantity;
	}

	public void setMcMinPackageQuantity(BigDecimal mcMinPackageQuantity) {
		this.mcMinPackageQuantity = mcMinPackageQuantity;
	}

	@Column(name = "AVGHDQTY_THREE", precision = 22, scale = 0)
	public BigDecimal getAvghdqtyThree() {
		return this.avghdqtyThree;
	}

	public void setAvghdqtyThree(BigDecimal avghdqtyThree) {
		this.avghdqtyThree = avghdqtyThree;
	}

	@Column(name = "AVGHDQTY_THREE_LIMIT", precision = 22, scale = 0)
	public BigDecimal getAvghdqtyThreeLimit() {
		return this.avghdqtyThreeLimit;
	}

	public void setAvghdqtyThreeLimit(BigDecimal avghdqtyThreeLimit) {
		this.avghdqtyThreeLimit = avghdqtyThreeLimit;
	}

	@Column(name = "THREE_MONTH_AVG_RECOMMAND", precision = 22, scale = 0)
	public BigDecimal getThreeMonthAvgRecommand() {
		return this.threeMonthAvgRecommand;
	}

	public void setThreeMonthAvgRecommand(BigDecimal threeMonthAvgRecommand) {
		this.threeMonthAvgRecommand = threeMonthAvgRecommand;
	}

	@Column(name = "SUMOFCONTER_FLAG", length = 1)
	public Character getSumofconterFlag() {
		return this.sumofconterFlag;
	}

	public void setSumofconterFlag(Character sumofconterFlag) {
		this.sumofconterFlag = sumofconterFlag;
	}

	@Column(name = "THREE_MONTH_AVG_FLAG", length = 1)
	public Character getThreeMonthAvgFlag() {
		return this.threeMonthAvgFlag;
	}

	public void setThreeMonthAvgFlag(Character threeMonthAvgFlag) {
		this.threeMonthAvgFlag = threeMonthAvgFlag;
	}

	@Column(name = "HIGHLIGHT_FLAG", length = 1)
	public Character getHighlightFlag() {
		return this.highlightFlag;
	}

	public void setHighlightFlag(Character highlightFlag) {
		this.highlightFlag = highlightFlag;
	}
}
