package mro.base.entity;

// Generated 2016/11/30 �W�� 09:55:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * MroInventoryIdleList generated by hbm2java
 */
@Entity
@Table(name = "MRO_INVENTORY_IDLE_LIST", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ITEMNUM", "ORGANIZATION_CODE", "LOCATION", "LOCATION_SITE" }))
public class MroInventoryIdleList implements java.io.Serializable {

	private String uuid;
	private String itemnum;
	private String organizationCode;
	private String location;
	private String createBy;
	private Date createDate;
	private String remark;
	private LocationSiteMap locationSiteMap;

	public MroInventoryIdleList() {
	}

	public MroInventoryIdleList(String uuid) {
		this.uuid = uuid;
	}

	public MroInventoryIdleList(String uuid, String itemnum,
			String organizationCode, String location, String createBy,
			Date createDate, String remark, LocationSiteMap locationSiteMap) {
		this.uuid = uuid;
		this.itemnum = itemnum;
		this.organizationCode = organizationCode;
		this.location = location;
		this.createBy = createBy;
		this.createDate = createDate;
		this.remark = remark;
		this.locationSiteMap = locationSiteMap;
	}


	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "UUID", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "ORGANIZATION_CODE", length = 8)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}
}
