package mro.base.entity;

// Generated 2014/6/17 �U�� 03:07:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MroOrgFacilityEq generated by hbm2java
 */
@Entity
@Table(name = "MRO_ORG_FACILITY_EQ")
public class MroOrgFacilityEq implements java.io.Serializable {

	private BigDecimal mroOrgFacilityEqId;
	private String reasoncode;
	private String fab;
	private String processType;
	private String eqType;
	private String eqId;
	private String remark;
	private String createBy;
	private Date createDate;
	private LocationSiteMap locationSiteMap;

	public MroOrgFacilityEq() {
	}

	public MroOrgFacilityEq(BigDecimal mroOrgFacilityEqId) {
		this.mroOrgFacilityEqId = mroOrgFacilityEqId;
	}

	public MroOrgFacilityEq(BigDecimal mroOrgFacilityEqId, String reasoncode,
			String fab, String processType, String eqType, String eqId,
			String remark, String createBy, Date createDate,LocationSiteMap locationSiteMap) {
		this.mroOrgFacilityEqId = mroOrgFacilityEqId;
		this.reasoncode = reasoncode;
		this.fab = fab;
		this.processType = processType;
		this.eqType = eqType;
		this.eqId = eqId;
		this.remark = remark;
		this.createBy = createBy;
		this.createDate = createDate;
		this.locationSiteMap = locationSiteMap;
	}

	@Id
	@SequenceGenerator(name="MRO_ORG_FACILITY_EQ_ID_GENERATOR", sequenceName="MRO_ORG_FACILITY_EQ_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MRO_ORG_FACILITY_EQ_ID_GENERATOR")
	@Column(name = "MRO_ORG_FACILITY_EQ_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMroOrgFacilityEqId() {
		return this.mroOrgFacilityEqId;
	}

	public void setMroOrgFacilityEqId(BigDecimal mroOrgFacilityEqId) {
		this.mroOrgFacilityEqId = mroOrgFacilityEqId;
	}

	@Column(name = "REASONCODE", length = 30)
	public String getReasoncode() {
		return this.reasoncode;
	}

	public void setReasoncode(String reasoncode) {
		this.reasoncode = reasoncode;
	}

	@Column(name = "FAB", length = 30)
	public String getFab() {
		return this.fab;
	}

	public void setFab(String fab) {
		this.fab = fab;
	}

	@Column(name = "PROCESS_TYPE", length = 50)
	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	@Column(name = "EQ_TYPE", length = 50)
	public String getEqType() {
		return this.eqType;
	}

	public void setEqType(String eqType) {
		this.eqType = eqType;
	}

	@Column(name = "EQ_ID", length = 50)
	public String getEqId() {
		return this.eqId;
	}

	public void setEqId(String eqId) {
		this.eqId = eqId;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}
}
