package mro.base.entity;

// Generated 2014/6/17 �W�� 08:51:44 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MroOrgFacility generated by hbm2java
 */
@Entity
@Table(name = "MRO_ORG_FACILITY")
public class MroOrgFacility implements java.io.Serializable {

	private BigDecimal mroOrgFacilityId;
	private String deptNo;
	private String fab;
	private String organizationCode;
	private String remark;
	private String createBy;
	private Date createDate;
	private String shortName;
	private LocationSiteMap locationSiteMap;

	@Override
	public boolean equals(Object obj) {
	    if(obj instanceof MroOrgFacility && 
	    	((MroOrgFacility)obj).getDeptNo().equals(this.deptNo)&& 
	    	((MroOrgFacility)obj).getOrganizationCode().equals(this.organizationCode)) {
	        return true;
	    }else {
	        return false;
	    }
	}
	
	public MroOrgFacility() {
	}

	public MroOrgFacility(BigDecimal mroOrgFacilityId) {
		this.mroOrgFacilityId = mroOrgFacilityId;
	}
	public MroOrgFacility(String deptNo,String organizationCode) {
		this.deptNo = deptNo;
		this.organizationCode = organizationCode;
	}

	public MroOrgFacility(BigDecimal mroOrgFacilityId, String deptNo,
			String fab, String organizationCode, String remark,
			String createBy, Date createDate,String shortName,LocationSiteMap locationSiteMap) {
		this.mroOrgFacilityId = mroOrgFacilityId;
		this.deptNo = deptNo;
		this.fab = fab;
		this.organizationCode = organizationCode;
		this.remark = remark;
		this.createBy = createBy;
		this.createDate = createDate;
		this.shortName = shortName;
		this.locationSiteMap = locationSiteMap;
	}


	@Id
	@SequenceGenerator(name="MRO_ORG_FACILITY_ID_GENERATOR", sequenceName="MRO_ORG_FACILITY_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MRO_ORG_FACILITY_ID_GENERATOR")
	@Column(name = "MRO_ORG_FACILITY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getMroOrgFacilityId() {
		return mroOrgFacilityId;
	}

	public void setMroOrgFacilityId(BigDecimal mroOrgFacilityId) {
		this.mroOrgFacilityId = mroOrgFacilityId;
	}


	@Column(name = "DEPT_NO", length = 30)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "FAB", length = 30)
	public String getFab() {
		return this.fab;
	}

	public void setFab(String fab) {
		this.fab = fab;
	}

	@Column(name = "ORGANIZATION_CODE", length = 10)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(name = "SHORT_NAME")
	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}

}
