package mro.base.entity;

// Generated 2013/7/16 �U�� 06:06:42 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON")
public class Person implements java.io.Serializable {

	private String personId;
	private String status;
	private String displayName;
	private String emailAddress;
	private String phoneNum;
	private String department;
	private String title;
	private String supervisor;
	private String delegate;
	private Date statusDate;
	private String langCode;
	private String location;
	private String locationSite;
	private String fab;
	private String deptCode;
	private String siteId;
	private String locationId;
	private String notesId;
	private String supervisorName;
	private String organizationCode;
	private String MDeptCode;

	public Person() {
	}

	public Person(String personId, String status, Date statusDate,
			String langCode) {
		this.personId = personId;
		this.status = status;
		this.statusDate = statusDate;
		this.langCode = langCode;
	}

	public Person(String personId, String status, String displayName,
			String emailAddress, String phoneNum, String department,
			String title, String supervisor, String delegate, Date statusDate,
			String langCode, String location, String locationSite, String fab,
			String deptCode, String siteId, String locationId,
			String notesId,String supervisorName,String organizationCode,
			String MDeptCode) {
		this.personId = personId;
		this.status = status;
		this.displayName = displayName;
		this.emailAddress = emailAddress;
		this.phoneNum = phoneNum;
		this.department = department;
		this.title = title;
		this.supervisor = supervisor;
		this.delegate = delegate;
		this.statusDate = statusDate;
		this.langCode = langCode;
		this.location = location;
		this.locationSite = locationSite;
		this.fab = fab;
		this.deptCode = deptCode;
		this.siteId = siteId;
		this.locationId = locationId;
		this.notesId = notesId;
		this.supervisorName = supervisorName;
		this.organizationCode = organizationCode;
		this.MDeptCode = MDeptCode;
	}

	@Id
	@Column(name = "PERSON_ID", unique = true, nullable = false, length = 30)
	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DISPLAY_NAME", length = 60)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "EMAIL_ADDRESS", length = 50)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PHONE_NUM", length = 52)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	@Column(name = "DEPARTMENT", length = 30)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "TITLE", length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "SUPERVISOR", length = 30)
	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "DELEGATE", length = 30)
	public String getDelegate() {
		return this.delegate;
	}

	public void setDelegate(String delegate) {
		this.delegate = delegate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STATUS_DATE", nullable = false, length = 7)
	public Date getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	@Column(name = "LANG_CODE", nullable = false, length = 4)
	public String getLangCode() {
		return this.langCode;
	}

	public void setLangCode(String langCode) {
		this.langCode = langCode;
	}

	@Column(name = "LOCATION", length = 30)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "LOCATION_SITE", length = 8)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "FAB", length = 12)
	public String getFab() {
		return this.fab;
	}

	public void setFab(String fab) {
		this.fab = fab;
	}

	@Column(name = "DEPT_CODE", length = 12)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "SITE_ID", length = 8)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@Column(name = "LOCATION_ID", length = 8)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}
	
	@Column(name = "NOTES_ID")
	public String getNotesId() {
		return notesId;
	}

	public void setNotesId(String notesId) {
		this.notesId = notesId;
	}
	
	@Column(name = "SUPERVISOR_NAME")
	public String getSupervisorName() {
		return supervisorName;
	}

	public void setSupervisorName(String supervisorName) {
		this.supervisorName = supervisorName;
	}
	
	@Column(name = "ORGANIZATION_CODE")
	public String getOrganizationCode() {
		return organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}
	@Column(name = "M_DEPT_CODE")
	public String getMDeptCode() {
		return MDeptCode;
	}

	public void setMDeptCode(String mDeptCode) {
		MDeptCode = mDeptCode;
	}
	
}
