package mro.base.entity;

// Generated 2012/10/30 �W�� 09:25:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Poline generated by hbm2java
 */
@Entity
@Table(name = "POLINE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SITEID", "POLINEID" }))
public class Poline implements java.io.Serializable {

	private BigDecimal polineid;
	private String ponum;
	private String itemnum;
	private String storeloc;
	private String modelnum;
	private String catalogcode;
	private BigDecimal orderqty;
	private String orderunit;
	private BigDecimal unitcost;
	private BigDecimal receivedqty;
	private BigDecimal receivedunitcost;
	private BigDecimal receivedtotalcost;
	private BigDecimal rejectedqty;
	private Date vendeliverydate;
	private String supervisor;
	private Date enterdate;
	private String enterby;
	private String description;
	private String pl1;
	private String pl2;
	private String pl3;
	private BigDecimal pl4;
	private String pl5;
	private String requestedby;
	private Date reqdeliverydate;
	private BigDecimal issue;
	private BigDecimal polinenum;
	private BigDecimal taxed;
	private String plin1;
	private String plin2;
	private String plin3;
	private Date plin4;
	private BigDecimal plin5;
	private String assetnum;
	private BigDecimal chargestore;
	private String gldebitacct;
	private String glcreditacct;
	private BigDecimal linecost;
	private String tax1code;
	private BigDecimal tax1;
	private String tax2code;
	private BigDecimal tax2;
	private String tax3code;
	private BigDecimal tax3;
	private BigDecimal receiptreqd;
	private String manufacturer;
	private String tax4code;
	private BigDecimal tax4;
	private String tax5code;
	private BigDecimal tax5;
	private String category;
	private String remark;
	private String location;
	private BigDecimal loadedcost;
	private BigDecimal prorateservice;
	private BigDecimal receiptscomplete;
	private BigDecimal inspectionrequired;
	private BigDecimal proratecost;
	private BigDecimal linecost2;
	private String mrnum;
	private BigDecimal mrlinenum;
	private String pl6;
	private String pl7;
	private String pl8;
	private String pl9;
	private String pl10;
	private String plin6;
	private String plin7;
	private String plin8;
	private String plin9;
	private String polaln1;
	private String polaln2;
	private String polaln3;
	private String polaln4;
	private String polaln5;
	private String pcardnum;
	private String pcardtype;
	private String pcardexpdate;
	private String fincntrlid;
	private String pcardverification;
	private String vendorpackcode;
	private String vendorpackquantity;
	private String vendorwarehouse;
	private String siteid;
	private String orgid;
	private BigDecimal isdistributed;
	private String refwo;
	private BigDecimal enteredastask;
	private String linetype;
	private String itemsetid;
	private String conditioncode;
	private String contractrefnum;
	private String commoditygroup;
	private String commodity;
	private BigDecimal contractrefid;
	private BigDecimal contractrefrev;
	private BigDecimal scheduleid;
	private BigDecimal contreflineid;
	private String tositeid;
	private String shipto;
	private String shiptoattn;
	private String langcode;
	private BigDecimal conversion;
	private BigDecimal hasld;
	private BigDecimal mktplcitem;
	private String rowstamp;
	private String erpPrnum;
	private BigDecimal erpPrline;
	private String erpPo;
	private BigDecimal erpPoline;
	private String erpPoComments;
	private String lineClosedCode;
	private String postatus;
	private String erpremark;
	private BigDecimal lineCancelFlag;
	private BigDecimal iqc;
	private String erpVendor;
	private BigDecimal unrecriveqty;
	private String purchaseagent;
	private String buyer;
	private String mcsuggest;
	private String progress;
	private String purtracking;
	private String reorderstatus;
	private String delivered;

	public Poline() {
	}

	public Poline(BigDecimal polineid, String ponum,
			BigDecimal receivedtotalcost, BigDecimal rejectedqty,
			Date enterdate, String enterby, BigDecimal issue,
			BigDecimal polinenum, BigDecimal taxed, BigDecimal chargestore,
			BigDecimal linecost, BigDecimal tax1, BigDecimal tax2,
			BigDecimal tax3, BigDecimal receiptreqd, BigDecimal tax4,
			BigDecimal tax5, BigDecimal loadedcost, BigDecimal prorateservice,
			BigDecimal receiptscomplete, BigDecimal inspectionrequired,
			String siteid, String orgid, BigDecimal isdistributed,
			BigDecimal enteredastask, String linetype, String tositeid,
			String langcode, BigDecimal conversion, BigDecimal hasld,
			BigDecimal mktplcitem, String rowstamp, BigDecimal lineCancelFlag) {
		this.polineid = polineid;
		this.ponum = ponum;
		this.receivedtotalcost = receivedtotalcost;
		this.rejectedqty = rejectedqty;
		this.enterdate = enterdate;
		this.enterby = enterby;
		this.issue = issue;
		this.polinenum = polinenum;
		this.taxed = taxed;
		this.chargestore = chargestore;
		this.linecost = linecost;
		this.tax1 = tax1;
		this.tax2 = tax2;
		this.tax3 = tax3;
		this.receiptreqd = receiptreqd;
		this.tax4 = tax4;
		this.tax5 = tax5;
		this.loadedcost = loadedcost;
		this.prorateservice = prorateservice;
		this.receiptscomplete = receiptscomplete;
		this.inspectionrequired = inspectionrequired;
		this.siteid = siteid;
		this.orgid = orgid;
		this.isdistributed = isdistributed;
		this.enteredastask = enteredastask;
		this.linetype = linetype;
		this.tositeid = tositeid;
		this.langcode = langcode;
		this.conversion = conversion;
		this.hasld = hasld;
		this.mktplcitem = mktplcitem;
		this.rowstamp = rowstamp;
		this.lineCancelFlag = lineCancelFlag;
	}

	public Poline(BigDecimal polineid, String ponum, String itemnum,
			String storeloc, String modelnum, String catalogcode,
			BigDecimal orderqty, String orderunit, BigDecimal unitcost,
			BigDecimal receivedqty, BigDecimal receivedunitcost,
			BigDecimal receivedtotalcost, BigDecimal rejectedqty,
			Date vendeliverydate, String supervisor, Date enterdate,
			String enterby, String description, String pl1, String pl2,
			String pl3, BigDecimal pl4, String pl5, String requestedby,
			Date reqdeliverydate, BigDecimal issue, BigDecimal polinenum,
			BigDecimal taxed, String plin1, String plin2, String plin3,
			Date plin4, BigDecimal plin5, String assetnum,
			BigDecimal chargestore, String gldebitacct, String glcreditacct,
			BigDecimal linecost, String tax1code, BigDecimal tax1,
			String tax2code, BigDecimal tax2, String tax3code, BigDecimal tax3,
			BigDecimal receiptreqd, String manufacturer, String tax4code,
			BigDecimal tax4, String tax5code, BigDecimal tax5, String category,
			String remark, String location, BigDecimal loadedcost,
			BigDecimal prorateservice, BigDecimal receiptscomplete,
			BigDecimal inspectionrequired, BigDecimal proratecost,
			BigDecimal linecost2, String mrnum, BigDecimal mrlinenum,
			String pl6, String pl7, String pl8, String pl9, String pl10,
			String plin6, String plin7, String plin8, String plin9,
			String polaln1, String polaln2, String polaln3, String polaln4,
			String polaln5, String pcardnum, String pcardtype,
			String pcardexpdate, String fincntrlid, String pcardverification,
			String vendorpackcode, String vendorpackquantity,
			String vendorwarehouse, String siteid, String orgid,
			BigDecimal isdistributed, String refwo, BigDecimal enteredastask,
			String linetype, String itemsetid, String conditioncode,
			String contractrefnum, String commoditygroup, String commodity,
			BigDecimal contractrefid, BigDecimal contractrefrev,
			BigDecimal scheduleid, BigDecimal contreflineid, String tositeid,
			String shipto, String shiptoattn, String langcode,
			BigDecimal conversion, BigDecimal hasld, BigDecimal mktplcitem,
			String rowstamp, String erpPrnum, BigDecimal erpPrline,
			String erpPo, BigDecimal erpPoline, String erpPoComments,
			String lineClosedCode, String postatus, String erpremark,
			BigDecimal lineCancelFlag, BigDecimal iqc, String erpVendor,
			BigDecimal unrecriveqty, String purchaseagent, String buyer,
			String mcsuggest, String progress, String purtracking,
			String reorderstatus, String delivered) {
		this.polineid = polineid;
		this.ponum = ponum;
		this.itemnum = itemnum;
		this.storeloc = storeloc;
		this.modelnum = modelnum;
		this.catalogcode = catalogcode;
		this.orderqty = orderqty;
		this.orderunit = orderunit;
		this.unitcost = unitcost;
		this.receivedqty = receivedqty;
		this.receivedunitcost = receivedunitcost;
		this.receivedtotalcost = receivedtotalcost;
		this.rejectedqty = rejectedqty;
		this.vendeliverydate = vendeliverydate;
		this.supervisor = supervisor;
		this.enterdate = enterdate;
		this.enterby = enterby;
		this.description = description;
		this.pl1 = pl1;
		this.pl2 = pl2;
		this.pl3 = pl3;
		this.pl4 = pl4;
		this.pl5 = pl5;
		this.requestedby = requestedby;
		this.reqdeliverydate = reqdeliverydate;
		this.issue = issue;
		this.polinenum = polinenum;
		this.taxed = taxed;
		this.plin1 = plin1;
		this.plin2 = plin2;
		this.plin3 = plin3;
		this.plin4 = plin4;
		this.plin5 = plin5;
		this.assetnum = assetnum;
		this.chargestore = chargestore;
		this.gldebitacct = gldebitacct;
		this.glcreditacct = glcreditacct;
		this.linecost = linecost;
		this.tax1code = tax1code;
		this.tax1 = tax1;
		this.tax2code = tax2code;
		this.tax2 = tax2;
		this.tax3code = tax3code;
		this.tax3 = tax3;
		this.receiptreqd = receiptreqd;
		this.manufacturer = manufacturer;
		this.tax4code = tax4code;
		this.tax4 = tax4;
		this.tax5code = tax5code;
		this.tax5 = tax5;
		this.category = category;
		this.remark = remark;
		this.location = location;
		this.loadedcost = loadedcost;
		this.prorateservice = prorateservice;
		this.receiptscomplete = receiptscomplete;
		this.inspectionrequired = inspectionrequired;
		this.proratecost = proratecost;
		this.linecost2 = linecost2;
		this.mrnum = mrnum;
		this.mrlinenum = mrlinenum;
		this.pl6 = pl6;
		this.pl7 = pl7;
		this.pl8 = pl8;
		this.pl9 = pl9;
		this.pl10 = pl10;
		this.plin6 = plin6;
		this.plin7 = plin7;
		this.plin8 = plin8;
		this.plin9 = plin9;
		this.polaln1 = polaln1;
		this.polaln2 = polaln2;
		this.polaln3 = polaln3;
		this.polaln4 = polaln4;
		this.polaln5 = polaln5;
		this.pcardnum = pcardnum;
		this.pcardtype = pcardtype;
		this.pcardexpdate = pcardexpdate;
		this.fincntrlid = fincntrlid;
		this.pcardverification = pcardverification;
		this.vendorpackcode = vendorpackcode;
		this.vendorpackquantity = vendorpackquantity;
		this.vendorwarehouse = vendorwarehouse;
		this.siteid = siteid;
		this.orgid = orgid;
		this.isdistributed = isdistributed;
		this.refwo = refwo;
		this.enteredastask = enteredastask;
		this.linetype = linetype;
		this.itemsetid = itemsetid;
		this.conditioncode = conditioncode;
		this.contractrefnum = contractrefnum;
		this.commoditygroup = commoditygroup;
		this.commodity = commodity;
		this.contractrefid = contractrefid;
		this.contractrefrev = contractrefrev;
		this.scheduleid = scheduleid;
		this.contreflineid = contreflineid;
		this.tositeid = tositeid;
		this.shipto = shipto;
		this.shiptoattn = shiptoattn;
		this.langcode = langcode;
		this.conversion = conversion;
		this.hasld = hasld;
		this.mktplcitem = mktplcitem;
		this.rowstamp = rowstamp;
		this.erpPrnum = erpPrnum;
		this.erpPrline = erpPrline;
		this.erpPo = erpPo;
		this.erpPoline = erpPoline;
		this.erpPoComments = erpPoComments;
		this.lineClosedCode = lineClosedCode;
		this.postatus = postatus;
		this.erpremark = erpremark;
		this.lineCancelFlag = lineCancelFlag;
		this.iqc = iqc;
		this.erpVendor = erpVendor;
		this.unrecriveqty = unrecriveqty;
		this.purchaseagent = purchaseagent;
		this.buyer = buyer;
		this.mcsuggest = mcsuggest;
		this.progress = progress;
		this.purtracking = purtracking;
		this.reorderstatus = reorderstatus;
		this.delivered = delivered;
	}

	@Id
	@Column(name = "POLINEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPolineid() {
		return this.polineid;
	}

	public void setPolineid(BigDecimal polineid) {
		this.polineid = polineid;
	}

	@Column(name = "PONUM", nullable = false, length = 80)
	public String getPonum() {
		return this.ponum;
	}

	public void setPonum(String ponum) {
		this.ponum = ponum;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "STORELOC", length = 16)
	public String getStoreloc() {
		return this.storeloc;
	}

	public void setStoreloc(String storeloc) {
		this.storeloc = storeloc;
	}

	@Column(name = "MODELNUM", length = 50)
	public String getModelnum() {
		return this.modelnum;
	}

	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "CATALOGCODE", length = 50)
	public String getCatalogcode() {
		return this.catalogcode;
	}

	public void setCatalogcode(String catalogcode) {
		this.catalogcode = catalogcode;
	}

	@Column(name = "ORDERQTY", precision = 15)
	public BigDecimal getOrderqty() {
		return this.orderqty;
	}

	public void setOrderqty(BigDecimal orderqty) {
		this.orderqty = orderqty;
	}

	@Column(name = "ORDERUNIT", length = 50)
	public String getOrderunit() {
		return this.orderunit;
	}

	public void setOrderunit(String orderunit) {
		this.orderunit = orderunit;
	}

	@Column(name = "UNITCOST", precision = 25)
	public BigDecimal getUnitcost() {
		return this.unitcost;
	}

	public void setUnitcost(BigDecimal unitcost) {
		this.unitcost = unitcost;
	}

	@Column(name = "RECEIVEDQTY", precision = 15)
	public BigDecimal getReceivedqty() {
		return this.receivedqty;
	}

	public void setReceivedqty(BigDecimal receivedqty) {
		this.receivedqty = receivedqty;
	}

	@Column(name = "RECEIVEDUNITCOST", precision = 25)
	public BigDecimal getReceivedunitcost() {
		return this.receivedunitcost;
	}

	public void setReceivedunitcost(BigDecimal receivedunitcost) {
		this.receivedunitcost = receivedunitcost;
	}

	@Column(name = "RECEIVEDTOTALCOST", nullable = false, precision = 25)
	public BigDecimal getReceivedtotalcost() {
		return this.receivedtotalcost;
	}

	public void setReceivedtotalcost(BigDecimal receivedtotalcost) {
		this.receivedtotalcost = receivedtotalcost;
	}

	@Column(name = "REJECTEDQTY", nullable = false, precision = 15)
	public BigDecimal getRejectedqty() {
		return this.rejectedqty;
	}

	public void setRejectedqty(BigDecimal rejectedqty) {
		this.rejectedqty = rejectedqty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VENDELIVERYDATE", length = 7)
	public Date getVendeliverydate() {
		return this.vendeliverydate;
	}

	public void setVendeliverydate(Date vendeliverydate) {
		this.vendeliverydate = vendeliverydate;
	}

	@Column(name = "SUPERVISOR", length = 30)
	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTERDATE", nullable = false, length = 7)
	public Date getEnterdate() {
		return this.enterdate;
	}

	public void setEnterdate(Date enterdate) {
		this.enterdate = enterdate;
	}

	@Column(name = "ENTERBY", nullable = false, length = 30)
	public String getEnterby() {
		return this.enterby;
	}

	public void setEnterby(String enterby) {
		this.enterby = enterby;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PL1", length = 10)
	public String getPl1() {
		return this.pl1;
	}

	public void setPl1(String pl1) {
		this.pl1 = pl1;
	}

	@Column(name = "PL2", length = 10)
	public String getPl2() {
		return this.pl2;
	}

	public void setPl2(String pl2) {
		this.pl2 = pl2;
	}

	@Column(name = "PL3", length = 10)
	public String getPl3() {
		return this.pl3;
	}

	public void setPl3(String pl3) {
		this.pl3 = pl3;
	}

	@Column(name = "PL4", precision = 15)
	public BigDecimal getPl4() {
		return this.pl4;
	}

	public void setPl4(BigDecimal pl4) {
		this.pl4 = pl4;
	}

	@Column(name = "PL5", length = 10)
	public String getPl5() {
		return this.pl5;
	}

	public void setPl5(String pl5) {
		this.pl5 = pl5;
	}

	@Column(name = "REQUESTEDBY", length = 30)
	public String getRequestedby() {
		return this.requestedby;
	}

	public void setRequestedby(String requestedby) {
		this.requestedby = requestedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQDELIVERYDATE", length = 7)
	public Date getReqdeliverydate() {
		return this.reqdeliverydate;
	}

	public void setReqdeliverydate(Date reqdeliverydate) {
		this.reqdeliverydate = reqdeliverydate;
	}

	@Column(name = "ISSUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIssue() {
		return this.issue;
	}

	public void setIssue(BigDecimal issue) {
		this.issue = issue;
	}

	@Column(name = "POLINENUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPolinenum() {
		return this.polinenum;
	}

	public void setPolinenum(BigDecimal polinenum) {
		this.polinenum = polinenum;
	}

	@Column(name = "TAXED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaxed() {
		return this.taxed;
	}

	public void setTaxed(BigDecimal taxed) {
		this.taxed = taxed;
	}

	@Column(name = "PLIN1", length = 10)
	public String getPlin1() {
		return this.plin1;
	}

	public void setPlin1(String plin1) {
		this.plin1 = plin1;
	}

	@Column(name = "PLIN2", length = 10)
	public String getPlin2() {
		return this.plin2;
	}

	public void setPlin2(String plin2) {
		this.plin2 = plin2;
	}

	@Column(name = "PLIN3", length = 10)
	public String getPlin3() {
		return this.plin3;
	}

	public void setPlin3(String plin3) {
		this.plin3 = plin3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PLIN4", length = 7)
	public Date getPlin4() {
		return this.plin4;
	}

	public void setPlin4(Date plin4) {
		this.plin4 = plin4;
	}

	@Column(name = "PLIN5", precision = 15)
	public BigDecimal getPlin5() {
		return this.plin5;
	}

	public void setPlin5(BigDecimal plin5) {
		this.plin5 = plin5;
	}

	@Column(name = "ASSETNUM", length = 20)
	public String getAssetnum() {
		return this.assetnum;
	}

	public void setAssetnum(String assetnum) {
		this.assetnum = assetnum;
	}

	@Column(name = "CHARGESTORE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getChargestore() {
		return this.chargestore;
	}

	public void setChargestore(BigDecimal chargestore) {
		this.chargestore = chargestore;
	}

	@Column(name = "GLDEBITACCT", length = 10)
	public String getGldebitacct() {
		return this.gldebitacct;
	}

	public void setGldebitacct(String gldebitacct) {
		this.gldebitacct = gldebitacct;
	}

	@Column(name = "GLCREDITACCT", length = 10)
	public String getGlcreditacct() {
		return this.glcreditacct;
	}

	public void setGlcreditacct(String glcreditacct) {
		this.glcreditacct = glcreditacct;
	}

	@Column(name = "LINECOST", nullable = false, precision = 25)
	public BigDecimal getLinecost() {
		return this.linecost;
	}

	public void setLinecost(BigDecimal linecost) {
		this.linecost = linecost;
	}

	@Column(name = "TAX1CODE", length = 8)
	public String getTax1code() {
		return this.tax1code;
	}

	public void setTax1code(String tax1code) {
		this.tax1code = tax1code;
	}

	@Column(name = "TAX1", nullable = false, precision = 10)
	public BigDecimal getTax1() {
		return this.tax1;
	}

	public void setTax1(BigDecimal tax1) {
		this.tax1 = tax1;
	}

	@Column(name = "TAX2CODE", length = 8)
	public String getTax2code() {
		return this.tax2code;
	}

	public void setTax2code(String tax2code) {
		this.tax2code = tax2code;
	}

	@Column(name = "TAX2", nullable = false, precision = 10)
	public BigDecimal getTax2() {
		return this.tax2;
	}

	public void setTax2(BigDecimal tax2) {
		this.tax2 = tax2;
	}

	@Column(name = "TAX3CODE", length = 8)
	public String getTax3code() {
		return this.tax3code;
	}

	public void setTax3code(String tax3code) {
		this.tax3code = tax3code;
	}

	@Column(name = "TAX3", nullable = false, precision = 10)
	public BigDecimal getTax3() {
		return this.tax3;
	}

	public void setTax3(BigDecimal tax3) {
		this.tax3 = tax3;
	}

	@Column(name = "RECEIPTREQD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getReceiptreqd() {
		return this.receiptreqd;
	}

	public void setReceiptreqd(BigDecimal receiptreqd) {
		this.receiptreqd = receiptreqd;
	}

	@Column(name = "MANUFACTURER", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "TAX4CODE", length = 8)
	public String getTax4code() {
		return this.tax4code;
	}

	public void setTax4code(String tax4code) {
		this.tax4code = tax4code;
	}

	@Column(name = "TAX4", nullable = false, precision = 10)
	public BigDecimal getTax4() {
		return this.tax4;
	}

	public void setTax4(BigDecimal tax4) {
		this.tax4 = tax4;
	}

	@Column(name = "TAX5CODE", length = 8)
	public String getTax5code() {
		return this.tax5code;
	}

	public void setTax5code(String tax5code) {
		this.tax5code = tax5code;
	}

	@Column(name = "TAX5", nullable = false, precision = 10)
	public BigDecimal getTax5() {
		return this.tax5;
	}

	public void setTax5(BigDecimal tax5) {
		this.tax5 = tax5;
	}

	@Column(name = "CATEGORY", length = 16)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "LOADEDCOST", nullable = false, precision = 25)
	public BigDecimal getLoadedcost() {
		return this.loadedcost;
	}

	public void setLoadedcost(BigDecimal loadedcost) {
		this.loadedcost = loadedcost;
	}

	@Column(name = "PRORATESERVICE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getProrateservice() {
		return this.prorateservice;
	}

	public void setProrateservice(BigDecimal prorateservice) {
		this.prorateservice = prorateservice;
	}

	@Column(name = "RECEIPTSCOMPLETE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getReceiptscomplete() {
		return this.receiptscomplete;
	}

	public void setReceiptscomplete(BigDecimal receiptscomplete) {
		this.receiptscomplete = receiptscomplete;
	}

	@Column(name = "INSPECTIONREQUIRED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getInspectionrequired() {
		return this.inspectionrequired;
	}

	public void setInspectionrequired(BigDecimal inspectionrequired) {
		this.inspectionrequired = inspectionrequired;
	}

	@Column(name = "PRORATECOST", precision = 25)
	public BigDecimal getProratecost() {
		return this.proratecost;
	}

	public void setProratecost(BigDecimal proratecost) {
		this.proratecost = proratecost;
	}

	@Column(name = "LINECOST2", precision = 25)
	public BigDecimal getLinecost2() {
		return this.linecost2;
	}

	public void setLinecost2(BigDecimal linecost2) {
		this.linecost2 = linecost2;
	}

	@Column(name = "MRNUM", length = 8)
	public String getMrnum() {
		return this.mrnum;
	}

	public void setMrnum(String mrnum) {
		this.mrnum = mrnum;
	}

	@Column(name = "MRLINENUM", precision = 22, scale = 0)
	public BigDecimal getMrlinenum() {
		return this.mrlinenum;
	}

	public void setMrlinenum(BigDecimal mrlinenum) {
		this.mrlinenum = mrlinenum;
	}

	@Column(name = "PL6", length = 10)
	public String getPl6() {
		return this.pl6;
	}

	public void setPl6(String pl6) {
		this.pl6 = pl6;
	}

	@Column(name = "PL7", length = 10)
	public String getPl7() {
		return this.pl7;
	}

	public void setPl7(String pl7) {
		this.pl7 = pl7;
	}

	@Column(name = "PL8", length = 10)
	public String getPl8() {
		return this.pl8;
	}

	public void setPl8(String pl8) {
		this.pl8 = pl8;
	}

	@Column(name = "PL9", length = 10)
	public String getPl9() {
		return this.pl9;
	}

	public void setPl9(String pl9) {
		this.pl9 = pl9;
	}

	@Column(name = "PL10", length = 10)
	public String getPl10() {
		return this.pl10;
	}

	public void setPl10(String pl10) {
		this.pl10 = pl10;
	}

	@Column(name = "PLIN6", length = 10)
	public String getPlin6() {
		return this.plin6;
	}

	public void setPlin6(String plin6) {
		this.plin6 = plin6;
	}

	@Column(name = "PLIN7", length = 10)
	public String getPlin7() {
		return this.plin7;
	}

	public void setPlin7(String plin7) {
		this.plin7 = plin7;
	}

	@Column(name = "PLIN8", length = 10)
	public String getPlin8() {
		return this.plin8;
	}

	public void setPlin8(String plin8) {
		this.plin8 = plin8;
	}

	@Column(name = "PLIN9", length = 10)
	public String getPlin9() {
		return this.plin9;
	}

	public void setPlin9(String plin9) {
		this.plin9 = plin9;
	}

	@Column(name = "POLALN1", length = 10)
	public String getPolaln1() {
		return this.polaln1;
	}

	public void setPolaln1(String polaln1) {
		this.polaln1 = polaln1;
	}

	@Column(name = "POLALN2", length = 10)
	public String getPolaln2() {
		return this.polaln2;
	}

	public void setPolaln2(String polaln2) {
		this.polaln2 = polaln2;
	}

	@Column(name = "POLALN3", length = 10)
	public String getPolaln3() {
		return this.polaln3;
	}

	public void setPolaln3(String polaln3) {
		this.polaln3 = polaln3;
	}

	@Column(name = "POLALN4", length = 10)
	public String getPolaln4() {
		return this.polaln4;
	}

	public void setPolaln4(String polaln4) {
		this.polaln4 = polaln4;
	}

	@Column(name = "POLALN5", length = 10)
	public String getPolaln5() {
		return this.polaln5;
	}

	public void setPolaln5(String polaln5) {
		this.polaln5 = polaln5;
	}

	@Column(name = "PCARDNUM", length = 30)
	public String getPcardnum() {
		return this.pcardnum;
	}

	public void setPcardnum(String pcardnum) {
		this.pcardnum = pcardnum;
	}

	@Column(name = "PCARDTYPE", length = 20)
	public String getPcardtype() {
		return this.pcardtype;
	}

	public void setPcardtype(String pcardtype) {
		this.pcardtype = pcardtype;
	}

	@Column(name = "PCARDEXPDATE", length = 7)
	public String getPcardexpdate() {
		return this.pcardexpdate;
	}

	public void setPcardexpdate(String pcardexpdate) {
		this.pcardexpdate = pcardexpdate;
	}

	@Column(name = "FINCNTRLID", length = 8)
	public String getFincntrlid() {
		return this.fincntrlid;
	}

	public void setFincntrlid(String fincntrlid) {
		this.fincntrlid = fincntrlid;
	}

	@Column(name = "PCARDVERIFICATION", length = 4)
	public String getPcardverification() {
		return this.pcardverification;
	}

	public void setPcardverification(String pcardverification) {
		this.pcardverification = pcardverification;
	}

	@Column(name = "VENDORPACKCODE", length = 12)
	public String getVendorpackcode() {
		return this.vendorpackcode;
	}

	public void setVendorpackcode(String vendorpackcode) {
		this.vendorpackcode = vendorpackcode;
	}

	@Column(name = "VENDORPACKQUANTITY", length = 12)
	public String getVendorpackquantity() {
		return this.vendorpackquantity;
	}

	public void setVendorpackquantity(String vendorpackquantity) {
		this.vendorpackquantity = vendorpackquantity;
	}

	@Column(name = "VENDORWAREHOUSE", length = 12)
	public String getVendorwarehouse() {
		return this.vendorwarehouse;
	}

	public void setVendorwarehouse(String vendorwarehouse) {
		this.vendorwarehouse = vendorwarehouse;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ISDISTRIBUTED", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIsdistributed() {
		return this.isdistributed;
	}

	public void setIsdistributed(BigDecimal isdistributed) {
		this.isdistributed = isdistributed;
	}

	@Column(name = "REFWO", length = 10)
	public String getRefwo() {
		return this.refwo;
	}

	public void setRefwo(String refwo) {
		this.refwo = refwo;
	}

	@Column(name = "ENTEREDASTASK", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEnteredastask() {
		return this.enteredastask;
	}

	public void setEnteredastask(BigDecimal enteredastask) {
		this.enteredastask = enteredastask;
	}

	@Column(name = "LINETYPE", nullable = false, length = 15)
	public String getLinetype() {
		return this.linetype;
	}

	public void setLinetype(String linetype) {
		this.linetype = linetype;
	}

	@Column(name = "ITEMSETID", length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "CONTRACTREFNUM", length = 8)
	public String getContractrefnum() {
		return this.contractrefnum;
	}

	public void setContractrefnum(String contractrefnum) {
		this.contractrefnum = contractrefnum;
	}

	@Column(name = "COMMODITYGROUP", length = 8)
	public String getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "COMMODITY", length = 8)
	public String getCommodity() {
		return this.commodity;
	}

	public void setCommodity(String commodity) {
		this.commodity = commodity;
	}

	@Column(name = "CONTRACTREFID", precision = 22, scale = 0)
	public BigDecimal getContractrefid() {
		return this.contractrefid;
	}

	public void setContractrefid(BigDecimal contractrefid) {
		this.contractrefid = contractrefid;
	}

	@Column(name = "CONTRACTREFREV", precision = 22, scale = 0)
	public BigDecimal getContractrefrev() {
		return this.contractrefrev;
	}

	public void setContractrefrev(BigDecimal contractrefrev) {
		this.contractrefrev = contractrefrev;
	}

	@Column(name = "SCHEDULEID", precision = 22, scale = 0)
	public BigDecimal getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(BigDecimal scheduleid) {
		this.scheduleid = scheduleid;
	}

	@Column(name = "CONTREFLINEID", precision = 22, scale = 0)
	public BigDecimal getContreflineid() {
		return this.contreflineid;
	}

	public void setContreflineid(BigDecimal contreflineid) {
		this.contreflineid = contreflineid;
	}

	@Column(name = "TOSITEID", nullable = false, length = 8)
	public String getTositeid() {
		return this.tositeid;
	}

	public void setTositeid(String tositeid) {
		this.tositeid = tositeid;
	}

	@Column(name = "SHIPTO", length = 30)
	public String getShipto() {
		return this.shipto;
	}

	public void setShipto(String shipto) {
		this.shipto = shipto;
	}

	@Column(name = "SHIPTOATTN", length = 30)
	public String getShiptoattn() {
		return this.shiptoattn;
	}

	public void setShiptoattn(String shiptoattn) {
		this.shiptoattn = shiptoattn;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "CONVERSION", nullable = false, precision = 15)
	public BigDecimal getConversion() {
		return this.conversion;
	}

	public void setConversion(BigDecimal conversion) {
		this.conversion = conversion;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getHasld() {
		return this.hasld;
	}

	public void setHasld(BigDecimal hasld) {
		this.hasld = hasld;
	}

	@Column(name = "MKTPLCITEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getMktplcitem() {
		return this.mktplcitem;
	}

	public void setMktplcitem(BigDecimal mktplcitem) {
		this.mktplcitem = mktplcitem;
	}

	@Column(name = "ROWSTAMP", nullable = false, length = 40)
	public String getRowstamp() {
		return this.rowstamp;
	}

	public void setRowstamp(String rowstamp) {
		this.rowstamp = rowstamp;
	}

	@Column(name = "ERP_PRNUM", length = 20)
	public String getErpPrnum() {
		return this.erpPrnum;
	}

	public void setErpPrnum(String erpPrnum) {
		this.erpPrnum = erpPrnum;
	}

	@Column(name = "ERP_PRLINE", precision = 22, scale = 0)
	public BigDecimal getErpPrline() {
		return this.erpPrline;
	}

	public void setErpPrline(BigDecimal erpPrline) {
		this.erpPrline = erpPrline;
	}

	@Column(name = "ERP_PO", length = 20)
	public String getErpPo() {
		return this.erpPo;
	}

	public void setErpPo(String erpPo) {
		this.erpPo = erpPo;
	}

	@Column(name = "ERP_POLINE", precision = 22, scale = 0)
	public BigDecimal getErpPoline() {
		return this.erpPoline;
	}

	public void setErpPoline(BigDecimal erpPoline) {
		this.erpPoline = erpPoline;
	}

	@Column(name = "ERP_PO_COMMENTS", length = 500)
	public String getErpPoComments() {
		return this.erpPoComments;
	}

	public void setErpPoComments(String erpPoComments) {
		this.erpPoComments = erpPoComments;
	}

	@Column(name = "LINE_CLOSED_CODE", length = 25)
	public String getLineClosedCode() {
		return this.lineClosedCode;
	}

	public void setLineClosedCode(String lineClosedCode) {
		this.lineClosedCode = lineClosedCode;
	}

	@Column(name = "POSTATUS", length = 20)
	public String getPostatus() {
		return this.postatus;
	}

	public void setPostatus(String postatus) {
		this.postatus = postatus;
	}

	@Column(name = "ERPREMARK", length = 500)
	public String getErpremark() {
		return this.erpremark;
	}

	public void setErpremark(String erpremark) {
		this.erpremark = erpremark;
	}

	@Column(name = "LINE_CANCEL_FLAG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLineCancelFlag() {
		return this.lineCancelFlag;
	}

	public void setLineCancelFlag(BigDecimal lineCancelFlag) {
		this.lineCancelFlag = lineCancelFlag;
	}

	@Column(name = "IQC", precision = 15)
	public BigDecimal getIqc() {
		return this.iqc;
	}

	public void setIqc(BigDecimal iqc) {
		this.iqc = iqc;
	}

	@Column(name = "ERP_VENDOR", length = 30)
	public String getErpVendor() {
		return this.erpVendor;
	}

	public void setErpVendor(String erpVendor) {
		this.erpVendor = erpVendor;
	}

	@Column(name = "UNRECRIVEQTY", precision = 15)
	public BigDecimal getUnrecriveqty() {
		return this.unrecriveqty;
	}

	public void setUnrecriveqty(BigDecimal unrecriveqty) {
		this.unrecriveqty = unrecriveqty;
	}

	@Column(name = "PURCHASEAGENT", length = 120)
	public String getPurchaseagent() {
		return this.purchaseagent;
	}

	public void setPurchaseagent(String purchaseagent) {
		this.purchaseagent = purchaseagent;
	}

	@Column(name = "BUYER", length = 50)
	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "MCSUGGEST", length = 50)
	public String getMcsuggest() {
		return this.mcsuggest;
	}

	public void setMcsuggest(String mcsuggest) {
		this.mcsuggest = mcsuggest;
	}

	@Column(name = "PROGRESS", length = 50)
	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	@Column(name = "PURTRACKING", length = 50)
	public String getPurtracking() {
		return this.purtracking;
	}

	public void setPurtracking(String purtracking) {
		this.purtracking = purtracking;
	}

	@Column(name = "REORDERSTATUS", length = 50)
	public String getReorderstatus() {
		return this.reorderstatus;
	}

	public void setReorderstatus(String reorderstatus) {
		this.reorderstatus = reorderstatus;
	}

	@Column(name = "DELIVERED", length = 50)
	public String getDelivered() {
		return this.delivered;
	}

	public void setDelivered(String delivered) {
		this.delivered = delivered;
	}

}
