package mro.base.entity;

// Generated 2013/2/25 �U�� 05:05:23 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import mro.base.System.config.SystemConfig;

/**
 * Pr generated by hbm2java
 */
@Entity
@Table(name = "PR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SITEID", "PRNUM" }))
public class Pr implements java.io.Serializable {

	private BigDecimal prid;
	private String prnum;
	private Date issuedate;
	private Date requireddate;
	private String requestedby;
	private String vendor;
	private String contact;
	private String customernum;
	private String fob;
	private String freightterms;
	private String shipvia;
	private String paymentterms;
	private String shipto;
	private String shiptoattn;
	private String billto;
	private String billtoattn;
	private String description;
	private String status;
	private Date statusdate;
	private Date changedate;
	private String changeby;
	private BigDecimal totalcost;
	private long priority;
	private long historyflag;
	private String pr1;
	private String pr2;
	private String pr3;
	private String pr4;
	private String pr5;
	private long pr6;
	private Date pr7;
	private long pr8;
	private long pr9;
	private long pr10;
	private String supervisor;
	private String currencycode;
	private long exchangerate;
	private Date exchangedate;
	private long buyahead;
	private long totaltax1;
	private long totaltax2;
	private long totaltax3;
	private long inclusive1;
	private long inclusive2;
	private long inclusive3;
	private long internal;
	private long totaltax4;
	private long totaltax5;
	private long inclusive4;
	private long inclusive5;
	private long payonreceipt;
	private long exchangerate2;
	private String sourcesysid;
	private String ownersysid;
	private String externalrefid;
	private String prla1;
	private String prla2;
	private String prla3;
	private String prla4;
	private String prla5;
	private String pcardnum;
	private String pcardtype;
	private String pcardexpdate;
	private String sendersysid;
	private String pcardverification;
	private String siteid;
	private String orgid;
	private String contractrefnum;
	private long novendor;
	private long contractrefid;
	private long contractrefrev;
	private String storeloc;
	private String storelocsiteid;
	private long inspectionrequired;
	private String langcode;
	private long hasld;
	private String MDept;
	private String deptcode;
	private String deptsupervisor;
	private String prtype;
	private BigDecimal totalbasecost2;
	private long deletemark;
	private String countersign1;
	private String countersign2;
	private String cmopriority;
	private String requestedby2;
	private BigDecimal totalcost2;
	private String vendoritemtype;
	private String reasoncode;
	private String obdept;
	private long rsflag;
	private Set<Prline> prlines = new HashSet<Prline>(0);
	private BigDecimal taskId;
	private String prlineStatus;
	private String lastSigner;
	private String transferFlag;
	private String extraRemark;
	private Date transferDate;
	private String ignoreDeptFlag;
	
	public Pr() {
		this.internal=1;
		this.novendor=1;
		this.langcode=SystemConfig.LANGCODE_ZH;
	}

	public Pr(BigDecimal prid, String prnum, String status, Date statusdate,
			Date changedate, String changeby, BigDecimal totalcost,
			long priority, long historyflag, long pr10,
			String currencycode, long buyahead, long inclusive1,
			long inclusive2, long inclusive3, long internal,
			long inclusive4, long inclusive5,
			long payonreceipt, String siteid, String orgid,
			long novendor, long inspectionrequired,
			String langcode, long hasld, long deletemark,
			long rsflag) {
		this.prid = prid;
		this.prnum = prnum;
		this.status = status;
		this.statusdate = statusdate;
		this.changedate = changedate;
		this.changeby = changeby;
		this.totalcost = totalcost;
		this.priority = priority;
		this.historyflag = historyflag;
		this.pr10 = pr10;
		this.currencycode = currencycode;
		this.buyahead = buyahead;
		this.inclusive1 = inclusive1;
		this.inclusive2 = inclusive2;
		this.inclusive3 = inclusive3;
		this.internal = internal;
		this.inclusive4 = inclusive4;
		this.inclusive5 = inclusive5;
		this.payonreceipt = payonreceipt;
		this.siteid = siteid;
		this.orgid = orgid;
		this.novendor = novendor;
		this.inspectionrequired = inspectionrequired;
		this.langcode = langcode;
		this.hasld = hasld;
		this.deletemark = deletemark;
		this.rsflag = rsflag;
	}

	public Pr(BigDecimal prid, String prnum, Date issuedate, Date requireddate,
			String requestedby, String vendor, String contact,
			String customernum, String fob, String freightterms,
			String shipvia, String paymentterms, String shipto,
			String shiptoattn, String billto, String billtoattn,
			String description, String status, Date statusdate,
			Date changedate, String changeby, BigDecimal totalcost,
			long priority, long historyflag, String pr1,
			String pr2, String pr3, String pr4, String pr5, long pr6,
			Date pr7, long pr8, long pr9, long pr10,
			String supervisor, String currencycode, long exchangerate,
			Date exchangedate, long buyahead, long totaltax1,
			long totaltax2, long totaltax3, long inclusive1,
			long inclusive2, long inclusive3, long internal,
			long totaltax4, long totaltax5, long inclusive4,
			long inclusive5, long payonreceipt,
			long exchangerate2, String sourcesysid, String ownersysid,
			String externalrefid, String prla1, String prla2, String prla3,
			String prla4, String prla5, String pcardnum, String pcardtype,
			String pcardexpdate, String sendersysid, String pcardverification,
			String siteid, String orgid, String contractrefnum,
			long novendor, long contractrefid,
			long contractrefrev, String storeloc, String storelocsiteid,
			long inspectionrequired, String langcode, long hasld,
			String MDept, String deptcode, String deptsupervisor, String prtype,
			BigDecimal totalbasecost2, long deletemark,
			String countersign1, String countersign2, String cmopriority,
			String requestedby2, BigDecimal totalcost2, String vendoritemtype,
			String reasoncode, String obdept, long rsflag,BigDecimal taskId,
			Set<Prline> prlines,String prlineStatus,String lastSigner,String transferFlag,
			String extraRemark,Date transferDate,String ignoreDeptFlag,
			String cmommcontrol) {
		this.prid = prid;
		this.prnum = prnum;
		this.issuedate = issuedate;
		this.requireddate = requireddate;
		this.requestedby = requestedby;
		this.vendor = vendor;
		this.contact = contact;
		this.customernum = customernum;
		this.fob = fob;
		this.freightterms = freightterms;
		this.shipvia = shipvia;
		this.paymentterms = paymentterms;
		this.shipto = shipto;
		this.shiptoattn = shiptoattn;
		this.billto = billto;
		this.billtoattn = billtoattn;
		this.description = description;
		this.status = status;
		this.statusdate = statusdate;
		this.changedate = changedate;
		this.changeby = changeby;
		this.totalcost = totalcost;
		this.priority = priority;
		this.historyflag = historyflag;
		this.pr1 = pr1;
		this.pr2 = pr2;
		this.pr3 = pr3;
		this.pr4 = pr4;
		this.pr5 = pr5;
		this.pr6 = pr6;
		this.pr7 = pr7;
		this.pr8 = pr8;
		this.pr9 = pr9;
		this.pr10 = pr10;
		this.supervisor = supervisor;
		this.currencycode = currencycode;
		this.exchangerate = exchangerate;
		this.exchangedate = exchangedate;
		this.buyahead = buyahead;
		this.totaltax1 = totaltax1;
		this.totaltax2 = totaltax2;
		this.totaltax3 = totaltax3;
		this.inclusive1 = inclusive1;
		this.inclusive2 = inclusive2;
		this.inclusive3 = inclusive3;
		this.internal = internal;
		this.totaltax4 = totaltax4;
		this.totaltax5 = totaltax5;
		this.inclusive4 = inclusive4;
		this.inclusive5 = inclusive5;
		this.payonreceipt = payonreceipt;
		this.exchangerate2 = exchangerate2;
		this.sourcesysid = sourcesysid;
		this.ownersysid = ownersysid;
		this.externalrefid = externalrefid;
		this.prla1 = prla1;
		this.prla2 = prla2;
		this.prla3 = prla3;
		this.prla4 = prla4;
		this.prla5 = prla5;
		this.pcardnum = pcardnum;
		this.pcardtype = pcardtype;
		this.pcardexpdate = pcardexpdate;
		this.sendersysid = sendersysid;
		this.pcardverification = pcardverification;
		this.siteid = siteid;
		this.orgid = orgid;
		this.contractrefnum = contractrefnum;
		this.novendor = novendor;
		this.contractrefid = contractrefid;
		this.contractrefrev = contractrefrev;
		this.storeloc = storeloc;
		this.storelocsiteid = storelocsiteid;
		this.inspectionrequired = inspectionrequired;
		this.langcode = langcode;
		this.hasld = hasld;
		this.MDept = MDept;
		this.deptcode = deptcode;
		this.deptsupervisor = deptsupervisor;
		this.prtype = prtype;
		this.totalbasecost2 = totalbasecost2;
		this.deletemark = deletemark;
		this.countersign1 = countersign1;
		this.countersign2 = countersign2;
		this.cmopriority = cmopriority;
		this.requestedby2 = requestedby2;
		this.totalcost2 = totalcost2;
		this.vendoritemtype = vendoritemtype;
		this.reasoncode = reasoncode;
		this.obdept = obdept;
		this.rsflag = rsflag;
		this.prlines = prlines;
		this.taskId = taskId;
		this.prlineStatus = prlineStatus;
		this.lastSigner = lastSigner;
		this.transferFlag = transferFlag;
		this.extraRemark =extraRemark;
		this.transferDate = transferDate;
		this.ignoreDeptFlag = ignoreDeptFlag;
	}

	@Id
	@SequenceGenerator(name="PR_PRID_GENERATOR", sequenceName="PRSEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PR_PRID_GENERATOR")
	@Column(name = "PRID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrid() {
		return this.prid;
	}

	public void setPrid(BigDecimal prid) {
		this.prid = prid;
	}

	@Column(name = "PRNUM", nullable = false, length = 80)
	public String getPrnum() {
		return this.prnum;
	}

	public void setPrnum(String prnum) {
		this.prnum = prnum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ISSUEDATE", length = 7)
	public Date getIssuedate() {
		return this.issuedate;
	}

	public void setIssuedate(Date issuedate) {
		this.issuedate = issuedate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUIREDDATE", length = 7)
	public Date getRequireddate() {
		return this.requireddate;
	}

	public void setRequireddate(Date requireddate) {
		this.requireddate = requireddate;
	}

	@Column(name = "REQUESTEDBY", length = 30)
	public String getRequestedby() {
		return this.requestedby;
	}

	public void setRequestedby(String requestedby) {
		this.requestedby = requestedby;
	}

	@Column(name = "VENDOR", length = 30)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "CONTACT", length = 100)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "CUSTOMERNUM", length = 16)
	public String getCustomernum() {
		return this.customernum;
	}

	public void setCustomernum(String customernum) {
		this.customernum = customernum;
	}

	@Column(name = "FOB", length = 20)
	public String getFob() {
		return this.fob;
	}

	public void setFob(String fob) {
		this.fob = fob;
	}

	@Column(name = "FREIGHTTERMS", length = 50)
	public String getFreightterms() {
		return this.freightterms;
	}

	public void setFreightterms(String freightterms) {
		this.freightterms = freightterms;
	}

	@Column(name = "SHIPVIA", length = 20)
	public String getShipvia() {
		return this.shipvia;
	}

	public void setShipvia(String shipvia) {
		this.shipvia = shipvia;
	}

	@Column(name = "PAYMENTTERMS", length = 20)
	public String getPaymentterms() {
		return this.paymentterms;
	}

	public void setPaymentterms(String paymentterms) {
		this.paymentterms = paymentterms;
	}

	@Column(name = "SHIPTO", length = 30)
	public String getShipto() {
		return this.shipto;
	}

	public void setShipto(String shipto) {
		this.shipto = shipto;
	}

	@Column(name = "SHIPTOATTN", length = 30)
	public String getShiptoattn() {
		return this.shiptoattn;
	}

	public void setShiptoattn(String shiptoattn) {
		this.shiptoattn = shiptoattn;
	}

	@Column(name = "BILLTO", length = 30)
	public String getBillto() {
		return this.billto;
	}

	public void setBillto(String billto) {
		this.billto = billto;
	}

	@Column(name = "BILLTOATTN", length = 30)
	public String getBilltoattn() {
		return this.billtoattn;
	}

	public void setBilltoattn(String billtoattn) {
		this.billtoattn = billtoattn;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATUS", nullable = false, length = 12)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STATUSDATE", nullable = false, length = 7)
	public Date getStatusdate() {
		return this.statusdate;
	}

	public void setStatusdate(Date statusdate) {
		this.statusdate = statusdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGEDATE", nullable = false, length = 7)
	public Date getChangedate() {
		return this.changedate;
	}

	public void setChangedate(Date changedate) {
		this.changedate = changedate;
	}

	@Column(name = "CHANGEBY", nullable = false, length = 30)
	public String getChangeby() {
		return this.changeby;
	}

	public void setChangeby(String changeby) {
		this.changeby = changeby;
	}

	@Column(name = "TOTALCOST", nullable = false, precision = 25)
	public BigDecimal getTotalcost() {
		return this.totalcost;
	}

	public void setTotalcost(BigDecimal totalcost) {
		this.totalcost = totalcost;
	}

	@Column(name = "PRIORITY", nullable = false, precision = 22, scale = 0)
	public long getPriority() {
		return this.priority;
	}

	public void setPriority(long priority) {
		this.priority = priority;
	}

	@Column(name = "HISTORYFLAG", nullable = false, precision = 22, scale = 0)
	public long getHistoryflag() {
		return this.historyflag;
	}

	public void setHistoryflag(long historyflag) {
		this.historyflag = historyflag;
	}

	@Column(name = "PR1", length = 10)
	public String getPr1() {
		return this.pr1;
	}

	public void setPr1(String pr1) {
		this.pr1 = pr1;
	}

	@Column(name = "PR2", length = 10)
	public String getPr2() {
		return this.pr2;
	}

	public void setPr2(String pr2) {
		this.pr2 = pr2;
	}

	@Column(name = "PR3", length = 10)
	public String getPr3() {
		return this.pr3;
	}

	public void setPr3(String pr3) {
		this.pr3 = pr3;
	}

	@Column(name = "PR4", length = 10)
	public String getPr4() {
		return this.pr4;
	}

	public void setPr4(String pr4) {
		this.pr4 = pr4;
	}

	@Column(name = "PR5", length = 10)
	public String getPr5() {
		return this.pr5;
	}

	public void setPr5(String pr5) {
		this.pr5 = pr5;
	}

	@Column(name = "PR6", precision = 10)
	public long getPr6() {
		return this.pr6;
	}

	public void setPr6(long pr6) {
		this.pr6 = pr6;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PR7", length = 7)
	public Date getPr7() {
		return this.pr7;
	}

	public void setPr7(Date pr7) {
		this.pr7 = pr7;
	}

	@Column(name = "PR8", precision = 15)
	public long getPr8() {
		return this.pr8;
	}

	public void setPr8(long pr8) {
		this.pr8 = pr8;
	}

	@Column(name = "PR9", precision = 22, scale = 0)
	public long getPr9() {
		return this.pr9;
	}

	public void setPr9(long pr9) {
		this.pr9 = pr9;
	}

	@Column(name = "PR10", nullable = false, precision = 22, scale = 0)
	public long getPr10() {
		return this.pr10;
	}

	public void setPr10(long pr10) {
		this.pr10 = pr10;
	}

	@Column(name = "SUPERVISOR", length = 30)
	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "CURRENCYCODE", nullable = false, length = 8)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "EXCHANGERATE", precision = 14, scale = 7)
	public long getExchangerate() {
		return this.exchangerate;
	}

	public void setExchangerate(long exchangerate) {
		this.exchangerate = exchangerate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXCHANGEDATE", length = 7)
	public Date getExchangedate() {
		return this.exchangedate;
	}

	public void setExchangedate(Date exchangedate) {
		this.exchangedate = exchangedate;
	}

	@Column(name = "BUYAHEAD", nullable = false, precision = 22, scale = 0)
	public long getBuyahead() {
		return this.buyahead;
	}

	public void setBuyahead(long buyahead) {
		this.buyahead = buyahead;
	}

	@Column(name = "TOTALTAX1", precision = 10)
	public long getTotaltax1() {
		return this.totaltax1;
	}

	public void setTotaltax1(long totaltax1) {
		this.totaltax1 = totaltax1;
	}

	@Column(name = "TOTALTAX2", precision = 10)
	public long getTotaltax2() {
		return this.totaltax2;
	}

	public void setTotaltax2(long totaltax2) {
		this.totaltax2 = totaltax2;
	}

	@Column(name = "TOTALTAX3", precision = 10)
	public long getTotaltax3() {
		return this.totaltax3;
	}

	public void setTotaltax3(long totaltax3) {
		this.totaltax3 = totaltax3;
	}

	@Column(name = "INCLUSIVE1", nullable = false, precision = 22, scale = 0)
	public long getInclusive1() {
		return this.inclusive1;
	}

	public void setInclusive1(long inclusive1) {
		this.inclusive1 = inclusive1;
	}

	@Column(name = "INCLUSIVE2", nullable = false, precision = 22, scale = 0)
	public long getInclusive2() {
		return this.inclusive2;
	}

	public void setInclusive2(long inclusive2) {
		this.inclusive2 = inclusive2;
	}

	@Column(name = "INCLUSIVE3", nullable = false, precision = 22, scale = 0)
	public long getInclusive3() {
		return this.inclusive3;
	}

	public void setInclusive3(long inclusive3) {
		this.inclusive3 = inclusive3;
	}

	@Column(name = "INTERNAL", nullable = false, precision = 22, scale = 0)
	public long getInternal() {
		return this.internal;
	}

	public void setInternal(long internal) {
		this.internal = internal;
	}

	@Column(name = "TOTALTAX4", precision = 10)
	public long getTotaltax4() {
		return this.totaltax4;
	}

	public void setTotaltax4(long totaltax4) {
		this.totaltax4 = totaltax4;
	}

	@Column(name = "TOTALTAX5", precision = 10)
	public long getTotaltax5() {
		return this.totaltax5;
	}

	public void setTotaltax5(long totaltax5) {
		this.totaltax5 = totaltax5;
	}

	@Column(name = "INCLUSIVE4", nullable = false, precision = 22, scale = 0)
	public long getInclusive4() {
		return this.inclusive4;
	}

	public void setInclusive4(long inclusive4) {
		this.inclusive4 = inclusive4;
	}

	@Column(name = "INCLUSIVE5", nullable = false, precision = 22, scale = 0)
	public long getInclusive5() {
		return this.inclusive5;
	}

	public void setInclusive5(long inclusive5) {
		this.inclusive5 = inclusive5;
	}

	@Column(name = "PAYONRECEIPT", nullable = false, precision = 22, scale = 0)
	public long getPayonreceipt() {
		return this.payonreceipt;
	}

	public void setPayonreceipt(long payonreceipt) {
		this.payonreceipt = payonreceipt;
	}

	@Column(name = "EXCHANGERATE2", precision = 14, scale = 7)
	public long getExchangerate2() {
		return this.exchangerate2;
	}

	public void setExchangerate2(long exchangerate2) {
		this.exchangerate2 = exchangerate2;
	}

	@Column(name = "SOURCESYSID", length = 10)
	public String getSourcesysid() {
		return this.sourcesysid;
	}

	public void setSourcesysid(String sourcesysid) {
		this.sourcesysid = sourcesysid;
	}

	@Column(name = "OWNERSYSID", length = 10)
	public String getOwnersysid() {
		return this.ownersysid;
	}

	public void setOwnersysid(String ownersysid) {
		this.ownersysid = ownersysid;
	}

	@Column(name = "EXTERNALREFID", length = 10)
	public String getExternalrefid() {
		return this.externalrefid;
	}

	public void setExternalrefid(String externalrefid) {
		this.externalrefid = externalrefid;
	}

	@Column(name = "PRLA1", length = 10)
	public String getPrla1() {
		return this.prla1;
	}

	public void setPrla1(String prla1) {
		this.prla1 = prla1;
	}

	@Column(name = "PRLA2", length = 10)
	public String getPrla2() {
		return this.prla2;
	}

	public void setPrla2(String prla2) {
		this.prla2 = prla2;
	}

	@Column(name = "PRLA3", length = 10)
	public String getPrla3() {
		return this.prla3;
	}

	public void setPrla3(String prla3) {
		this.prla3 = prla3;
	}

	@Column(name = "PRLA4", length = 10)
	public String getPrla4() {
		return this.prla4;
	}

	public void setPrla4(String prla4) {
		this.prla4 = prla4;
	}

	@Column(name = "PRLA5", length = 10)
	public String getPrla5() {
		return this.prla5;
	}

	public void setPrla5(String prla5) {
		this.prla5 = prla5;
	}

	@Column(name = "PCARDNUM", length = 30)
	public String getPcardnum() {
		return this.pcardnum;
	}

	public void setPcardnum(String pcardnum) {
		this.pcardnum = pcardnum;
	}

	@Column(name = "PCARDTYPE", length = 20)
	public String getPcardtype() {
		return this.pcardtype;
	}

	public void setPcardtype(String pcardtype) {
		this.pcardtype = pcardtype;
	}

	@Column(name = "PCARDEXPDATE", length = 7)
	public String getPcardexpdate() {
		return this.pcardexpdate;
	}

	public void setPcardexpdate(String pcardexpdate) {
		this.pcardexpdate = pcardexpdate;
	}

	@Column(name = "SENDERSYSID", length = 50)
	public String getSendersysid() {
		return this.sendersysid;
	}

	public void setSendersysid(String sendersysid) {
		this.sendersysid = sendersysid;
	}

	@Column(name = "PCARDVERIFICATION", length = 4)
	public String getPcardverification() {
		return this.pcardverification;
	}

	public void setPcardverification(String pcardverification) {
		this.pcardverification = pcardverification;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "CONTRACTREFNUM", length = 8)
	public String getContractrefnum() {
		return this.contractrefnum;
	}

	public void setContractrefnum(String contractrefnum) {
		this.contractrefnum = contractrefnum;
	}

	@Column(name = "NOVENDOR", nullable = false, precision = 22, scale = 0)
	public long getNovendor() {
		return this.novendor;
	}

	public void setNovendor(long novendor) {
		this.novendor = novendor;
	}

	@Column(name = "CONTRACTREFID", precision = 22, scale = 0)
	public long getContractrefid() {
		return this.contractrefid;
	}

	public void setContractrefid(long contractrefid) {
		this.contractrefid = contractrefid;
	}

	@Column(name = "CONTRACTREFREV", precision = 22, scale = 0)
	public long getContractrefrev() {
		return this.contractrefrev;
	}

	public void setContractrefrev(long contractrefrev) {
		this.contractrefrev = contractrefrev;
	}

	@Column(name = "STORELOC", length = 16)
	public String getStoreloc() {
		return this.storeloc;
	}

	public void setStoreloc(String storeloc) {
		this.storeloc = storeloc;
	}

	@Column(name = "STORELOCSITEID", length = 8)
	public String getStorelocsiteid() {
		return this.storelocsiteid;
	}

	public void setStorelocsiteid(String storelocsiteid) {
		this.storelocsiteid = storelocsiteid;
	}

	@Column(name = "INSPECTIONREQUIRED", nullable = false, precision = 22, scale = 0)
	public long getInspectionrequired() {
		return this.inspectionrequired;
	}

	public void setInspectionrequired(long inspectionrequired) {
		this.inspectionrequired = inspectionrequired;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public long getHasld() {
		return this.hasld;
	}

	public void setHasld(long hasld) {
		this.hasld = hasld;
	}

	@Column(name = "M_DEPT", length = 48)
	public String getMDept() {
		return MDept;
	}

	public void setMDept(String mDept) {
		MDept = mDept;
	}


	@Column(name = "DEPTCODE", length = 48)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "DEPTSUPERVISOR", length = 30)
	public String getDeptsupervisor() {
		return this.deptsupervisor;
	}

	public void setDeptsupervisor(String deptsupervisor) {
		this.deptsupervisor = deptsupervisor;
	}

	@Column(name = "PRTYPE", length = 15)
	public String getPrtype() {
		return this.prtype;
	}

	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}

	@Column(name = "TOTALBASECOST2", precision = 25)
	public BigDecimal getTotalbasecost2() {
		return this.totalbasecost2;
	}

	public void setTotalbasecost2(BigDecimal totalbasecost2) {
		this.totalbasecost2 = totalbasecost2;
	}

	@Column(name = "DELETEMARK", nullable = false, precision = 22, scale = 0)
	public long getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(long deletemark) {
		this.deletemark = deletemark;
	}

	@Column(name = "COUNTERSIGN1", length = 30)
	public String getCountersign1() {
		return this.countersign1;
	}

	public void setCountersign1(String countersign1) {
		this.countersign1 = countersign1;
	}

	@Column(name = "COUNTERSIGN2", length = 30)
	public String getCountersign2() {
		return this.countersign2;
	}

	public void setCountersign2(String countersign2) {
		this.countersign2 = countersign2;
	}

	@Column(name = "CMOPRIORITY", length = 40)
	public String getCmopriority() {
		return this.cmopriority;
	}

	public void setCmopriority(String cmopriority) {
		this.cmopriority = cmopriority;
	}

	@Column(name = "REQUESTEDBY2", length = 30)
	public String getRequestedby2() {
		return this.requestedby2;
	}

	public void setRequestedby2(String requestedby2) {
		this.requestedby2 = requestedby2;
	}

	@Column(name = "TOTALCOST2", precision = 25)
	public BigDecimal getTotalcost2() {
		return this.totalcost2;
	}

	public void setTotalcost2(BigDecimal totalcost2) {
		this.totalcost2 = totalcost2;
	}

	@Column(name = "VENDORITEMTYPE", length = 20)
	public String getVendoritemtype() {
		return this.vendoritemtype;
	}

	public void setVendoritemtype(String vendoritemtype) {
		this.vendoritemtype = vendoritemtype;
	}

	@Column(name = "REASONCODE", length = 50)
	public String getReasoncode() {
		return this.reasoncode;
	}

	public void setReasoncode(String reasoncode) {
		this.reasoncode = reasoncode;
	}

	@Column(name = "OBDEPT", length = 12)
	public String getObdept() {
		return this.obdept;
	}

	public void setObdept(String obdept) {
		this.obdept = obdept;
	}

	@Column(name = "RSFLAG", nullable = false, precision = 22, scale = 0)
	public long getRsflag() {
		return this.rsflag;
	}

	public void setRsflag(long rsflag) {
		this.rsflag = rsflag;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "pr")
	public Set<Prline> getPrlines() {
		return this.prlines;
	}

	public void setPrlines(Set<Prline> prlines) {
		this.prlines = prlines;
	}
	
	@Column(name = "TASK_ID")
	public BigDecimal getTaskId() {
		return taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}
	@Column(name = "PRLINE_STATUS")
	public String getPrlineStatus() {
		return prlineStatus;
	}

	public void setPrlineStatus(String prlineStatus) {
		this.prlineStatus = prlineStatus;
	}
	
	@Column(name = "LAST_SIGNER")
	public String getLastSigner() {
		return lastSigner;
	}

	public void setLastSigner(String lastSigner) {
		this.lastSigner = lastSigner;
	}
	
	@Column(name = "TRANSFER_FLAG")
	public String getTransferFlag() {
		return transferFlag;
	}

	public void setTransferFlag(String transferFlag) {
		this.transferFlag = transferFlag;
	}
	@Column(name = "EXTRA_REMARK")
	public String getExtraRemark() {
		return extraRemark;
	}

	public void setExtraRemark(String extraRemark) {
		this.extraRemark = extraRemark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSFER_DATE", length = 7)
	public Date getTransferDate() {
		return transferDate;
	}

	public void setTransferDate(Date transferDate) {
		this.transferDate = transferDate;
	}
	@Column(name = "IGNORE_DEPT_FLAG")
	public String getIgnoreDeptFlag() {
		return ignoreDeptFlag;
	}

	public void setIgnoreDeptFlag(String ignoreDeptFlag) {
		this.ignoreDeptFlag = ignoreDeptFlag;
	}
}
