package mro.base.entity;

// Generated 2016/8/10 �W�� 10:23:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * PrControlConfig generated by hbm2java
 */
@Entity
@Table(name = "PR_CONTROL_CONFIG", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LOCATION_SITE", "COMMODITYGROUP" }))
public class PrControlConfig implements java.io.Serializable {

	private String id;
	private String locationSite;
	private String commoditygroup;
	private String highlightFlag;
	private Date lastUpdate;
	private String lastUpdateBy;
	private String controlType;
	private String sstockFlag;
	private int stockDays;

	public PrControlConfig() {
	}
	public PrControlConfig(String commoditygroup, String locationSite) {
		this.locationSite = locationSite;
		this.commoditygroup = commoditygroup;
	}
	
	public PrControlConfig(String id, String locationSite,
			String commoditygroup, String highlightFlag) {
		this.id = id;
		this.locationSite = locationSite;
		this.commoditygroup = commoditygroup;
		this.highlightFlag = highlightFlag;
	}

	public PrControlConfig(String id, String locationSite,
			String commoditygroup, String highlightFlag, Date lastUpdate,
			String lastUpdateBy,String controlType,String sstockFlag,int stockDays) {
		this.id = id;
		this.locationSite = locationSite;
		this.commoditygroup = commoditygroup;
		this.highlightFlag = highlightFlag;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.controlType = controlType;
		this.sstockFlag = sstockFlag;
		this.stockDays = stockDays;
	}

	@Id	
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "LOCATION_SITE", nullable = false, length = 50)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Column(name = "COMMODITYGROUP", nullable = false, length = 8)
	public String getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "HIGHLIGHT_FLAG", nullable = false, length = 1)
	public String getHighlightFlag() {
		return this.highlightFlag;
	}

	public void setHighlightFlag(String highlightFlag) {
		this.highlightFlag = highlightFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 20)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}
	
	@Column(name = "CONTROL_TYPE", length = 50)
	public String getControlType() {
		return controlType;
	}
	public void setControlType(String controlType) {
		this.controlType = controlType;
	}
	@Column(name = "SSTOCK_FLAG", length = 1)
	public String getSstockFlag() {
		return sstockFlag;
	}
	public void setSstockFlag(String sstockFlag) {
		this.sstockFlag = sstockFlag;
	}
	@Column(name = "STOCK_DAYS")
	public int getStockDays() {
		return stockDays;
	}
	public void setStockDays(int stockDays) {
		this.stockDays = stockDays;
	}

}
