package mro.base.entity;

// Generated 2013/2/25 �U�� 05:05:23 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import javax.persistence.Transient; 

import mro.base.System.config.SystemConfig;
import mro.base.System.config.basicType.SignStatus;

/**
 * Prline generated by hbm2java
 */
@Entity
@Table(name = "PRLINE", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "ITEMNUM", "PRNUM", "ERP_PRLINE",
				"DEPTCODE", "ISSTOCKOP" }),
		@UniqueConstraint(columnNames = { "SITEID", "PRLINEID" }) })
public class Prline implements java.io.Serializable,Comparable {

	private BigDecimal prlineid;
	private Pr pr;
	private String prnum;
	private String itemnum;
	private String storeloc;
	private long orderqty;
	private String orderunit;
	private BigDecimal unitcost;
	private String ponum;
	private Date reqdeliverydate;
	private Date vendeliverydate;
	private Date enterdate;
	private String enterby;
	private String description;
	private String rl1;
	private String rl2;
	private String rl3;
	private long rl4;
	private String rl5;
	private String requestedby;
	private long issue;
	private String rlin1;
	private String rlin2;
	private String rlin3;
	private Date rlin4;
	private long rlin5;
	private String assetnum;
	private long chargestore;
	private String gldebitacct;
	private String glcreditacct;
	private BigDecimal linecost;
	private String tax1code;
	private long tax1;
	private String tax2code;
	private long tax2;
	private String tax3code;
	private long tax3;
	private long receiptreqd;
	private String manufacturer;
	private String modelnum;
	private String catalogcode;
	private String tax4code;
	private long tax4;
	private String tax5code;
	private long tax5;
	private long prlinenum;
	private long polinenum;
	private String category;
	private String remark;
	private String location;
	private long loadedcost;
	private long prorateservice;
	private long converttorfq;
	private String rfqnum;
	private long rfqlinenum;
	private long inspectionrequired;
	private long rfqlineid;
	private long polineid;
	private BigDecimal linecost2;
	private String mrnum;
	private long mrlinenum;
	private String rl6;
	private String rl7;
	private String rl8;
	private String rl9;
	private String rl10;
	private String rlin6;
	private String rlin7;
	private String rlin8;
	private String rlin9;
	private String prlaln1;
	private String prlaln2;
	private String prlaln3;
	private String prlaln4;
	private String prlaln5;
	private String pcardnum;
	private String pcardtype;
	private String pcardexpdate;
	private String fincntrlid;
	private String pcardverification;
	private String vendorpackcode;
	private String vendorpackquantity;
	private String vendorwarehouse;
	private String siteid;
	private String orgid;
	private long isdistributed;
	private String refwo;
	private long enteredastask;
	private String linetype;
	private String itemsetid;
	private String conditioncode;
	private String contractnum;
	private long contractlinenum;
	private long contractlineid;
	private String contractrefnum;
	private String commoditygroup;
	private String commodity;
	private long converttocontract;
	private long contractrefid;
	private long contractrefrev;
	private long contractrev;
	private long scheduleid;
	private long contreflineid;
	private String langcode;
	private long conversion;
	private long contractid;
	private long hasld;
	private long mktplcitem;
	private String binnum;
	private BigDecimal minlevel;
	private BigDecimal sstock;
	private BigDecimal stdcost;
	private BigDecimal usefreq;
	private long approve;
	private String issueunit;
	private String classstructureid;
	private BigDecimal onhandqty;
	private String costtype;
	private long fixable;
	private String currencycode;
	private BigDecimal orisstock;
	private BigDecimal oriminlevel;
	private String storeroom;
	private String deptcode;
	private String MDept;
	private BigDecimal deliverytime;
	private String itemstatus;
	private BigDecimal newminlevel;
	private BigDecimal newsstock;
	private String prtype;
	private BigDecimal nextqty;
	private long lineCancelFlag;
	private String lineClosedCode;
	private Date erpprcreationdate;
	private String erpPrnum;
	private BigDecimal erpPrline;
	private String erpPo;
	private BigDecimal erpPoline;
	private String itemnum2;
	private String cmoremark;
	private String cmoitemname;
	private String itemnum3;
	private String requestedby2;
	private long stockflag;
	private String asset01;
	private String asset02;
	private String asset03;
	private String asset04;
	private String asset06;
	private String asset07;
	private String asset08;
	private String asset09;
	private String asset10;
	private String asset05;
	private long orivendoritemqty;
	private long orivendoritemssqty;
	private long vendoritemqty;
	private long vendoritemssqty;
	private long newvendoritemqty;
	private long newvendoritemssqty;
	private long vendoritemflag;
	private String itemnum4;
	private BigDecimal pmreqqty;
	private String itemnum5;
	private long isstockop;
	private String itemnum6;
	private String itemnum7;
	private String delivered;
	private long islidledays;
	private Date islinputdate;
	private String isllocation;
	private String mcsuggest;
	private String progress;
	private String purtracking;
	private String reorderstatus;
	private String buyer;
	private long isaltitem;
	private String itemnum8;
	private String itemnum9;
	private BigDecimal oriavguseqty;
	private BigDecimal davguseqty;
	private BigDecimal newavguseqty;
	private String reqmark1;
	private String reqmark2;
	private BigDecimal usecounter;
	private BigDecimal hdqty;
	private BigDecimal maxhdqty;
	private BigDecimal avghdqty;
	private BigDecimal sumofusecounter;
	private BigDecimal hdcost;
	private BigDecimal maxhdcost;
	private BigDecimal avghdcost;
	private String obdept;
	private BigDecimal orideliverytime;
	private BigDecimal oriunitcost;
	private String changeDeliverytimeRemark;
	private String changeUnitcostRemark;
	private String changeBy;
	private Date changeDate;
	private String closeRemark;
	private String combineRemark;
	//入貨廠
	private String combineInplant;
	//入貨日期
	private Date combineIndate;

	private String minBasicUnit;
	private String packageUnit;
	private BigDecimal transferQuantity;
	private BigDecimal mcOrderQuantity;
	private BigDecimal mcMinPackageQuantity;
	private BigDecimal halfyearIssueCounter;
	private BigDecimal maxidledays;
	private String mccommand;
	private String vendor;
	private BigDecimal invsstock;
	private BigDecimal epInterfaceId;
	private String erpPrStatus;
	private String erpPoStatus;
	private String erpPrBuyerEmpNo;
	private String erpPoBuyerEmpNo;
	private String noteToAgent;
	private String storeCategory;
	private String poVendorId;
	private Date poPromisedDate;
	private String inspectionEmpno;
	private String erpBuyerReturnNote;
	private String vendorRemark;
	private String eqId;
	private BigDecimal erpPrLineNum;
	private BigDecimal erpPoLineNum;
	private Date epmallCreateDate;
	private String inspectionDeptCode;
	private String epmallPrLineCancelFlag;
	private Date erpPrCancelDate;
	private BigDecimal sumofissuecounter;
	private String iepInterfaceId;
	private BigDecimal avghdqtyThree;
	private BigDecimal maxhdqtyThree;
	private BigDecimal multipleAvghdqtyThree;
	private BigDecimal avghdcostThree;
	private BigDecimal maxhdcostThree;
	private BigDecimal hdqtyThree;
	private BigDecimal hdcostThree;
	private String transferMsg;
	private String epNum;
	private String cmommcontrol;
	private String erpPrStatusDescription;
	
	
	
	public Prline() {
		
	}
	public Prline(Pr pr) {
		this.initial(pr);
	}
	public void initial(Pr pr){
		this.pr = pr;
		prnum=pr.getPrnum();
		siteid=pr.getSiteid();
		langcode=pr.getLangcode();
		deptcode = pr.getDeptcode();
		MDept=pr.getMDept();
		orgid=pr.getOrgid();
		prtype=pr.getPrtype();
		conversion=1;
		approve=1;
		isaltitem=1;
		orderqty=1;
		receiptreqd=1;
		linetype=SystemConfig.LINETYPE_ITEM;
		costtype=SystemConfig.COSTTYPE_F;
		lineClosedCode=SignStatus.OPEN.toString();
	}
	/*
	 * hongjie.wu
	 * 2015/05/21
	 * 依照prlinenum 排序
	 */
	@Override
	public int compareTo(Object o) {
        long compareage=((Prline)o).getPrlinenum();
		return (int) (this.prlinenum-compareage);
	}
	
	@Id
	@SequenceGenerator(name="PRLINEID_GENERATOR", sequenceName="PRLINESEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PRLINEID_GENERATOR")
	@Column(name = "PRLINEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrlineid() {
		return this.prlineid;
	}

	public void setPrlineid(BigDecimal prlineid) {
		this.prlineid = prlineid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRID")
	public Pr getPr() {
		return this.pr;
	}

	public void setPr(Pr pr) {
		this.pr = pr;
	}

	@Column(name = "PRNUM", nullable = false, length = 80)
	public String getPrnum() {
		return this.prnum;
	}

	public void setPrnum(String prnum) {
		this.prnum = prnum;
	}

	@Column(name = "ITEMNUM", length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "STORELOC", length = 16)
	public String getStoreloc() {
		return this.storeloc;
	}

	public void setStoreloc(String storeloc) {
		this.storeloc = storeloc;
	}

	@Column(name = "ORDERQTY", precision = 15)
	public long getOrderqty() {
		return this.orderqty;
	}

	public void setOrderqty(long orderqty) {
		this.orderqty = orderqty;
	}

	@Column(name = "ORDERUNIT", length = 50)
	public String getOrderunit() {
		return this.orderunit;
	}

	public void setOrderunit(String orderunit) {
		this.orderunit = orderunit;
	}

	@Column(name = "UNITCOST", precision = 25)
	public BigDecimal getUnitcost() {
		return this.unitcost;
	}

	public void setUnitcost(BigDecimal unitcost) {
		this.unitcost = unitcost;
	}

	@Column(name = "PONUM", length = 80)
	public String getPonum() {
		return this.ponum;
	}

	public void setPonum(String ponum) {
		this.ponum = ponum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQDELIVERYDATE", length = 7)
	public Date getReqdeliverydate() {
		return this.reqdeliverydate;
	}

	public void setReqdeliverydate(Date reqdeliverydate) {
		this.reqdeliverydate = reqdeliverydate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VENDELIVERYDATE", length = 7)
	public Date getVendeliverydate() {
		return this.vendeliverydate;
	}

	public void setVendeliverydate(Date vendeliverydate) {
		this.vendeliverydate = vendeliverydate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTERDATE", nullable = false, length = 7)
	public Date getEnterdate() {
		return this.enterdate;
	}

	public void setEnterdate(Date enterdate) {
		this.enterdate = enterdate;
	}

	@Column(name = "ENTERBY", nullable = false, length = 30)
	public String getEnterby() {
		return this.enterby;
	}

	public void setEnterby(String enterby) {
		this.enterby = enterby;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RL1", length = 10)
	public String getRl1() {
		return this.rl1;
	}

	public void setRl1(String rl1) {
		this.rl1 = rl1;
	}

	@Column(name = "RL2", length = 10)
	public String getRl2() {
		return this.rl2;
	}

	public void setRl2(String rl2) {
		this.rl2 = rl2;
	}

	@Column(name = "RL3", length = 10)
	public String getRl3() {
		return this.rl3;
	}

	public void setRl3(String rl3) {
		this.rl3 = rl3;
	}

	@Column(name = "RL4", precision = 15)
	public long getRl4() {
		return this.rl4;
	}

	public void setRl4(long rl4) {
		this.rl4 = rl4;
	}

	@Column(name = "RL5", length = 10)
	public String getRl5() {
		return this.rl5;
	}

	public void setRl5(String rl5) {
		this.rl5 = rl5;
	}

	@Column(name = "REQUESTEDBY", length = 30)
	public String getRequestedby() {
		return this.requestedby;
	}

	public void setRequestedby(String requestedby) {
		this.requestedby = requestedby;
	}

	@Column(name = "ISSUE", nullable = false, precision = 22, scale = 0)
	public long getIssue() {
		return this.issue;
	}

	public void setIssue(long issue) {
		this.issue = issue;
	}

	@Column(name = "RLIN1", length = 10)
	public String getRlin1() {
		return this.rlin1;
	}

	public void setRlin1(String rlin1) {
		this.rlin1 = rlin1;
	}

	@Column(name = "RLIN2", length = 10)
	public String getRlin2() {
		return this.rlin2;
	}

	public void setRlin2(String rlin2) {
		this.rlin2 = rlin2;
	}

	@Column(name = "RLIN3", length = 10)
	public String getRlin3() {
		return this.rlin3;
	}

	public void setRlin3(String rlin3) {
		this.rlin3 = rlin3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RLIN4", length = 7)
	public Date getRlin4() {
		return this.rlin4;
	}

	public void setRlin4(Date rlin4) {
		this.rlin4 = rlin4;
	}

	@Column(name = "RLIN5", precision = 15)
	public long getRlin5() {
		return this.rlin5;
	}

	public void setRlin5(long rlin5) {
		this.rlin5 = rlin5;
	}

	@Column(name = "ASSETNUM", length = 20)
	public String getAssetnum() {
		return this.assetnum;
	}

	public void setAssetnum(String assetnum) {
		this.assetnum = assetnum;
	}

	@Column(name = "CHARGESTORE", nullable = false, precision = 22, scale = 0)
	public long getChargestore() {
		return this.chargestore;
	}

	public void setChargestore(long chargestore) {
		this.chargestore = chargestore;
	}

	@Column(name = "GLDEBITACCT", length = 10)
	public String getGldebitacct() {
		return this.gldebitacct;
	}

	public void setGldebitacct(String gldebitacct) {
		this.gldebitacct = gldebitacct;
	}

	@Column(name = "GLCREDITACCT", length = 10)
	public String getGlcreditacct() {
		return this.glcreditacct;
	}

	public void setGlcreditacct(String glcreditacct) {
		this.glcreditacct = glcreditacct;
	}

	@Column(name = "LINECOST", nullable = false, precision = 25)
	public BigDecimal getLinecost() {
		return this.linecost;
	}

	public void setLinecost(BigDecimal linecost) {
		this.linecost = linecost;
	}

	@Column(name = "TAX1CODE", length = 8)
	public String getTax1code() {
		return this.tax1code;
	}

	public void setTax1code(String tax1code) {
		this.tax1code = tax1code;
	}

	@Column(name = "TAX1", nullable = false, precision = 10)
	public long getTax1() {
		return this.tax1;
	}

	public void setTax1(long tax1) {
		this.tax1 = tax1;
	}

	@Column(name = "TAX2CODE", length = 8)
	public String getTax2code() {
		return this.tax2code;
	}

	public void setTax2code(String tax2code) {
		this.tax2code = tax2code;
	}

	@Column(name = "TAX2", nullable = false, precision = 10)
	public long getTax2() {
		return this.tax2;
	}

	public void setTax2(long tax2) {
		this.tax2 = tax2;
	}

	@Column(name = "TAX3CODE", length = 8)
	public String getTax3code() {
		return this.tax3code;
	}

	public void setTax3code(String tax3code) {
		this.tax3code = tax3code;
	}

	@Column(name = "TAX3", nullable = false, precision = 10)
	public long getTax3() {
		return this.tax3;
	}

	public void setTax3(long tax3) {
		this.tax3 = tax3;
	}

	@Column(name = "RECEIPTREQD", nullable = false, precision = 22, scale = 0)
	public long getReceiptreqd() {
		return this.receiptreqd;
	}

	public void setReceiptreqd(long receiptreqd) {
		this.receiptreqd = receiptreqd;
	}

	@Column(name = "MANUFACTURER", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "MODELNUM", length = 50)
	public String getModelnum() {
		return this.modelnum;
	}

	public void setModelnum(String modelnum) {
		this.modelnum = modelnum;
	}

	@Column(name = "CATALOGCODE", length = 50)
	public String getCatalogcode() {
		return this.catalogcode;
	}

	public void setCatalogcode(String catalogcode) {
		this.catalogcode = catalogcode;
	}

	@Column(name = "TAX4CODE", length = 8)
	public String getTax4code() {
		return this.tax4code;
	}

	public void setTax4code(String tax4code) {
		this.tax4code = tax4code;
	}

	@Column(name = "TAX4", nullable = false, precision = 10)
	public long getTax4() {
		return this.tax4;
	}

	public void setTax4(long tax4) {
		this.tax4 = tax4;
	}

	@Column(name = "TAX5CODE", length = 8)
	public String getTax5code() {
		return this.tax5code;
	}

	public void setTax5code(String tax5code) {
		this.tax5code = tax5code;
	}

	@Column(name = "TAX5", nullable = false, precision = 10)
	public long getTax5() {
		return this.tax5;
	}

	public void setTax5(long tax5) {
		this.tax5 = tax5;
	}

	@Column(name = "PRLINENUM", nullable = false, precision = 22, scale = 0)
	public long getPrlinenum() {
		return this.prlinenum;
	}

	public void setPrlinenum(long prlinenum) {
		this.prlinenum = prlinenum;
	}

	@Column(name = "POLINENUM", precision = 22, scale = 0)
	public long getPolinenum() {
		return this.polinenum;
	}

	public void setPolinenum(long polinenum) {
		this.polinenum = polinenum;
	}

	@Column(name = "CATEGORY", length = 16)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LOCATION", length = 16)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "LOADEDCOST", nullable = false, precision = 25)
	public long getLoadedcost() {
		return this.loadedcost;
	}

	public void setLoadedcost(long loadedcost) {
		this.loadedcost = loadedcost;
	}

	@Column(name = "PRORATESERVICE", nullable = false, precision = 22, scale = 0)
	public long getProrateservice() {
		return this.prorateservice;
	}

	public void setProrateservice(long prorateservice) {
		this.prorateservice = prorateservice;
	}

	@Column(name = "CONVERTTORFQ", nullable = false, precision = 22, scale = 0)
	public long getConverttorfq() {
		return this.converttorfq;
	}

	public void setConverttorfq(long converttorfq) {
		this.converttorfq = converttorfq;
	}

	@Column(name = "RFQNUM", length = 8)
	public String getRfqnum() {
		return this.rfqnum;
	}

	public void setRfqnum(String rfqnum) {
		this.rfqnum = rfqnum;
	}

	@Column(name = "RFQLINENUM", precision = 22, scale = 0)
	public long getRfqlinenum() {
		return this.rfqlinenum;
	}

	public void setRfqlinenum(long rfqlinenum) {
		this.rfqlinenum = rfqlinenum;
	}

	@Column(name = "INSPECTIONREQUIRED", nullable = false, precision = 22, scale = 0)
	public long getInspectionrequired() {
		return this.inspectionrequired;
	}

	public void setInspectionrequired(long inspectionrequired) {
		this.inspectionrequired = inspectionrequired;
	}

	@Column(name = "RFQLINEID", precision = 22, scale = 0)
	public long getRfqlineid() {
		return this.rfqlineid;
	}

	public void setRfqlineid(long rfqlineid) {
		this.rfqlineid = rfqlineid;
	}

	@Column(name = "POLINEID", precision = 22, scale = 0)
	public long getPolineid() {
		return this.polineid;
	}

	public void setPolineid(long polineid) {
		this.polineid = polineid;
	}

	@Column(name = "LINECOST2", precision = 25)
	public BigDecimal getLinecost2() {
		return this.linecost2;
	}

	public void setLinecost2(BigDecimal linecost2) {
		this.linecost2 = linecost2;
	}

	@Column(name = "MRNUM", length = 8)
	public String getMrnum() {
		return this.mrnum;
	}

	public void setMrnum(String mrnum) {
		this.mrnum = mrnum;
	}

	@Column(name = "MRLINENUM", precision = 22, scale = 0)
	public long getMrlinenum() {
		return this.mrlinenum;
	}

	public void setMrlinenum(long mrlinenum) {
		this.mrlinenum = mrlinenum;
	}

	@Column(name = "RL6", length = 10)
	public String getRl6() {
		return this.rl6;
	}

	public void setRl6(String rl6) {
		this.rl6 = rl6;
	}

	@Column(name = "RL7", length = 10)
	public String getRl7() {
		return this.rl7;
	}

	public void setRl7(String rl7) {
		this.rl7 = rl7;
	}

	@Column(name = "RL8", length = 10)
	public String getRl8() {
		return this.rl8;
	}

	public void setRl8(String rl8) {
		this.rl8 = rl8;
	}

	@Column(name = "RL9", length = 10)
	public String getRl9() {
		return this.rl9;
	}

	public void setRl9(String rl9) {
		this.rl9 = rl9;
	}

	@Column(name = "RL10", length = 10)
	public String getRl10() {
		return this.rl10;
	}

	public void setRl10(String rl10) {
		this.rl10 = rl10;
	}

	@Column(name = "RLIN6", length = 10)
	public String getRlin6() {
		return this.rlin6;
	}

	public void setRlin6(String rlin6) {
		this.rlin6 = rlin6;
	}

	@Column(name = "RLIN7", length = 10)
	public String getRlin7() {
		return this.rlin7;
	}

	public void setRlin7(String rlin7) {
		this.rlin7 = rlin7;
	}

	@Column(name = "RLIN8", length = 10)
	public String getRlin8() {
		return this.rlin8;
	}

	public void setRlin8(String rlin8) {
		this.rlin8 = rlin8;
	}

	@Column(name = "RLIN9", length = 10)
	public String getRlin9() {
		return this.rlin9;
	}

	public void setRlin9(String rlin9) {
		this.rlin9 = rlin9;
	}

	@Column(name = "PRLALN1", length = 10)
	public String getPrlaln1() {
		return this.prlaln1;
	}

	public void setPrlaln1(String prlaln1) {
		this.prlaln1 = prlaln1;
	}

	@Column(name = "PRLALN2", length = 10)
	public String getPrlaln2() {
		return this.prlaln2;
	}

	public void setPrlaln2(String prlaln2) {
		this.prlaln2 = prlaln2;
	}

	@Column(name = "PRLALN3", length = 10)
	public String getPrlaln3() {
		return this.prlaln3;
	}

	public void setPrlaln3(String prlaln3) {
		this.prlaln3 = prlaln3;
	}

	@Column(name = "PRLALN4", length = 10)
	public String getPrlaln4() {
		return this.prlaln4;
	}

	public void setPrlaln4(String prlaln4) {
		this.prlaln4 = prlaln4;
	}

	@Column(name = "PRLALN5", length = 10)
	public String getPrlaln5() {
		return this.prlaln5;
	}

	public void setPrlaln5(String prlaln5) {
		this.prlaln5 = prlaln5;
	}

	@Column(name = "PCARDNUM", length = 30)
	public String getPcardnum() {
		return this.pcardnum;
	}

	public void setPcardnum(String pcardnum) {
		this.pcardnum = pcardnum;
	}

	@Column(name = "PCARDTYPE", length = 20)
	public String getPcardtype() {
		return this.pcardtype;
	}

	public void setPcardtype(String pcardtype) {
		this.pcardtype = pcardtype;
	}

	@Column(name = "PCARDEXPDATE", length = 7)
	public String getPcardexpdate() {
		return this.pcardexpdate;
	}

	public void setPcardexpdate(String pcardexpdate) {
		this.pcardexpdate = pcardexpdate;
	}

	@Column(name = "FINCNTRLID", length = 8)
	public String getFincntrlid() {
		return this.fincntrlid;
	}

	public void setFincntrlid(String fincntrlid) {
		this.fincntrlid = fincntrlid;
	}

	@Column(name = "PCARDVERIFICATION", length = 4)
	public String getPcardverification() {
		return this.pcardverification;
	}

	public void setPcardverification(String pcardverification) {
		this.pcardverification = pcardverification;
	}

	@Column(name = "VENDORPACKCODE", length = 12)
	public String getVendorpackcode() {
		return this.vendorpackcode;
	}

	public void setVendorpackcode(String vendorpackcode) {
		this.vendorpackcode = vendorpackcode;
	}

	@Column(name = "VENDORPACKQUANTITY", length = 12)
	public String getVendorpackquantity() {
		return this.vendorpackquantity;
	}

	public void setVendorpackquantity(String vendorpackquantity) {
		this.vendorpackquantity = vendorpackquantity;
	}

	@Column(name = "VENDORWAREHOUSE", length = 12)
	public String getVendorwarehouse() {
		return this.vendorwarehouse;
	}

	public void setVendorwarehouse(String vendorwarehouse) {
		this.vendorwarehouse = vendorwarehouse;
	}

	@Column(name = "SITEID", nullable = false, length = 8)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "ORGID", nullable = false, length = 8)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ISDISTRIBUTED", nullable = false, precision = 22, scale = 0)
	public long getIsdistributed() {
		return this.isdistributed;
	}

	public void setIsdistributed(long isdistributed) {
		this.isdistributed = isdistributed;
	}

	@Column(name = "REFWO", length = 10)
	public String getRefwo() {
		return this.refwo;
	}

	public void setRefwo(String refwo) {
		this.refwo = refwo;
	}

	@Column(name = "ENTEREDASTASK", nullable = false, precision = 22, scale = 0)
	public long getEnteredastask() {
		return this.enteredastask;
	}

	public void setEnteredastask(long enteredastask) {
		this.enteredastask = enteredastask;
	}

	@Column(name = "LINETYPE", nullable = false, length = 15)
	public String getLinetype() {
		return this.linetype;
	}

	public void setLinetype(String linetype) {
		this.linetype = linetype;
	}

	@Column(name = "ITEMSETID", length = 8)
	public String getItemsetid() {
		return this.itemsetid;
	}

	public void setItemsetid(String itemsetid) {
		this.itemsetid = itemsetid;
	}

	@Column(name = "CONDITIONCODE", length = 30)
	public String getConditioncode() {
		return this.conditioncode;
	}

	public void setConditioncode(String conditioncode) {
		this.conditioncode = conditioncode;
	}

	@Column(name = "CONTRACTNUM", length = 8)
	public String getContractnum() {
		return this.contractnum;
	}

	public void setContractnum(String contractnum) {
		this.contractnum = contractnum;
	}

	@Column(name = "CONTRACTLINENUM", precision = 22, scale = 0)
	public long getContractlinenum() {
		return this.contractlinenum;
	}

	public void setContractlinenum(long contractlinenum) {
		this.contractlinenum = contractlinenum;
	}

	@Column(name = "CONTRACTLINEID", precision = 22, scale = 0)
	public long getContractlineid() {
		return this.contractlineid;
	}

	public void setContractlineid(long contractlineid) {
		this.contractlineid = contractlineid;
	}

	@Column(name = "CONTRACTREFNUM", length = 8)
	public String getContractrefnum() {
		return this.contractrefnum;
	}

	public void setContractrefnum(String contractrefnum) {
		this.contractrefnum = contractrefnum;
	}

	@Column(name = "COMMODITYGROUP", length = 8)
	public String getCommoditygroup() {
		return this.commoditygroup;
	}

	public void setCommoditygroup(String commoditygroup) {
		this.commoditygroup = commoditygroup;
	}

	@Column(name = "COMMODITY", length = 8)
	public String getCommodity() {
		return this.commodity;
	}

	public void setCommodity(String commodity) {
		this.commodity = commodity;
	}

	@Column(name = "CONVERTTOCONTRACT", nullable = false, precision = 22, scale = 0)
	public long getConverttocontract() {
		return this.converttocontract;
	}

	public void setConverttocontract(long converttocontract) {
		this.converttocontract = converttocontract;
	}

	@Column(name = "CONTRACTREFID", precision = 22, scale = 0)
	public long getContractrefid() {
		return this.contractrefid;
	}

	public void setContractrefid(long contractrefid) {
		this.contractrefid = contractrefid;
	}

	@Column(name = "CONTRACTREFREV", precision = 22, scale = 0)
	public long getContractrefrev() {
		return this.contractrefrev;
	}

	public void setContractrefrev(long contractrefrev) {
		this.contractrefrev = contractrefrev;
	}

	@Column(name = "CONTRACTREV", precision = 22, scale = 0)
	public long getContractrev() {
		return this.contractrev;
	}

	public void setContractrev(long contractrev) {
		this.contractrev = contractrev;
	}

	@Column(name = "SCHEDULEID", precision = 22, scale = 0)
	public long getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(long scheduleid) {
		this.scheduleid = scheduleid;
	}

	@Column(name = "CONTREFLINEID", precision = 22, scale = 0)
	public long getContreflineid() {
		return this.contreflineid;
	}

	public void setContreflineid(long contreflineid) {
		this.contreflineid = contreflineid;
	}

	@Column(name = "LANGCODE", nullable = false, length = 4)
	public String getLangcode() {
		return this.langcode;
	}

	public void setLangcode(String langcode) {
		this.langcode = langcode;
	}

	@Column(name = "CONVERSION", nullable = false, precision = 15)
	public long getConversion() {
		return this.conversion;
	}

	public void setConversion(long conversion) {
		this.conversion = conversion;
	}

	@Column(name = "CONTRACTID", precision = 22, scale = 0)
	public long getContractid() {
		return this.contractid;
	}

	public void setContractid(long contractid) {
		this.contractid = contractid;
	}

	@Column(name = "HASLD", nullable = false, precision = 22, scale = 0)
	public long getHasld() {
		return this.hasld;
	}

	public void setHasld(long hasld) {
		this.hasld = hasld;
	}

	@Column(name = "MKTPLCITEM", nullable = false, precision = 22, scale = 0)
	public long getMktplcitem() {
		return this.mktplcitem;
	}

	public void setMktplcitem(long mktplcitem) {
		this.mktplcitem = mktplcitem;
	}

	@Column(name = "BINNUM", length = 30)
	public String getBinnum() {
		return this.binnum;
	}

	public void setBinnum(String binnum) {
		this.binnum = binnum;
	}

	@Column(name = "MINLEVEL", precision = 15)
	public BigDecimal getMinlevel() {
		return this.minlevel;
	}

	public void setMinlevel(BigDecimal minlevel) {
		this.minlevel = minlevel;
	}

	@Column(name = "SSTOCK", precision = 15)
	public BigDecimal getSstock() {
		return this.sstock;
	}

	public void setSstock(BigDecimal sstock) {
		this.sstock = sstock;
	}

	@Column(name = "STDCOST", precision = 15)
	public BigDecimal getStdcost() {
		return this.stdcost;
	}

	public void setStdcost(BigDecimal stdcost) {
		this.stdcost = stdcost;
	}

	@Column(name = "USEFREQ", precision = 22, scale = 0)
	public BigDecimal getUsefreq() {
		return this.usefreq;
	}

	public void setUsefreq(BigDecimal usefreq) {
		this.usefreq = usefreq;
	}

	@Column(name = "APPROVE", nullable = false, precision = 22, scale = 0)
	public long getApprove() {
		return this.approve;
	}

	public void setApprove(long approve) {
		this.approve = approve;
	}

	@Column(name = "ISSUEUNIT", length = 50)
	public String getIssueunit() {
		return this.issueunit;
	}

	public void setIssueunit(String issueunit) {
		this.issueunit = issueunit;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 26)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "ONHANDQTY", precision = 15)
	public BigDecimal getOnhandqty() {
		return this.onhandqty;
	}

	public void setOnhandqty(BigDecimal onhandqty) {
		this.onhandqty = onhandqty;
	}

	@Column(name = "COSTTYPE", length = 80)
	public String getCosttype() {
		return this.costtype;
	}

	public void setCosttype(String costtype) {
		this.costtype = costtype;
	}

	@Column(name = "FIXABLE", nullable = false, precision = 22, scale = 0)
	public long getFixable() {
		return this.fixable;
	}

	public void setFixable(long fixable) {
		this.fixable = fixable;
	}

	@Column(name = "CURRENCYCODE", length = 8)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "ORISSTOCK", precision = 15)
	public BigDecimal getOrisstock() {
		return this.orisstock;
	}

	public void setOrisstock(BigDecimal orisstock) {
		this.orisstock = orisstock;
	}

	@Column(name = "ORIMINLEVEL", precision = 15)
	public BigDecimal getOriminlevel() {
		return this.oriminlevel;
	}

	public void setOriminlevel(BigDecimal oriminlevel) {
		this.oriminlevel = oriminlevel;
	}

	@Column(name = "STOREROOM", length = 16)
	public String getStoreroom() {
		return this.storeroom;
	}

	public void setStoreroom(String storeroom) {
		this.storeroom = storeroom;
	}

	@Column(name = "DEPTCODE", length = 48)
	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Column(name = "M_DEPT", length = 48)
	public String getMDept() {
		return MDept;
	}

	public void setMDept(String mDept) {
		MDept = mDept;
	}

	@Column(name = "DELIVERYTIME", precision = 22, scale = 0)
	public BigDecimal getDeliverytime() {
		return this.deliverytime;
	}

	public void setDeliverytime(BigDecimal deliverytime) {
		this.deliverytime = deliverytime;
	}

	@Column(name = "ITEMSTATUS", length = 15)
	public String getItemstatus() {
		return this.itemstatus;
	}

	public void setItemstatus(String itemstatus) {
		this.itemstatus = itemstatus;
	}

	@Column(name = "NEWMINLEVEL", precision = 15)
	public BigDecimal getNewminlevel() {
		return this.newminlevel;
	}

	public void setNewminlevel(BigDecimal newminlevel) {
		this.newminlevel = newminlevel;
	}

	@Column(name = "NEWSSTOCK", precision = 15)
	public BigDecimal getNewsstock() {
		return this.newsstock;
	}

	public void setNewsstock(BigDecimal newsstock) {
		this.newsstock = newsstock;
	}

	@Column(name = "PRTYPE", length = 15)
	public String getPrtype() {
		return this.prtype;
	}

	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}

	@Column(name = "NEXTQTY", precision = 16)
	public BigDecimal getNextqty() {
		return this.nextqty;
	}

	public void setNextqty(BigDecimal nextqty) {
		this.nextqty = nextqty;
	}

	@Column(name = "LINE_CANCEL_FLAG", nullable = false, precision = 22, scale = 0)
	public long getLineCancelFlag() {
		return this.lineCancelFlag;
	}

	public void setLineCancelFlag(long lineCancelFlag) {
		this.lineCancelFlag = lineCancelFlag;
	}

	@Column(name = "LINE_CLOSED_CODE", length = 25)
	public String getLineClosedCode() {
		return this.lineClosedCode;
	}

	public void setLineClosedCode(String lineClosedCode) {
		this.lineClosedCode = lineClosedCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERPPRCREATIONDATE", length = 7)
	public Date getErpprcreationdate() {
		return this.erpprcreationdate;
	}

	public void setErpprcreationdate(Date erpprcreationdate) {
		this.erpprcreationdate = erpprcreationdate;
	}

	@Column(name = "ERP_PRNUM", length = 20)
	public String getErpPrnum() {
		return this.erpPrnum;
	}

	public void setErpPrnum(String erpPrnum) {
		this.erpPrnum = erpPrnum;
	}

	@Column(name = "ERP_PRLINE", precision = 22, scale = 0)
	public BigDecimal getErpPrline() {
		return this.erpPrline;
	}

	public void setErpPrline(BigDecimal erpPrline) {
		this.erpPrline = erpPrline;
	}

	@Column(name = "ERP_PO", length = 20)
	public String getErpPo() {
		return this.erpPo;
	}

	public void setErpPo(String erpPo) {
		this.erpPo = erpPo;
	}

	@Column(name = "ERP_POLINE", precision = 22, scale = 0)
	public BigDecimal getErpPoline() {
		return this.erpPoline;
	}

	public void setErpPoline(BigDecimal erpPoline) {
		this.erpPoline = erpPoline;
	}

	@Column(name = "ITEMNUM2", length = 120)
	public String getItemnum2() {
		return this.itemnum2;
	}

	public void setItemnum2(String itemnum2) {
		this.itemnum2 = itemnum2;
	}

	@Column(name = "CMOREMARK", length = 1000)
	public String getCmoremark() {
		return this.cmoremark;
	}

	public void setCmoremark(String cmoremark) {
		this.cmoremark = cmoremark;
	}

	@Column(name = "CMOITEMNAME", length = 1000)
	public String getCmoitemname() {
		return this.cmoitemname;
	}

	public void setCmoitemname(String cmoitemname) {
		this.cmoitemname = cmoitemname;
	}

	@Column(name = "ITEMNUM3", length = 120)
	public String getItemnum3() {
		return this.itemnum3;
	}

	public void setItemnum3(String itemnum3) {
		this.itemnum3 = itemnum3;
	}

	@Column(name = "REQUESTEDBY2", length = 30)
	public String getRequestedby2() {
		return this.requestedby2;
	}

	public void setRequestedby2(String requestedby2) {
		this.requestedby2 = requestedby2;
	}

	@Column(name = "STOCKFLAG", nullable = false, precision = 22, scale = 0)
	public long getStockflag() {
		return this.stockflag;
	}

	public void setStockflag(long stockflag) {
		this.stockflag = stockflag;
	}

	@Column(name = "ASSET01", length = 20)
	public String getAsset01() {
		return this.asset01;
	}

	public void setAsset01(String asset01) {
		this.asset01 = asset01;
	}

	@Column(name = "ASSET02", length = 20)
	public String getAsset02() {
		return this.asset02;
	}

	public void setAsset02(String asset02) {
		this.asset02 = asset02;
	}

	@Column(name = "ASSET03", length = 20)
	public String getAsset03() {
		return this.asset03;
	}

	public void setAsset03(String asset03) {
		this.asset03 = asset03;
	}

	@Column(name = "ASSET04", length = 20)
	public String getAsset04() {
		return this.asset04;
	}

	public void setAsset04(String asset04) {
		this.asset04 = asset04;
	}

	@Column(name = "ASSET06", length = 20)
	public String getAsset06() {
		return this.asset06;
	}

	public void setAsset06(String asset06) {
		this.asset06 = asset06;
	}

	@Column(name = "ASSET07", length = 20)
	public String getAsset07() {
		return this.asset07;
	}

	public void setAsset07(String asset07) {
		this.asset07 = asset07;
	}

	@Column(name = "ASSET08", length = 20)
	public String getAsset08() {
		return this.asset08;
	}

	public void setAsset08(String asset08) {
		this.asset08 = asset08;
	}

	@Column(name = "ASSET09", length = 20)
	public String getAsset09() {
		return this.asset09;
	}

	public void setAsset09(String asset09) {
		this.asset09 = asset09;
	}

	@Column(name = "ASSET10", length = 20)
	public String getAsset10() {
		return this.asset10;
	}

	public void setAsset10(String asset10) {
		this.asset10 = asset10;
	}

	@Column(name = "ASSET05", length = 20)
	public String getAsset05() {
		return this.asset05;
	}

	public void setAsset05(String asset05) {
		this.asset05 = asset05;
	}

	@Column(name = "ORIVENDORITEMQTY", precision = 16)
	public long getOrivendoritemqty() {
		return this.orivendoritemqty;
	}

	public void setOrivendoritemqty(long orivendoritemqty) {
		this.orivendoritemqty = orivendoritemqty;
	}

	@Column(name = "ORIVENDORITEMSSQTY", precision = 16)
	public long getOrivendoritemssqty() {
		return this.orivendoritemssqty;
	}

	public void setOrivendoritemssqty(long orivendoritemssqty) {
		this.orivendoritemssqty = orivendoritemssqty;
	}

	@Column(name = "VENDORITEMQTY", precision = 16)
	public long getVendoritemqty() {
		return this.vendoritemqty;
	}

	public void setVendoritemqty(long vendoritemqty) {
		this.vendoritemqty = vendoritemqty;
	}

	@Column(name = "VENDORITEMSSQTY", precision = 16)
	public long getVendoritemssqty() {
		return this.vendoritemssqty;
	}

	public void setVendoritemssqty(long vendoritemssqty) {
		this.vendoritemssqty = vendoritemssqty;
	}

	@Column(name = "NEWVENDORITEMQTY", precision = 16)
	public long getNewvendoritemqty() {
		return this.newvendoritemqty;
	}

	public void setNewvendoritemqty(long newvendoritemqty) {
		this.newvendoritemqty = newvendoritemqty;
	}

	@Column(name = "NEWVENDORITEMSSQTY", precision = 16)
	public long getNewvendoritemssqty() {
		return this.newvendoritemssqty;
	}

	public void setNewvendoritemssqty(long newvendoritemssqty) {
		this.newvendoritemssqty = newvendoritemssqty;
	}

	@Column(name = "VENDORITEMFLAG", nullable = false, precision = 22, scale = 0)
	public long getVendoritemflag() {
		return this.vendoritemflag;
	}

	public void setVendoritemflag(long vendoritemflag) {
		this.vendoritemflag = vendoritemflag;
	}

	@Column(name = "ITEMNUM4", length = 30)
	public String getItemnum4() {
		return this.itemnum4;
	}

	public void setItemnum4(String itemnum4) {
		this.itemnum4 = itemnum4;
	}

	@Column(name = "PMREQQTY", precision = 16)
	public BigDecimal getPmreqqty() {
		return this.pmreqqty;
	}

	public void setPmreqqty(BigDecimal pmreqqty) {
		this.pmreqqty = pmreqqty;
	}

	@Column(name = "ITEMNUM5", length = 30)
	public String getItemnum5() {
		return this.itemnum5;
	}

	public void setItemnum5(String itemnum5) {
		this.itemnum5 = itemnum5;
	}

	@Column(name = "ISSTOCKOP", nullable = false, precision = 22, scale = 0)
	public long getIsstockop() {
		return this.isstockop;
	}

	public void setIsstockop(long isstockop) {
		this.isstockop = isstockop;
	}

	@Column(name = "ITEMNUM6", length = 30)
	public String getItemnum6() {
		return this.itemnum6;
	}

	public void setItemnum6(String itemnum6) {
		this.itemnum6 = itemnum6;
	}

	@Column(name = "ITEMNUM7", length = 30)
	public String getItemnum7() {
		return this.itemnum7;
	}

	public void setItemnum7(String itemnum7) {
		this.itemnum7 = itemnum7;
	}

	@Column(name = "DELIVERED", length = 50)
	public String getDelivered() {
		return this.delivered;
	}

	public void setDelivered(String delivered) {
		this.delivered = delivered;
	}

	@Column(name = "ISLIDLEDAYS", precision = 16)
	public long getIslidledays() {
		return this.islidledays;
	}

	public void setIslidledays(long islidledays) {
		this.islidledays = islidledays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ISLINPUTDATE", length = 7)
	public Date getIslinputdate() {
		return this.islinputdate;
	}

	public void setIslinputdate(Date islinputdate) {
		this.islinputdate = islinputdate;
	}

	@Column(name = "ISLLOCATION", length = 16)
	public String getIsllocation() {
		return this.isllocation;
	}

	public void setIsllocation(String isllocation) {
		this.isllocation = isllocation;
	}

	@Column(name = "MCSUGGEST", length = 50)
	public String getMcsuggest() {
		return this.mcsuggest;
	}

	public void setMcsuggest(String mcsuggest) {
		this.mcsuggest = mcsuggest;
	}

	@Column(name = "PROGRESS", length = 50)
	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	@Column(name = "PURTRACKING", length = 50)
	public String getPurtracking() {
		return this.purtracking;
	}

	public void setPurtracking(String purtracking) {
		this.purtracking = purtracking;
	}

	@Column(name = "REORDERSTATUS", length = 50)
	public String getReorderstatus() {
		return this.reorderstatus;
	}

	public void setReorderstatus(String reorderstatus) {
		this.reorderstatus = reorderstatus;
	}

	@Column(name = "BUYER", length = 50)
	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "ISALTITEM", nullable = false, precision = 22, scale = 0)
	public long getIsaltitem() {
		return this.isaltitem;
	}

	public void setIsaltitem(long isaltitem) {
		this.isaltitem = isaltitem;
	}

	@Column(name = "ITEMNUM8", length = 30)
	public String getItemnum8() {
		return this.itemnum8;
	}

	public void setItemnum8(String itemnum8) {
		this.itemnum8 = itemnum8;
	}

	@Column(name = "ITEMNUM9", length = 30)
	public String getItemnum9() {
		return this.itemnum9;
	}

	public void setItemnum9(String itemnum9) {
		this.itemnum9 = itemnum9;
	}

	@Column(name = "ORIAVGUSEQTY", precision = 15)
	public BigDecimal getOriavguseqty() {
		return this.oriavguseqty;
	}

	public void setOriavguseqty(BigDecimal oriavguseqty) {
		this.oriavguseqty = oriavguseqty;
	}

	@Column(name = "DAVGUSEQTY", precision = 15)
	public BigDecimal getDavguseqty() {
		return this.davguseqty;
	}

	public void setDavguseqty(BigDecimal davguseqty) {
		this.davguseqty = davguseqty;
	}

	@Column(name = "NEWAVGUSEQTY", precision = 15)
	public BigDecimal getNewavguseqty() {
		return this.newavguseqty;
	}

	public void setNewavguseqty(BigDecimal newavguseqty) {
		this.newavguseqty = newavguseqty;
	}

	@Column(name = "REQMARK1", length = 250)
	public String getReqmark1() {
		return this.reqmark1;
	}

	public void setReqmark1(String reqmark1) {
		this.reqmark1 = reqmark1;
	}

	@Column(name = "REQMARK2", length = 250)
	public String getReqmark2() {
		return this.reqmark2;
	}

	public void setReqmark2(String reqmark2) {
		this.reqmark2 = reqmark2;
	}

	@Column(name = "USECOUNTER", precision = 22, scale = 0)
	public BigDecimal getUsecounter() {
		return this.usecounter;
	}

	public void setUsecounter(BigDecimal usecounter) {
		this.usecounter = usecounter;
	}

	@Column(name = "HDQTY", precision = 15)
	public BigDecimal getHdqty() {
		return this.hdqty;
	}

	public void setHdqty(BigDecimal hdqty) {
		this.hdqty = hdqty;
	}

	@Column(name = "MAXHDQTY", precision = 15)
	public BigDecimal getMaxhdqty() {
		return this.maxhdqty;
	}

	public void setMaxhdqty(BigDecimal maxhdqty) {
		this.maxhdqty = maxhdqty;
	}

	@Column(name = "AVGHDQTY", precision = 15)
	public BigDecimal getAvghdqty() {
		return this.avghdqty;
	}

	public void setAvghdqty(BigDecimal avghdqty) {
		this.avghdqty = avghdqty;
	}

	@Column(name = "SUMOFUSECOUNTER", precision = 22, scale = 0)
	public BigDecimal getSumofusecounter() {
		return this.sumofusecounter;
	}

	public void setSumofusecounter(BigDecimal sumofusecounter) {
		this.sumofusecounter = sumofusecounter;
	}

	@Column(name = "HDCOST", precision = 15)
	public BigDecimal getHdcost() {
		return this.hdcost;
	}

	public void setHdcost(BigDecimal hdcost) {
		this.hdcost = hdcost;
	}

	@Column(name = "MAXHDCOST", precision = 15)
	public BigDecimal getMaxhdcost() {
		return this.maxhdcost;
	}

	public void setMaxhdcost(BigDecimal maxhdcost) {
		this.maxhdcost = maxhdcost;
	}

	@Column(name = "AVGHDCOST", precision = 15)
	public BigDecimal getAvghdcost() {
		return this.avghdcost;
	}

	public void setAvghdcost(BigDecimal avghdcost) {
		this.avghdcost = avghdcost;
	}

	@Column(name = "OBDEPT", length = 12)
	public String getObdept() {
		return this.obdept;
	}

	public void setObdept(String obdept) {
		this.obdept = obdept;
	}

	@Column(name = "ORIDELIVERYTIME", precision = 22, scale = 0)
	public BigDecimal getOrideliverytime() {
		return this.orideliverytime;
	}

	public void setOrideliverytime(BigDecimal orideliverytime) {
		this.orideliverytime = orideliverytime;
	}

	@Column(name = "ORIUNITCOST", precision = 22, scale = 0)
	public BigDecimal getOriunitcost() {
		return this.oriunitcost;
	}

	public void setOriunitcost(BigDecimal oriunitcost) {
		this.oriunitcost = oriunitcost;
	}
	@Column(name = "CHANGE_DELIVERYTIME_REMARK", length = 100)
	public String getChangeDeliverytimeRemark() {
		return changeDeliverytimeRemark;
	}

	public void setChangeDeliverytimeRemark(String changeDeliverytimeRemark) {
		this.changeDeliverytimeRemark = changeDeliverytimeRemark;
	}
	@Column(name = "CHANGE_UNITCOST_REMARK", length = 100)
	public String getChangeUnitcostRemark() {
		return changeUnitcostRemark;
	}

	public void setChangeUnitcostRemark(String changeUnitcostRemark) {
		this.changeUnitcostRemark = changeUnitcostRemark;
	}
	
	@Column(name = "CHANGE_BY", length = 30)
	public String getChangeBy() {
		return changeBy;
	}

	public void setChangeBy(String changeBy) {
		this.changeBy = changeBy;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGE_DATE", length = 7)
	public Date getChangeDate() {
		return changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
	@Column(name = "MIN_BASIC_UNIT", length = 30)
	public String getMinBasicUnit() {
		return this.minBasicUnit;
	}

	public void setMinBasicUnit(String minBasicUnit) {
		this.minBasicUnit = minBasicUnit;
	}

	@Column(name = "PACKAGE_UNIT", length = 30)
	public String getPackageUnit() {
		return this.packageUnit;
	}

	public void setPackageUnit(String packageUnit) {
		this.packageUnit = packageUnit;
	}

	@Column(name = "TRANSFER_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getTransferQuantity() {
		return this.transferQuantity;
	}

	public void setTransferQuantity(BigDecimal transferQuantity) {
		this.transferQuantity = transferQuantity;
	}
	
	@Column(name = "CLOSE_REMARK", length = 30)
	public String getCloseRemark() {
		return closeRemark;
	}

	public void setCloseRemark(String closeRemark) {
		this.closeRemark = closeRemark;
	}
	
	@Column(name = "COMBINE_REMARK", length = 30)
	public String getCombineRemark() {
		return combineRemark;
	}

	public void setCombineRemark(String combineRemark) {
		this.combineRemark = combineRemark;
	}
	@Column(name = "COMBINE_INPLANT", length = 30)
	public String getCombineInplant() {
		return combineInplant;
	}

	public void setCombineInplant(String combineInplant) {
		this.combineInplant = combineInplant;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMBINE_INDATE", length = 7)
	public Date getCombineIndate() {
		return combineIndate;
	}

	public void setCombineIndate(Date combineIndate) {
		this.combineIndate = combineIndate;
	}
	@Column(name = "MC_ORDER_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getMcOrderQuantity() {
		return this.mcOrderQuantity;
	}

	public void setMcOrderQuantity(BigDecimal mcOrderQuantity) {
		this.mcOrderQuantity = mcOrderQuantity;
	}

	@Column(name = "MC_MIN_PACKAGE_QUANTITY", precision = 22, scale = 0)
	public BigDecimal getMcMinPackageQuantity() {
		return this.mcMinPackageQuantity;
	}

	public void setMcMinPackageQuantity(BigDecimal mcMinPackageQuantity) {
		this.mcMinPackageQuantity = mcMinPackageQuantity;
	}
	@Column(name = "HALFYEAR_ISSUE_COUNTER")
	public BigDecimal getHalfyearIssueCounter() {
		return halfyearIssueCounter;
	}

	public void setHalfyearIssueCounter(BigDecimal halfyearIssueCounter) {
		this.halfyearIssueCounter = halfyearIssueCounter;
	}
	@Column(name = "MAXIDLEDAYS")
	public BigDecimal getMaxidledays() {
		return maxidledays;
	}

	public void setMaxidledays(BigDecimal maxidledays) {
		this.maxidledays = maxidledays;
	}
	@Column(name = "MCCOMMAND")
	public String getMccommand() {
		return mccommand;
	}

	public void setMccommand(String mccommand) {
		this.mccommand = mccommand;
	}
	@Column(name = "VENDOR")
	public String getVendor() {
		return vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}
	@Column(name = "INVSSTOCK")
	public BigDecimal getInvsstock() {
		return invsstock;
	}

	public void setInvsstock(BigDecimal invsstock) {
		this.invsstock = invsstock;
	}
	@Column(name = "EP_INTERFACE_ID")
	public BigDecimal getEpInterfaceId() {
		return epInterfaceId;
	}

	public void setEpInterfaceId(BigDecimal epInterfaceId) {
		this.epInterfaceId = epInterfaceId;
	}
	@Column(name = "ERP_PR_STATUS")
	public String getErpPrStatus() {
		return erpPrStatus;
	}

	public void setErpPrStatus(String erpPrStatus) {
		this.erpPrStatus = erpPrStatus;
	}
	@Column(name = "ERP_PO_STATUS")
	public String getErpPoStatus() {
		return erpPoStatus;
	}

	public void setErpPoStatus(String erpPoStatus) {
		this.erpPoStatus = erpPoStatus;
	}
	@Column(name = "ERP_PR_BUYER_EMP_NO")
	public String getErpPrBuyerEmpNo() {
		return erpPrBuyerEmpNo;
	}

	public void setErpPrBuyerEmpNo(String erpPrBuyerEmpNo) {
		this.erpPrBuyerEmpNo = erpPrBuyerEmpNo;
	}
	@Column(name = "ERP_PO_BUYER_EMP_NO")
	public String getErpPoBuyerEmpNo() {
		return erpPoBuyerEmpNo;
	}

	public void setErpPoBuyerEmpNo(String erpPoBuyerEmpNo) {
		this.erpPoBuyerEmpNo = erpPoBuyerEmpNo;
	}
	@Column(name = "NOTE_TO_AGENT")
	public String getNoteToAgent() {
		return noteToAgent;
	}

	public void setNoteToAgent(String noteToAgent) {
		this.noteToAgent = noteToAgent;
	}
	
	@Column(name = "STORE_CATEGORY")
	public String getStoreCategory() {
		return storeCategory;
	}

	public void setStoreCategory(String storeCategory) {
		this.storeCategory = storeCategory;
	}
	@Column(name = "PO_VENDOR_ID")
	public String getPoVendorId() {
		return poVendorId;
	}

	public void setPoVendorId(String poVendorId) {
		this.poVendorId = poVendorId;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PO_PROMISED_DATE", length = 7)
	public Date getPoPromisedDate() {
		return poPromisedDate;
	}

	public void setPoPromisedDate(Date poPromisedDate) {
		this.poPromisedDate = poPromisedDate;
	}
	@Column(name = "INSPECTION_EMPNO")
	public String getInspectionEmpno() {
		return inspectionEmpno;
	}

	public void setInspectionEmpno(String inspectionEmpno) {
		this.inspectionEmpno = inspectionEmpno;
	}

	@Column(name = "ERP_BUYER_RETURN_NOTE")
	public String getErpBuyerReturnNote() {
		return erpBuyerReturnNote;
	}

	public void setErpBuyerReturnNote(String erpBuyerReturnNote) {
		this.erpBuyerReturnNote = erpBuyerReturnNote;
	}
	
	@Column(name = "VENDOR_REMARK")
	public String getVendorRemark() {
		return vendorRemark;
	}

	public void setVendorRemark(String vendorRemark) {
		this.vendorRemark = vendorRemark;
	}
	@Column(name = "EQ_ID")
	public String getEqId() {
		return eqId;
	}

	public void setEqId(String eqId) {
		this.eqId = eqId;
	}

	@Column(name = "ERP_PR_LINE_NUM")
	public BigDecimal getErpPrLineNum() {
		return erpPrLineNum;
	}

	public void setErpPrLineNum(BigDecimal erpPrLineNum) {
		this.erpPrLineNum = erpPrLineNum;
	}
	@Column(name = "ERP_PO_LINE_NUM")
	public BigDecimal getErpPoLineNum() {
		return erpPoLineNum;
	}

	public void setErpPoLineNum(BigDecimal erpPoLineNum) {
		this.erpPoLineNum = erpPoLineNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EPMALL_CREATE_DATE", length = 7)
	public Date getEpmallCreateDate() {
		return epmallCreateDate;
	}

	public void setEpmallCreateDate(Date epmallCreateDate) {
		this.epmallCreateDate = epmallCreateDate;
	}
	@Column(name = "INSPECTION_DEPT_CODE")
	public String getInspectionDeptCode() {
		return inspectionDeptCode;
	}

	public void setInspectionDeptCode(String inspectionDeptCode) {
		this.inspectionDeptCode = inspectionDeptCode;
	}

	@Column(name = "EPMALL_PR_LINE_CANCEL_FLAG")
	public String getEpmallPrLineCancelFlag() {
		return epmallPrLineCancelFlag;
	}

	public void setEpmallPrLineCancelFlag(String epmallPrLineCancelFlag) {
		this.epmallPrLineCancelFlag = epmallPrLineCancelFlag;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERP_PR_CANCEL_DATE", length = 7)
	public Date getErpPrCancelDate() {
		return erpPrCancelDate;
	}

	public void setErpPrCancelDate(Date erpPrCancelDate) {
		this.erpPrCancelDate = erpPrCancelDate;
	}
	@Column(name = "SUMOFISSUECOUNTER")
	public BigDecimal getSumofissuecounter() {
		return sumofissuecounter;
	}

	public void setSumofissuecounter(BigDecimal sumofissuecounter) {
		this.sumofissuecounter = sumofissuecounter;
	}
	@Column(name = "IEP_INTERFACE_ID")
	public String getIepInterfaceId() {
		return iepInterfaceId;
	}

	public void setIepInterfaceId(String iepInterfaceId) {
		this.iepInterfaceId = iepInterfaceId;
	}

	@Column(name = "AVGHDQTY_THREE", precision = 22, scale = 0)
	public BigDecimal getAvghdqtyThree() {
		return avghdqtyThree;
	}

	public void setAvghdqtyThree(BigDecimal avghdqtyThree) {
		this.avghdqtyThree = avghdqtyThree;
	}
	@Column(name = "MAXHDQTY_THREE", precision = 22, scale = 0)
	public BigDecimal getMaxhdqtyThree() {
		return maxhdqtyThree;
	}

	public void setMaxhdqtyThree(BigDecimal maxhdqtyThree) {
		this.maxhdqtyThree = maxhdqtyThree;
	}

	@Column(name = "MULTIPLE_AVGHDQTY_THREE", precision = 22, scale = 0)
	public BigDecimal getMultipleAvghdqtyThree() {
		return multipleAvghdqtyThree;
	}

	public void setMultipleAvghdqtyThree(BigDecimal multipleAvghdqtyThree) {
		this.multipleAvghdqtyThree = multipleAvghdqtyThree;
	}
	@Column(name = "AVGHDCOST_THREE", precision = 22, scale = 0)
	public BigDecimal getAvghdcostThree() {
		return avghdcostThree;
	}

	public void setAvghdcostThree(BigDecimal avghdcostThree) {
		this.avghdcostThree = avghdcostThree;
	}
	@Column(name = "MAXHDCOST_THREE", precision = 22, scale = 0)
	public BigDecimal getMaxhdcostThree() {
		return maxhdcostThree;
	}

	public void setMaxhdcostThree(BigDecimal maxhdcostThree) {
		this.maxhdcostThree = maxhdcostThree;
	}
	@Column(name = "HDQTY_THREE", precision = 22, scale = 0)
	public BigDecimal getHdqtyThree() {
		return hdqtyThree;
	}

	public void setHdqtyThree(BigDecimal hdqtyThree) {
		this.hdqtyThree = hdqtyThree;
	}
	@Column(name = "HDCOST_THREE", precision = 22, scale = 0)
	public BigDecimal getHdcostThree() {
		return hdcostThree;
	}

	public void setHdcostThree(BigDecimal hdcostThree) {
		this.hdcostThree = hdcostThree;
	}
	@Column(name = "TRANSFER_MSG")
	public String getTransferMsg() {
		return transferMsg;
	}

	public void setTransferMsg(String transferMsg) {
		this.transferMsg = transferMsg;
	}
	@Column(name = "EP_NUM")
	public String getEpNum() {
		return epNum;
	}

	public void setEpNum(String epNum) {
		this.epNum = epNum;
	}

	@Column(name = "CMOMMCONTROL")
	public String getCmommcontrol() {
		return cmommcontrol;
	}

	public void setCmommcontrol(String cmommcontrol) {
		this.cmommcontrol = cmommcontrol;
	}
	@Column(name = "ERP_PR_STATUS_DESCRIPTION")
	public String getErpPrStatusDescription() {
		return erpPrStatusDescription;
	}
	public void setErpPrStatusDescription(String erpPrStatusDescription) {
		this.erpPrStatusDescription = erpPrStatusDescription;
	}
	
	@Transient
	private String issitecontrol;
	@Transient
	public String getIssitecontrol() {
		return this.issitecontrol;
	}
	public void setIssitecontrol(String issitecontrol) {
		this.issitecontrol = issitecontrol;
	}
	
}
