package mro.base.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * PrlineDisableSumcounter generated by hbm2java
 */
@Entity
@Table(name = "PRLINE_DISABLE_SUMCOUNTER", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ORGANIZATION_CODE", "ITEMNUM", "DEPT_CODE" }))
public class PrlineDisableSumcounter implements java.io.Serializable {

	private String id;
	private String organizationCode;
	private String deptCode;
	private String itemnum;
	private String remark;
	private Date lastUpdate;
	private String lastUpdateBy;

	public PrlineDisableSumcounter() {
	}

	public PrlineDisableSumcounter(String id, String organizationCode,
			String itemnum) {
		this.id = id;
		this.organizationCode = organizationCode;
		this.itemnum = itemnum;
	}

	public PrlineDisableSumcounter(String id, String organizationCode,
			String deptCode, String itemnum, String remark, Date lastUpdate,
			String lastUpdateBy) {
		this.id = id;
		this.organizationCode = organizationCode;
		this.deptCode = deptCode;
		this.itemnum = itemnum;
		this.remark = remark;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ORGANIZATION_CODE", nullable = false, length = 26)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "DEPT_CODE", length = 26)
	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	@Column(name = "ITEMNUM", nullable = false, length = 30)
	public String getItemnum() {
		return this.itemnum;
	}

	public void setItemnum(String itemnum) {
		this.itemnum = itemnum;
	}

	@Column(name = "REMARK", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

}
