package mro.base.entity;

// Generated 2014/3/26 �U�� 02:48:51 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrtypeBudget generated by hbm2java
 */
@Entity
@Table(name = "PRTYPE_BUDGET", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DEPT_NO", "BUDGET_TYPE" }))
public class PrtypeBudget implements java.io.Serializable {

	private BigDecimal prtypeBudgetId;
	private String deptNo;
	private String budgetType;
	private BigDecimal totalBudget;
	private BigDecimal totalDlEmployee;
	private BigDecimal totalIdlEmployee;
	private Date lastupdateDate;
	private String lastupdateBy;
	private String budgetMonth;
	private String remark;
	private LocationSiteMap locationSiteMap;

	public PrtypeBudget() {
	}

	public PrtypeBudget(BigDecimal prtypeBudgetId, String deptNo, String budgetType) {
		this.prtypeBudgetId = prtypeBudgetId;
		this.deptNo = deptNo;
		this.budgetType = budgetType;
	}

	public PrtypeBudget(BigDecimal prtypeBudgetId, String deptNo,
			 String budgetType, BigDecimal totalBudget,
			BigDecimal totalDlEmployee, BigDecimal totalIdlEmployee,
			Date lastupdateDate, String lastupdateBy, 
			String budgetMonth,String remark,LocationSiteMap locationSiteMap) {
		this.prtypeBudgetId = prtypeBudgetId;
		this.deptNo = deptNo;
		this.budgetType = budgetType;
		this.totalBudget = totalBudget;
		this.totalDlEmployee = totalDlEmployee;
		this.totalIdlEmployee = totalIdlEmployee;
		this.lastupdateDate = lastupdateDate;
		this.lastupdateBy = lastupdateBy;
		this.budgetMonth = budgetMonth;
		this.remark  = remark;
		this.locationSiteMap = locationSiteMap;
	}

	@Id
	@SequenceGenerator(name="PRTYPE_BUDGET_ID_GENERATOR", sequenceName="PRTYPE_BUDGET_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PRTYPE_BUDGET_ID_GENERATOR")
	@Column(name = "PRTYPE_BUDGET_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrtypeBudgetId() {
		return this.prtypeBudgetId;
	}

	public void setPrtypeBudgetId(BigDecimal prtypeBudgetId) {
		this.prtypeBudgetId = prtypeBudgetId;
	}

	@Column(name = "DEPT_NO", nullable = false, length = 10)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "BUDGET_TYPE", nullable = false, length = 30)
	public String getBudgetType() {
		return budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}

	@Column(name = "TOTAL_BUDGET", precision = 22, scale = 0)
	public BigDecimal getTotalBudget() {
		return this.totalBudget;
	}


	public void setTotalBudget(BigDecimal totalBudget) {
		this.totalBudget = totalBudget;
	}

	@Column(name = "TOTAL_DL_EMPLOYEE", precision = 22, scale = 0)
	public BigDecimal getTotalDlEmployee() {
		return this.totalDlEmployee;
	}

	public void setTotalDlEmployee(BigDecimal totalDlEmployee) {
		this.totalDlEmployee = totalDlEmployee;
	}

	@Column(name = "TOTAL_IDL_EMPLOYEE", precision = 22, scale = 0)
	public BigDecimal getTotalIdlEmployee() {
		return this.totalIdlEmployee;
	}

	public void setTotalIdlEmployee(BigDecimal totalIdlEmployee) {
		this.totalIdlEmployee = totalIdlEmployee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE_DATE", length = 7)
	public Date getLastupdateDate() {
		return this.lastupdateDate;
	}

	public void setLastupdateDate(Date lastupdateDate) {
		this.lastupdateDate = lastupdateDate;
	}

	@Column(name = "LASTUPDATE_BY", length = 16)
	public String getLastupdateBy() {
		return this.lastupdateBy;
	}

	public void setLastupdateBy(String lastupdateBy) {
		this.lastupdateBy = lastupdateBy;
	}


	@Column(name = "BUDGET_MONTH", length = 8)
	public String getBudgetMonth() {
		return budgetMonth;
	}

	public void setBudgetMonth(String budgetMonth) {
		this.budgetMonth = budgetMonth;
	}
	@Column(name = "REMARK", length = 4000)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}

}
