package mro.base.entity;

// Generated 2015/11/24 �U�� 04:55:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrtypeBudgetReasoncode generated by hbm2java
 */
@Entity
@Table(name = "PRTYPE_BUDGET_REASONCODE", uniqueConstraints = @UniqueConstraint(columnNames = "PRTYPE"))
public class PrtypeBudgetReasoncode implements java.io.Serializable {

	private String id;
	private String prtype;
	private Date lastupdateDate;
	private String lastupdateBy;
	private String budgetType;

	public PrtypeBudgetReasoncode() {
	}

	public PrtypeBudgetReasoncode(String id, String prtype) {
		this.id = id;
		this.prtype = prtype;
	}

	public PrtypeBudgetReasoncode(String id, String prtype,
			Date lastupdateDate, String lastupdateBy, String budgetType) {
		this.id = id;
		this.prtype = prtype;
		this.lastupdateDate = lastupdateDate;
		this.lastupdateBy = lastupdateBy;
		this.budgetType = budgetType;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 1)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PRTYPE", unique = true, nullable = false, length = 30)
	public String getPrtype() {
		return this.prtype;
	}

	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE_DATE", length = 7)
	public Date getLastupdateDate() {
		return this.lastupdateDate;
	}

	public void setLastupdateDate(Date lastupdateDate) {
		this.lastupdateDate = lastupdateDate;
	}

	@Column(name = "LASTUPDATE_BY", length = 16)
	public String getLastupdateBy() {
		return this.lastupdateBy;
	}

	public void setLastupdateBy(String lastupdateBy) {
		this.lastupdateBy = lastupdateBy;
	}

	@Column(name = "BUDGET_TYPE", length = 30)
	public String getBudgetType() {
		return this.budgetType;
	}

	public void setBudgetType(String budgetType) {
		this.budgetType = budgetType;
	}

}
