package mro.base.entity;

// Generated 2016/7/28 �W�� 11:13:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * PrtypeEpr generated by hbm2java
 */
@Entity
@Table(name = "PRTYPE_EPR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PRTYPE", "LOCATION_SITE" }))
public class PrtypeEpr implements java.io.Serializable {

	private String id;
	private String prtype;
	private String eprRequestedby2Type;
	private Date lastUpdate;
	private String lastUpdateBy;
	private String locationSite;

	public PrtypeEpr() {
	}
	
	public PrtypeEpr(String prtype, String locationSite) {
		this.prtype = prtype;
		this.locationSite  = locationSite;
	}
	
	public PrtypeEpr(String id, String prtype, String eprRequestedby2Type) {
		this.id = id;
		this.prtype = prtype;
		this.eprRequestedby2Type = eprRequestedby2Type;
	}

	public PrtypeEpr(String id, String prtype, String eprRequestedby2Type,
			Date lastUpdate, String lastUpdateBy, String locationSite) {
		this.id = id;
		this.prtype = prtype;
		this.eprRequestedby2Type = eprRequestedby2Type;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.locationSite = locationSite;
	}

	@Id	
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PRTYPE", nullable = false, length = 30)
	public String getPrtype() {
		return this.prtype;
	}

	public void setPrtype(String prtype) {
		this.prtype = prtype;
	}

	@Column(name = "EPR_REQUESTEDBY2_TYPE", nullable = false, length = 30)
	public String getEprRequestedby2Type() {
		return this.eprRequestedby2Type;
	}

	public void setEprRequestedby2Type(String eprRequestedby2Type) {
		this.eprRequestedby2Type = eprRequestedby2Type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 20)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Column(name = "LOCATION_SITE", length = 50)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

}
