package mro.base.entity;

// Generated 2016/3/2 �U�� 02:46:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SapAccessLog generated by hbm2java
 */
@Entity
@Table(name = "SAP_ACCESS_LOG")
public class SapAccessLog implements java.io.Serializable {

	private BigDecimal aiId;
	private String material;
	private String plant;
	private String type;
	private String loginfo;
	private Date accessTime;
	private String storageLocation;
	private String materialGroup;

	public SapAccessLog() {
	}

	public SapAccessLog(BigDecimal aiId) {
		this.aiId = aiId;
	}

	public SapAccessLog(BigDecimal aiId, String material, String plant,
			String type, String loginfo, Date accessTime,
			String storageLocation, String materialGroup) {
		this.aiId = aiId;
		this.material = material;
		this.plant = plant;
		this.type = type;
		this.loginfo = loginfo;
		this.accessTime = accessTime;
		this.storageLocation = storageLocation;
		this.materialGroup = materialGroup;
	}

	@Id
	@Column(name = "AI_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAiId() {
		return this.aiId;
	}

	public void setAiId(BigDecimal aiId) {
		this.aiId = aiId;
	}

	@Column(name = "MATERIAL", length = 20)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "PLANT", length = 10)
	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	@Column(name = "TYPE", length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "LOGINFO", length = 300)
	public String getLoginfo() {
		return this.loginfo;
	}

	public void setLoginfo(String loginfo) {
		this.loginfo = loginfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACCESS_TIME", length = 7)
	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	@Column(name = "STORAGE_LOCATION", length = 4)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "MATERIAL_GROUP", length = 9)
	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

}
