package mro.base.entity;

// Generated 2015/2/2 �W�� 10:05:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SapAccessLogEq generated by hbm2java
 */
@Entity
@Table(name = "SAP_ACCESS_LOG_EQ")
public class SapAccessLogEq implements java.io.Serializable {

	private String aiId;
	private String material;
	private String classstructureid;
	private String type;
	private String loginfo;
	private Date accessTime;
	private String facilityNum;

	public SapAccessLogEq() {
	}

	public SapAccessLogEq(String aiId) {
		this.aiId = aiId;
	}

	public SapAccessLogEq(String aiId, String material,
			String classstructureid, String type, String loginfo,
			Date accessTime, String facilityNum) {
		this.aiId = aiId;
		this.material = material;
		this.classstructureid = classstructureid;
		this.type = type;
		this.loginfo = loginfo;
		this.accessTime = accessTime;
		this.facilityNum = facilityNum;
	}

	@Id
	@Column(name = "AI_ID", unique = true, nullable = false, length = 32)
	public String getAiId() {
		return this.aiId;
	}

	public void setAiId(String aiId) {
		this.aiId = aiId;
	}

	@Column(name = "MATERIAL", length = 20)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 10)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "TYPE", length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "LOGINFO", length = 300)
	public String getLoginfo() {
		return this.loginfo;
	}

	public void setLoginfo(String loginfo) {
		this.loginfo = loginfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACCESS_TIME", length = 7)
	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	@Column(name = "FACILITY_NUM", length = 100)
	public String getFacilityNum() {
		return this.facilityNum;
	}

	public void setFacilityNum(String facilityNum) {
		this.facilityNum = facilityNum;
	}

}
