package mro.base.entity;

// Generated 2014/1/14 �U�� 03:57:05 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SapAccessLogPn generated by hbm2java
 */
@Entity
@Table(name = "SAP_ACCESS_LOG_PN")
public class SapAccessLogPn implements java.io.Serializable {

	private BigDecimal aiId;
	private String material;
	private String classstructureid;
	private String type;
	private String loginfo;
	private Date accessTime;

	public SapAccessLogPn() {
	}

	public SapAccessLogPn(BigDecimal aiId) {
		this.aiId = aiId;
	}

	public SapAccessLogPn(BigDecimal aiId, String material,
			String classstructureid, String type, String loginfo,
			Date accessTime) {
		this.aiId = aiId;
		this.material = material;
		this.classstructureid = classstructureid;
		this.type = type;
		this.loginfo = loginfo;
		this.accessTime = accessTime;
	}

	@Id
	@Column(name = "AI_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAiId() {
		return this.aiId;
	}

	public void setAiId(BigDecimal aiId) {
		this.aiId = aiId;
	}

	@Column(name = "MATERIAL", length = 20)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "CLASSSTRUCTUREID", length = 10)
	public String getClassstructureid() {
		return this.classstructureid;
	}

	public void setClassstructureid(String classstructureid) {
		this.classstructureid = classstructureid;
	}

	@Column(name = "TYPE", length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "LOGINFO", length = 300)
	public String getLoginfo() {
		return this.loginfo;
	}

	public void setLoginfo(String loginfo) {
		this.loginfo = loginfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACCESS_TIME", length = 7)
	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

}
