package mro.base.entity;

// Generated 2017/3/8 �W�� 09:54:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SapPlantAttribute generated by hbm2java
 */
@Entity
@Table(name = "SAP_PLANT_ATTRIBUTE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PLANT_CODE", "MATERIAL_GROUP", "STORAGE_LOCATION" }))
public class SapPlantAttribute implements java.io.Serializable {

	private BigDecimal id;
	private String plantCode;
	private String materialGroup;
	private String materialGroupDesc;
	private String materialType;
	private String sdSalesOrganization;
	private String sdDistributionChannel;
	private String sdDivision;
	private String sdMaterialFreightGrp;
	private String sdAccountAssignmentGroup;
	private String sdMatlGrpPackMatls;
	private String purchasingInspectionType;
	private String purchasingGroup;
	private String mrpGroup;
	private String mrpType;
	private String mrpController;
	private String mrpSelectionMethod;
	private String mrpLotSize;
	private String mrpProcurementType;
	private String mrpReorderPoint;
	private String mrpGrprocessingDay;
	private String mrpProdStorageLoc;
	private String mrpStorageLocForEp;
	private String mrpSpecialProcurementType;
	private String mrpProdSchedProfile;
	private String mrpRepetitiveMfg;
	private String mrpRemProfile;
	private String mrpIndividualColl;
	private String mrpStrategyGroup;
	private String mrpMixedMrp;
	private String mrpBackflush;
	private String mrpInhouseProduction;
	private String mrpProductionUnit;
	private String issueUnit;
	private String storageLocation;
	private String storageBatchManagement;
	private String accountingValuationClass;
	private String accountingPriceControl;
	private BigDecimal accountionPriceUnit;
	private String specprocuremCosting;
	private String itemCat;
	private String transGrp;
	private String loadinggrp;
	//private String availcheck;
	private String matlStats;
	private String taxType1;
	private String taxclass1;

	public SapPlantAttribute() {
	}

	public SapPlantAttribute(BigDecimal id, String plantCode,
			String materialGroup) {
		this.id = id;
		this.plantCode = plantCode;
		this.materialGroup = materialGroup;
	}

	public SapPlantAttribute(BigDecimal id, String plantCode,
			String materialGroup, String materialGroupDesc,
			String materialType, String sdSalesOrganization,
			String sdDistributionChannel, String sdDivision,
			String sdMaterialFreightGrp, String sdAccountAssignmentGroup,
			String sdMatlGrpPackMatls, String purchasingInspectionType,
			String purchasingGroup, String mrpGroup, String mrpType,
			String mrpController, String mrpSelectionMethod, String mrpLotSize,
			String mrpProcurementType, String mrpReorderPoint,
			String mrpGrprocessingDay, String mrpProdStorageLoc,
			String mrpStorageLocForEp, String mrpSpecialProcurementType,
			String mrpProdSchedProfile, String mrpRepetitiveMfg,
			String mrpRemProfile, String mrpIndividualColl,
			String mrpStrategyGroup, String mrpMixedMrp, String mrpBackflush,
			String mrpInhouseProduction, String mrpProductionUnit,
			String issueUnit, String storageLocation,
			String storageBatchManagement, String accountingValuationClass,
			String accountingPriceControl, BigDecimal accountionPriceUnit,
			String specprocuremCosting, String itemCat, String transGrp,
			String loadinggrp, String matlStats,
			String taxType1, String taxclass1) {
		this.id = id;
		this.plantCode = plantCode;
		this.materialGroup = materialGroup;
		this.materialGroupDesc = materialGroupDesc;
		this.materialType = materialType;
		this.sdSalesOrganization = sdSalesOrganization;
		this.sdDistributionChannel = sdDistributionChannel;
		this.sdDivision = sdDivision;
		this.sdMaterialFreightGrp = sdMaterialFreightGrp;
		this.sdAccountAssignmentGroup = sdAccountAssignmentGroup;
		this.sdMatlGrpPackMatls = sdMatlGrpPackMatls;
		this.purchasingInspectionType = purchasingInspectionType;
		this.purchasingGroup = purchasingGroup;
		this.mrpGroup = mrpGroup;
		this.mrpType = mrpType;
		this.mrpController = mrpController;
		this.mrpSelectionMethod = mrpSelectionMethod;
		this.mrpLotSize = mrpLotSize;
		this.mrpProcurementType = mrpProcurementType;
		this.mrpReorderPoint = mrpReorderPoint;
		this.mrpGrprocessingDay = mrpGrprocessingDay;
		this.mrpProdStorageLoc = mrpProdStorageLoc;
		this.mrpStorageLocForEp = mrpStorageLocForEp;
		this.mrpSpecialProcurementType = mrpSpecialProcurementType;
		this.mrpProdSchedProfile = mrpProdSchedProfile;
		this.mrpRepetitiveMfg = mrpRepetitiveMfg;
		this.mrpRemProfile = mrpRemProfile;
		this.mrpIndividualColl = mrpIndividualColl;
		this.mrpStrategyGroup = mrpStrategyGroup;
		this.mrpMixedMrp = mrpMixedMrp;
		this.mrpBackflush = mrpBackflush;
		this.mrpInhouseProduction = mrpInhouseProduction;
		this.mrpProductionUnit = mrpProductionUnit;
		this.issueUnit = issueUnit;
		this.storageLocation = storageLocation;
		this.storageBatchManagement = storageBatchManagement;
		this.accountingValuationClass = accountingValuationClass;
		this.accountingPriceControl = accountingPriceControl;
		this.accountionPriceUnit = accountionPriceUnit;
		this.specprocuremCosting = specprocuremCosting;
		this.itemCat = itemCat;
		this.transGrp = transGrp;
		this.loadinggrp = loadinggrp;
		this.matlStats = matlStats;
		this.taxType1 = taxType1;
		this.taxclass1 = taxclass1;
	}

	@Id
	@SequenceGenerator(name="ID_GENERATOR", sequenceName="SAP_PLANT_ATTRIBUTE_SEQ",allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ID_GENERATOR")	
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "PLANT_CODE", nullable = false, length = 4)
	public String getPlantCode() {
		return this.plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	@Column(name = "MATERIAL_GROUP", nullable = false, length = 9)
	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

	@Column(name = "MATERIAL_GROUP_DESC", length = 200)
	public String getMaterialGroupDesc() {
		return this.materialGroupDesc;
	}

	public void setMaterialGroupDesc(String materialGroupDesc) {
		this.materialGroupDesc = materialGroupDesc;
	}

	@Column(name = "MATERIAL_TYPE", length = 4)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	@Column(name = "SD_SALES_ORGANIZATION", length = 4)
	public String getSdSalesOrganization() {
		return this.sdSalesOrganization;
	}

	public void setSdSalesOrganization(String sdSalesOrganization) {
		this.sdSalesOrganization = sdSalesOrganization;
	}

	@Column(name = "SD_DISTRIBUTION_CHANNEL", length = 2)
	public String getSdDistributionChannel() {
		return this.sdDistributionChannel;
	}

	public void setSdDistributionChannel(String sdDistributionChannel) {
		this.sdDistributionChannel = sdDistributionChannel;
	}

	@Column(name = "SD_DIVISION", length = 2)
	public String getSdDivision() {
		return this.sdDivision;
	}

	public void setSdDivision(String sdDivision) {
		this.sdDivision = sdDivision;
	}

	@Column(name = "SD_MATERIAL_FREIGHT_GRP", length = 8)
	public String getSdMaterialFreightGrp() {
		return this.sdMaterialFreightGrp;
	}

	public void setSdMaterialFreightGrp(String sdMaterialFreightGrp) {
		this.sdMaterialFreightGrp = sdMaterialFreightGrp;
	}

	@Column(name = "SD_ACCOUNT_ASSIGNMENT_GROUP", length = 2)
	public String getSdAccountAssignmentGroup() {
		return this.sdAccountAssignmentGroup;
	}

	public void setSdAccountAssignmentGroup(String sdAccountAssignmentGroup) {
		this.sdAccountAssignmentGroup = sdAccountAssignmentGroup;
	}

	@Column(name = "SD_MATL_GRP_PACK_MATLS", length = 4)
	public String getSdMatlGrpPackMatls() {
		return this.sdMatlGrpPackMatls;
	}

	public void setSdMatlGrpPackMatls(String sdMatlGrpPackMatls) {
		this.sdMatlGrpPackMatls = sdMatlGrpPackMatls;
	}

	@Column(name = "PURCHASING_INSPECTION_TYPE", length = 1)
	public String getPurchasingInspectionType() {
		return this.purchasingInspectionType;
	}

	public void setPurchasingInspectionType(String purchasingInspectionType) {
		this.purchasingInspectionType = purchasingInspectionType;
	}

	@Column(name = "PURCHASING_GROUP", length = 3)
	public String getPurchasingGroup() {
		return this.purchasingGroup;
	}

	public void setPurchasingGroup(String purchasingGroup) {
		this.purchasingGroup = purchasingGroup;
	}

	@Column(name = "MRP_GROUP", length = 4)
	public String getMrpGroup() {
		return this.mrpGroup;
	}

	public void setMrpGroup(String mrpGroup) {
		this.mrpGroup = mrpGroup;
	}

	@Column(name = "MRP_TYPE", length = 2)
	public String getMrpType() {
		return this.mrpType;
	}

	public void setMrpType(String mrpType) {
		this.mrpType = mrpType;
	}

	@Column(name = "MRP_CONTROLLER", length = 3)
	public String getMrpController() {
		return this.mrpController;
	}

	public void setMrpController(String mrpController) {
		this.mrpController = mrpController;
	}

	@Column(name = "MRP_SELECTION_METHOD", length = 1)
	public String getMrpSelectionMethod() {
		return this.mrpSelectionMethod;
	}

	public void setMrpSelectionMethod(String mrpSelectionMethod) {
		this.mrpSelectionMethod = mrpSelectionMethod;
	}

	@Column(name = "MRP_LOT_SIZE", length = 13)
	public String getMrpLotSize() {
		return this.mrpLotSize;
	}

	public void setMrpLotSize(String mrpLotSize) {
		this.mrpLotSize = mrpLotSize;
	}

	@Column(name = "MRP_PROCUREMENT_TYPE", length = 1)
	public String getMrpProcurementType() {
		return this.mrpProcurementType;
	}

	public void setMrpProcurementType(String mrpProcurementType) {
		this.mrpProcurementType = mrpProcurementType;
	}

	@Column(name = "MRP_REORDER_POINT", length = 13)
	public String getMrpReorderPoint() {
		return this.mrpReorderPoint;
	}

	public void setMrpReorderPoint(String mrpReorderPoint) {
		this.mrpReorderPoint = mrpReorderPoint;
	}

	@Column(name = "MRP_GRPROCESSING_DAY", length = 3)
	public String getMrpGrprocessingDay() {
		return this.mrpGrprocessingDay;
	}

	public void setMrpGrprocessingDay(String mrpGrprocessingDay) {
		this.mrpGrprocessingDay = mrpGrprocessingDay;
	}

	@Column(name = "MRP_PROD_STORAGE_LOC", length = 4)
	public String getMrpProdStorageLoc() {
		return this.mrpProdStorageLoc;
	}

	public void setMrpProdStorageLoc(String mrpProdStorageLoc) {
		this.mrpProdStorageLoc = mrpProdStorageLoc;
	}

	@Column(name = "MRP_STORAGE_LOC_FOR_EP", length = 4)
	public String getMrpStorageLocForEp() {
		return this.mrpStorageLocForEp;
	}

	public void setMrpStorageLocForEp(String mrpStorageLocForEp) {
		this.mrpStorageLocForEp = mrpStorageLocForEp;
	}

	@Column(name = "MRP_SPECIAL_PROCUREMENT_TYPE", length = 2)
	public String getMrpSpecialProcurementType() {
		return this.mrpSpecialProcurementType;
	}

	public void setMrpSpecialProcurementType(String mrpSpecialProcurementType) {
		this.mrpSpecialProcurementType = mrpSpecialProcurementType;
	}

	@Column(name = "MRP_PROD_SCHED_PROFILE", length = 6)
	public String getMrpProdSchedProfile() {
		return this.mrpProdSchedProfile;
	}

	public void setMrpProdSchedProfile(String mrpProdSchedProfile) {
		this.mrpProdSchedProfile = mrpProdSchedProfile;
	}

	@Column(name = "MRP_REPETITIVE_MFG", length = 1)
	public String getMrpRepetitiveMfg() {
		return this.mrpRepetitiveMfg;
	}

	public void setMrpRepetitiveMfg(String mrpRepetitiveMfg) {
		this.mrpRepetitiveMfg = mrpRepetitiveMfg;
	}

	@Column(name = "MRP_REM_PROFILE", length = 4)
	public String getMrpRemProfile() {
		return this.mrpRemProfile;
	}

	public void setMrpRemProfile(String mrpRemProfile) {
		this.mrpRemProfile = mrpRemProfile;
	}

	@Column(name = "MRP_INDIVIDUAL_COLL", length = 1)
	public String getMrpIndividualColl() {
		return this.mrpIndividualColl;
	}

	public void setMrpIndividualColl(String mrpIndividualColl) {
		this.mrpIndividualColl = mrpIndividualColl;
	}

	@Column(name = "MRP_STRATEGY_GROUP", length = 2)
	public String getMrpStrategyGroup() {
		return this.mrpStrategyGroup;
	}

	public void setMrpStrategyGroup(String mrpStrategyGroup) {
		this.mrpStrategyGroup = mrpStrategyGroup;
	}

	@Column(name = "MRP_MIXED_MRP", length = 1)
	public String getMrpMixedMrp() {
		return this.mrpMixedMrp;
	}

	public void setMrpMixedMrp(String mrpMixedMrp) {
		this.mrpMixedMrp = mrpMixedMrp;
	}

	@Column(name = "MRP_BACKFLUSH", length = 1)
	public String getMrpBackflush() {
		return this.mrpBackflush;
	}

	public void setMrpBackflush(String mrpBackflush) {
		this.mrpBackflush = mrpBackflush;
	}

	@Column(name = "MRP_INHOUSE_PRODUCTION", length = 3)
	public String getMrpInhouseProduction() {
		return this.mrpInhouseProduction;
	}

	public void setMrpInhouseProduction(String mrpInhouseProduction) {
		this.mrpInhouseProduction = mrpInhouseProduction;
	}

	@Column(name = "MRP_PRODUCTION_UNIT", length = 3)
	public String getMrpProductionUnit() {
		return this.mrpProductionUnit;
	}

	public void setMrpProductionUnit(String mrpProductionUnit) {
		this.mrpProductionUnit = mrpProductionUnit;
	}

	@Column(name = "ISSUE_UNIT", length = 3)
	public String getIssueUnit() {
		return this.issueUnit;
	}

	public void setIssueUnit(String issueUnit) {
		this.issueUnit = issueUnit;
	}

	@Column(name = "STORAGE_LOCATION", length = 4)
	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	@Column(name = "STORAGE_BATCH_MANAGEMENT", length = 1)
	public String getStorageBatchManagement() {
		return this.storageBatchManagement;
	}

	public void setStorageBatchManagement(String storageBatchManagement) {
		this.storageBatchManagement = storageBatchManagement;
	}

	@Column(name = "ACCOUNTING_VALUATION_CLASS", length = 4)
	public String getAccountingValuationClass() {
		return this.accountingValuationClass;
	}

	public void setAccountingValuationClass(String accountingValuationClass) {
		this.accountingValuationClass = accountingValuationClass;
	}

	@Column(name = "ACCOUNTING_PRICE_CONTROL", length = 1)
	public String getAccountingPriceControl() {
		return this.accountingPriceControl;
	}

	public void setAccountingPriceControl(String accountingPriceControl) {
		this.accountingPriceControl = accountingPriceControl;
	}

	@Column(name = "ACCOUNTION_PRICE_UNIT", precision = 22, scale = 0)
	public BigDecimal getAccountionPriceUnit() {
		return this.accountionPriceUnit;
	}

	public void setAccountionPriceUnit(BigDecimal accountionPriceUnit) {
		this.accountionPriceUnit = accountionPriceUnit;
	}

	@Column(name = "SPECPROCUREM_COSTING", length = 2)
	public String getSpecprocuremCosting() {
		return this.specprocuremCosting;
	}

	public void setSpecprocuremCosting(String specprocuremCosting) {
		this.specprocuremCosting = specprocuremCosting;
	}

	@Column(name = "ITEM_CAT", length = 4)
	public String getItemCat() {
		return this.itemCat;
	}

	public void setItemCat(String itemCat) {
		this.itemCat = itemCat;
	}

	@Column(name = "TRANS_GRP", length = 4)
	public String getTransGrp() {
		return this.transGrp;
	}

	public void setTransGrp(String transGrp) {
		this.transGrp = transGrp;
	}

	@Column(name = "LOADINGGRP", length = 4)
	public String getLoadinggrp() {
		return this.loadinggrp;
	}

	public void setLoadinggrp(String loadinggrp) {
		this.loadinggrp = loadinggrp;
	}

	@Column(name = "MATL_STATS", length = 1)
	public String getMatlStats() {
		return this.matlStats;
	}

	public void setMatlStats(String matlStats) {
		this.matlStats = matlStats;
	}

	@Column(name = "TAX_TYPE_1", length = 4)
	public String getTaxType1() {
		return this.taxType1;
	}

	public void setTaxType1(String taxType1) {
		this.taxType1 = taxType1;
	}

	@Column(name = "TAXCLASS_1", length = 1)
	public String getTaxclass1() {
		return this.taxclass1;
	}

	public void setTaxclass1(String taxclass1) {
		this.taxclass1 = taxclass1;
	}

}
