package mro.base.entity;

// Generated 2016/3/2 �U�� 03:36:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SapProfitCenter generated by hbm2java
 */
@Entity
@Table(name = "SAP_PROFIT_CENTER")
public class SapProfitCenter implements java.io.Serializable {

	private String plantCode;
	private String profitCenter;
	private Date createDate;
	private String createBy;

	public SapProfitCenter() {
	}

	public SapProfitCenter(String plantCode, String profitCenter) {
		this.plantCode = plantCode;
		this.profitCenter = profitCenter;
	}

	public SapProfitCenter(String plantCode, String profitCenter,
			Date createDate, String createBy) {
		this.plantCode = plantCode;
		this.profitCenter = profitCenter;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@Column(name = "PLANT_CODE", unique = true, nullable = false, length = 4)
	public String getPlantCode() {
		return this.plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	@Column(name = "PROFIT_CENTER", nullable = false, length = 10)
	public String getProfitCenter() {
		return this.profitCenter;
	}

	public void setProfitCenter(String profitCenter) {
		this.profitCenter = profitCenter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_BY", length = 29)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
