package mro.base.entity;

// Generated 2015/11/23 �U�� 05:30:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignTask generated by hbm2java
 */
@Entity
@Table(name = "SIGN_TASK")
public class SignTask implements java.io.Serializable {

	private BigDecimal taskId;
	private SignTaskList signTaskList;
	private String status;
	private String actorId;
	private String createBy;
	private Date createDate;
	private String applyNum;
	private String sourceSystem;
	private String sourceCategory;
	private BigDecimal processId;
	private Set<SignTaskList> signTaskLists = new HashSet<SignTaskList>(0);

	public SignTask() {
	}

	public SignTask(BigDecimal taskId) {
		this.taskId = taskId;
	}

	public SignTask(BigDecimal taskId, SignTaskList signTaskList,
			String status, String actorId, String createBy, Date createDate,
			String applyNum, String sourceSystem, String sourceCategory,
			BigDecimal processId, Set<SignTaskList> signTaskLists) {
		this.taskId = taskId;
		this.signTaskList = signTaskList;
		this.status = status;
		this.actorId = actorId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.applyNum = applyNum;
		this.sourceSystem = sourceSystem;
		this.sourceCategory = sourceCategory;
		this.processId = processId;
		this.signTaskLists = signTaskLists;
	}

	@Id
	@SequenceGenerator(name="TASK_ID_GENERATOR", sequenceName="SIGN_TASK_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TASK_ID_GENERATOR")
	@Column(name = "TASK_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskId() {
		return this.taskId;
	}

	public void setTaskId(BigDecimal taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_LIST_ID")
	public SignTaskList getSignTaskList() {
		return this.signTaskList;
	}

	public void setSignTaskList(SignTaskList signTaskList) {
		this.signTaskList = signTaskList;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ACTOR_ID", length = 30)
	public String getActorId() {
		return this.actorId;
	}

	public void setActorId(String actorId) {
		this.actorId = actorId;
	}

	@Column(name = "CREATE_BY", length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "APPLY_NUM", length = 50)
	public String getApplyNum() {
		return this.applyNum;
	}

	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	@Column(name = "SOURCE_SYSTEM", length = 50)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	@Column(name = "SOURCE_CATEGORY", length = 50)
	public String getSourceCategory() {
		return this.sourceCategory;
	}

	public void setSourceCategory(String sourceCategory) {
		this.sourceCategory = sourceCategory;
	}

	@Column(name = "PROCESS_ID", precision = 22, scale = 0)
	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "signTask")
	public Set<SignTaskList> getSignTaskLists() {
		return this.signTaskLists;
	}

	public void setSignTaskLists(Set<SignTaskList> signTaskLists) {
		this.signTaskLists = signTaskLists;
	}

}
