package mro.base.entity;

// Generated 2013/3/11 �W�� 09:58:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SignProcessList generated by hbm2java
 */
@Entity
@Table(name = "SIGN_PROCESS_LIST")
public class SignProcessList implements java.io.Serializable {

	private BigDecimal processListId;
	private SignProcess signProcess;
	private String signCategory;
	private String signEmpNo;
	private BigDecimal signLevel;
	private BigDecimal signPrice;
	private BigDecimal signSequence;
	private String signDescription;
	private String signDeptNo;
	private BigDecimal signValidateTrue;
	private BigDecimal signValidateFalse;
	private String signValidateFunction;

	public SignProcessList() {
	}

	public SignProcessList(BigDecimal processListId, SignProcess signProcess) {
		this.processListId = processListId;
		this.signProcess = signProcess;
	}

	public SignProcessList(BigDecimal processListId, SignProcess signProcess,
			String signCategory, String signEmpNo, BigDecimal signLevel,
			BigDecimal signPrice, BigDecimal signSequence,String signDescription,
			String signDeptNo,
			BigDecimal signValidateTrue,BigDecimal signValidateFalse,String signValidateFunction) {
		this.processListId = processListId;
		this.signProcess = signProcess;
		this.signCategory = signCategory;
		this.signEmpNo = signEmpNo;
		this.signLevel = signLevel;
		this.signPrice = signPrice;
		this.signSequence = signSequence;
		this.signDescription= signDescription;
		this.signDeptNo= signDeptNo;
		this.signValidateTrue=signValidateTrue;
		this.signValidateFalse =signValidateFalse;
		this.signValidateFunction=signValidateFunction;
	}

	@Id
	@SequenceGenerator(name="PROCESS_LIST_ID_GENERATOR", sequenceName="SIGN_PROCESS_LIST_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PROCESS_LIST_ID_GENERATOR")
	@Column(name = "PROCESS_LIST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProcessListId() {
		return this.processListId;
	}

	public void setProcessListId(BigDecimal processListId) {
		this.processListId = processListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROCESS_ID", nullable = false)
	public SignProcess getSignProcess() {
		return this.signProcess;
	}

	public void setSignProcess(SignProcess signProcess) {
		this.signProcess = signProcess;
	}

	@Column(name = "SIGN_CATEGORY", length = 20)
	public String getSignCategory() {
		return this.signCategory;
	}

	public void setSignCategory(String signCategory) {
		this.signCategory = signCategory;
	}

	@Column(name = "SIGN_EMP_NO", length = 10)
	public String getSignEmpNo() {
		return this.signEmpNo;
	}

	public void setSignEmpNo(String signEmpNo) {
		this.signEmpNo = signEmpNo;
	}

	@Column(name = "SIGN_LEVEL", precision = 22, scale = 0)
	public BigDecimal getSignLevel() {
		return this.signLevel;
	}

	public void setSignLevel(BigDecimal signLevel) {
		this.signLevel = signLevel;
	}

	@Column(name = "SIGN_PRICE", precision = 22, scale = 0)
	public BigDecimal getSignPrice() {
		return this.signPrice;
	}

	public void setSignPrice(BigDecimal signPrice) {
		this.signPrice = signPrice;
	}

	@Column(name = "SIGN_SEQUENCE", precision = 22, scale = 0)
	public BigDecimal getSignSequence() {
		return this.signSequence;
	}

	public void setSignSequence(BigDecimal signSequence) {
		this.signSequence = signSequence;
	}
	@Column(name = "SIGN_DESCRIPTION")
	public String getSignDescription() {
		return signDescription;
	}

	public void setSignDescription(String signDescription) {
		this.signDescription = signDescription;
	}
	@Column(name = "SIGN_DEPT_NO")
	public String getSignDeptNo() {
		return signDeptNo;
	}

	public void setSignDeptNo(String signDeptNo) {
		this.signDeptNo = signDeptNo;
	}


	@Column(name = "SIGN_VALIDATE_TRUE")
	public BigDecimal getSignValidateTrue() {
		return signValidateTrue;
	}

	public void setSignValidateTrue(BigDecimal signValidateTrue) {
		this.signValidateTrue = signValidateTrue;
	}

	@Column(name = "SIGN_VALIDATE_FALSE")
	public BigDecimal getSignValidateFalse() {
		return signValidateFalse;
	}

	public void setSignValidateFalse(BigDecimal signValidateFalse) {
		this.signValidateFalse = signValidateFalse;
	}

	@Column(name = "SIGN_VALIDATE_FUNCTION")
	public String getSignValidateFunction() {
		return signValidateFunction;
	}

	public void setSignValidateFunction(String signValidateFunction) {
		this.signValidateFunction = signValidateFunction;
	}

}
