package mro.base.entity;

// Generated 2013/3/11 �W�� 09:58:26 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignProcess generated by hbm2java
 */
@Entity
@Table(name = "SIGN_PROCESS")
public class SignProcess implements java.io.Serializable {

	private BigDecimal processId;
	private String processName;
	private String description;
	private String createBy;
	private Date createDate;
	private String changeBy;
	private Date changeDate;
	private Date inactiveDate;
	private Set<SignProcessList> signProcessLists = new HashSet<SignProcessList>(
			0);
	private String sourceSystem;
	private String sourceCategory;
	private String notifyFlag;
	
	public SignProcess() {
	}

	public SignProcess(BigDecimal processId, String createBy, String changeBy) {
		this.processId = processId;
		this.createBy = createBy;
		this.changeBy = changeBy;
	}

	public SignProcess(BigDecimal processId, String processName,
			String description, String createBy, Date createDate,
			String changeBy, Date changeDate, Date inactiveDate,
			Set<SignProcessList> signProcessLists,String sourceSystem,String sourceCategory,
			String notifyFlag) {
		this.processId = processId;
		this.processName = processName;
		this.description = description;
		this.createBy = createBy;
		this.createDate = createDate;
		this.changeBy = changeBy;
		this.changeDate = changeDate;
		this.inactiveDate = inactiveDate;
		this.signProcessLists = signProcessLists;
		this.sourceSystem=sourceSystem;
		this.sourceCategory=sourceCategory;
		this.notifyFlag = notifyFlag;
	}

	@Id
	@SequenceGenerator(name="PROCESS_ID_GENERATOR", sequenceName="SIGN_PROCESS_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PROCESS_ID_GENERATOR")
	@Column(name = "PROCESS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProcessId() {
		return this.processId;
	}

	public void setProcessId(BigDecimal processId) {
		this.processId = processId;
	}

	@Column(name = "PROCESS_NAME", length = 50)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATE_BY", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CHANGE_BY", nullable = false, length = 30)
	public String getChangeBy() {
		return this.changeBy;
	}

	public void setChangeBy(String changeBy) {
		this.changeBy = changeBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHANGE_DATE", length = 7)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "signProcess")
	public Set<SignProcessList> getSignProcessLists() {
		return this.signProcessLists;
	}

	public void setSignProcessLists(Set<SignProcessList> signProcessLists) {
		this.signProcessLists = signProcessLists;
	}
	@Column(name = "SOURCE_SYSTEM", length = 50)
	public String getSourceSystem() {
		return sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}
	
	@Column(name = "SOURCE_CATEGORY", length = 50)
	public String getSourceCategory() {
		return sourceCategory;
	}
	
	public void setSourceCategory(String sourceCategory) {
		this.sourceCategory = sourceCategory;
	}
	
	@Column(name = "NOTIFY_FLAG")
	public String getNotifyFlag() {
		return notifyFlag;
	}

	public void setNotifyFlag(String notifyFlag) {
		this.notifyFlag = notifyFlag;
	}
	
}
