package mro.base.entity;

// Generated 2015/11/23 �U�� 05:30:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignTaskList generated by hbm2java
 */
@Entity
@Table(name = "SIGN_TASK_LIST")
public class SignTaskList implements java.io.Serializable {

	private BigDecimal taskListId;
	private SignTask signTask;
	private String actorId;
	private Date signDate;
	private String signerComment;
	private String action;
	private BigDecimal signSeqId;
	private String actorDept;
	private String signDescription;
	private Date fromDate;
	private Set<SignTask> signTasks = new HashSet<SignTask>(0);

	public SignTaskList() {
	}

	public SignTaskList(BigDecimal taskListId, SignTask signTask) {
		this.taskListId = taskListId;
		this.signTask = signTask;
	}

	public SignTaskList(BigDecimal taskListId, SignTask signTask,
			String actorId, Date signDate, String signerComment, String action,
			BigDecimal signSeqId, String actorDept, String signDescription,
			Date fromDate, Set<SignTask> signTasks) {
		this.taskListId = taskListId;
		this.signTask = signTask;
		this.actorId = actorId;
		this.signDate = signDate;
		this.signerComment = signerComment;
		this.action = action;
		this.signSeqId = signSeqId;
		this.actorDept = actorDept;
		this.signDescription = signDescription;
		this.fromDate = fromDate;
		this.signTasks = signTasks;
	}
	
	@Id
	@SequenceGenerator(name="TASK_LIST_ID_GENERATOR", sequenceName="SIGN_TASK_LIST_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TASK_LIST_ID_GENERATOR")
	@Column(name = "TASK_LIST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskListId() {
		return this.taskListId;
	}

	public void setTaskListId(BigDecimal taskListId) {
		this.taskListId = taskListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_ID", nullable = false)
	public SignTask getSignTask() {
		return this.signTask;
	}

	public void setSignTask(SignTask signTask) {
		this.signTask = signTask;
	}

	@Column(name = "ACTOR_ID", length = 50)
	public String getActorId() {
		return this.actorId;
	}

	public void setActorId(String actorId) {
		this.actorId = actorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIGN_DATE", length = 7)
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	@Column(name = "SIGNER_COMMENT", length = 1024)
	public String getSignerComment() {
		return this.signerComment;
	}

	public void setSignerComment(String signerComment) {
		this.signerComment = signerComment;
	}

	@Column(name = "ACTION", length = 50)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "SIGN_SEQ_ID", precision = 22, scale = 0)
	public BigDecimal getSignSeqId() {
		return this.signSeqId;
	}

	public void setSignSeqId(BigDecimal signSeqId) {
		this.signSeqId = signSeqId;
	}

	@Column(name = "ACTOR_DEPT", length = 50)
	public String getActorDept() {
		return this.actorDept;
	}

	public void setActorDept(String actorDept) {
		this.actorDept = actorDept;
	}

	@Column(name = "SIGN_DESCRIPTION", length = 20)
	public String getSignDescription() {
		return this.signDescription;
	}

	public void setSignDescription(String signDescription) {
		this.signDescription = signDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 7)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "signTaskList")
	public Set<SignTask> getSignTasks() {
		return this.signTasks;
	}

	public void setSignTasks(Set<SignTask> signTasks) {
		this.signTasks = signTasks;
	}

}
