package mro.base.entity;

// Generated 2013/3/14 �U�� 03:05:02 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignParameter generated by hbm2java
 */
@Entity
@Table(name = "SIGN_PARAMETER")
public class SignParameter implements java.io.Serializable {

	private BigDecimal parameterId;
	private String parameterKey;
	private String parameterValue;
	private String delted;
	private Date lastUpdate;
	private String category;
	private String parameterDescription;

	public SignParameter() {
	}

	public SignParameter(BigDecimal parameterId) {
		this.parameterId = parameterId;
	}

	public SignParameter(BigDecimal parameterId, String parameterKey,
			String parameterValue, String delted, Date lastUpdate,
			String category, String parameterDescription) {
		this.parameterId = parameterId;
		this.parameterKey = parameterKey;
		this.parameterValue = parameterValue;
		this.delted = delted;
		this.lastUpdate = lastUpdate;
		this.category = category;
		this.parameterDescription = parameterDescription;
	}

	@Id
	@Column(name = "PARAMETER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getParameterId() {
		return this.parameterId;
	}

	public void setParameterId(BigDecimal parameterId) {
		this.parameterId = parameterId;
	}

	@Column(name = "PARAMETER_KEY", length = 50)
	public String getParameterKey() {
		return this.parameterKey;
	}

	public void setParameterKey(String parameterKey) {
		this.parameterKey = parameterKey;
	}

	@Column(name = "PARAMETER_VALUE", length = 50)
	public String getParameterValue() {
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	@Column(name = "DELTED", length = 1)
	public String getDelted() {
		return this.delted;
	}

	public void setDelted(String delted) {
		this.delted = delted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "CATEGORY", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "PARAMETER_DESCRIPTION", length = 50)
	public String getParameterDescription() {
		return this.parameterDescription;
	}

	public void setParameterDescription(String parameterDescription) {
		this.parameterDescription = parameterDescription;
	}

}
