package mro.base.entity;

// Generated 2013/3/14 �U�� 02:57:49 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignSourceCategory generated by hbm2java
 */
@Entity
@Table(name = "SIGN_SOURCE_CATEGORY")
public class SignSourceCategory implements java.io.Serializable {

	private BigDecimal sourceCategoryId;
	private SignSourceSystem signSourceSystem;
	private String sourceCategoryKey;
	private String sourceCategoryValue;
	private String delted;
	private Date lastUpdate;
	private String description;

	public SignSourceCategory() {
	}

	public SignSourceCategory(BigDecimal sourceCategoryId) {
		this.sourceCategoryId = sourceCategoryId;
	}

	public SignSourceCategory(BigDecimal sourceCategoryId,
			SignSourceSystem signSourceSystem, String sourceCategoryKey,
			String sourceCategoryValue, String delted, Date lastUpdate,
			String description) {
		this.sourceCategoryId = sourceCategoryId;
		this.signSourceSystem = signSourceSystem;
		this.sourceCategoryKey = sourceCategoryKey;
		this.sourceCategoryValue = sourceCategoryValue;
		this.delted = delted;
		this.lastUpdate = lastUpdate;
		this.description = description;
	}

	@Id
	@SequenceGenerator(name="SOURCE_CATEGORY_ID_GENERATOR", sequenceName="SIGN_SOURCE_CATEGORY_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SOURCE_CATEGORY_ID_GENERATOR")
	@Column(name = "SOURCE_CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSourceCategoryId() {
		return sourceCategoryId;
	}

	public void setSourceCategoryId(BigDecimal sourceCategoryId) {
		this.sourceCategoryId = sourceCategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCE_SYSTEM_ID")
	public SignSourceSystem getSignSourceSystem() {
		return this.signSourceSystem;
	}

	public void setSignSourceSystem(SignSourceSystem signSourceSystem) {
		this.signSourceSystem = signSourceSystem;
	}

	@Column(name = "SOURCE_CATEGORY_KEY", length = 50)
	public String getSourceCategoryKey() {
		return this.sourceCategoryKey;
	}

	public void setSourceCategoryKey(String sourceCategoryKey) {
		this.sourceCategoryKey = sourceCategoryKey;
	}

	@Column(name = "SOURCE_CATEGORY_VALUE", length = 50)
	public String getSourceCategoryValue() {
		return this.sourceCategoryValue;
	}

	public void setSourceCategoryValue(String sourceCategoryValue) {
		this.sourceCategoryValue = sourceCategoryValue;
	}

	@Column(name = "DELTED", length = 1)
	public String getDelted() {
		return this.delted;
	}

	public void setDelted(String delted) {
		this.delted = delted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "DESCRIPTION", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
