package mro.base.entity;

// Generated 2013/3/15 �U�� 03:17:52 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignTaskListDeputy generated by hbm2java
 */
@Entity
@Table(name = "SIGN_TASK_LIST_DEPUTY")
public class SignTaskListDeputy implements java.io.Serializable {

	private BigDecimal taskListDeputyId;
	private BigDecimal taskListId;
	private String actorId;
	private String deputyActorId;
	private Date signDate;

	public SignTaskListDeputy() {
	}

	public SignTaskListDeputy(BigDecimal taskListDeputyId, BigDecimal taskListId) {
		this.taskListDeputyId = taskListDeputyId;
		this.taskListId = taskListId;
	}

	public SignTaskListDeputy(BigDecimal taskListDeputyId,
			BigDecimal taskListId, String actorId, String deputyActorId,
			Date signDate) {
		this.taskListDeputyId = taskListDeputyId;
		this.taskListId = taskListId;
		this.actorId = actorId;
		this.deputyActorId = deputyActorId;
		this.signDate = signDate;
	}

	@Id
	@SequenceGenerator(name="TASK_LIST_DEPUTY_ID_GENERATOR", sequenceName="SIGN_TASK_LIST_DEPUTY_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TASK_LIST_DEPUTY_ID_GENERATOR")
	@Column(name = "TASK_LIST_DEPUTY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskListDeputyId() {
		return this.taskListDeputyId;
	}

	public void setTaskListDeputyId(BigDecimal taskListDeputyId) {
		this.taskListDeputyId = taskListDeputyId;
	}

	@Column(name = "TASK_LIST_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTaskListId() {
		return this.taskListId;
	}

	public void setTaskListId(BigDecimal taskListId) {
		this.taskListId = taskListId;
	}

	@Column(name = "ACTOR_ID", length = 50)
	public String getActorId() {
		return this.actorId;
	}

	public void setActorId(String actorId) {
		this.actorId = actorId;
	}

	@Column(name = "DEPUTY_ACTOR_ID", length = 50)
	public String getDeputyActorId() {
		return this.deputyActorId;
	}

	public void setDeputyActorId(String deputyActorId) {
		this.deputyActorId = deputyActorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIGN_DATE", length = 7)
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

}
