package mro.base.entity;

// Generated 2013/3/14 �U�� 02:57:49 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SignSourceSystem generated by hbm2java
 */
@Entity
@Table(name = "SIGN_SOURCE_SYSTEM")
public class SignSourceSystem implements java.io.Serializable {

	private BigDecimal sourceSystemId;
	private String sourceSystemKey;
	private String sourceSystemValue;
	private String delted;
	private Date lastUpdate;
	private String description;
	private Set<SignSourceCategory> signSourceCategories = new HashSet<SignSourceCategory>(
			0);

	public SignSourceSystem() {
	}

	public SignSourceSystem(BigDecimal sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	public SignSourceSystem(BigDecimal sourceSystemId, String sourceSystemKey,
			String sourceSystemValue, String delted, Date lastUpdate,
			String description, Set<SignSourceCategory> signSourceCategories) {
		this.sourceSystemId = sourceSystemId;
		this.sourceSystemKey = sourceSystemKey;
		this.sourceSystemValue = sourceSystemValue;
		this.delted = delted;
		this.lastUpdate = lastUpdate;
		this.description = description;
		this.signSourceCategories = signSourceCategories;
	}

	@Id
	@SequenceGenerator(name="SOURCE_SYSTEM_ID_GENERATOR", sequenceName="SIGN_SOURCE_SYSTEM_SEQ" ,allocationSize=0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SOURCE_SYSTEM_ID_GENERATOR")
	@Column(name = "SOURCE_SYSTEM_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSourceSystemId() {
		return this.sourceSystemId;
	}

	public void setSourceSystemId(BigDecimal sourceSystemId) {
		this.sourceSystemId = sourceSystemId;
	}

	@Column(name = "SOURCE_SYSTEM_KEY", length = 50)
	public String getSourceSystemKey() {
		return this.sourceSystemKey;
	}

	public void setSourceSystemKey(String sourceSystemKey) {
		this.sourceSystemKey = sourceSystemKey;
	}

	@Column(name = "SOURCE_SYSTEM_VALUE", length = 50)
	public String getSourceSystemValue() {
		return this.sourceSystemValue;
	}

	public void setSourceSystemValue(String sourceSystemValue) {
		this.sourceSystemValue = sourceSystemValue;
	}

	@Column(name = "DELTED", length = 1)
	public String getDelted() {
		return this.delted;
	}

	public void setDelted(String delted) {
		this.delted = delted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "DESCRIPTION", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "signSourceSystem")
	public Set<SignSourceCategory> getSignSourceCategories() {
		return this.signSourceCategories;
	}

	public void setSignSourceCategories(
			Set<SignSourceCategory> signSourceCategories) {
		this.signSourceCategories = signSourceCategories;
	}

}
