package mro.base.entity;

// Generated 2016/11/30 �U�� 02:29:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SubinventoryConfig generated by hbm2java
 */
@Entity
@Table(name = "SUBINVENTORY_CONFIG")
public class SubinventoryConfig implements java.io.Serializable {

	private String id;
	private String assignOrganizationCode;
	private String type;
	private String oriOrganizationCode;
	private String oriLocation;
	private String locationSite;
	private Date lastUpdate;
	private String lastUpdateBy;
	private String oriLocationDesc;

	public SubinventoryConfig() {
	}

	public SubinventoryConfig(String id) {
		this.id = id;
	}

	public SubinventoryConfig(String id, String assignOrganizationCode,
			String type, String oriOrganizationCode, String oriLocation,
			String locationSite, Date lastUpdate, String lastUpdateBy,
			String oriLocationDesc) {
		this.id = id;
		this.assignOrganizationCode = assignOrganizationCode;
		this.type = type;
		this.oriOrganizationCode = oriOrganizationCode;
		this.oriLocation = oriLocation;
		this.locationSite = locationSite;
		this.lastUpdate = lastUpdate;
		this.lastUpdateBy = lastUpdateBy;
		this.oriLocationDesc = oriLocationDesc;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid2")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ASSIGN_ORGANIZATION_CODE", length = 20)
	public String getAssignOrganizationCode() {
		return this.assignOrganizationCode;
	}

	public void setAssignOrganizationCode(String assignOrganizationCode) {
		this.assignOrganizationCode = assignOrganizationCode;
	}

	@Column(name = "TYPE", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ORI_ORGANIZATION_CODE", length = 20)
	public String getOriOrganizationCode() {
		return this.oriOrganizationCode;
	}

	public void setOriOrganizationCode(String oriOrganizationCode) {
		this.oriOrganizationCode = oriOrganizationCode;
	}

	@Column(name = "ORI_LOCATION", length = 20)
	public String getOriLocation() {
		return this.oriLocation;
	}

	public void setOriLocation(String oriLocation) {
		this.oriLocation = oriLocation;
	}

	@Column(name = "LOCATION_SITE", length = 50)
	public String getLocationSite() {
		return this.locationSite;
	}

	public void setLocationSite(String locationSite) {
		this.locationSite = locationSite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE", length = 7)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "LAST_UPDATE_BY", length = 30)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Column(name = "ORI_LOCATION_DESC", length = 100)
	public String getOriLocationDesc() {
		return this.oriLocationDesc;
	}

	public void setOriLocationDesc(String oriLocationDesc) {
		this.oriLocationDesc = oriLocationDesc;
	}

}
