package mro.base.entity;

// Generated 2016/6/15 �U�� 01:31:21 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * UserLocationSiteMap generated by hbm2java
 */
@Entity
@Table(name = "USER_LOCATION_SITE_MAP")
public class UserLocationSiteMap implements java.io.Serializable {

	private String id;
	private String empNo;
	private LocationSiteMap locationSiteMap;
	private String updateUser;
	private Date updateDate;

	public UserLocationSiteMap() {
	}

	public UserLocationSiteMap(String id) {
		this.id = id;
	}
	
	public UserLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}
	
	public UserLocationSiteMap(String id, String empNo,
			LocationSiteMap locationSiteMap, String updateUser, Date updateDate) {
		this.id = id;
		this.empNo = empNo;
		this.locationSiteMap = locationSiteMap;
		this.updateUser = updateUser;
		this.updateDate = updateDate;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "EMP_NO")
	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_SITE")
	public LocationSiteMap getLocationSiteMap() {
		return locationSiteMap;
	}

	public void setLocationSiteMap(LocationSiteMap locationSiteMap) {
		this.locationSiteMap = locationSiteMap;
	}

	@Column(name = "UPDATE_USER", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
