package mro.base.entity;

// Generated 2015/3/5 �W�� 11:02:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZErpUnprocessPr generated by hbm2java
 */
@Entity
@Table(name = "Z_ERP_UNPROCESS_PR")
public class ZErpUnprocessPr implements java.io.Serializable {

	private BigDecimal prLineId;
	private String organizationId;
	private String prNo;
	private BigDecimal prLineNo;
	private String prStatus;
	private Date prCreationDate;
	private String prComments;
	private String lineCancelFlag;
	private String lineClosedCode;
	private String partNo;
	private String partNoDesc;
	private String partNoUom;
	private Date needByDate;
	private String requestorEmployeeNumber;
	private String requestorName;
	private String suggestedBuyerNum;
	private String suggestedBuyerName;
	private BigDecimal quantity;
	private String inspectorEmpNum;
	private String inspectorName;
	private String noteToAgent;
	private String destinationSubinventory;
	private BigDecimal prHeaderId;
	private String lineMemo;
	private Date dispatchDate;
	private String inspectorDeptCode;
	private String requestorEmpNo;
	private String requestorDeptCode;

	public ZErpUnprocessPr() {
	}

	public ZErpUnprocessPr(BigDecimal prLineId) {
		this.prLineId = prLineId;
	}

	public ZErpUnprocessPr(BigDecimal prLineId, String organizationId,
			String prNo, BigDecimal prLineNo, String prStatus,
			Date prCreationDate, String prComments, String lineCancelFlag,
			String lineClosedCode, String partNo, String partNoDesc,
			String partNoUom, Date needByDate, String requestorEmployeeNumber,
			String requestorName, String suggestedBuyerNum,
			String suggestedBuyerName, BigDecimal quantity,
			String inspectorEmpNum, String inspectorName, String noteToAgent,
			String destinationSubinventory, BigDecimal prHeaderId,
			String lineMemo, Date dispatchDate, String inspectorDeptCode,
			String requestorEmpNo, String requestorDeptCode) {
		this.prLineId = prLineId;
		this.organizationId = organizationId;
		this.prNo = prNo;
		this.prLineNo = prLineNo;
		this.prStatus = prStatus;
		this.prCreationDate = prCreationDate;
		this.prComments = prComments;
		this.lineCancelFlag = lineCancelFlag;
		this.lineClosedCode = lineClosedCode;
		this.partNo = partNo;
		this.partNoDesc = partNoDesc;
		this.partNoUom = partNoUom;
		this.needByDate = needByDate;
		this.requestorEmployeeNumber = requestorEmployeeNumber;
		this.requestorName = requestorName;
		this.suggestedBuyerNum = suggestedBuyerNum;
		this.suggestedBuyerName = suggestedBuyerName;
		this.quantity = quantity;
		this.inspectorEmpNum = inspectorEmpNum;
		this.inspectorName = inspectorName;
		this.noteToAgent = noteToAgent;
		this.destinationSubinventory = destinationSubinventory;
		this.prHeaderId = prHeaderId;
		this.lineMemo = lineMemo;
		this.dispatchDate = dispatchDate;
		this.inspectorDeptCode = inspectorDeptCode;
		this.requestorEmpNo = requestorEmpNo;
		this.requestorDeptCode = requestorDeptCode;
	}

	@Id
	@Column(name = "PR_LINE_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrLineId() {
		return this.prLineId;
	}

	public void setPrLineId(BigDecimal prLineId) {
		this.prLineId = prLineId;
	}

	@Column(name = "ORGANIZATION_ID", length = 8)
	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "PR_NO", length = 60)
	public String getPrNo() {
		return this.prNo;
	}

	public void setPrNo(String prNo) {
		this.prNo = prNo;
	}

	@Column(name = "PR_LINE_NO", precision = 22, scale = 0)
	public BigDecimal getPrLineNo() {
		return this.prLineNo;
	}

	public void setPrLineNo(BigDecimal prLineNo) {
		this.prLineNo = prLineNo;
	}

	@Column(name = "PR_STATUS", length = 75)
	public String getPrStatus() {
		return this.prStatus;
	}

	public void setPrStatus(String prStatus) {
		this.prStatus = prStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PR_CREATION_DATE", length = 7)
	public Date getPrCreationDate() {
		return this.prCreationDate;
	}

	public void setPrCreationDate(Date prCreationDate) {
		this.prCreationDate = prCreationDate;
	}

	@Column(name = "PR_COMMENTS", length = 450)
	public String getPrComments() {
		return this.prComments;
	}

	public void setPrComments(String prComments) {
		this.prComments = prComments;
	}

	@Column(name = "LINE_CANCEL_FLAG", length = 3)
	public String getLineCancelFlag() {
		return this.lineCancelFlag;
	}

	public void setLineCancelFlag(String lineCancelFlag) {
		this.lineCancelFlag = lineCancelFlag;
	}

	@Column(name = "LINE_CLOSED_CODE", length = 75)
	public String getLineClosedCode() {
		return this.lineClosedCode;
	}

	public void setLineClosedCode(String lineClosedCode) {
		this.lineClosedCode = lineClosedCode;
	}

	@Column(name = "PART_NO", length = 120)
	public String getPartNo() {
		return this.partNo;
	}

	public void setPartNo(String partNo) {
		this.partNo = partNo;
	}

	@Column(name = "PART_NO_DESC", length = 720)
	public String getPartNoDesc() {
		return this.partNoDesc;
	}

	public void setPartNoDesc(String partNoDesc) {
		this.partNoDesc = partNoDesc;
	}

	@Column(name = "PART_NO_UOM", length = 75)
	public String getPartNoUom() {
		return this.partNoUom;
	}

	public void setPartNoUom(String partNoUom) {
		this.partNoUom = partNoUom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEED_BY_DATE", length = 7)
	public Date getNeedByDate() {
		return this.needByDate;
	}

	public void setNeedByDate(Date needByDate) {
		this.needByDate = needByDate;
	}

	@Column(name = "REQUESTOR_EMPLOYEE_NUMBER", length = 90)
	public String getRequestorEmployeeNumber() {
		return this.requestorEmployeeNumber;
	}

	public void setRequestorEmployeeNumber(String requestorEmployeeNumber) {
		this.requestorEmployeeNumber = requestorEmployeeNumber;
	}

	@Column(name = "REQUESTOR_NAME", length = 720)
	public String getRequestorName() {
		return this.requestorName;
	}

	public void setRequestorName(String requestorName) {
		this.requestorName = requestorName;
	}

	@Column(name = "SUGGESTED_BUYER_NUM", length = 90)
	public String getSuggestedBuyerNum() {
		return this.suggestedBuyerNum;
	}

	public void setSuggestedBuyerNum(String suggestedBuyerNum) {
		this.suggestedBuyerNum = suggestedBuyerNum;
	}

	@Column(name = "SUGGESTED_BUYER_NAME", length = 720)
	public String getSuggestedBuyerName() {
		return this.suggestedBuyerName;
	}

	public void setSuggestedBuyerName(String suggestedBuyerName) {
		this.suggestedBuyerName = suggestedBuyerName;
	}

	@Column(name = "QUANTITY", precision = 22, scale = 0)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "INSPECTOR_EMP_NUM", length = 180)
	public String getInspectorEmpNum() {
		return this.inspectorEmpNum;
	}

	public void setInspectorEmpNum(String inspectorEmpNum) {
		this.inspectorEmpNum = inspectorEmpNum;
	}

	@Column(name = "INSPECTOR_NAME", length = 450)
	public String getInspectorName() {
		return this.inspectorName;
	}

	public void setInspectorName(String inspectorName) {
		this.inspectorName = inspectorName;
	}

	@Column(name = "NOTE_TO_AGENT", length = 1440)
	public String getNoteToAgent() {
		return this.noteToAgent;
	}

	public void setNoteToAgent(String noteToAgent) {
		this.noteToAgent = noteToAgent;
	}

	@Column(name = "DESTINATION_SUBINVENTORY", length = 30)
	public String getDestinationSubinventory() {
		return this.destinationSubinventory;
	}

	public void setDestinationSubinventory(String destinationSubinventory) {
		this.destinationSubinventory = destinationSubinventory;
	}

	@Column(name = "PR_HEADER_ID", precision = 22, scale = 0)
	public BigDecimal getPrHeaderId() {
		return this.prHeaderId;
	}

	public void setPrHeaderId(BigDecimal prHeaderId) {
		this.prHeaderId = prHeaderId;
	}

	@Column(name = "LINE_MEMO", length = 3072)
	public String getLineMemo() {
		return this.lineMemo;
	}

	public void setLineMemo(String lineMemo) {
		this.lineMemo = lineMemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DISPATCH_DATE", length = 7)
	public Date getDispatchDate() {
		return this.dispatchDate;
	}

	public void setDispatchDate(Date dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	@Column(name = "INSPECTOR_DEPT_CODE", length = 100)
	public String getInspectorDeptCode() {
		return this.inspectorDeptCode;
	}

	public void setInspectorDeptCode(String inspectorDeptCode) {
		this.inspectorDeptCode = inspectorDeptCode;
	}

	@Column(name = "REQUESTOR_EMP_NO", length = 90)
	public String getRequestorEmpNo() {
		return this.requestorEmpNo;
	}

	public void setRequestorEmpNo(String requestorEmpNo) {
		this.requestorEmpNo = requestorEmpNo;
	}

	@Column(name = "REQUESTOR_DEPT_CODE", length = 450)
	public String getRequestorDeptCode() {
		return this.requestorDeptCode;
	}

	public void setRequestorDeptCode(String requestorDeptCode) {
		this.requestorDeptCode = requestorDeptCode;
	}

}
