package mro.base.entity;

// Generated 2015/1/26 �W�� 11:36:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ZZpoMroVendorItem generated by hbm2java
 */
@Entity
@Table(name = "Z_ZPO_MRO_VENDOR_ITEM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"INVENTORY_ITEM_ID", "VENDOR_ID", "ORG_NAME" }))
public class ZZpoMroVendorItem implements java.io.Serializable {

	private BigDecimal rowId;
	private BigDecimal inventoryItemId;
	private String segment1;
	private BigDecimal vendorId;
	private String vendorName;
	private String vendorSiteCode;
	private BigDecimal vendorSiteId;
	private String lastPoYear;
	private String orgName;

	public ZZpoMroVendorItem() {
	}

	public ZZpoMroVendorItem(BigDecimal rowId, BigDecimal inventoryItemId,
			BigDecimal vendorId, String orgName) {
		this.rowId = rowId;
		this.inventoryItemId = inventoryItemId;
		this.vendorId = vendorId;
		this.orgName = orgName;
	}

	public ZZpoMroVendorItem(BigDecimal rowId, BigDecimal inventoryItemId,
			String segment1, BigDecimal vendorId, String vendorName,
			String vendorSiteCode, BigDecimal vendorSiteId, String lastPoYear,
			String orgName) {
		this.rowId = rowId;
		this.inventoryItemId = inventoryItemId;
		this.segment1 = segment1;
		this.vendorId = vendorId;
		this.vendorName = vendorName;
		this.vendorSiteCode = vendorSiteCode;
		this.vendorSiteId = vendorSiteId;
		this.lastPoYear = lastPoYear;
		this.orgName = orgName;
	}

	@Id
	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	@Column(name = "INVENTORY_ITEM_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getInventoryItemId() {
		return this.inventoryItemId;
	}

	public void setInventoryItemId(BigDecimal inventoryItemId) {
		this.inventoryItemId = inventoryItemId;
	}

	@Column(name = "SEGMENT1", length = 40)
	public String getSegment1() {
		return this.segment1;
	}

	public void setSegment1(String segment1) {
		this.segment1 = segment1;
	}

	@Column(name = "VENDOR_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(BigDecimal vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "VENDOR_NAME", length = 240)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "VENDOR_SITE_CODE", length = 15)
	public String getVendorSiteCode() {
		return this.vendorSiteCode;
	}

	public void setVendorSiteCode(String vendorSiteCode) {
		this.vendorSiteCode = vendorSiteCode;
	}

	@Column(name = "VENDOR_SITE_ID", precision = 22, scale = 0)
	public BigDecimal getVendorSiteId() {
		return this.vendorSiteId;
	}

	public void setVendorSiteId(BigDecimal vendorSiteId) {
		this.vendorSiteId = vendorSiteId;
	}

	@Column(name = "LAST_PO_YEAR", length = 4)
	public String getLastPoYear() {
		return this.lastPoYear;
	}

	public void setLastPoYear(String lastPoYear) {
		this.lastPoYear = lastPoYear;
	}

	@Column(name = "ORG_NAME", nullable = false, length = 50)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

}
